### ISSUE TITLE
Edit/Correct Messages

### ISSUE THREAD

**Issue by trymeouteh** [dino/dino#1004]
Please add feature to edit sent messages to correct spelling errors, this feature is supported in the Conversations app.

**Comment by mimi89999** [comment]
This feature is supported in Dino. You can edit the last message you sent.

**Comment by licaon-kter** [comment]
@trymeouteh do update to 0.2

**Comment by fiaxh** [comment]
This feature has been in Dino for a while now and was already part of the Dino 0.2 release. If you don't have the feature, that means you're using an old Dino version. [This blog post](https://dino.im/blog/2020/11/dino-0.2-release/) illustrates how message correction works UI-wise.
