### ISSUE TITLE
Set password to unlock app

### ISSUE THREAD

**Issue by trymeouteh** [dino/dino#1005]
Add an optional password which is required to be entered when the app is launched to use the app.

**Comment by fiaxh** [comment]
Rather then duplicating encryption or password protection logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).

Here's how to use encfs to encrypt Dino's data and enter a password on every launch of Dino: https://github.com/dino/dino/issues/745#issuecomment-588436869 .

**Comment by trymeouteh** [comment]
> Rather then duplicating encryption or password protection logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).
> 
> Here's how to use encfs to encrypt Dino's data and enter a password on every launch of Dino: [#745 (comment)](https://github.com/dino/dino/issues/745#issuecomment-588436869) .

Will this work on all Desktop OSes and be easy to do for non tech savvy users?

**Comment by lm2lm2** [comment]
> Rather then duplicating encryption or password protection logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).
> 
> Here's how to use encfs to encrypt Dino's data and enter a password on every launch of Dino: [#745 (comment)](https://github.com/dino/dino/issues/745#issuecomment-588436869) .

well, i let few people using my computer almost everyday for few things.. even thund get a module to protect by password the access of mailboxes..


https://github.com/dino/dino/issues/1005
https://github.com/dino/dino/issues/1754
https://github.com/dino/dino/issues/1754
it's really an interesting (and wished) feature :)

**Comment by christf** [comment]
> > Rather then duplicating encryption or password protection logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).
> > Here's how to use encfs to encrypt Dino's data and enter a password on every launch of Dino: [#745 (comment)](https://github.com/dino/dino/issues/745#issuecomment-588436869) .
> 
> Will this work on all Desktop OSes and be easy to do for non tech savvy users?

All major desktop OS have a way to encrypt data on disk including Linux,  BSD,  Mac,  Windows.
