### ISSUE TITLE
Contacts stealing avatars each other

### ISSUE THREAD

**Issue by resoli** [dino/dino#1008]
I have a strange avatar interference between two specific contacts: it seems that when one changes, the other follows changing to the same image. These two users are on different domains. 

Dino version: 0.2.0~git33.2021-02-17.73f01213 on ubuntu 20.04

**Comment by Echolon** [comment]
#363

**Comment by fiaxh** [comment]
Please have a look whether your issue is fixed on master now. It might have been fixed by f2ef2bcfe7f3e5d1449285c1517df703af1221a4.

**Comment by fiaxh** [comment]
I'm closing this issue assuming that f2ef2bc fixed this as mentioned above. If you still have this issue, please leave a message here.
