### ISSUE TITLE
Plugins don't install deplibname-vala.so

### ISSUE THREAD

**Issue by andrey-utkin** [dino/dino#1011]
Hi,

Gentoo user has spotted [an issue](https://bugs.gentoo.org/772275) that installing a package built from upstream git HEAD doesn't work:
```
** (dino:288593): WARNING **: 15:09:35.179: main.vala:25: Fatal error: libsignal-protocol-vala.so: cannot open shared object file: No such file or directory
```

The files libsignal-protocol-vala.so libgpgme-vala.so libcrypto-vala.so are in fact built, but are not installed into destdir on `ninja install` step. Copying these files manually from the build dir to /usr/lib64 makes it work.

This doesn't happen with the latest release 0.2 which gives me a reason to think that Gentoo users are just first to spot it due to existence of live ebuilds, and that this would become an issue for other packagers when a new release comes out.

Seems like an omission of cmake script logic?

But I'm not sure what would be the best way to resolve this:
* put these files into /usr/lib64;
* link statically if possible;
* keep these files together with plugin files, and use some location hints like rpath.

**Comment by mar-v-in** [comment]
I guess the issue is that you have `-DBUILD_SHARED_LIBS=yes` which is currently not supported (the default is `no`, and we assume it to be like that). Should be easy to fix though on our side by forcing static libs where needed even when `BUILD_SHARED_LIBS` is set to `yes`.

**Comment by mar-v-in** [comment]
64237a83a45ab949e28bdb0221663ac918a2c5d2 should fix this for you.

**Comment by andrey-utkin** [comment]
Thank you! Now it works indeed.
