### ISSUE TITLE
Feature request: Pasting images into chat

### ISSUE THREAD

**Issue by 1Gigabit** [dino/dino#1012]
Hello, this will be a feature request.

I'd like to request that we have a feature for copying and pasting images into Dino.

Y'know how you can 'copy image' on a website, I want to be able to send that image when I 'CTRL+V' or (PASTE) into Dino.

Can this be a future possibility?

**Comment by licaon-kter** [comment]
Try to update to 0.2
https://dino.im/blog/2020/11/dino-0.2-release/

/close this

**Comment by fiaxh** [comment]
This feature is already implemented and is part of the 0.2 release.
