### ISSUE TITLE
Regression: Address instead of nicknames attached to sent files

### ISSUE THREAD

**Issue by Zash** [dino/dino#1019]
#643 seems to be back.

To reproduce:

1. Join channel
2. Send image
3. Restart

Observe nickname attached to image.

`git bisect` claims 80c8e18cea4f243ffa7caa921f8bf6d9baca01bd is the first bad commit

Thanks to anubis in the chat for noticing that it seemed to have returned. Unclear if they had encountered this exact issue or a similar one.

**Comment by fiaxh** [comment]
Thanks for noticing and you were also right about the faulty commit. It's fixed in 7ce49d7.
