### ISSUE TITLE
some app icons broken due to gdk-pixbuf and svg

### ISSUE THREAD

**Issue by alexmat** [dino/dino#1024]
getting the following issue after building https://github.com/dino/dino/commit/7ce49d7d68f19fb49a33e907485d83da2c9131a3

```
$ dino

** (dino:7753): CRITICAL **: 17:26:13.256: file /tmp/pkgmk-dino/src/dino/main/src/ui/main_window.vala: line 68: uncaught error: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

(dino:7753): Gtk-WARNING **: 17:26:13.279: Found an icon but could not load it. Most likely gdk-pixbuf does not provide SVG support.
```

I do have gdk-pixbuf and librsvg installed:

```
$ gdk-pixbuf-query-loaders | grep svg

"/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so"
"svg" 6 "gdk-pixbuf" "Scalable Vector Graphics" "LGPL"
"image/svg+xml" "image/svg" "image/svg-xml" "image/vnd.adobe.svg+xml" "text/xml-svg" "image/svg+xml-compressed" ""
"svg" "svgz" "svg.gz" ""
" <svg" "*    " 100
" <!DOCTYPE svg" "*             " 100
```

**Comment by alexmat** [comment]
found the solution, I had to run the following after installing librsvg:

```bash
gdk-pixbuf-query-loaders --update-cache
```

**Comment by dreamlayers** [comment]
In Ubuntu 24.04, libpixbufloader-svg.so is in librsvg2-common, so only having librsvg2-2 is not enough. That package also takes care of the gdk-pixbuf cache update in a postinst script, saying that earlier triggering "might not work yet due to unconfigured/missing dependencies" as described in https://bugs.launchpad.net/ubuntu/+source/librsvg/+bug/719861/comments/9

**Comment by un-clouded** [comment]
If `umask` of `root` does not make newly created files world readable (mine is `0027`) then `/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache` may be readable by the `root` user after `/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache` but unreadable by other users.  `strace` showed:

    openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders.cache", O_RDONLY) = -1 EACCES (Permission denied)
