### ISSUE TITLE
Dino notifications no longer atomatically disappear

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#1026]
When a chat message arrives, Dino shows a notification -- or rather, it makes my desktop (KDE Plasma) show a notification. It used to be the case that this notification was set to disappear automatically. Recently I updated my system and dino, and now the notification sticks around in the bottom-right corner until I close it manually. This is rather distracting as I am usually working on something else and will get back to the notification later.

Other notifications still disappear automatically, so I suspect it is a change in dino (and not a change in my system) that caused this behavior to change.

**Comment by muppeth** [comment]
Noticed the same behaviour on phosh (pinephone) which is that much more annoying that the only way to get rid of it is by tapping it, which then brings you to dino.

**Comment by aereaux** [comment]
To add to this, the notification disappears for me (0.2.0~git56.20210321.9fed5ea) when I focus dino, but not when I read the triggering message on another device.

**Comment by aereaux** [comment]
This appears to still be an issue for me.  How long are the notifications supposed to stay there?  I'm using [mako](https://github.com/emersion/mako/) for notifications in case it makes a difference
