### ISSUE TITLE
Dino does not clear contact avatar on removal

### ISSUE THREAD

**Issue by Zash** [dino/dino#1039]
1. Open chat with a contact (someone who has an avatar published)
2. Have the contact remove their own avatar
3. Observe their avatar in Dino

Expect: Dino should revert to the default (ie colored square with a letter).

Actual: No change observed.

Dino version: 0.2.0~git86.20210412.328c3cf

Per [XEP-0084 3.5 Publisher Disables Avatar Publishing](https://xmpp.org/extensions/xep-0084.html#pub-disable) receiving the following indicates that a contact has removed their avatar:

```xml
<message id='bAQ4v0lrHFlpSZFB' type='headline' from='user@example.com'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
    <items node='urn:xmpp:avatar:metadata'>
      <item id='5daf833b-b81b-4896-9e5c-689dd73627b6'>
        <metadata xmlns='urn:xmpp:avatar:metadata'/>
      </item>
    </items>
  </event>
</message>
```

With servers supporting more of XEP-0060 on users PEP services, it may also be good to handle [purge](https://xmpp.org/extensions/xep-0060.html#owner-purge) if it isn't too much trouble:

```xml
<message id='w46wOynPy-IFRdfm' type='headline' from='user@example.com'>
  <event xmlns='http://jabber.org/protocol/pubsub#event'>
    <purge node='urn:xmpp:avatar:metadata'/>
  </event>
</message>
```

Or even the [nuclear option](https://xmpp.org/extensions/xep-0060.html#owner-delete)...

**Comment by fiaxh** [comment]
Incoming support for avatar deletion was added in fe45ab575c687febc1f342b0882a7597bd6ae9dc, and UI for deleting the avatar from Dino was added in 21ae42762d8a57da5cb1ec40b46e7510fc3121ad.
