### ISSUE TITLE
Unable to locate package dino-im

### ISSUE THREAD

**Issue by namelessperson0** [dino/dino#1040]
Trying to install dino in Ubuntu 16.04 with the command 
```
sudo apt update
sudo apt install dino-im
```

Getting the error
`E: Unable to locate package dino-im
`

What is the alternative way to install?

**Comment by licaon-kter** [comment]
https://dino.im has alternatives like https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino but your distro is too old. Any chance to uprade?

/close this
