### ISSUE TITLE
Qlite Error: Add columns for version: SQLite error: 1 - duplicate column name: encryption (master->call-branch)

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#1048]
Since I also test the call feature I switch back and forth between master (AUR) and the call-branch 0ad968df367f5a44c568329834115018866ff8b9.

When I start the call-branch version after I have started and quit the master version, I see the following error in the terminal:

```
** (dino:528283): CRITICAL **: 15:58:58.031: table.vala:174: Qlite Error: Add columns for version: SQLite error: 1 - duplicate column name: encryption
```

OS: Manjaro

**Comment by fiaxh** [comment]
Switching Dino versions back and forth isn't generally something that should be done. Database modifications are not always supported both ways, and thus switching back and forth can put the database into an inconsistent state.

In this particular case, switching between the feature/calls branch and master shouldn't cause any issues, though.

The calls branch is on a newer database version, which includes an additional `encryption` column on a table. And when you upgrade a second time, the column is already there from the first time, thus Dino can't add it. Dino complains about that in the log output, but it won't cause issues.
