### ISSUE TITLE
onion certificate verification

### ISSUE THREAD

**Issue by gaudenum** [dino/dino#1051]
Context: using dino to authenticate to onion xmpp service

Problem: From debian 11 (bullseye), can't connect to an onion server as dino refuse its certificate. 

Same dino version used, 0.2.0~git51.20210501.e92ed273-1

> (dino:9460): dconf-DEBUG: 13:10:39.948: watch_fast: "/org/gtk/settings/emoji-chooser/" (establishing: 0, active: 0)
> (dino:9460): dconf-DEBUG: 13:10:39.948: watch_established: "/org/gtk/settings/emoji-chooser/" (establishing: 1)
> (dino:9460): xmpp-vala-DEBUG: 13:10:57.558: stream_connect.vala:29: Got no xmpp-client DNS records for jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion: Aucun enregistrement DNS du type demandé pour « _xmpp-client._tcp.jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion »
> (dino:9460): xmpp-vala-DEBUG: 13:10:57.642: stream_connect.vala:37: Got no xmpps-client DNS records for jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion: Aucun enregistrement DNS du type demandé pour « _xmpps-client._tcp.jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion »
> (dino:9460): xmpp-vala-DEBUG: 13:10:57.642: starttls_xmpp_stream.vala:19: Connecting to jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion 5222 (starttls)
> (dino:9460): dconf-DEBUG: 13:10:57.647: watch_fast: "/system/proxy/" (establishing: 0, active: 0)
> (dino:9460): dconf-DEBUG: 13:10:57.647: watch_fast: "/system/proxy/http/" (establishing: 0, active: 0)
> (dino:9460): dconf-DEBUG: 13:10:57.647: watch_fast: "/system/proxy/https/" (establishing: 0, active: 0)
> (dino:9460): dconf-DEBUG: 13:10:57.647: watch_fast: "/system/proxy/ftp/" (establishing: 0, active: 0)
> (dino:9460): dconf-DEBUG: 13:10:57.648: watch_fast: "/system/proxy/socks/" (establishing: 0, active: 0)
> (dino:9460): GLib-GIO-DEBUG: 13:10:57.648: _g_io_module_get_default: Found default implementation gnome (GProxyResolverGnome) for ‘gio-proxy-resolver’
> (dino:9460): GLib-GIO-DEBUG: 13:10:57.648: GSocketClient: Starting new address enumeration
> (dino:9460): dconf-DEBUG: 13:10:57.648: watch_established: "/system/proxy/" (establishing: 1)
> (dino:9460): GLib-GIO-DEBUG: 13:10:57.649: GSocketClient: Address enumeration succeeded
> (dino:9460): GLib-GIO-DEBUG: 13:10:57.649: GSocketClient: Starting TCP connection attempt
> [proxychains] Strict chain  ...  127.0.0.1:9050 (dino:9460): dconf-DEBUG: 13:10:57.649: watch_established: "/system/proxy/http/" (establishing: 1)
> (dino:9460): dconf-DEBUG: 13:10:57.649: watch_established: "/system/proxy/https/" (establishing: 1)
> (dino:9460): dconf-DEBUG: 13:10:57.649: watch_established: "/system/proxy/ftp/" (establishing: 1)
> (dino:9460): dconf-DEBUG: 13:10:57.649: watch_established: "/system/proxy/socks/" (establishing: 1)
>  ...  jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion:5222  ...  OK
> (dino:9460): GLib-GIO-DEBUG: 13:10:59.921: GSocketClient: Timeout reached, trying another enumeration
> (dino:9460): GLib-GIO-DEBUG: 13:10:59.921: GSocketClient: Starting new address enumeration
> (dino:9460): GLib-GIO-DEBUG: 13:10:59.921: GSocketClient: TCP connection successful
> (dino:9460): GLib-GIO-DEBUG: 13:10:59.921: GSocketClient: Starting application layer connection
> (dino:9460): GLib-GIO-DEBUG: 13:10:59.921: GSocketClient: Connection successful!
> (dino:9460): GLib-GIO-DEBUG: 13:11:00.943: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
> (dino:9460): GLib-Net-DEBUG: 13:11:00.944: CLIENT[0x5626596da240]: starting to write 167 bytes to TLS connection
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claiming operation OP_WRITE
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: Implcit TLS handshaking starts
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claim_op failed: implicit handshake required
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: Asynchronous TLS handshake thread starts
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: TLS handshake thread starts
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: starting to read data from TLS connection
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claiming operation OP_HANDSHAKE
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claiming operation OP_READ
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claiming operation OP_HANDSHAKE succeeded
> (dino:9460): GLib-Net-DEBUG: 13:11:00.945: CLIENT[0x5626596da240]: claim_op failed: operation would block
> (dino:9460): GLib-Net-DEBUG: 13:11:01.641: CLIENT[0x5626596da240]: verifying peer certificate
> 
> (dino:9460): xmpp-vala-WARNING **: 13:11:01.694: tls_xmpp_stream.vala:28: [0x5626596a6150, jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion] Tls Certificate Errors: G_TLS_CERTIFICATE_BAD_IDENTITY, 
> (dino:9460): GLib-Net-DEBUG: 13:11:01.694: CLIENT[0x5626596da240]: TLS handshake thread failed: Certificat TLS inacceptable
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: yielding operation OP_HANDSHAKE
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: starting to write 167 bytes to TLS connection
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: claiming operation OP_WRITE
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: finishing TLS handshake
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: TLS handshake has finished with error: Certificat TLS inacceptable
> (dino:9460): GLib-Net-DEBUG: 13:11:01.695: CLIENT[0x5626596da240]: claim_op failed: finish_handshake failed or operation has been cancelled
> 
> (dino:9460): xmpp-vala-WARNING **: 13:11:01.696: stream_connect.vala:76: Could not establish XMPP session with jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion:5222: Failed connecting to jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion:5222 (starttls): GLib.IOError: L’opération a été annulée
> (dino:9460): libdino-DEBUG: 13:11:01.696: registration.vala:91: Error connecting to stream: Failed connecting to jukrlvyhgguiedqswc5lehrag2fjunfktouuhi4wozxhb6heyzvshuyd.onion:5222 (starttls): GLib.IOError: L’opération a été annulée
> (dino:9460): GLib-Net-DEBUG: 13:11:01.703: CLIENT[0x5626596da240]: starting to close the TLS connection
> (dino:9460): GLib-Net-DEBUG: 13:11:01.703: CLIENT[0x5626596da240]: claiming operation OP_CLOSE_BOTH
> (dino:9460): GLib-Net-DEBUG: 13:11:01.703: CLIENT[0x5626596da240]: claiming operation OP_CLOSE_BOTH succeeded
> (dino:9460): GLib-Net-DEBUG: 13:11:01.703: CLIENT[0x5626596da240]: yielding operation OP_CLOSE_BOTH
> (dino:9460): GLib-Net-DEBUG: 13:11:01.703: CLIENT[0x5626596da240]: the TLS connection has been closed successfully
![Capture d’écran de 2021-05-07 13-27-58](https://user-images.githubusercontent.com/83818393/117460759-6017c080-af3c-11eb-8ebf-66355a809243.png)

>

**Comment by licaon-kter** [comment]
There were same fixes for .onion 

Which Dino version do you have?

**Comment by fiaxh** [comment]
Dino 0.2 doesn't connect to servers with bad certificates. We made an exception for .onion domains, but that was after 0.2 (81a55052707d460a7f437b664682817c2c99dce6). When you try this with the current master, it should work.
