### ISSUE TITLE
Randomly crashes

### ISSUE THREAD

**Issue by rugk** [dino/dino#106]
Dino randomly crashes.

Fedora 25, installed from copr.

Version: 0.0-1.git.107.4247922.fc25.x86_64
https://retrace.fedoraproject.org/faf/reports/bthash/93d567392736a8eefebaaa3c5c6c5dd82ce5f4bc

**Comment by fiaxh** [comment]
This should not happen anymore since 3a8df20.

For further reports, debug symbols might be useful. They are in `dino-debuginfo` in copr.

**Comment by participante0** [comment]
> For further reports, debug symbols might be useful. They are in `dino-debuginfo` in copr.

@fiaxh, please add that info to the Wiki, README.md or CONTRIBUTING.md
