### ISSUE TITLE
Disabling ice/rtp plugins does not disable dependencies

### ISSUE THREAD

**Issue by hololeap** [dino/dino#1060]
I'm working on updating the live version of dino for Gentoo for my personal overlay, and it seems like disabling the `ice` and `rtp` plugins does not prevent cmake from looking for the new dependencies.

Here is the `cmake` command that is run during the Gentoo build:

```
cmake -C /var/tmp/portage/net-im/dino-9999/work/dino-9999_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DENABLED_PLUGINS=notification-sound -DDISABLED_PLUGINS=ice;rtp -DVALA_EXECUTABLE=/usr/bin/valac-0.48 -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/net-im/dino-9999/work/dino-9999_build/gentoo_toolchain.cmake  /var/tmp/portage/net-im/dino-9999/work/dino-9999
```

Further down, there is this:

```
-- Enabled plugin: omemo
-- Enabled plugin: openpgp
-- Enabled plugin: http-files
-- Enabled plugin: ice
-- Enabled plugin: rtp
-- Disabled plugin: ice
-- Disabled plugin: rtp
-- Enabled plugin: notification-sound
-- Configuring Dino 0.2.0~git112.20210515.686035c with plugins: http-files, notification-sound, omemo, openpgp
```

And yet, cmake still seems to require the following libraries even with these plugins disabled (it will fail if they are not found):

```
-- Found Gst: /usr/lib64/libgstreamer-1.0.so (found version "1.16.3")
-- Found GstVideo: /usr/lib64/libgstvideo-1.0.so (found version "1.16.3")
-- Found Srtp2: /usr/lib64/libsrtp2.so (found version "2.3.0")
```

**Comment by hololeap** [comment]
In retrospect, I may be mistaken that these plugins toggle the new calling feature.

**Comment by mar-v-in** [comment]
- libsrtp2 is required for libcrypto-vala. We currently don't plan to make SRTP support in libcrypto-vala optional (but this may change in the future). libcrypto-vala is also used by the omemo plugin.
- libgstreamer and libgstvideo dependencies are not required when not building rtp plugin and shouldn't pop up there, I'll investigate and fix this.
