### ISSUE TITLE
UX: "... is typing" Message should not shift Messages up and down

### ISSUE THREAD

**Issue by paskalito** [dino/dino#1062]
Verison 0.2
Debian

# STR
1. Be in a chat with someone
2. scroll up the history a little bit ( optional )
3. try to read a message
4. have your chatpartner start typing or stop typing  (or do both consequently)

# Expected Behavior
Have a tiny **overlay** "... is typing" banner

# current behavior
The "... is typing" banner is shifting the whole Conversation up
If it disappears again it is shifting everything back down.

## Problem
Its really hard toe read a conversation when your chatpartner is constantly typing and not typing again.

**Comment by fiaxh** [comment]
This has already been brought up in #688.
