### ISSUE TITLE
Input field grows by 1 pixel when text is entered

### ISSUE THREAD

**Issue by haasn** [dino/dino#1064]
A picture is worth a thousand words:

![before entering text](https://user-images.githubusercontent.com/1149047/119130404-7774a480-ba38-11eb-9a68-467f36f9d539.png) \
![after entering text](https://user-images.githubusercontent.com/1149047/119130406-780d3b00-ba38-11eb-8ae8-acb1e79d1626.png)

If you open both of those and go back and forth between them, you can see that the second screenshot has the input bar be 1 pixel higher than the first screenshot. This is annoying in particular because it causes the entire chat window above it to also scroll up by 1 pixel.

**Comment by selurvedu** [comment]
I saw the same behaviour in a few other GTK programs. I don't remember which ones, but this may be a non-Dino-specific bug, but, in any case, it would need a Dino-specific fix. 😕

**Comment by selurvedu** [comment]
One does not simply use GTK without employing hacks :)
Thanks for fixing!
