### ISSUE TITLE
Debian 10 nightly package depends on >= libnice10-0.1.15, not available upstream

### ISSUE THREAD

**Issue by fl0bo** [dino/dino#1065]
Since recently dino cannot update from nightly anymore:
_dino : Depends: libnice10 (>= 0.1.15) but 0.1.14-1 is to be installed_

Package source http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/Debian_10/

Debian 10 / buster has libnice10-0.14-1:
https://packages.debian.org/search?keywords=libnice10&searchon=names&suite=stable&section=all

Is this intended?

Backports would provide libnice10-0.1.16-1~bpo10+1
Didn't try yet.

**Comment by fiaxh** [comment]
The current Dino nightlies indeed depend on libnice >= 0.1.15, which Debian buster unfortunately does not provide. Thus, you'll have to get libnice from backports if you want to use current Dino nightlies on Debian buster.

In the future we might include a newer libnice version in our buster repo, but that hasn't been done yet.

**Comment by fl0bo** [comment]
Installed libnice from backports and upgraded to latest nightly. Thanks.
