### ISSUE TITLE
Weird scrolling behavior viewing past history

### ISSUE THREAD

**Issue by Zash** [dino/dino#1070]
1. Use search to find and jump to a message far in the past
2. Scroll down (or up?) a bit, as one would do while reading the context
3. ???
4. Dino starts scrolling the chat log by itself, all the way to the end (as in, most recent messages)

Each scroll 'step' can also seem to have varying size when scrolled far back. 

Something related to dynamic loading of messages from the database?

**Comment by selurvedu** [comment]
This bug will probably vanish if the lag when loading more messages get fixed. You can see that Dino hangs for a moment when you scroll past the currently loaded messages.

**Comment by selurvedu** [comment]
See also #629

**Comment by Zash** [comment]
I haven't seen this exact issue lately with 0.4.x but I have some other issues when scrolling up a bit.
