### ISSUE TITLE
Call UX experiences and recommendations

### ISSUE THREAD

**Issue by rscmbbng** [dino/dino#1073]
Hello,

Finally I had the chance to do some longer audio calls between Dino and Conversations and I'm opening up this issue to flag some UX issues I came across. I'm really happy and impressed by the work so far! Thank you for that!

Version:
```
user@computer:~$ dino --version
Dino 0.2.0~git113.20210601.1ac16ecd-1
```

System:
Debian Stable with LXDE

## Reconnection UI

During calls with people on unstable connections (for example because they walk in and out of the range of their WLAN when talking on the phone) there are frequent disconnections. Dino automatically seems to reconnect but this is presented as the other party calling again and it gives the user the option to pick up or reject the call.This requires me to actively nurse the dino conversation window by keeping it in view and manually 'answer' reconnection attempts. I found that I could reconnect so fast that the other party never noticed. These reconnections should happen automatically.

### Call list 

Extending on that, the resulting chat dialog looks like there have been 10 or more calls while in actuality it has been only a single call with many reconnections. This should be bundled in one single call UI element. 

See image below. 
![dino_call](https://user-images.githubusercontent.com/5276865/121370412-00e30c80-c93d-11eb-8506-6b20e1a5156c.png) (also: why do some show the encryption symbol and  others not? Has the security of the call been compromised during the session?) 

### Call start & end sounds

Considering there are no audio notifications when a call starts or ends, I actively need to watch the window to know whether the other party can still hear me.  

## Window behavior

Upon calling, Dino spawns a second window breaking the elegance of the single window application. Replacing a section of the chat history with the call details could be a way forward.

### Accidentally ending calls 
At the same time, when there are two windows, closing the main Dino window ends the call. I know this makes sense from a software perspective, but it doesn't from a usability perspective.

When someone intends to close the main window it does not likely mean they wish to end the ongoing call, but it is more likely they are trying to make space to work on something while calling. 

![bar](https://user-images.githubusercontent.com/5276865/121372999-004b7580-c93f-11eb-9bb5-0ac4b71a076c.png) (Can you guess which one is the call? Wrong! It was the other one! :p)

### Window titles  

When calling there are two identical items on my desktop bar called Dino, yet one represents the main application window and the other is the call.

 It would be helpful if the call retained the application logo but was called Call with X instead. Or just X. Where X is the name of the other party.

**Comment by fiaxh** [comment]
> Reconnection UI

Dino doesn't have any logic for reconnecting calls, and I never encountered that sort of behavior myself. What you describe sounds like the counterpart's client is establishing new calls, or there's a bug somewhere. What client was your counterpart using? It might help if you could get a log of this behavior with `dino --print-xmpp="iq|message"`.

> why do some show the encryption symbol and others not? Has the security of the call been compromised during the session?

It shows encryption symbols if encryption has been negotiated during the call. In your case there's a missed call and a call that seemingly didn't establish. But of course it's misleading to show an unencrypted warning in those cases. I opened a dedicated issue: #1089

> Call start & end sounds

I opened a dedicated issue for this: #1088

> Accidentally ending calls

Sounds like this issue would be solved by #299.

**Comment by rscmbbng** [comment]
> Dino should have any logic that would result in new call requests like this, and I never encountered that sort of behavior myself. What you describe sounds like the counterpart's client is establishing new calls, or there's a bug somewhere. What client was your counterpart using? It might help if you could get a log of this behavior with `dino --print-xmpp="iq|message"`.

Thanks, I'll try to log it the next time we call. The other party was using the fdroid version of the Conversations client by the way.

**Comment by fiaxh** [comment]
Since I opened dedicated issues for your individual points, I'll close this one. If you have further information on that strange calling-over-and-over-again behavior, please leave a message here or open a dedicated issue for it.
