### ISSUE TITLE
[Help] Compile against manually built sqlite3 3.36.0

### ISSUE THREAD

**Issue by josephmturner** [dino/dino#1081]
Hello! As mentioned [here](https://github.com/dino/dino/issues/941#issuecomment-763641379) and [here](https://github.com/dino/dino/issues/982#issuecomment-767511675), dino now requires sqlite 3.24 to build. I'm running Mint 19.1, which only has 3.22.

I have manually compiled sqlite3 (3.36.0) from [source](https://sqlite.org/download.html), and I'm wondering how I can compile dino against that newer version.

Thank you!

**Comment by fiaxh** [comment]
We're using pkgconfig, so you'll have to make pkgconfig look in the folder where your own `sqlite3.pc` is. You can apparently get pkgconfig to do that by setting your `PKG_CONFIG_PATH` environment variable accordingly.
