### ISSUE TITLE
Emoji picker not working with gtk3-3.24.30

### ISSUE THREAD

**Issue by slanderous-mambo** [dino/dino#1083]
Dino's builtin emoji picker only shows my recently used emojis:
![Bildschirmfoto von 2021-07-26 18-12-38](https://user-images.githubusercontent.com/64353947/127022779-f1c2705f-9bd4-41ac-8e39-0ca31bef3b89.png)
The debug output shows nothing, when I open the emoji picker.

Gnome's emoji picker (that can be accessed by right clicking) still works:
![Bildschirmfoto von 2021-07-26 18-12-58](https://user-images.githubusercontent.com/64353947/127022922-d5c82f85-1323-4ef4-91af-91d5d8b0cd01.png)
Here, the debug output shows
```
(dino:19497): dconf-DEBUG: 17:37:43.347: watch_fast: "/org/gtk/settings/emoji-chooser/" (establishing: 0, active: 1)
(dino:19497): Gtk-DEBUG: 17:37:43.412: Found emoji data for de in resource /org/gtk/libgtk/emoji/de.data
```

This issue appears after upgrading to gtk3-3.24.30 on Fedora 34. This version [does introduce some changes](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/NEWS) for the GtkEmojiChooser.

**Comment by ericschdt** [comment]
Same issue on recent openSUSE TW obviously.

**Comment by jscott0** [comment]
Just for the record, I wanted to point out that we [discovered in Debian](https://bugs.debian.org/992627) that this can lead to crashes as well.
