### ISSUE TITLE
Enable OMEMO encryption by default

### ISSUE THREAD

**Issue by rdravi110** [dino/dino#1087]
I am using Dino in Debian 11. Whenever, I send a message to a new contact using Dino, I have to enable encryption manually. I sometimes forget to do so and send a few unencrypted messages and then realize that the encryption is off. I think users new to XMPP won't even enable it manually and therefore might end up sending a lot of unencrypted messages. 

I request you to include OMEMO encryption by default in Dino.

**Comment by fiaxh** [comment]
This is a duplicate of #844.

**Comment by rdravi110** [comment]
How do I enable OMEMO in settings?

**Comment by licaon-kter** [comment]
@rdravi110 per chat only, there's no global toggle (yet)
