### ISSUE TITLE
missing download links for portable binaries

### ISSUE THREAD

**Issue by Tcll** [dino/dino#1099]
where do you guys provide an ELF.tar.gz or Appimage??

**Comment by licaon-kter** [comment]
/close as duplicate https://github.com/dino/dino/issues/278

Which OS do you have? No builds in OBS repo?

**Comment by Tcll** [comment]
I have a glibc 2.23 OS, but that shouldn't matter...

don't you guys have a portable binary that works across all linux distros??
(the 2 formats listed above are the best)

**Comment by fiaxh** [comment]
We don't provide Dino in those two formats at the moment.

**Comment by docop** [comment]
This is quite a great soft and the used of Appimage can be quite great and make use dino on any machine. with all dependencies and on so...  a simple portable app .  Any news if it's coming ?
