### ISSUE TITLE
Loss of messages in private MUC caused by wrong URI

### ISSUE THREAD

**Issue by danjde** [dino/dino#1104]
Hi Devs!
We are experiencing loss of messages in private room, where multiple servers interact with each other and every user uses OMEMO.

This issue for now occurs only with Dino and occasionally Converse.js, while it does not occur with Conversations (Android) and Gajim (Linux).

if we can provide you with more details please ask.

Thanks!

**Comment by licaon-kter** [comment]
There's no MAM in MUCs yet, is this about that or?

**Comment by danjde** [comment]
Done, close.
