### ISSUE TITLE
Dino is not opening

### ISSUE THREAD

**Issue by Wuuko** [dino/dino#1109]
fedora 34
gnome
HP HP Pavilion Gaming Laptop 15-ec0xxx
AMD® Ryzen 7 3750h with radeon vega mobile gfx × 8
64-bit

**Comment by licaon-kter** [comment]
See Wiki above, then Debugging, use `--print...` commands to get some info about why it doesn't start

**Comment by fiaxh** [comment]
We will need more information to debug this. Please open Dino from the Terminal to look for *why* Dino is not opening. Does it crash? If so, please obtain a [stack trace](https://github.com/dino/dino/wiki/Debugging#stack-trace) with gdb.

**Comment by fiaxh** [comment]
Sorry, but we won't be able to understand your issue without further information. If you provide terminal logs or a stack trace, I'll reopen this issue.
