### ISSUE TITLE
Encryption jumping back to disabled for an existing chat

### ISSUE THREAD

**Issue by mmahmoudian** [dino/dino#1112]
As [suggested by Marvin](https://mastodon.social/@larma/106974584083440847), I'm opening this bug report.

I have realized that the OMEMO have switched back to disabled in an existing chat. Up to some point it was enabled and was working but from some point I realized my chat are not encrypted.

![image](https://user-images.githubusercontent.com/390889/134323225-a5b56041-04bc-461a-a9e1-beda6f9f151c.png)

Now, I wish:
1. This would have never happened
2. There is a safeguard that if such thing is happening, I get a warning before sending it.
3. There was a way to always enforce encryption (OMEMO, PGP, etc.) in any chat regardless of being new or not
4. There was an option to set the background color of the text to something like red or salmon if the text was unencrypted.

I'm using v0.2.1 of Dino on the following machine:
```sh
inxi --system --width 80
```

> ```
> System:
>   Host: precisiontower Kernel: 5.10.63-1-MANJARO x86_64 bits: 64
>   Desktop: KDE Plasma 5.22.5 Distro: Manjaro Linux
> ```

**Comment by mar-v-in** [comment]
For clarification/confirmation:
1. Was the unencrypted message send from the same device / OS / linux user as the encrypted message?
2. Did the encryption selector (bottom right) also switch to unencrypted? (in the screenshot it's already back to encrypted)
3. Was the message flagged as received (single tick) or read (double tick) in the meantime?
4. Was the unencrypted message actually send and shown to the recipient?

**Comment by mmahmoudian** [comment]
> Was the unencrypted message send from the same device / OS / linux user as the encrypted message?

I don't know how to double check it, but as far as I can recall, yes. If you know where to see the log files or meta-data of the messages, I'll be happy to check them and provide them as far as it does not contain personal information.

> Did the encryption selector (bottom right) also switch to unencrypted?

exactly as it shows in the screenshot

> Was the message flagged as received (single tick) or read (double tick) in the meantime?

exactly as it shows in the screenshot

> Was the unencrypted message actually send and shown to the recipient?

no because the recipient is still offline (I confirmed through other communication channels)

**Comment by mar-v-in** [comment]
Thanks.

> I'll be happy to check them and provide them as far as it does not contain personal information.

You can display the sending devices "resource" - some public device identifier used in XMPP.

```bash
$ sqlite3 ~/.local/share/dino/dino.db 'select our_resource,body from message join jid as peer on counterpart_id=peer.id where direction = 1 and peer.bare_jid = "[your-contact-jabber-address-here]"'
```

The above command will display the resource before each message you send to that contact, separated by a `|`. If it's the same resource for both messages, it's the same device and configuration for both messages. It should be something like `dino.12345678` for Dino and something very different for other clients.

You can display the currently used resource (prefixed with your account address) using the following command:
```bash
$ sqlite3 ~/.local/share/dino/dino.db 'select bare_jid,resourcepart from account'
```

The only thing I'd need to know is if the resource displayed for each of the messages sent match the current resource.

**Comment by mmahmoudian** [comment]
> You can display the sending devices "resource" - some public device identifier used in XMPP.

Thanks for the sqlite command. now this is when it gets confusing. I have Dino on 2 computers and also I have an XMPP client on my phone. It is easy to know which one is the phone because of the client, but that leaves me with 

`dino.124f27f6`  definitely this computer because I just sent another message and checked it. This is the same for messages before OMEMO activation and after.
`dino.b93982b8` which probably is my other computer but it has only sent unencrypted message before based on the Dino's chat window. At the moment I don't have access to that computer but I will report back in some hours.

**Comment by mar-v-in** [comment]
So the main issue here is probably that we don't synchronize the encryption status between clients on multiple devices, right?

**Comment by mmahmoudian** [comment]
I'll get back to you when I checked the situation on the other computer. I think any conclusion at this point is premature as it can well be another case of PEBCAK 😅

**Comment by mmahmoudian** [comment]
The `dino.b93982b8` is my other computer. One thing that is very interesting and surprising is that the current state of that Dino is encrypted! I have no idea when I have turned it on. So considering that the OMEMO is per chat, It would be a good idea to also:
1. in the sqlite record when the encryption has been turned on as a record with the local date and time 
2. in the chat window also show a record when the status is changed (possibly encryption "off" with red background and "on" with green?)

I close this issue as it clearly is my mistake. Thanks for putting time into this and also sorry for wasting your time.
