### ISSUE TITLE
Invalid TLS certificate (Let'sEncrypt issue)

### ISSUE THREAD

**Issue by danjde** [dino/dino#1115]
Hi Devs,
I am writing to you only to report the issue.
After the last renewal of Let'sEncrypt certificate, Dino (no Conversations, Converse.j, and others client) show me the error message "Invalid TLS certificate" blocking the servers connection.

I've open an help request on Let'sEncrypt  community forum, where seems the issues caused from " Multiple CA certificates  expired very recently" as suggested by Nummer378: https://community.letsencrypt.org/t/chain-of-trust-not-ok-expired-for-dino-xmpp-client/160992

Server side (Prosody) all seems working fine.

davide

**Comment by mar-v-in** [comment]
Dino uses the OS certificate store to validate the certificate offered by the server.

Until recently, the Let's Encrypt certificates was considered valid either through their official root CA (ISRG Root X1) or via cross-sign from IdenTrust (DST Root CA X3). The latter expired by end of September and the cross-sign will thus not be considered valid by clients (except on Android, which doesn't care about expiry dates of root CAs).

Most platforms do support the ISRG Root X1, for a complete list see https://letsencrypt.org/docs/certificate-compatibility/.

So the relevant question here is what operating system and version you use. Firefox and some other browsers come with their own set of trusted CAs and thus are not affected if ISRG Root X1 is missing from the system certificate store (and thus Converse.js would also not be affected). On many systems you can add ISRG Root X1 manually if it's missing.

**Comment by danjde** [comment]
We are using, server side, Debian9 (and Prosody 0.11.5-1), updating SO to the latest updates could it be enough to fix the issue?
If this is right, this means that outdated systems will be excluded, just in case could you give us a tips to add ISRG Root X1 manually if missing?


Thanks!

**Comment by mar-v-in** [comment]
This is about the client side operating system that runs Dino, not the server. The exact procedure to add ISRG Root X1 depends on the clients operating system.

The server you provided in letsencrypt community (3x1t.org) seems fine to me, I verified that Dino on my local device (Debian testing) can connect to it.

**Comment by ThomasAH** [comment]
On Debian 9 you need to either install the lasted security update for openssl ... or edit /etc/ca-certificates.conf, put "!" in front of the line "mozilla/DST_Root_CA_X3.crt" and run update-ca-certificates.

**Comment by danjde** [comment]
Well, 
solved "server side" regenerating Letsencrypt certificate (using acme.sh) using option:

--preferred-chain  "isrg"

this should leave the task to the client operating system to provide the missing certificate.
Working on Debian9

Thanks!

**Comment by mar-v-in** [comment]
Glad it worked out for you.

FYI, the new server setup may cause problems with clients running on Android < 7.1
