### ISSUE TITLE
"omemo" not a valid MIME type

### ISSUE THREAD

**Issue by Zash** [dino/dino#1116]
https://github.com/dino/dino/blob/7ce49d7d68f19fb49a33e907485d83da2c9131a3/plugins/omemo/src/file_transfer/file_encryptor.vala#L41

That's not a [valid MIME type](https://datatracker.ietf.org/doc/html/rfc2045#section-5.1).

If the goal is to hide the real content type, why not set it to `application/octet-stream` or something overly generic like that?

**Comment by sunny775** [comment]
Hi @Zash @mar-v-in 👋
I'm a GSOC student, and particularly interested in the project: "Add support for attaching and displaying link metadata in dino using the OpenGraph protocol". I have some idea of OpenGraph protocol, and I'd love to learn Vala

I'd like to take on this issue as part of my qualifying contribution
Please assign

**Comment by mar-v-in** [comment]
Hi @sunny775 

Great to see you being interested in contributing to Dino as part of GSoC.
I assigned the issue to you. Please understand the teaser task not only as its verbatim task, but also as an opportunity to set up your dev environment and to get familiar with the codebase.
If you have any questions, don't hesitate to ask in our public channel.

**Comment by sunny775** [comment]
Thanks! @mar-v-in
