### ISSUE TITLE
DTLS(-SRTP) fingerprint formatting

### ISSUE THREAD

**Issue by defanor** [dino/dino#1118]
Currently [Dino uses "%02x" to format XEP-0320 fingerprint octets](https://github.com/dino/dino/blob/c85945ae26cab7eb65c67dbe49ebbf668a028b1c/plugins/ice/src/dtls_srtp.vala#L343), but [XEP-0320](https://xmpp.org/extensions/xep-0320.html) is based on the [RFC 4572's Fingerprint Attribute](https://datatracker.ietf.org/doc/html/rfc4572#section-5), which requires uppercase hexadecimal bytes; would be nice to replace it with "%02X".

**Comment by mar-v-in** [comment]
Fixed in 51dc41463134a07a5768fcd46243f97f8da077bb
