### ISSUE TITLE
Messages consisting of certain numbers aren't immediately rendered

### ISSUE THREAD

**Issue by kmq** [dino/dino#1129]
Steps to reproduce
---------------------------

Open Dino and send a contact the string  10826 - that is, a message consisting only of these digits. The actual numbers affected are probably different to every installation. On my instance there are thousands of numbers exhibiting this problem.

Expectation
----------------

Dino should send this message to my contact and display this message in the conversation view

Reality
----------

The message is sent to the contact, but it does *not* show up in the conversation view. It is correctly transmitted to my other devices as a sent message. Only when I switch to a different contact, and then back to the original contact, is my message visible.

Cause
---------

After I hit send, the message passes through the function `announce_message` where it is filtered out by the call to `discard` https://github.com/dino/dino/blob/8339d95621530664b8306b8b033976529510ed17/libdino/src/service/content_item_store.vala#L168

`discard` calls a [`FileMessageFilter`](https://github.com/dino/dino/blob/master/plugins/http-files/src/message_filter.vala)  which in turn calls [`message_is_file`](https://github.com/dino/dino/blob/8339d95621530664b8306b8b033976529510ed17/plugins/http-files/src/plugin.vala#L29). The heuristic used to determine if message_is_file is
to check the dino database if an item like this exists:

```
SELECT * FROM file_transfer WHERE info = message.id OR info = message.body";
```

If it does, the message is 'discarded' - but it seems still inserted in the database.

The logic for initially populating the conversation view doesn't have the messages go through this logic,  but rather just pulls a list of messages of the database and displays them, that's why the message then shows up.

I didn't figure out why this filter is applied in the first place.

**Comment by fiaxh** [comment]
Thanks for investigating this, it was really helpful :)
