### ISSUE TITLE
Plans to port on Windows/Mac?

### ISSUE THREAD

**Issue by Echolon** [dino/dino#113]
Just like to ask whether you have plans to release for windows and mac, too?

Kind regards

**Comment by linkmauve** [comment]
From a quick look around, nothing in the code seems to be specific to Linux, if you are interested in that port it should be straightforward.

**Comment by Echolon** [comment]
Thanks - but I'm not a programmer - Just intended to discuss this option - maybe someone else can do the effort.
Cheers!

**Comment by fiaxh** [comment]
Dino can already be compiled for Windows. We will probably provide a build as soon as there is a release.

_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Echolon** [comment]
Okay, nice - thanks for your work. Looking forward!
