### ISSUE TITLE
[Feature Request] New Setting: Preferred Encryption Method.

### ISSUE THREAD

**Issue by Jieiku** [dino/dino#1136]
A new setting that allows you to select your preferred encryption method would be great. All of my contacts use omemo so it would be great if I could make it so that omemo is always my selected form of encryption when opening dino or a new chat in dino.

**Comment by xekon** [comment]
the titles on all the other issues I see seem to be asking for encryption by default, but I would be happy just having a setting in the settings where I can specify my preferred encryption.

**Comment by licaon-kter** [comment]
Same thing, yes

**Comment by theotheroracle** [comment]
https://github.com/dino/dino/pull/1236

**Comment by fiaxh** [comment]
OMEMO by default was added as an option as part of https://github.com/dino/dino/commit/21ae42762d8a57da5cb1ec40b46e7510fc3121ad.
