### ISSUE TITLE
OMEMO the message is not encrypted for this device

### ISSUE THREAD

**Issue by BentiGorlich** [dino/dino#1151]
I use an account on a openfire server with 2 devices: Dino for windows and Conversations on my phone. My Contact uses Dino for windows as well and when he sends me a message it just says "The message was not encrypted for this device".
When he goes to my profile it says "2 OMEMO devicves" but one of the keys is deactivated

**Comment by licaon-kter** [comment]
Do you both see eachothers keys?

**Comment by BentiGorlich** [comment]
yes, he sees both keys and one is marked as "unused"
I see his key on both devices

**Comment by licaon-kter** [comment]
Unused means "do not encrypt to it"

**Comment by BentiGorlich** [comment]
But why do I see the mentioned message then?

**Comment by BentiGorlich** [comment]
Additionally I cannot force Dino to use it. It is under "Inactive Keys". He did already proof the key, because I thought that might help, but it did nothing

**Comment by licaon-kter** [comment]
All your devices advertise all their keys? Your contact sees them all and trusts them?

**Comment by BentiGorlich** [comment]
exactly

**Comment by licaon-kter** [comment]
If using the Windows version, you might need to report this to the unofficial repo and/or support channel. Not here.

**Comment by BentiGorlich** [comment]
yeah, could be, but they don't have issues in their repo and Dino won't join their channel...

**Comment by licaon-kter** [comment]
@lagonauta ^^^^

**Comment by LAGonauta** [comment]
Just enabled issues over there, please copy the issue to it:
https://github.com/LAGonauta/dino/issues

**Comment by BentiGorlich** [comment]
Created it: LAGonauta/dino#6
