### ISSUE TITLE
Images dont received

### ISSUE THREAD

**Issue by BentiGorlich** [dino/dino#1152]
Server: openfire
Sender: Dino for Windows
Receiver: Conversations for Android and Dino for windows

When my contact sends images I don't see anything in Dino. I see them on Conversations, but there they are just grey. I already opened an issue there: iNPUTmice/Conversations#4240

**Comment by licaon-kter** [comment]
Encrypted or not? What kind of images? Format? Attach a sample...

**Comment by BentiGorlich** [comment]
It says not encrypted on my phone, but I doubt that he switched it off just to send me the images, so eigher Dino for Windows switches it off for images automatically, or it is just wrong what the app sais

**Comment by licaon-kter** [comment]
If using the Windows version, you might need to report this to the unofficial repo and/or support channel. Not here.

**Comment by fiaxh** [comment]
> When my contact sends images I don't see anything in Dino.

If your server doesn't support http file upload, the file would be transferred via Jingle, which means that only one receiver gets the file - in this case Conversations. This would also happen if the file is too big for http file upload.

> I see them on Conversations, but there they are just grey.

That could mean that Conversations can't display the file type, that the Windows build of Dino somehow sends the wrong stuff, or that there was a human error for example sending the wrong image.
