### ISSUE TITLE
25s delay in startup 

### ISSUE THREAD

**Issue by tuxcodejohn** [dino/dino#1155]
Hi, 
I have a starting issue with dino for longer (also current version): When I start dino it seems like nothing happens for about 25 seconds, then it starts normally. I tried some things to get a idea what is happening:
strace dino:
I see ther is a poll systemcall with 25 seconds timeout  on an fd that dino got with eventfd2 this runs into the timeout and then dino starts normal like it did some years ago :)

When I start dino with _G_MESSAGES_DEBUG=all_ the last thing before nothing happens is this:
```
(dino:1376767): Gtk-DEBUG: 21:54:40.243: Connecting to session manager
(dino:1376767): Gtk-DEBUG: 21:54:40.243: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(dino:1376767): Gtk-DEBUG: 21:54:40.244: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
```
and the first thing after is this:

```(dino:1376767): GLib-GIO-DEBUG: 21:55:05.590: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(dino:1376767): dconf-DEBUG: 21:55:05.590: watch_fast: "/org/gtk/settings/emoji-chooser/" (establishing: 0, active: 0)
(dino:1376767): dconf-DEBUG: 21:55:05.591: watch_established: "/org/gtk/settings/emoji-chooser/" (establishing: 1)
``` 

Does anyone have a suggestion what I can check, to get decent startup performance?

**Comment by jugendhacker** [comment]
Maybe `--print-xmpp=all` might help to look at what's going on at the XMPP side.

**Comment by licaon-kter** [comment]
After https://github.com/dino/dino/commit/975b37c498f2611bc7f13017d4491961426a8a7f I see Dino start really fast, maybe update and retest?

**Comment by tuxcodejohn** [comment]
@jugendhacker  Thank you for the suggestion, but the mystery wait seems to be before any messeage gets logged. When 25s are over dino starts really fast, with all the xmpp debug output.... 

@licaon-kter I tried also newest git version (eefce3fd). No change... The commit messages  in between suggest to deal with things that are already behind my mystery wait.

During the wait time not even a window has been drawn. I don't think there is some network or protocoll related waiting issue.

My guess is, that i see some gui /system integration effect, that waits for something not present in my setup very early in the program start...

**Comment by licaon-kter** [comment]
Try `strace` or `gdb` to get more info?

**Comment by tuxcodejohn** [comment]
yes, gdb helped ... I was able to track down the function that takes long. Its from libdino/src/dbus/notifications.vala:23 and I made a small example from it:

	[DBus (name = "org.freedesktop.Notifications")]
	public interface DBusNotifications : GLib.Object {

		public signal void action_invoked(uint32 key, string action_key);

		public signal void notification_closed (uint32 id, uint32 reason);

		public abstract uint32 notify(string app_name, uint32 replaces_id, string app_icon, string summary,
					       string body, string[] actions, HashTable<string, Variant> hints, int32 expire_timeout) throws DBusError, IOError;

		public abstract void get_capabilities(out string[] capabilities) throws Error;

		public abstract void close_notification(uint id) throws DBusError, IOError;

		public abstract void get_server_information(out string name, out string vendor, out string version, out string spec_version) throws DBusError, IOError;
	}

	void main() {
		DBusNotifications upower = null;
		try {
		    upower = Bus.get_proxy_sync(BusType.SESSION, "org.freedesktop.Notifications", "/org/freedesktop/Notifications");
		    string oname;
		    string ovendor;
		    string oversion;
		    string ospec;
		    upower.get_server_information(out oname,out ovendor,out oversion,out ospec);
		    stdout.printf("%s\n%s\n%s\n%s",oname,ovendor,oversion,ospec);
		} catch (IOError e) {
		    warning("Couldn't get org.freedesktop.Notifications DBus instance: %s\n", e.message);
		}

	}

I compiled with 
    	       valac --pkg gio-2.0 blah2.vala
and it took the exact 25s  (mainly in   Bus.get_proxy_sync)   to output this:

    naughty
    awesome
    v4.3
    1.0

**Comment by tuxcodejohn** [comment]
I guess this is no dino issue any longer then.... Maybe somebody who knows more about notificationBus stuff or vala in gerenel has any idea anyways....

**Comment by fiaxh** [comment]
While it's odd that your dbus takes 25 seconds to respond, we should use dbus with async functions anyways. I did that change in b7ca33a37de5dd2ecffa7575681c6009996b7ba2. Notifications will be queued until the dbus interface is loaded now. In your case it will lead to notifications appearing only after 25 seconds, but Dino should otherwise start.

**Comment by selurvedu** [comment]
This fixed 25 s delay for me, thanks!

**Comment by tuxcodejohn** [comment]
Year! That totally fixes the startup for me to. Thanks a lot! <3
