### ISSUE TITLE
Audio calls are broken on linux.

### ISSUE THREAD

**Issue by crocket** [dino/dino#1156]
I tried to make audio calls between two dino instances on 404.city

Both dino instances are 905f93bcccd26a035cc9d37378b45ff87298adb5

They keep connecting without really connecting.

Someone reported audio calls work for dino on windows, but not on linux.

Dino can still make unencrypted audio calls with gajim over 404.city

Operating System:
Gentoo Linux
Artix Linux

I haven't tried video calls.

**Comment by licaon-kter** [comment]
Logs of it failing?

**Comment by crocket** [comment]
It turned out that I needed to enable netlink protocol in firejail sandbox.

Without netlink protocol, audio/video calls keep connecting for ever.

By the way, if I run dino with torsocks or inside a network namespace subject to tor transparent proxy with firejail, the audio calls keep connecting for ever, too. I guess audio/video calls don't really work over tor yet on dino?

**Comment by licaon-kter** [comment]
TURN is over UDP usually.

**Comment by crocket** [comment]
If 404.city configured TURN over TCP, would it support tor?

**Comment by licaon-kter** [comment]
Dunno, might...
