### ISSUE TITLE
Own nickname not shown in outgoing MUC messages

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#116]
When you participate in a MUC, your messages are shown as originating from your account's "Local alias", as opposed to your nickname in the MUC. This is very confusing, especially when you consider the "local alias" to be an account name and not your nickname to show to others. It took @linkmauve 's hint to realize where the displayed string is even coming from in my setup...

Please make the MUC display your actual nickname in that MUC to reduce confusion.

**Comment by fiaxh** [comment]
Nicks are now shown for all occupants, including oneself (5fcf8e7).
