### ISSUE TITLE
Making xmpp-vala as an independent library

### ISSUE THREAD

**Issue by pravi** [dino/dino#1169]
Background: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/454

This would allow chatty to use this library instead of libpurple which is old and a blocker for adding to official gnome.

Side note: Wouldn't Dino itself a good fit for being included in official gnome ? Empathy seems not active.

**Comment by licaon-kter** [comment]
Do they still NEED for app name = app purpose? Eg. Dino means nothing, Chat is taken? :)

**Comment by fiaxh** [comment]
I believe the chatty developers are aware of the existence of libdino and decided for libpurple on purpose. However, if the We didn't plan on split out libdino just yet, but if the chatty developers are interested in using libdino in that they can contact us and we might be able to find a solution.

> Side note: Wouldn't Dino itself a good fit for being included in official gnome ? Empathy seems not active.

I think that the GNOME maintainers made it quite clear in the issue you linked that they don't want an XMPP client in their ecosystem.

**Comment by ppibburr** [comment]
I also think xmpp-vala should be more public facing.
