### ISSUE TITLE
Chat State Notifications show bare MUC JID in a MUC, not nickname

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#117]
When somebody is typing in a MUC, dino shows "dino@chat.yax.im is typing..." with the bare JID of the MUC.

It should display the nickname of the active user (or the nicknames if multiple people are typing).

**Comment by ThibG** [comment]
The behavior seems to have partially changed, or is not exactly the one described in the bug report: it only happens as described if the chatstate was received prior to switching to the conversation. If the chatstate is received afterwards, the proper nick is displayed (at most one nick at a time, though)
