### ISSUE TITLE
Crash due to markup parsing error in 0.2.1 and 0.2.2 (message contains umlauts)

### ISSUE THREAD

**Issue by mjk-gh** [dino/dino#1172]
After I finally found an ncurses XMPP client that seemed to half-way work (Profanity 0.11.1),
I used it to type messages containing umlauts. As it seems, Profanity can only deal with
UTF-8 and not my system locale of ISO-8859-15. As a result, the umlauts of these messages
are displayed as inverse question marks in a square on its tip in the Android app "Conversations",
and the app seems to otherwise work just fine.

dino, however, crashes as soon I left-click on a conversation containing such an umlaut message.

Version `0.2.1+git20210824.93e2e0d-1~bpo11+1` (I'm using Debian stable on amd64) says:

```
$ dino-im

(dino-im:16424): Gtk-WARNING **: 22:36:53.845: Failed to set text 'Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn&apos;s rot oder unlesbar ist. :)' from markup due to error parsing markup: Error on line 1 char 114: Invalid UTF-8 encoded text in name ? not valid ?Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn's rot oder unlesbar ist. :)?

(dino-im:16424): Gtk-WARNING **: 22:36:53.846: Failed to set text 'Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn&apos;s rot oder unlesbar ist. :)' from markup due to error parsing markup: Error on line 1 char 114: Invalid UTF-8 encoded text in name ? not valid ?Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn's rot oder unlesbar ist. :)?
zsh: segmentation fault  dino-im
```
(That \xf6 is an o-umlaut ("ö"))

While the freshly home-compiled version `0.2.2` from github succinctly states:

```
zsh: segmentation fault  /usr/local/bin/dino
```

**Comment by mjk-gh** [comment]
Wanted to try the current git version to see if it fixes this issue. After
installing tons of new dependencies, I finally managed to compile
and install it. It did not install libcrypto-vala.so.0, that seems to be
needed, though, so I used LD_PRELOAD to point to the libcrypto-vala.so.0
that got installed by the Debian Backports package of "dino-im":

```
$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/dino-im/libcrypto-vala.so.0 /usr/local/bin/dino

(dino:2084): Gtk-WARNING **: 23:15:09.118: Failed to set text 'Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn&apos;s rot oder unlesbar ist. :)' from markup due to error parsing markup: Error on line 1 char 114: Invalid UTF-8 encoded text in name ? not valid ?Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn's rot oder unlesbar ist. :)?

(dino:2084): Gtk-WARNING **: 23:15:09.118: Failed to set text 'Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn&apos;s rot oder unlesbar ist. :)' from markup due to error parsing markup: Error on line 1 char 114: Invalid UTF-8 encoded text in name ? not valid ?Noch ein kurzer Test, wohl kein ACK von Euch n\xf6tig ... nur ein NAK, wenn's rot oder unlesbar ist. :)?
zsh: segmentation fault  LD_PRELOAD=/usr/lib/x86_64-linux-gnu/dino-im/libcrypto-vala.so.0 

```

At least it's as talkative as 0.2.1 again, but it still crashes due to that umlaut.

**Comment by mar-v-in** [comment]
XMPP is strictly UTF-8 as per [RFC 6120 § 11.6](https://datatracker.ietf.org/doc/html/rfc6120#section-11.6), so if Profanity allows you to somehow send non-UTF-8 encoded strings, please also open an issue with them.

Are you using OMEMO or OpenPGP encryption?

**Comment by mjk-gh** [comment]
Wow, there is even an RFC for XMPP, didn't know that, thanks!

I will check profanity's issue tracker.

I am using OMEMO.

**Comment by mjk-gh** [comment]
But even if Profanity gets fixed, the wrongly encoded umlaut is still part of the chat,
and I would love to continue that chat using Dino. :-} Replacing the umlaut by a
question mark or even replacing the complete message with "This message contains
character encoding errors and cannot be displayed", everything would be better
than Dino crashing.

**Comment by mjk-gh** [comment]
Opened an issue for Profanity:

https://github.com/profanity-im/profanity/issues/1626

**Comment by mar-v-in** [comment]
As you are already compiling yourself from source, can you try if adding
```vala
if (body != null) body = body.make_valid();
```
after
https://github.com/dino/dino/blob/447464f4d1ac0c184764f103ac9e51f7ff2dce91/libdino/src/entity/message.vala#L97
solves the issue for you?

**Comment by mjk-gh** [comment]
Yes, it does, perfectly! No crashes anymore, and the wrongly encoded umlauts are
replaced with [https://www.fileformat.info/info/unicode/char/fffd/index.htm](Unicode REPLACEMENT CHARACTER)!

Thank you very much! Thou shalt be drowned in cuddles! <3
