### ISSUE TITLE
Closing all chats, than joining MUC opens the last closed chat instead

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#118]
Steps to reproduce:

1. Open a chat with a friend
2. Close the chat again
3. Join some MUC

Expected result:
* you see the MUC chat window

Actual result:
* you see the chat log of your friend in the right pane, and the MUC listed in the conversations pane.

Clicking the MUC in the left pane shows the expected chat log.

**Comment by fiaxh** [comment]
This does not happen anymore on current master.
