### ISSUE TITLE
Consider move to libadwaita

### ISSUE THREAD

**Issue by mossymossmoss** [dino/dino#1182]
GNOME 42 will move all core apps to use libadwaita, as it is the successor to libhandy. Moving Dino to libadwaita would help it to fit in with other GNOME applications

**Comment by Zash** [comment]
As I understand this is already the plan per https://github.com/dino/dino/issues/178#issuecomment-981101970

**Comment by mossymossmoss** [comment]
Great news! It would be good to have a responsive interface in main

**Comment by fiaxh** [comment]
Dino uses libadwaita now.
