### ISSUE TITLE
Input box - no scrolling with arrow keys

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#1188]
Linux, Debian Sid, amd64, self build 1e63cb3bd935ad42af7b203efc5f4f83ae131e58

In the input box, paste a looooooong text.

I can scroll by mouse wheel just fine, there's a scroll bar too.

But, arrow down/up does not scroll down/up... the cursor just disappears below/above.

**Comment by sonicnkt** [comment]
With 0.2.2 in the manjaro repos this works fine.

![Peek 2022-01-31 08-54](https://user-images.githubusercontent.com/5454622/151757293-64bf6d09-a300-44f6-80c5-a90f9dd8f59a.gif)

**Comment by licaon-kter** [comment]
Well, there are commits on top of 0.2.2 so maybe https://github.com/dino/dino/commit/eefce3fd81d7fcb349acb073941ebf5ca9140507 is at fault.

Will try to bisect asap.
