### ISSUE TITLE
encryption in MUCs no longer possible?

### ISSUE THREAD

**Issue by IzzySoft** [dino/dino#1191]
I'm participating in multiple MUCs, two of them had encryption enabled. This worked fine with Dino until a few weeks ago (and still works fine with Conversations).

A week or two ago we noticed that in one room several of us were no longer able to send encrypted messages with Dino. So just to try, we disabled OMEMO to send an unencrypted message (worked), then re-enabled OMEMO (sending no longer worked). Until we forgot to re-enable OMEMO before switching to another channel. Returning, the lock symbol was gone.

I've checked all MUCs I'm in, none of them has the lock symbol anymore – so I cannot even try whether it was just a temporary glitch (e.g. caused by one member having added a new device, and then went offline), as OMEMO can no longer be enabled. Not even for new MUCs.

As this only affects Dino, and those members using Dino, I wonder if there was a corresponding change? I could find no matching issue or commit so far, but at least for the latter I only checked commit messages and thus might have missed it. All of use use Dino on Linux, and most of us the (latest) version coming via the PPA, in case that matters. Those MUCs with encryption have only few members (4..8 participants).

**Comment by licaon-kter** [comment]
Can you explicitely say which version the About screen lists?

Try to get some error messages from the console via --print, https://github.com/dino/dino/wiki/Debugging

**Comment by IzzySoft** [comment]
@licaon-kter I can, but that value changes at least twice a week. Currently it's `0.2.0~git226.20220206.5ed8d28a-1`, yesterday's update. There were at least 4 updates since this first happened. `G_MESSAGES_DEBUG=OMEMO dino` gives no clue. Just a load of `received device list for` messages. Setting it to `all` floods the terminal, but I see nothing related. Using `OMEMO,libdino` (to focus on the relevant parts) looks OK. A single `Received OMEMO encryped message that could not be decrypted` is all I can find – but a single one cannot count for multiple MUCs. And even if there's such a message in each of the MUCs, this does not explain why I cannot turn on encryption for messages I write.

That said, I can **read** encrypted messages in those MUCs just fine, and they show up as being encrypted. I just cannot turn encryption on for messages **I** want to send via Dino in a MUC (I can do so in 1:1 chats, so it's clearly bound to MUCs). No "lock toggle" visible in any of the MUCs I participate.

**Comment by licaon-kter** [comment]
@IzzySoft did "show all jids" muc settings fix it for everyone?

**Comment by IzzySoft** [comment]
It seems it did fix this issue, yes – though we still have weird behavior with encryption we're trying to sort out (one (Android) device seems unable to communicate encrypted in the MUC, though it can do so fine in all 1:1 chats), I don't think those are related – and more specifically, are not Dino-specific as we can reproduce them on other clients as well. The lock symbol is back for everyone who reported so far (one person is still AWOL).

Thanks a lot for taking the time to debug this with me! I never thought those settings would be related (as I told you, I just inherited ownership of the room, and this problem only came up months after that). Apologies again for the false alert here; as the above issue no longer exists for us, I'm closing this issue then.
