### ISSUE TITLE
./configure errors

### ISSUE THREAD

**Issue by ThomasSensoli** [dino/dino#1193]
Hi,
sorry to disturb you,
i'm trying to install Dino on a MacBook Pro 16-inch/2019 with macOS Monterey and when i do

$ brew sh
$ ./configure

it gives me the error

```
CMake Error at /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Soup (missing: Soup_LIBRARY)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.22.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSoup.cmake:29 (find_package_handle_standard_args)
  cmake/MultiFind.cmake:20 (find_package)
  plugins/http-files/CMakeLists.txt:1 (find_packages)


-- Configuring incomplete, errors occurred!
See also "/Users/tsensoli/dino/build/CMakeFiles/CMakeOutput.log".
See also "/Users/tsensoli/dino/build/CMakeFiles/CMakeError.log".
```

[CMakeError.log](https://github.com/dino/dino/files/8023260/CMakeError.log)
[CMakeOutput.log](https://github.com/dino/dino/files/8023261/CMakeOutput.log)

i'm not really an expert and i'm using a mac only because of my job, so what can i do to fix it ?

Thank you

**Comment by licaon-kter** [comment]
Due to a recent upgrade from libsoup 2 to 3 by Homebrew try:  `brew link libsoup@2`

**Comment by ThomasSensoli** [comment]
Thanks @licaon-kter , it has been solved:

` brew install libsoup`
` brew install libsoup@2`
` brew link libsoup@2`

deleted the folder dino,
and redone steps 4, 5 and 6 of the guide

Have a nice day
