### ISSUE TITLE
I want to contact the project admin

### ISSUE THREAD

**Issue by Ivans-Git** [dino/dino#1202]
I think it is @fiaxh. Its for removal of personal information

**Comment by fiaxh** [comment]
You can find contact details on [dino.im](https://dino.im).

**Comment by Ivans-Git** [comment]
@fiaxh According to google my email appears on this page: https://git.p2501.de/schorsch/dino/blame/commit/e52a4eacb2a3410a80156a50c267b5ac4b6d49ae/plugins/omemo/po/dino-omemo.pot
 Is there a way to delete it?

**Comment by Ivans-Git** [comment]
@fiaxh @licaon-kter Can you at least remove my data from here? How can I send the mail privately?

**Comment by licaon-kter** [comment]
Did you remove it from Weblate already?

**Comment by Ivans-Git** [comment]
> Did you remove it from Weblate already?

@fiaxh @licaon-kter I do not have the power to delete my public data there or in the repositories, nor do I know how to do it
