### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by xi1976github** [dino/dino#1205]
Building issue on arch:
ninja: error: '/usr/lib/libdl.so', needed by 'libcrypto-vala.so.0.0', missing and no known rule to make it

libdl.so is not in glibc anymore

**Comment by stevenroose** [comment]
What was the solution to this? I'm having the same issue.

**Comment by edenist** [comment]
The issue isn't that libdl is not in glibc any more, it is that it **_is_** in glibc as of v2.34. I haven't checked the various toolchain configs yet, but there could be an edge case which is putting -ldl into a makefile somewhere. 

Just to add a quick [and possibly dirty] solution to those having this issue, you can link to an existing libdl.so file which may still be on your system. 

`ln -s /usr/lib64/libdl.so.2 /usr/lib64/libdl.so`

This works for me on Solus which now has glibc v2.35.
