### ISSUE TITLE
"Click here to start a conversation or join a channel" points to close window

### ISSUE THREAD

**Issue by louwers** [dino/dino#1208]
This is pretty funny, but with window control buttons on the left, the arrow "Click here to start a conversation or join a channel" points to the button to close the window. :laughing: 

![image](https://user-images.githubusercontent.com/649392/156918293-a3809e69-c5c5-48f2-823e-5672b0868afd.png)

**Comment by fiaxh** [comment]
Thanks for reporting. The current Dino version from master does not have such an arrow anymore, which resolves the issue.
