### ISSUE TITLE
How install Dino 0.3 on Librem 5 Byzantium?

### ISSUE THREAD

**Issue by dln949** [dino/dino#1215]
How install Dino 0.3 on Librem 5 Byzantium?

I see how to install 0.2, but not how to install 0.3

**Comment by licaon-kter** [comment]
Using the same steps does not help? What guide did you follow?

**Comment by dln949** [comment]
I'm not aware of a "guide".  

The only way I know to install it is via the Pure Store.  But that installs version 0.2.

**Comment by licaon-kter** [comment]
Then contact said Store and ask them to update.

**Comment by fiaxh** [comment]
As licaon-kter mentioned, the Pure Store is responsible for the Dino version that is available there, not the Dino developers. Also, there's always the option to self-compile.
