### ISSUE TITLE
Can we have ring-tones for incoming calls?

### ISSUE THREAD

**Issue by stormchaser3000** [dino/dino#1219]
As the title suggests. Given that this could potentially be a trivial change, I could attempt to implement it myself if no one else is willing to take this on. I would love to have my computer notify me on an incoming call since I use xmpp with JMP.chat and this ends up being my phone to some extent. I didn't see an existing feature request for this so I figured I would submit one.

**Comment by licaon-kter** [comment]
It does ring once for me. Do detail how you've installed Dino.

**Comment by stormchaser3000** [comment]
> It does ring once for me. Do detail how you've installed Dino.

I installed from source. I get no rings at all.

> /close as duplicate #1088

I was not aware of this issue because I was searching for "ringtone" and "ring tone"... I will continue discussion there.
