### ISSUE TITLE
Dino doesn't connect when using VPN

### ISSUE THREAD

**Issue by ChloeWolfieGirl** [dino/dino#122]
I logged in to some accounts and it didn't connect to any of my accounts, I turned off my vpn to try and update discord, and as I did, I noticed that Dino had connected some of my accounts, when they where connected I messaged my brother, and checked conversations on my phone, and they came through, I then decided to turn on my VPN, and even though it said my account was connected, none of the messages I sent, went through.

I'm using Bitmask on my desktop.

**Comment by fiaxh** [comment]
Dino should now detect that a connection is broken within one minute; if the connection change is done via network manager, directly (f9436b6).
