### ISSUE TITLE
http upload fails

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#123]
Running under Fedora 26, latest version from copr (corresponding to the master branch here), I can't use the newly implemented http_upload. I see the new file icon and can select a file but when I click OK to send the file nothing happens. The command line gives this error:
```
** (dino:11653): CRITICAL **: __lambda5_: assertion 'url_down != NULL' failed
```

**Comment by fiaxh** [comment]
Looking at the stanzas revealed that this issue was due to a bug in an unstable version of prosody.

**Comment by silberzwiebel** [comment]
for the record, here is the corresponding prosody bug (if I got this right): https://prosody.im/issues/issue/968

**Comment by schmittlauch** [comment]
@fiaxh Are you sure about the "unstable version"? I'm running prosody-0.9.12 but am also affected by this bug.

`** (dino:24816): CRITICAL **: __lambda5_: assertion 'url_down != NULL' failed`

**Comment by mar-v-in** [comment]
@schmittlauch Using prosody's http file upload plugin puts your prosody in an "unstable" state as the plugin is still "alpha", it doesn't matter what prosody version you're using.

Ref: https://hg.prosody.im/prosody-modules/file/tip/mod_http_upload/README.markdown#l3

_Sent from my Eterna Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schmittlauch** [comment]
@mar-v-in So it's probably not a fault in prosody itself, but in mod_http_upload.

**Comment by fiaxh** [comment]
Dino is now (3123723) compatible with that behavior of prosody, thus people shouldn't have problems anymore.
