### ISSUE TITLE
It's not possible to LMC after closing and re-opening Dino

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#1239]
Version 0.3

1) Send a message in some public MUC
2) Close Dino
3) Open Dino
4) Try to edit your last message

Result

It doesn't work, there's no option to edit the last message. It works eg in Conversations.

**Comment by licaon-kter** [comment]
Are you an owner/admin/moderator of that MUC?

**Comment by ericschdt** [comment]
> Are you an owner/admin/moderator of that MUC?

Nope

**Comment by licaon-kter** [comment]
Ok, then, on connect to that public MUC, your client doesn't know* that **you** or some other user that had your nick is the rightful person.

*well it could look in its local DB and find the duplicate message then decide locally to allow you to edit it. But only locally for you...

**Comment by ericschdt** [comment]
Looks like a Conversations' bug actually! It shouldn't allow to correct the message after re-connecting.
