### ISSUE TITLE
[Feature request] ability to mute certain chats

### ISSUE THREAD

**Issue by mmahmoudian** [dino/dino#1244]
At the moment (v0.3.0 - Theikenmeer) there is no way to suppress notifications from certain chats. One should either suppress notifications from Dino (all chats get affected) or everything is open. It would be great if user be able to right-click on the chat and mute notifications, and it would be great to be able to have the option to mute it for certain number of hours, or indefinitely. This is because certain groups can be noisy from time to time and it disturb user's focus, but because of other chats user cannot close Dino altogether.

**Comment by lemon-sh** [comment]
What about `Group chat -> Triple-dot menu -> Notifications -> Off`?

**Comment by mmahmoudian** [comment]
Yes, thanks for pointing it out. It is inconvenient but it is the correct answer. The worst thing is there is no icon to show which chats are muted. Also would be nice to have it in a right-click menu. But as you said, the hamburger menu in each chat has the notification.

I'll close this issue then.


Also, to my surprise, it seems this project/repo is not actively maintained anymore:

![image](https://user-images.githubusercontent.com/390889/180648105-fbabd30a-a890-4aea-a932-61a00c881dbf.png)

![image](https://user-images.githubusercontent.com/390889/180648152-48ee23ef-85f7-4559-a7ab-1e405e5cef09.png)


I hope this project doesn't get abandoned.
