### ISSUE TITLE
No package for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by cweiske** [dino/dino#1250]
The official packages on the OpenSuse build server do not have packages for Ubuntu 22.04 LTS (jammy):
https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino

The latest Ubuntu release there is 21.04. Trying to use the dino package for Ubuntu 21.04 on a 22.04 system fails with:
```
# LC_ALL=C apt install dino
The following packages have unmet dependencies:
 dino : Depends: libicu67 (>= 67.1-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

It would be nice if you would provide packages for Ubuntu 22.04.

(Ubuntu itself provides a package dino-im 0.3.0-3, but that is from 2022-02, while official packages here are from 2022-05. https://packages.ubuntu.com/jammy/dino-im)

**Comment by fiaxh** [comment]
We added packages for 22.04.
