### ISSUE TITLE
feature/libhandy: Update feature branch to v0.3

### ISSUE THREAD

**Issue by earboxer** [dino/dino#1251]
This would be useful for [postmarketos](https://gitlab.com/postmarketOS/pmaports/-/blob/master/temp/dino/APKBUILD) so they could have the feature to switch microphone source in a call.

You can rebase to `v0.3.0` in a single hop (see https://github.com/earboxer/dino/tree/feature/handy). Might be nice to tag the feature branch too.

@mimi89999

(Though I do understand the current plan for mobile-friendliness is port to gtk4/libadwaita first)

**Comment by mimi89999** [comment]
Hello,

I don't have push rights to this repo. If only a rebase is needed (and no changes in the code), then the maintainers should do it.

**Comment by stealthgun** [comment]
There need to be changes to the code, tbh it would be even better as the application is just mobile friendly so these changes get pushed to the main branch. But would be very nice if this branch gets more updates since almost all Linux Distro's that support mobile phones use this application.

**Comment by earboxer** [comment]
This is irrelevant now that we're in GTK-4 and https://github.com/dino/dino/pull/1276 exists (just need that to be merged and get a version bump and we'll be good).

**Comment by stealthgun** [comment]
That's fair, it solves the same problem and its in the main branch so I'm all for this. One way or an other making it viable for Mobiles Devices will help a lot for a lot of ppl.
