### ISSUE TITLE
First character after ">" disappears

### ISSUE THREAD

**Issue by clavinet** [dino/dino#1257]
When posting ">", such as when quoting someone, the first character directly after the symbol will disappear.

For example
`>Hello`

becomes
`> ello`

The first letter after ">" gets replaced by blank space.

Dino 0.3.0

**Comment by mar-v-in** [comment]
Fixed on master since https://github.com/dino/dino/commit/1309d7e2e42a1fdced3127c641f108fb72cc2fdd
