### ISSUE TITLE
GTK4 - black border around menus

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#1264]
Dino, b8e84c83268a11ae41ad1d673999362427fd755c, Debian Sid amd64

Same for plus, menu, muc members list

![dinogtk4black](https://user-images.githubusercontent.com/2282799/186023338-4adc374f-916e-485c-b5b7-ab60c9cf6bde.png)

**Comment by fiaxh** [comment]
Can you please check whether you have the same issue in other GTK4 applications?

**Comment by fiaxh** [comment]
To quote Link Mauve's response to you in the Dino Channel from back when you opened this issue: 
> this is a known issue when using X11 without a compositor. You should install a compositor, or use Wayland instead.

**Comment by xuges** [comment]
This is a GTK4 known issue when using without a compositor. Developer can use gdk_display_is_composited() function to check it, and can be use CSS to fix it.

example:

popover contents {
border: 1px solid rgb(150,150,150);
border-radius: 0;
box-shadow: none;
margin-top: -12px;
}

popover arrow {
background: transparent;
border-color: transparent;
}

see: https://bbs.archlinux.org/viewtopic.php?id=294262
