### ISSUE TITLE
GTK4 - keyboard input ignored when menu is open

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#1265]
eg: during https://github.com/dino/dino/issues/1264 I could not press PrtScr to take a screen shot, I could not switch desktops etc

Some keys worked like up/down arrows for main menu or CTRL-G/CTRL-T for plus menu.

**Comment by fiaxh** [comment]
I can reproduce this. However, this also happens in other GTK applications. Thus, this seems to be a GTK-thing. I don't know whether it's a bug or a feature, though.
