### ISSUE TITLE
GTK4 - QR codes don't scale correctly and icon is missing

### ISSUE THREAD

**Issue by mesonium** [dino/dino#1278]
### Issue

The icon for the QR code button is missing and it scales unusable wrong:

![Screenshot_Dino_QR](https://user-images.githubusercontent.com/93607429/190489968-28961e6d-7cfa-4af1-90a5-2c2a7c06f7cb.png)

The rest of the UI scales fine.

### Setup
Dino https://github.com/dino/dino/commit/b8e84c83268a11ae41ad1d673999362427fd755c
Scaling: 200%
openSUSE TW KDE Plasma 5.25.5 Wayland

**Comment by fiaxh** [comment]
The missing icon and the white border are fixed in 146af3152475f12c9b19a92c4779a53f6fc517ce and 146af3152475f12c9b19a92c4779a53f6fc517ce, respectively. The issue with the too-small icon is still open.

**Comment by iampkumar02** [comment]
Hi @fiaxh 
I would like to work on this issue with the too-small QR code. Can you assign this to me?
