### ISSUE TITLE
on first use, OMEMO only works after restart 

### ISSUE THREAD

**Issue by ghost** [dino/dino#128]
Hi,

I just compiled dino from the current master and added an existing account. OMEMO did not work initially. When writing to other people, I was not able to select OMEMO encryption. dino showed me a fingerprint though. After restarting dino, it worked.

Yours
  David

**Comment by NicoHood** [comment]
You need to wait some time. I think this is the same issue as #112

**Comment by MicroJoe** [comment]
I reproduced this after installing dino-git from AUR on Archlinux. Needed to close and reopen for the lock to propose OMEMO crypto.
