### ISSUE TITLE
Dino 0.3.0 dont work on openSuse Thumbleweed anymore

### ISSUE THREAD

**Issue by kri164** [dino/dino#1285]
Hi,

not sure if reporting this issue to right place, but Dino 0.3.0 stopped working on openSuse Thumbleweed 20221008 with error

(dino:29150): libsoup-ERROR **: 11:24:37.094: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
Trace/breakpoint trap (core dumped)

rpm -qi dino
Name        : dino
Version     : 0.3.0
Release     : 1.5
Architecture: x86_64
Group       : Productivity/Networking/Instant Messenger
Source RPM  : dino-0.3.0-1.5.src.rpm
Build Date  : Wed Jun 15 06:53:51 2022
Build Host  : sheep88
Packager    : https://bugs.opensuse.org
Vendor      : openSUSE
URL         : https://github.com/dino/dino

cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20221008"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20221008"

**Comment by kri164** [comment]
Same situation for GAJIM

https://bugzilla.opensuse.org/show_bug.cgi?id=1203676

**Comment by jubalh** [comment]
> Same situation for GAJIM
> https://bugzilla.opensuse.org/show_bug.cgi?id=1203676

This one got solved by temporarily removing the affected code.

openSUSE bug for this issue: https://bugzilla.opensuse.org/show_bug.cgi?id=1204259

**Comment by niclashoyer** [comment]
No solution so far, seems to be a problem with dependencies: https://bugzilla.opensuse.org/show_bug.cgi?id=1203676#c5

**Comment by gllmhyt** [comment]
Happening with Arch Linux since the GNOME 43 update (in testing) too.

**Comment by mar-v-in** [comment]
Before running `make`, run `cmake -B build -DUSE_SOUP3=1` (assuming you use our `./configure` and `make` scripts). This was added only after 0.3.0, we will have to create a 0.3.1 release to backport libsoup-3 support.

**Comment by gllmhyt** [comment]
@mar-v-in It worked! Thanks a lot for the info, it compiled and is running now. I'm passing the message to my distro packagers. Somewhat I lost the dark theme in the process, not a huge problem as I can use the app again.

**Comment by jubalh** [comment]
> Before running `make`, run `cmake -B build -DUSE_SOUP3=1` (assuming you use our `./configure` and `make` scripts). This was added only after 0.3.0, we will have to create a 0.3.1 release to backport libsoup-3 support.
> 
> If any distro wants to backport libsoup-3 support to 0.3.0 already: [baa4a6a](https://github.com/dino/dino/commit/baa4a6a1eb4e98558acfef6e2a24c2c13d42db5c) should be everything needed.

That worked fine. Thank you.
Bug can be closed. openSUSE update is on its way.

**Comment by fiaxh** [comment]
We just released Dino 0.3.1 which includes the libsoup3 support and also some other bugfixes. @jubalh

**Comment by jubalh** [comment]
Thanks, openSUSE package is [updated](https://build.opensuse.org/request/show/1033469).

**Comment by svalo** [comment]
Hello, sorry for the late comment. I've been trying on Archlinux and had problems. It seems that when building in a clean chroot the `ice` plugin somehow gets linked against `libsoup2` while `http-file` is linked against `libsoup3`. When I try to build outside of the chroot everything gets linked against `libsoup2`.

If I build in a clean chroot without `ice` plugin everything works fine and `http-file` is linket against `libsoup3`

Here are some tests I made:

### clean build in chroot cmake flag

* dependency: only libsoup3
* build function:
	```
	build() {
	    cd "${srcdir}/${pkgname%-git}"
	    ./configure $_DISABLE_PLUGINS $_ENABLE_PLUGINS --with-tests --prefix="/usr" CC="$CC" CFLAGS="$CFLAGS" VALACFLAGS="$VALACFLAGS"
	    cmake -B build -DUSE_SOUP3=1
	    make
	}
	```
* plugins enabled: all
* outcome: *broken*
	```
	 pacman -Ql dino-git | grep lib| cut -d ' ' -f 2 | xargs ldd  | grep -e soup -e '^/'
	/usr/lib/dino/plugins/http-files.so:
		libsoup-3.0.so.0 => /usr/lib/libsoup-3.0.so.0 (0x00007ff9d2aea000)
	/usr/lib/dino/plugins/ice.so:
		libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f98435f6000)
	```

### clean build in chroot cmake flag set to 0

* dependency: only libsoup
  Note that libsoup3 is present anyway as it's a dependency of gssdp  gst-plugins-good  gupnp  tracker3
* build function:
	```
	build() {
	    cd "${srcdir}/${pkgname%-git}"
	    ./configure $_DISABLE_PLUGINS $_ENABLE_PLUGINS --with-tests --prefix="/usr" CC="$CC" CFLAGS="$CFLAGS" VALACFLAGS="$VALACFLAGS"
	    cmake -B build -DUSE_SOUP3=0
	    make
	}
	```
* plugins enabled: all
* outcome: *broken*
	```
	 pacman -Ql dino-git | grep lib| cut -d ' ' -f 2 | xargs ldd  | grep -e soup -e '^/'
	/usr/lib/dino/plugins/http-files.so:
		libsoup-3.0.so.0 => /usr/lib/libsoup-3.0.so.0 (0x00007ff9d2aea000)
	/usr/lib/dino/plugins/ice.so:
		libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f98435f6000)
	```

### clean build in chroot no cmake flag

* dependency: only libsoup3
* build function:
	```
	build() {
	    cd "${srcdir}/${pkgname%-git}"
	    ./configure $_DISABLE_PLUGINS $_ENABLE_PLUGINS --with-tests --prefix="/usr" CC="$CC" CFLAGS="$CFLAGS" VALACFLAGS="$VALACFLAGS"
	    make
	}
	```
* plugins enabled: all
* outcome: *broken*
	```
	 pacman -Ql dino-git | grep lib| cut -d ' ' -f 2 | xargs ldd  | grep -e soup -e '^/'
	/usr/lib/dino/plugins/http-files.so:
		libsoup-3.0.so.0 => /usr/lib/libsoup-3.0.so.0 (0x00007ff9d2aea000)
	/usr/lib/dino/plugins/ice.so:
		libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f98435f6000)
	```

### build in system no cmake flag

* dependency: only libsoup3
* build function:
	```
	build() {
	    cd "${srcdir}/${pkgname%-git}"
	    ./configure $_DISABLE_PLUGINS $_ENABLE_PLUGINS --with-tests --prefix="/usr" CC="$CC" CFLAGS="$CFLAGS" VALACFLAGS="$VALACFLAGS"
	    make
	}
	```
* plugins enabled: all
* outcome: *working*
	```
	pacman -Ql dino-git | grep lib| cut -d ' ' -f 2 | xargs ldd  | grep -e soup -e '^/'
	/usr/lib/dino/plugins/http-files.so:
		libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f10eb034000)
	/usr/lib/dino/plugins/ice.so:
		libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f532b25d000)
	```

### build in system cmake flag

* dependency: only libsoup3
* build function:
	```
	build() {
	    cd "${srcdir}/${pkgname%-git}"
	    ./configure $_DISABLE_PLUGINS $_ENABLE_PLUGINS --with-tests --prefix="/usr" CC="$CC" CFLAGS="$CFLAGS" VALACFLAGS="$VALACFLAGS"
	    cmake -B build -DUSE_SOUP3=1
	    make
	}
	```
* plugins enabled: all
* outcome: *working*
	```
	 pacman -Ql dino-git | grep lib| cut -d ' ' -f 2 | xargs ldd  | grep -e soup -e '^/'
		/usr/lib/dino/plugins/http-files.so:
			libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f26a8cb3000)
		/usr/lib/dino/plugins/ice.so:
			libsoup-2.4.so.1 => /usr/lib/libsoup-2.4.so.1 (0x00007f9fdcca7000)
		```

**Comment by mar-v-in** [comment]
Dino's ice plugin does not directly link against libsoup. It uses libnice which uses gupnp-igd which uses gupnp which links against libnice. ldd resolves dependencies recursively so the version of libsoup bring displayed as used by the ice plugin does not depend on the Dino package you use, but depends solely on the versions of gupnp and gupnp-igd installed.

If the versions of gupnp/gupnp-igd installed at build-time don't match the ones at runtime, you're likely to see issues. Based on your description, I'd guess that you have newer versions of those packages in your chroot than you have on the system.

Dino's build system now effectively runs ldd on libnice to figure out the libsoup version to link from the http-files plugin, so those two should always match at build-time.

**Comment by svalo** [comment]
Thank you @mar-v-in I noticed ice plugin didn't directly link against libsoup, Upgrading host system did indeed fix the issue. Thank you and excuse me for the noise
