### ISSUE TITLE
readme does not contain all build dependencies

### ISSUE THREAD

**Issue by NoreSoft** [dino/dino#129]
Hi,

i just compiled the dino from the current master and it seems to me that there are build dependencies, that are not listed in the readme.

On Debian Stable I had to install following additional packages:

libgee-0.8-dev
libsqlite3-dev
libgdk-pixbuf2.0-dev
libgtk-3-dev
libnotify-dev
libgpgme-dev
libgcrypt20-dev
libsoup2.4-dev

Yours
  David

**Comment by fiaxh** [comment]
Except for gdk-pixbuf, the packages you listed are already in the README. gdk-pixbuf however is a dependency of gtk3, which is listed.

**Comment by NoreSoft** [comment]
Just to clarify, so I do not have to open unnecessary Issues in the future: When you list them as run time dependencies it means I need the corresponding -dev packages during the build process?

**Comment by NicoHood** [comment]
@NoreSoft Normally yes, for debian systems.
