### ISSUE TITLE
Unable to choose encryption with dino master on mobile

### ISSUE THREAD

**Issue by pravi** [dino/dino#1299]
Using dino from experimental on Librem 5.
![d8dceea1-f711-4b5c-8eda-195adaa69d08](https://user-images.githubusercontent.com/708222/197509669-b9e83921-aca4-49c3-a481-6439c5e4abce.png)

It is somewhat usable, though with automated scaling and with smaller text, but choosing encryption seems to be not working. I click on the lock icon in the text area, but nothing happens. On desktop the same version works fine.

Edit: Screenshot shows a public group but in a private group I could not turn on encryption.

**Comment by licaon-kter** [comment]
This is the normal version or libhand

**Comment by pravi** [comment]
dino master with gtk4, no patches. I was using libhandy version earlier, but wanted to move to master for muc mam.

**Comment by pravi** [comment]
https://salsa.debian.org/xmpp-team/dino-im/-/tree/debian/experimental/debian/patches only some other debian patches are used.

**Comment by pravi** [comment]
Without automatic scaling in compositor (phosh-mobile-settings app) the main window gets cut in half and cannot be adjusted.
![572fe347-96c5-40e5-8bf9-a38e104f20cf](https://user-images.githubusercontent.com/708222/197512626-1d1ee23d-af91-483b-9686-ac062ae7aa21.png)

**Comment by pravi** [comment]
The encryption options actually comes below the screen bottom so I can only see the top border of the dialogue but can't choose any options in it.

**Comment by pravi** [comment]
A work around might be possible in phoc https://gitlab.gnome.org/guidog/phosh-mobile-settings/-/issues/18

**Comment by pravi** [comment]
This looks to be a problem with phoc itself - https://gitlab.gnome.org/World/Phosh/phoc/-/issues/303

**Comment by pravi** [comment]
Moving to libadwaita with https://github.com/dino/dino/pull/1276 resolves this issue.

**Comment by fiaxh** [comment]
Since we're now using libadwaita, I'm closing this issue.
