### ISSUE TITLE
Meta/docs: Introduce+document a support MUC

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#13]
Hi,

it'd great to have a more direct way to chat with the developers and to discuss ideas than the bug tracker. You are doing an awesome job, and I'm sure you have great ideas on how to make this the #1 desktop XMPP client.

Please create (if not existent already) and document in the README a MUC where you can be contacted and client features can be tested in a direct way. Thanks! :)

**Comment by ge0rg** [comment]
This seems to be an often requested thing, so I have created a MUC at [xmpp:dino@chat.yax.im](https://yax.im/i/#dino@chat.yax.im?join).

Feel free to join it, document it, ignore it or do whatever suits your needs. People who have contributed to dino will be made admin/owner on request.

**Comment by NicoHood** [comment]
@ge0rg Could you please explain how to join the chat with dino? I am either unable to join or I did it wrong.

**Comment by ge0rg** [comment]
Oh, it looks like dino doesn't handle `xmpp:` URIs yet. The steps to join are easy and straight-forward:

1. Click `[+]` in the top if you already have conversations open
2. Click `[Join Conference]`
3. Enter `dino@chat.yax.im` into the unlabeled empty text input field
4. Click `dino@chat.yax.im` that has appeared in the list below
5. Click `[Next]`
6. Enter the nickname others will see you with into the `Nick` textbox (see #116).
7. Click `[Join]`
8. Change the nick under `[🛑]` ⭢ `Accounts` ⭢ `Local alias` to match what you entered into the nickname field
9. Profit!

**Comment by fiaxh** [comment]
There is a MUC at `chat@dino.im` now.
