### ISSUE TITLE
XEP-0461: Message Replies

### ISSUE THREAD

**Issue by fgnix** [dino/dino#1303]
[XEP-0461: Message Replies](https://xmpp.org/extensions/xep-0461.html) defines a way to indicate that a message is a reply to a previous message. This would allow to reply to messages like we are used to in other messaging apps.

It would awesome if the app was capable to jump to the replied message by simply clicking on it.

**Comment by ghjardim** [comment]
I agree. This is an important feature.

**Comment by fiaxh** [comment]
Done in dc52e7595cca06d0a2da7d11b3c88cb2f7ce529c.

<img src="https://user-images.githubusercontent.com/9932450/211021983-623c0b8a-ef36-49d3-aa44-4d20a8913737.png"  width="500" />
