### ISSUE TITLE
Poor contrast of highlight in search results with dark theme

### ISSUE THREAD

**Issue by Zash** [dino/dino#1308]
1. Search for something.
2. Try to read the text with yellow background.

With light theme (Materia-compact):

![image](https://user-images.githubusercontent.com/197474/200870483-40b1e5fe-cfd6-4e0b-91ae-4a541eb34fc9.png)

With dark theme (Materia-dark-compact):

![image](https://user-images.githubusercontent.com/197474/200870562-c2d3e0cc-0260-4d60-aa8d-ea2322fba113.png)

Observe that the search term highlight becomes light text on yellow background, which is I find hard to read.

Dino 0.3.0-2~bpo11+1 from Debian 11 backports.

**Comment by eerielili** [comment]
@Zash I tested it right now and you're right, I got the same on Dino 0.4.1.
I will make a PR very soon, looks like this now on my branch:
![image](https://github.com/dino/dino/assets/81772782/323615e2-988b-42db-a902-5217e292a971) 
![image](https://github.com/dino/dino/assets/81772782/121e6c4b-7cf1-4367-8982-ef1260811039)
