### ISSUE TITLE
Feature request: Add more settings

### ISSUE THREAD

**Issue by notmentaloutlaw** [dino/dino#1314]
The current settings for dino leaves one wanting for more. Such as changing fonts of the text as well as the sizes. How images /videos/previews are rendered if at all etc. It would be beneficial to have this level of customisability as many users will be able to configure dino to their likings. Also the distance between each message could be manipulated by the user as well as maybe the layout of the chat.

**Comment by fiaxh** [comment]
A feature request to have more settings is not very specific. I would prefer to have different issues for specific preferences.

I agree that there are certain settings and features that we should add. However, Dino is not going to become a client where you can configure every tinyest bit of behaviour. For example, I can already say that I don't see us having a setting for the distance between messages.
