### ISSUE TITLE
Feature request: Make it possible to open a chat as separate window

### ISSUE THREAD

**Issue by aurabindo** [dino/dino#1316]
Allow the use of opening a chat (direct / muc) as  a separate window to enabled optimizations like being able to focus a chat through window manager. For instance, when using this under sway wm, a user will be able to search the chats by name and open the window fully with keyboard.

Presently we can use Ctrl-Tab to switch focus to different chats in the roster but this scrolling through this marks the messages read in that chat. By allowing to pop out a chat window, user can switch to the chat they need faster. This improves user experience.

**Comment by fiaxh** [comment]
This is not something we are planing to do.

However, we want to have a jump-to-conversation feature: You press a keyboard shortcut, type the name of a person/channel, use the arrows to select a result, and press enter. This should enable you to quickly switch between conversations. (#1292)
