### ISSUE TITLE
Adding a MUC as a contact by accident breaks the MUC forever

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#132]
Steps to reproduce (git master, 51b4f9b204d4555d354b7324ba918dbfff151c59):

1. Press `[+]` then `Start Chat`
2. Enter a MUC JID (e.g. `xmpp@chat.yax.im`) and press `[Start]`
3. dino will show a regular chat tab, but sending messages will fail silently (`type=chat` can't be delivered to a MUC)
4. remove the chat
5. Press `[+]` then `Join Conference`
6. Enter a MUC JID (e.g. `xmpp@chat.yax.im`) and press `[Next]` and `[Join]`
7. dino will again display the regular chat tab, not a MUC tab

Removing the chat and/or restarting dino doesn't make it work as a MUC again, though it is displayed in the MUC bookmarks(?) list under `Join Conference`.

**Comment by fiaxh** [comment]
Fixed.
