### ISSUE TITLE
allow closing a chat from the chat screen hamburger menu

### ISSUE THREAD

**Issue by pravi** [dino/dino#1321]
This will improve the usability along with #1276 on mobile screens and for touch screens. Currently closing a chat is possible only by hovering on a chat with a mouse and not possible on a touch screen.

**Comment by pravi** [comment]
Since we have libadwaita support merged, we need a way to close chats in touch screen devices.

**Comment by eerielili** [comment]
![image](https://github.com/dino/dino/assets/81772782/b3bf1f56-014c-415f-b6b6-0c50fa81cf9a)

Like this would be great?

**Comment by fiaxh** [comment]
Conversations can be closed from the conversation menu now.
