### ISSUE TITLE
Dino with WebEx Connect

### ISSUE THREAD

**Issue by jtmajorx** [dino/dino#133]
We're using WebEx connect, and I'm getting some strange TLS errors. The certificate is trusted, but the server name and the subject name of the certificate are different (not sure what I can do about that either since it's all managed by Cisco).

** (dino:7748): CRITICAL **: file /home/abuild/rpmbuild/BUILD/dino-0.0~git149.51b4f9b/xmpp-vala/src/core/stanza_writer.vala: line 10: uncaught error: Unacceptable TLS certificate (g-tls-error-quark, 2)
Stream Error: TlsError in GLib: Unacceptable TLS certificate
recovering in 3

**Comment by jtmajorx** [comment]
Any advice?

**Comment by jtmajorx** [comment]
I mean - aside from "Don't use WebEx Connect" lol.

**Comment by mar-v-in** [comment]
Dino currently does not allow to accept invalid certificates (cisco uses invalid certificates, invalid dns records and no dns security), see #57
