### ISSUE TITLE
[Bounty 1k USDT] Feature request: Ability to pin chats above others

### ISSUE THREAD

**Issue by asxpi** [dino/dino#1330]
Our team often uses Dino for work and personal purposes. Sometimes, it's hard to find a chat with an important person. So, we need the pin on top feature like in Telegram or latest version of Gajim. The bounty will be sent after feature pull request will be accepted into the master branch. We are ready to prepay 250 USDT to any active contributor of Dino.

My JID: asxpi@narayana.im

**Comment by m-shinder** [comment]
I would like to take this task. Will be done in ~10 days.
It will be in telegram-like style:
* Stick to top
* Last pinned have highest priority
* Small pin icon near chat
The only question is action needed to pin chat
Looks like now ConversationSelectorRow have no context menu, and i think it's nice btw.
So, IDK should i do it for single action or double-click will be fine
