### ISSUE TITLE
Emojis don't work or show up

### ISSUE THREAD

**Issue by tdm4** [dino/dino#1337]
Clicking the emoji icon just brings up a text menu:

Smileys & People
Body & Clothing
Animals & Nature
Food & Drink
etc...

but no emojis are displayed.

A quick look at emojichooser.c shows that it uses gtk functions for this. I've tried removing my $HOME/.config/gtk-3.0/settings.ini, I've installed noto fonts for emojis, I've tried copying back my settings.ini and setting gtk-font-name to one of the emoji font names. Nothing seems to work!

Any ideas on where to start? Is this a Dino issue or a GTK issue?

I've tested this on 3 different platforms:
* Void Linux
* OpenBSD
* FreeBSD

Void Linux showed only really partial emoji icons and they were in black & white and not all of them were used.

What is dino trying to do to show these? Am I missing some vital fonts file somewhere?

**Comment by SuperSandro2000** [comment]
https://github.com/dino/dino/issues/593#issuecomment-571334981

**Comment by tdm4** [comment]
@SuperSandro2000 I don't have Plasma. How would I turn off the antialiasing? I'm assuming dino uses gtk-3.0.
I can't tell which font it's using to display anything. How do I go about diagnosing this?

**Comment by SuperSandro2000** [comment]
dino 0.4.0 uses gtk4, older versions use gtk3. Check if you have a fontconfig file that enables anti aliasing for all fonts.

**Comment by tdm4** [comment]
@SuperSandro2000 I'm using dino 0.3.1. I'll have a check through fontconfig if I can find all the locations it looks for config.

**Comment by tdm4** [comment]
I have this in my fonts.conf:
```
$ cat $XDG_CONFIG_HOME/fontconfig/fonts.conf
<fontconfig>

  <match target="font">
    <test name="family" qual="any">
      <string>Noto Color Emoji</string>
    </test>
    <edit name="antialias" mode="assign">
      <bool>false</bool>
    </edit>
  </match>

</fontconfig>
`

I'm not 100% sure dino is using Noto Color Emoji. Is there a way to find out what dino sees?

**Comment by tdm4** [comment]
I even tried:

```
<fontconfig>

  <match target="font">
    <edit name="antialias" mode="assign">
      <bool>false</bool>
    </edit>
  </match>

</fontconfig>
```

and it still doesn't show any emojis

**Comment by SuperSandro2000** [comment]
Try removing the antialias config entirely

**Comment by tdm4** [comment]
Well, for whatever reason it started working in Void Linux but is still broken in the BSDs. I wonder if it's related to this bug: https://gitlab.freedesktop.org/cairo/cairo/-/issues/280

**Comment by fiaxh** [comment]
Closing this old issue. This isn't a Dino bug as Dino isn't doing anything related to emoji rendering itself. Instead, it is related to how the system is set up - asking in a BSD channel might be a good idea.
