### ISSUE TITLE
Channel Details under menu ☰ appears wrongly centered

### ISSUE THREAD

**Issue by gnusupport** [dino/dino#1348]
I can see that Channel Details under menu ☰, first start appearing as smaller window, and that one is centered, I can see it for fraction of a second, and that window get populated, once it get populated, the channel details window is badly positioned, rather appears on the bottom of screen.

**Comment by licaon-kter** [comment]
Which version exactly? 0.3.1 on GTK3 or latest code with GTK4?

**Comment by gnusupport** [comment]
0.3.1. Theikenmeer

**Comment by fiaxh** [comment]
This dialog has been completely rewritten since. If you still have this issue with the new dialog, please open a new issue including a screenshot of the bad positioning such that it's clear what we're talking about.
