### ISSUE TITLE
Shift-Up to edit last message will not work if there is existing message from future

### ISSUE THREAD

**Issue by gnusupport** [dino/dino#1355]
If user sets up date to be in future, and sends the message, that message constantly keep pending as last one.

This is funny, I do not think it is correct, but is amusing. It could be used as "topic" feature in private chats.

However, when I write a new message, that message of course appears as before the last for the above mentioned reason.

In that case Shift-UP will not work to edit the last message. It should find last message maybe by some ID, but now I see it is finding it by date, maybe. Maybe not.

I can still edit last message by using mouse and icon.

**Comment by fiaxh** [comment]
This is an effect that's local for the user that sets up their date to be in the future. It should not have any effect on other people. Dino does not accept messages that claim to be from the future (instead, it assumes that they were sent at the current time).

And frankly, all sorts of stuff is going to go wrong if you set your time to the future. That's should be expected. It would be very hard for applications to detect when and how the continuity of time changed and retrospectively change all events that happened during that timeframe.

**Comment by gnusupport** [comment]
No, you did not understand it right.

Here it how it goes:

1. Set up time in future
2. Send message by using Dino and Conversations
3. Receive message by using Dino and Conversations
4. Set up time to present time
5. Observe your sent message pending as about the last
6. Observe the received message pending as about the last
7. Observe that Conversations and other messengers will not keep that message pending as last.

Dino will not accept message from future, because Dino knows only present time.

But if present time is future time, Dino will take that message.

Do the exercise to understand it.

We already found similar bug in the mailing list and rectified it.
