### ISSUE TITLE
"Call declined" when call attempt timed out is misleading

### ISSUE THREAD

**Issue by tuxayo** [dino/dino#1367]
When calling someone that uses Conversations (I don't know if that happens when the receiver has only a Dino client online) went it times out I get "Call declined" "$RECEIVER declined the call". But it's false, they didn't press the red button to decline the call.

Does Dino has a way know the difference between a call timing out and a call being explicitly declined?
A question to investigate this is where does the timeout comes from in this case? Dino or Conversations?

dino version: from 0.3 to 0.4
conversations: since more than a year (so the versions at that time) to recently (2.11 or 2.12)

**Comment by fiaxh** [comment]
> where does the timeout comes from in this case? Dino or Conversations?

Conversations. When the user doesn't pick up the call for some time, it sends a message with the content
```xml
<reject id='uuid' xmlns='urn:xmpp:jingle-message:0' />
```
 The same thing is sent when the user explicitly declines. As far as I see, there is no way to destingish those cases.
