### ISSUE TITLE
Cannot start conversation in portrait mode on small screen

### ISSUE THREAD

**Issue by code-mart** [dino/dino#1371]
On my pinephone, I cannot see the right side of the contacts list after clicking, "start conversation." In particular, I cannot see the "Start" button, which I need in order to start a conversation, after selecting a contact. Please see screenshot:

![image](https://user-images.githubusercontent.com/24482781/219783743-3122f90e-4bbd-4668-b810-a8fb03246014.png)

**Comment by licaon-kter** [comment]
This is Dino 0.4? On which device? OS?

**Comment by code-mart** [comment]
@licaon-kter yes, Dino 0.4.

Pinephone, postmarket OS with sxmo wayland interface.

**Comment by earboxer** [comment]
@code-mart (the workaround for sxmo-sway, if you're not already familiar with it, would be to use a userscript script like https://git.sr.ht/~anjan/sxmo-userscripts/tree/master/item/scripts/scale_display.sh to change your display's scale whenever using an app which is not *fully* adaptable)

parent issue: #178

**Comment by fiaxh** [comment]
Fixed by #1533.
