### ISSUE TITLE
"Next" button in "Sign in" page remains grayed out

### ISSUE THREAD

**Issue by earboxer** [dino/dino#1375]
I'm trying to sign in to my existing account with Dino 0.4.0 (from pmOS edge with desktop sxmo-sway).

I click "Set up account" and it pops up the "Add Account" with just a JID field. Nothing changes when I enter my JID, so I can't click the "Next" button.

**Comment by licaon-kter** [comment]
Rotate the device?

**Comment by earboxer** [comment]
@licaon-kter It makes no difference

**Comment by earboxer** [comment]
I compiled it myself, and this problem doesn't exist. (It's either an issue with Alpine's packaging, or has been fixed in master since 0.4.0).
