### ISSUE TITLE
Duplicate messages in muc with mam enabled

### ISSUE THREAD

**Issue by srgcdev** [dino/dino#138]
Hello,

I noticed that when I connect to a muc where is mam enabled, messages arrive two times. If for example there are 10 messages, I can see the 10 messages and then the 10 messages again.

**Comment by fiaxh** [comment]
I assume that this was not due to duplicated messages from mam but due to an error in the way the messages where loaded. However, the relevant code was completely rewritten in 8bc0d10. As a side effect, this should not happen anymore.

**Comment by srgcdev** [comment]
Thanks, with 8bc0d10 seems its working now.
