### ISSUE TITLE
MUC MAM (0313) doesn't work

### ISSUE THREAD

**Issue by ichthyx** [dino/dino#1386]
I have a prosody server with MUC and MUC_MAM activated.
Conversations say on MUC XEP-0313 : MAM Supported.
My user use the archive option : always.

Conversations and Gajim can get all history of the MUC (while I'm offline and go back online)
But Dino since 0.4 doesn't, only like 4 messages then history is cut.

**Comment by haansn08** [comment]
I also noticed a similar issue. When I upgraded to 0.4, I think only one contact got properly synchronized, all other chats have missing messages.
