### ISSUE TITLE
[FR] Show contact status in "Start Chat" window

### ISSUE THREAD

**Issue by sandwm** [dino/dino#139]
The following information can be seen for open conversations, but not in the "Start Chat" window. It would be useful to be able to see it in both places:

- [ ] Online / offline (shown as gray / color)
- [ ] Status (available / away / ...)
- [ ] Resource

Low priority and not shown anywhere at the moment:
- [ ] Status message

**Comment by linkmauve** [comment]
I’d recommend against showing the resource anywhere in the UI, it’s pretty much always meaningless to users.

**Comment by DanScharon** [comment]
@linkmauve the way the resource is shown at the moment (when hovering over a contact in the open conversations list) is OK for me as some people do put a meaningful name into the resource (like "phone", "work", etc.) and want others be able to see it.
But yeah, I regard the other listed items (Online/offline, Status and Status message) as way more important.
Although @sandwm set the Status message as low priority I see it as a valuable way to convey additional information to my potential conversation partners like "I am logged in but as I am on a conference my answer may come hours or even days late".

**Comment by RalfJung** [comment]
I also recently missed this feature (sorry for creating a duplicate report). Here's my use case:

> I have some contacts in my roster multiple times, and I forgot which account they actively use. If I could see that one of the accounts was online, that would be a good indicator -- whereas right now, I'd have to start conversations with all these accounts just to see if any of them is still being used.

**Comment by wilhelmy** [comment]
I have many contacts in my roster (over 300, since all members of an organization are added automatically), and I would appreciate to be able to see their status and read their status message. Status (and status messages) are a very prominent feature in all other XMPP clients I've used, which means lots of people using other clients use it.

I'll donate 50€ either to dino or some FOSS organization of your choice if dino gets a proper roster, status messages, setting the status and contact groups. Sorry for attempting to bribe you, but this feature is important to me :)

Thanks for the great work, I like dino a lot.

**Comment by wnereiz** [comment]
This is a "must have" feature IMHO, otherwise it is really inconvenience.

**Comment by lord-aerion** [comment]
Not being able to set my own status, or to see my contacts' status, is the #1 reason I uninstalled Dino 5 minutes after having installed it.

It is essential for me to be able to manually set my status, but it seems that many XMPP clients (looking at you, Conversations) are going the way of WhatsApp, Signal, Skype, Telegram, etc., i.e. designed to be online 24/7. This means there is no way to escape from being contactable.

Sure, I could simply close Dino, but I may want to be available on one account, e.g. Work, and Do Not Disturb on another, e.g. Private.

**Comment by wilhelmy** [comment]
I agree that gajim's roster window is pretty much how I think it should be done for any xmpp client.

**Comment by wiktor-k** [comment]
> So for now I'm back on Gajim. It looks like I'm back in the 90s, but I can control my status (and priority, as well as see that of my contacts.

Yes, an XMPP client without XML Console? Unthinkable! Where is Service Discovery? All XMPP clients have this feature!

Just kidding of course - I'm glad Dino is not this kind of client but a simple and approachable one. If I need extra features then, surprise, surprise - it's still possible to use Gajim! I guess it's nice that XMPP has a client for everyone :)

**Comment by stevenroose** [comment]
I think the requested features are totally not essential. Even more, they might make UX for the average user worse. If there were to be added at all, I'd suggest making them as subtle as possible.

Things like "statuses" and "resources" are no longer part of the common "instant messaging" culture. (Not to mention that they both have nothing to do with "messaging".)

**Comment by wilhelmy** [comment]
I think there's something to be done about the contact list though. It isn't nice to look at when there's many contacts and it would make sense to be able to see whether someone is online before you attempt to start a conversation.

I don't think either of us wants this discussion though, so I'll just unsubscribe.

**Comment by wiktor-k** [comment]
@wilhelmy you can see if someone is offline because their avatar is grayscaled in Dino. It's just not as fine grained as in other messengers (e.g. DND icons or extended away...).

**Comment by wilhelmy** [comment]
Not in the "start conversation" menu (i.e. the plus button on the top left). I guess the "dino workflow" is that you always have your often-used contacts on the left and that it doesn't matter for the other ones because you were going to contact them anyway. Nevermind.

**Comment by licaon-kter** [comment]
@wilhelmy open a separate issue then, about the avatars

**Comment by lord-aerion** [comment]
> > So for now I'm back on Gajim. It looks like I'm back in the 90s, but I can control my status (and priority, as well as see that of my contacts.
> 
> Yes, an XMPP client without XML Console? Unthinkable! Where is Service Discovery? All XMPP clients have this feature!
> 
> Just kidding of course - I'm glad Dino is not this kind of client but a simple and approachable one. If I need extra features then, surprise, surprise - it's still possible to use Gajim! I guess it's nice that XMPP has a client for everyone :)

While that's certainly true, I see no harm in asking for features that many other clients have, in a client that I would like to use. This Github is full of feature requests.

**Comment by lord-aerion** [comment]
> I think the requested features are totally not essential. Even more, they might make UX for the average user worse. If there were to be added at all, I'd suggest making them as subtle as possible.
> 
> Things like "statuses" and "resources" are no longer part of the common "instant messaging" culture. (Not to mention that they both have nothing to do with "messaging".)

I wholeheartedly disagree. Statuses and resources are indeed no longer part of modern IM clients, and it's an absolute curse. It's not by user demand that the ability to set one's status has disappeared. No, it's developers that have unilaterally decided that users should be online 24/7, just like Apple set the norm for removing still actively used ports from their hardware, and websites and streaming services are automatically playing videos, whether we like it or not!

The need for things like USB ports and 3.5mm headphone sockets still exists (just look at the insane amount of dongles that have appeared to accommodate disgruntled users), and Netflix have even (finally!!) provided an option to disable the accursed auto play. In the same way the need to be able to disconnect from chat networks still exists, and I'd argue it's now needed even more than ever.

The Guardian even wrote an [article](https://www.theguardian.com/lifeandstyle/2020/apr/16/zoomed-out-how-can-we-politely-tell-people-wed-rather-not-chat) on it.

Most IM apps now work, and are used, primarily on mobile phones (many don't even work on tablets as they are connected to a phone number), devices that we use for many different things. Without a way to indicate to others that you are not available to chat, we're left with turning off our phones as the only option to get away from invasive messaging, which is neither practical nor acceptable, and I don't see the desktop any different.

One of the many strengths of XMPP is the ability to use multiple accounts at the same time, something that's even against the T&C of networks such as WhatsApp and Signal, never mind it even being technically possible.

An XMPP user may have multiple accounts configured, on multiple devices, and there are several use cases why one may want to be available for chat on one account, while indicating Do Not Disturb on another, and be entirely offline on a third. XMPP caters for such situations, with its support for both statuses, resources, and priorities, so I feel that a request for these features to be added to a promising looking new client are wholly justified.

The fact that other networks no longer offer (Skype) or have never offered this (WhatsApp, Signal, Telegram, et al.) is no justification for not supporting it in Dino (or Conversations/Pix Art Messenger), nor does it mean that this is the right way to go.

The removal or suppression of user choice can only ever be a negative thing, and is a course that should be actively discouraged.

While I don't mean to imply that the Dino developers are guilty of this, it is time for the "manufacturers/developers know best" culture, and by extension the "take it or leave it" attitude, to come to an end.

**Comment by codedust** [comment]
Do we need the "Start Chat" window at all? Another option would be to just include all your contacts/group chats at the bottom of the conversation selector (left panel of the main window).

This would really simplify the process, wouldn't involve any new UI elements (as the users status is already show in the conversation selector), and new conversations could be started by just opening that chat and start writing. A seach field to seach/filter the contacts could be added at the top of the conversation selector. Adding new contacts can still be done via some "Start new conversation" menu.

Also, this is done by most other desktop messengers (Signal, Telegram, at least). I think the current solution is quite unintuitive and needs a fresh design anyway.

**Comment by licaon-kter** [comment]
> include all your contacts/group chats at the bottom of the conversation selector

Umm please don't, that's awful...

**Comment by smnthermes** [comment]
> Just kidding of course - I'm glad Dino is not this kind of client but a simple and approachable one. If I need extra features then, surprise, surprise - it's still possible to use Gajim! I guess it's nice that XMPP has a client for everyone :)

Implementing it as an optional feature is feasible.

**Comment by germanicianus** [comment]
My suggestion: Show the status of each contact in the contacts list as border around the corresponding avatar, taking the _most available_ one of the contact's resources - like showing _online_ when the contact is _away_ with one resource, but _online_ with another one.

Being able to set the own status is a must have, e.g. to show _don't disturb_ but to stay online for really important matters. That's can be made possible with a simple drop-down which is easily understandable for the average user.

**Comment by eerielili** [comment]
I did add a pull request that should take care of the presence (online, away, etc) showing in the window.
Did not add support for status yet, I'd see it in the conversation details window or on hovering an avatar in the conversation list.
