### ISSUE TITLE
Cannot run 

### ISSUE THREAD

**Issue by Ygarr** [dino/dino#1391]
Debian(lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux bookworm/sid
Release:	n/a
Codename:	bookworm
)
:
`dino-im 

(process:1867807): Gtk-WARNING **: 23:42:43.025: Theme parser error: gtk-dark.css:123:137-163: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.025: Theme parser error: gtk-dark.css:129:143-169: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.025: Theme parser error: gtk-dark.css:155:615-641: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.025: Theme parser error: gtk-dark.css:157:663-689: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:167:356-382: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:169:380-406: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:173:702-728: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:175:750-776: Expected a valid color.

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:189:55-69: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:190:26-40: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.026: Theme parser error: gtk-dark.css:200:348-364: No property named "-gtk-icon-effect"

(process:1867807): Gtk-WARNING **: 23:42:43.027: Theme parser error: gtk-dark.css:204:589-605: No property named "-gtk-icon-effect"

(process:1867807): Gtk-WARNING **: 23:42:43.030: Theme parser error: gtk-dark.css:388:42-61: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.030: Theme parser error: gtk-dark.css:428:814-833: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.030: Theme parser error: gtk-dark.css:430:1242-1270: No property named "-gtk-outline-top-left-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.030: Theme parser error: gtk-dark.css:430:1277-1308: No property named "-gtk-outline-bottom-left-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:432:1237-1266: No property named "-gtk-outline-top-right-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:432:1273-1305: No property named "-gtk-outline-bottom-right-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:434:1410-1429: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:436:391-410: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:438:1014-1042: No property named "-gtk-outline-top-left-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:438:1049-1078: No property named "-gtk-outline-top-right-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:440:1044-1075: No property named "-gtk-outline-bottom-left-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:440:1082-1114: No property named "-gtk-outline-bottom-right-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.031: Theme parser error: gtk-dark.css:442:464-483: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.033: Theme parser error: gtk-dark.css:571:54-80: No property named "-GtkWidget-window-dragging"

(process:1867807): Gtk-WARNING **: 23:42:43.034: Theme parser error: gtk-dark.css:631:610-626: No property named "-gtk-icon-effect"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:102-135: No property named "-GtkTreeView-horizontal-separator"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:140-168: No property named "-GtkTreeView-grid-line-width"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:173-203: No property named "-GtkTreeView-grid-line-pattern"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:209-237: No property named "-GtkTreeView-tree-line-width"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:242-272: No property named "-GtkTreeView-tree-line-pattern"

(process:1867807): Gtk-WARNING **: 23:42:43.037: Theme parser error: gtk-dark.css:751:278-304: No property named "-GtkTreeView-expander-size"

(process:1867807): Gtk-WARNING **: 23:42:43.038: Theme parser error: gtk-dark.css:828:21-47: No property named "-GtkWidget-window-dragging"

(process:1867807): Gtk-WARNING **: 23:42:43.039: Theme parser error: gtk-dark.css:1041:102-136: No property named "-GtkScrollbar-has-backward-stepper"

(process:1867807): Gtk-WARNING **: 23:42:43.039: Theme parser error: gtk-dark.css:1041:145-178: No property named "-GtkScrollbar-has-forward-stepper"

(process:1867807): Gtk-WARNING **: 23:42:43.041: Theme parser error: gtk-dark.css:1293:95-114: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.041: Theme parser error: gtk-dark.css:1295:51-70: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.042: Theme parser error: gtk-dark.css:1495:50-64: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.042: Theme parser error: gtk-dark.css:1497:59-73: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.042: Theme parser error: gtk-dark.css:1499:53-67: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.042: Theme parser error: gtk-dark.css:1501:62-76: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.042: Theme parser error: gtk-dark.css:1503:51-65: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.043: Theme parser error: gtk-dark.css:1505:60-74: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.043: Theme parser error: gtk-dark.css:1507:52-66: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.043: Theme parser error: gtk-dark.css:1509:61-75: Not a valid image

(process:1867807): Gtk-WARNING **: 23:42:43.043: Theme parser error: gtk-dark.css:1610:715-746: No property named "-gtk-outline-bottom-left-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.043: Theme parser error: gtk-dark.css:1612:688-720: No property named "-gtk-outline-bottom-right-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.044: Theme parser error: gtk-dark.css:1684:130-149: No property named "-gtk-outline-radius"

(process:1867807): Gtk-WARNING **: 23:42:43.045: Theme parser error: gtk-dark.css:1842:23-39: No property named "-gtk-icon-effect"

(process:1867807): Gtk-WARNING **: 23:42:43.046: Theme parser error: gtk-dark.css:1912:42-61: No property named "-gtk-outline-radius"

(process:1867807): libsoup-ERROR **: 23:42:43.082: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
`

**Comment by mar-v-in** [comment]
You're probably trying to run a version of Dino not build for your system. Did you compile dino from source or where did you get it from?

**Comment by fiaxh** [comment]
Closing this as there was no response.
