### ISSUE TITLE
Dino crashes when sending or receiving files

### ISSUE THREAD

**Issue by Epicalert** [dino/dino#1395]
Every time an image is sent or received, dino freezes and I have to manually send a SIGTERM to it. After restarting dino I can click on the file to download it and it works fine, until the next file is sent and it freezes again.

Dino version: 0.4.1 - Ilulissat
Operating system: Arch linux

stderr log:
```
(dino:19825): Adwaita-WARNING **: 18:39:49.193: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

(dino:19825): Gtk-WARNING **: 18:39:49.713: No IM module matching GTK_IM_MODULE=fcitx found

(dino:19825): Gtk-CRITICAL **: 18:40:04.643: GtkGrid 0x55c5f770c020 reports a minimum height of 136, but minimum height for width of 1048576 is 336. Expect overlapping widgets.

(dino:19825): Gtk-CRITICAL **: 18:40:04.843: GtkGrid 0x55c5f770c020 reports a minimum height of 136, but minimum height for width of 1048576 is 336. Expect overlapping widgets.

(dino:19825): libsoup-WARNING **: 18:40:04.892: (../libsoup/libsoup/soup-session.c:334):soup_session_dispose: runtime check failed: (soup_connection_manager_get_num_conns (priv->conn_manager) == 0)

(dino:19825): libsoup-WARNING **: 18:40:04.892: (../libsoup/libsoup/soup-connection-manager.c:84):soup_host_free: runtime check failed: (host->conns == NULL)
```

**Comment by lorddavidiii** [comment]
Downgrading `libsoup3` from 3.4.0-1 to 3.2.2-1 seems to fix the problem for me. (dino version: 0.4.1~git12.20230321.adb2b58b on Arch Linux)

**Comment by Epicalert** [comment]
It may be a packaging issue then since the libsoup package was updated a day before the dino package was.

-------- Original Message --------

**Comment by lorddavidiii** [comment]
hm, I rebuild the `dino-git` aur package with the `libsoup3` package 3.4.0-1 as I also thought, that this is a packaging issue, but this still crashes, so I build  `libsoup3`  3.2.2-1 on my laptop and downgrade `libsoup3`  and then it don't craches anymore, without rebuiling `dino-git` again.
