### ISSUE TITLE
dino-0.4.1 fails to compile on gentoo with musl

### ISSUE THREAD

**Issue by ghost** [dino/dino#1396]
Here is the build log:
[build.log](https://github.com/dino/dino/files/11031554/build.log)

I am using the musl overlay so perhaps that has something to do with it.

**Comment by mar-v-in** [comment]
CMake complains about your system not providing a suitable ldconfig. Current versions of sys-libs/musl do provide such ldconfig so your systems seems to somehow miss those. You can bypass the need for ldconfig by specifying -DSOUP_VERSION= to the appropriate version (2 or 3, depending on your system; using the wrong version will crash Dino at startup).
