### ISSUE TITLE
No notificatoion on wrong password

### ISSUE THREAD

**Issue by Akasch** [dino/dino#14]
I had entered a wrong password for my test account and no notification was shown in the gui. In the console it printed::
   
```
Stream Error: mandatory-to-negotiate feature not negotiated
recovering in 10
```

multiple times. The server log indicated the Password was wrong.

Additionally after changing the password it only worked after restarting dino.

**Comment by fiaxh** [comment]
The current status (connected, connecting, disconnected, errors) of an account is shown in the manage-accounts-dialog as of d8881c4. Also, changing the password has an immediate effect now. 

![screenshot from 2017-04-10 15-51-01](https://cloud.githubusercontent.com/assets/9932450/24865190/d33ed6f0-1e06-11e7-85a4-1f1d67220fee.png)
![screenshot from 2017-04-10 15-52-04](https://cloud.githubusercontent.com/assets/9932450/24865203/da4c2010-1e06-11e7-8da3-a6956785404e.png)
