### ISSUE TITLE
Building dino against vala 0.56.5 fails with "error: initializer element is not constant"

### ISSUE THREAD

**Issue by Antiz96** [dino/dino#1407]
Hi,

Building dino (`0.4.2`) against vala `0.56.5` fails with `/build/dino/src/build/plugins/rtp/src/voice_processor.c:111:96: error: initializer element is not constant`. You can read the whole build log here: http://ix.io/4rTv
For what it's worth, building dino against the previous vala release (`0.56.4`) works as intended. I assume there's a change in vala `0.56.5` that require a modification on dino's side.

I remain available if needed.

**Comment by Antiz96** [comment]
Alright, sorry for the noise in case it is a vala issue... 

Do you mind posting the link to your upstream report here? I'm interested in following the discussion (since vala `0.56.5` is the current release on Arch repo, it might involve some eventual quick patching/update on our side if there's indeed a regression in it).

Thanks a lot!

**Comment by mar-v-in** [comment]
Here's the upstream issue: https://gitlab.gnome.org/GNOME/vala/-/issues/1424

**Comment by Antiz96** [comment]
A new vala version containing the fix [has been released](https://gitlab.gnome.org/GNOME/vala/-/commit/0f2907e34ff23505b79eafc6f22dd367c5d3c572). Thanks once again for raising the issue to upstream.
I'll retry to build `dino` on Arch's side once the new `vala` release has been packaged into the repo.

I assume this issue can be closed *(specifically since it wasn't a `dino` issue)*?

**Comment by Antiz96** [comment]
I've been able to [rebuild dino correctly](https://github.com/archlinux/svntogit-community/commit/cccff1ae4ee99df152f7af42c6163abe53c11ae4) on Arch side against `vala 0.56.6` so I can confirm the new `vala` release fixes the issue.
Thanks once again for your help!

**Comment by albjeremias** [comment]
I did: 
`yay -Suy vala=0.56.6`
and then
`yay -Suy dino-git`

and didn't work for me
