### ISSUE TITLE
Can't open links within dino

### ISSUE THREAD

**Issue by PolarianDev** [dino/dino#1409]
Hello,

This is an issue reported by 4+ people over on the XMPP channel, I believe all of which were Arch Linux users. I believe there is 2 reasons this could be occurring:

- Outdated dependencies (unlikely)
- move to GTK4

After the move to gtk4 we have not seemed to be able to open links within the client, I have seen many people blaming Arch Linux for this, but this is unlikely.

The versions of software to test against which were pulled from the Arch Repository:

`dino`: 0.4.2
`xdg-utils`: 1.1.3+25+g8ae0263
`gio (glib2)`: 2.76.1

If you also having this issue, please could you back me up by providing the software versions of the 3 above packages installed on your system using the following command:

`pacman -Q dino xdg-utils glib2`

Please could you post the results of these in reply to this issue.

Thanks,
Polarian

**Comment by PolarianDev** [comment]
Oh it might also be useful to know the gtk4 version:

`gtk4 1:4.10.1-2`

**Comment by alkino** [comment]
Same bug here on archlinux:
```
dino: 0.4.2
xdg-utils: 1.1.3+25+g8ae0263
gio: 2.76.1
1:4.10.1
```

**Comment by PolarianDev** [comment]
Also to clarify, this is not a bug with xdg-utils or gio on arch linux, these both have been tested, and past testing by the arch testing team.

**Comment by alkino** [comment]
Not a dino bug: string "No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"

https://github.com/emersion/xdg-desktop-portal-wlr/issues/42

**Comment by alkino** [comment]
What can be done on the dino side?

An error is returned by the task, maybe there is a way to show it in debug?

**Comment by moparisthebest** [comment]
I'm not sure that's the bug, I'm using KDE and i3 on X which doesn't need the hacky wayland workarounds and clicking links doesn't work for me either.

**Comment by PolarianDev** [comment]
> I'm not sure that's the bug, I'm using KDE and i3 on X which doesn't need the hacky wayland workarounds and clicking links doesn't work for me either.

The last time I remember being able to open links was within the gtk3 version, once dino updated to gtk4, I do not believe it has worked since.

I would need to compile and install the old version to verify this, unfortunately I do not have the time, if someone else does it would be helpful to find the origins to this issue.

**Comment by PolarianDev** [comment]
> Not a dino bug: string "No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"
> 
> [emersion/xdg-desktop-portal-wlr#42](https://github.com/emersion/xdg-desktop-portal-wlr/issues/42)

I can't reproduce this issue.

**Comment by alkino** [comment]
Can you launch dbus-monitor and try to click on a link?

**Comment by alkino** [comment]
> I'm not sure that's the bug, I'm using KDE and i3 on X which doesn't need the hacky wayland workarounds and clicking links doesn't work for me either.

This is not related to wayland but to freedesktop.

Launch dbus-monitor and click on a link.

**Comment by haansn08** [comment]
I also have this issue
```
$ pacman -Q dino xdg-utils glib2 gtk4
dino 0.4.2-1
xdg-utils 1.1.3+25+g8ae0263-1
glib2 2.76.1-1
gtk4 1:4.10.1-2

$ dbus-monitor
[...]
method call time=1680427546.093732 sender=:1.53 -> destination=:1.11 serial=65 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.OpenURI; member=OpenURI
   string "wayland:abcc95384135d8fa6debb9ef116a531c"
   string "https://orf.at/stories/xxxxxxx/"
   array [
      dict entry(
         string "handle_token"
         variant             string "gtk128561231"
      )
      dict entry(
         string "activation_token"
         variant             string "eb3e99f42028542ae9736172e12c7987"
      )
   ]
error time=1680427546.094379 sender=:1.11 -> destination=:1.53 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=65
   string "No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"
```

**Comment by alkino** [comment]
> I also have this issue
> ```
> $ pacman -Q dino xdg-utils glib2 gtk4
> dino 0.4.2-1
> xdg-utils 1.1.3+25+g8ae0263-1
> glib2 2.76.1-1
> gtk4 1:4.10.1-2
> 
> $ dbus-monitor
> [...]
> method call time=1680427546.093732 sender=:1.53 -> destination=:1.11 serial=65 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.OpenURI; member=OpenURI
>    string "wayland:abcc95384135d8fa6debb9ef116a531c"
>    string "https://orf.at/stories/xxxxxxx/"
>    array [
>       dict entry(
>          string "handle_token"
>          variant             string "gtk128561231"
>       )
>       dict entry(
>          string "activation_token"
>          variant             string "eb3e99f42028542ae9736172e12c7987"
>       )
>    ]
> error time=1680427546.094379 sender=:1.11 -> destination=:1.53 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=65
>    string "No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop"
> ```

You should install xdg-desktop-portal-XXX (xfce, gnome, kde) and relaunch xdg-desktop-portal.

systemctl --user restart xdg-desktop-portal

**Comment by haansn08** [comment]
> You should install xdg-desktop-portal-XXX (xfce, gnome, kde) and relaunch xdg-desktop-portal.
> systemctl --user restart xdg-desktop-portal

I am using sway and had `xdg-desktop-portal-wlr` installed. 
```
$ pacman -Q xdg-desktop-portal xdg-desktop-portal-wlr sway
xdg-desktop-portal 1.16.0-1
xdg-desktop-portal-wlr 0.6.0-1
sway 1:1.8.1-1
```

**Comment by alkino** [comment]
> > You should install xdg-desktop-portal-XXX (xfce, gnome, kde) and relaunch xdg-desktop-portal.
> > systemctl --user restart xdg-desktop-portal
> 
> I am using sway and had `xdg-desktop-portal-wlr` installed. 
> ```
> $ pacman -Q xdg-desktop-portal xdg-desktop-portal-wlr sway
> xdg-desktop-portal 1.16.0-1
> xdg-desktop-portal-wlr 0.6.0-1
> sway 1:1.8.1-1
> ```
> 
> EDIT: Installing `xdg-desktop-portal-gtk` and restarting `xdg-desktop-portal.service` did indeed fix the problem! I did not realize I have to install multiple "desktop portals". Thank you very much!

In fact the wlr only install two backend for screen capture.

**Comment by moparisthebest** [comment]
So I had `xdg-desktop-portal-kde` installed already, but `xdg-desktop-portal` was not installed, after installing it and starting the user service clicking links works.

I'm still unclear where the bug is though, if gtk4 depends on this wayland hack running for basic desktop functionality (even when running under X) like clicking links to work it seems like the dependency should be there, if it's dino specific, then dino should depend on it.

**Comment by alkino** [comment]
> So I had `xdg-desktop-portal-kde` installed already, but `xdg-desktop-portal` was not installed, after installing it and starting the user service clicking links works.
> 
> I'm still unclear where the bug is though, if gtk4 depends on this wayland hack running for basic desktop functionality (even when running under X) like clicking links to work it seems like the dependency should be there, if it's dino specific, then dino should depend on it.

This is not a wayland hack, nor a dino bug.
This is a gtk-4/flatpack feature. Using the desktop-portal freedesktop api to open a link.
This API has been created for flatpack so he can doing some stuff on desktop even if he is encapsulated.

What dino should do is catching the error and print it.

**Comment by sandwm** [comment]
@alkino: Is xdg-desktop-portal a required dependency of gtk4 even outside of flatpak? I did a bit of searching in [gtk](https://gitlab.gnome.org/GNOME/gtk) and [glib](https://gitlab.gnome.org/GNOME/glib) and while I found multiple references to those portals, I saw nothing about it being *required*. Do you have a link?

So I think this probably requires
 * a declared dependency on xdg-desktop-portal both a) in the gtk4 or glib documentation (not sure which of those) and b) for the gtk4 or glib2 package in Arch
 * or, if this is a bug, fixing it in gtk4 / glib to use the "classic" way of opening URIs when xdg-desktop-portal is not found / does not provide OpenURI

> What dino should do is catching the error and print it.

Maybe should be implemented in gtk (/ glib / whatever), since (as you said) this doesn't seem to be a dino-specific issue. For example if you click on the "website" button in gnome-font-viewer (one of the few other programs already ported to gtk4), it shows the same behaviour as clicking links in dino.

I'm going to create the corresponding issues on gtk4 and/or Arch, but if you have more information on the above that would be appreciated, so I can create the correct bug reports.

**Comment by alkino** [comment]
THank you for you interest.

https://github.com/GNOME/gtk/blob/9608e4e503df28e31137f4841409876f5aaf1e0d/gtk/gtkurilauncher.c#L279-L310

We can see here that if openuri_portal is available : https://github.com/GNOME/gtk/blob/9608e4e503df28e31137f4841409876f5aaf1e0d/gtk/gtkopenuriportal.c#L86
It means : https://github.com/GNOME/gtk/blob/9608e4e503df28e31137f4841409876f5aaf1e0d/gtk/gtkopenuriportal.c#L49
https://github.com/GNOME/gtk/blob/9608e4e503df28e31137f4841409876f5aaf1e0d/gtk/gtkprivate.h#L115

So, the function `gtk_openuri_portal_is_available` is not testing if there is an openuri but only a portal.

I think the "bug" in GTK4 is there.

The interface of the freedesktop portal, is only an interface and behind you can have several partial implementations. Here, it seems we all got some partial impl.

**Comment by sandwm** [comment]
gtk issue created: https://gitlab.gnome.org/GNOME/gtk/-/issues/5733

Until it is resolved, just make sure you have these installed (or others providing OpenURI): xdg-desktop-portal xdg-desktop-portal-gtk

@alkion: Thank you, that was helpful in digging deeper. Apparently `gtk_xdp_open_uri_proxy_new_sync`, while only getting PORTAL_BUS_NAME and PORTAL_OBJECT_PATH as parameters, does then call `g_initable_new (GTK_XDP_TYPE_OPEN_URI_PROXY, ..., "org.freedesktop.portal.OpenURI", NULL);`, so it seems specific to OpenURI, not just the portal. But I didn't dig deeper there.

Oh, and `gtk_xdp_open_uri_proxy_new_sync` is defined in xdp-dbus.c, which seems to be auto-generated during build based on the org.freedesktop.portal.OpenURI specification I guess? Again, didn't go deeper there.

**Comment by alkino** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/5826 a patch has been merged in gtk4, I think we should close this ticket?
