### ISSUE TITLE
Unusual long loading times when downloading/displaying an image

### ISSUE THREAD

**Issue by jubalh** [dino/dino#1421]
Contact is sending an image using Monal. On Conversations I receive the image immediately. On Dino I see the loading sign for ages (irregular time, but several minutes). The image is only 300kB in size and I'm connected via WiFi.

I'm using Dino 0.4.2 from openSUSE. OMEMO Is enabled.
Ejabberd 22.10.

**Comment by licaon-kter** [comment]
Not fixed in https://github.com/dino/dino/issues/1373 ?

**Comment by jubalh** [comment]
That seems to be exactly it. I'll close this one and comment there. Thank you.
