### ISSUE TITLE
Allow blocking entire domain

### ISSUE THREAD

**Issue by pravi** [dino/dino#1429]
In cheogram android app (possibly on conversations too), when you receive a message from stranger (people not added as a contact), in addition to block user, there is a block domain option too. We should have such an option on Dino too to tackle huge amounts of spam.

**Comment by pravi** [comment]
![Screenshot_20230422-184748](https://user-images.githubusercontent.com/708222/233787488-a12967cb-18bd-4ee0-b9b9-3e7cf7850269.png)

**Comment by pravi** [comment]
Though with many spammers adding you to contact first, it would be nice to have this option even with a contact request.

**Comment by eerielili** [comment]
Would be nice
Seems it's described in [XEP-0133](https://xmpp.org/extensions/xep-0133.html#edit-blacklist)

**Comment by Zash** [comment]
XEP-0133 describes a collection of administrative commands, not something regular users would use.

[XEP-0191](https://xmpp.org/extensions/xep-0191.html) is what you want for this, and what is used in the screenshot.

**Comment by eerielili** [comment]
@pravi I have pushed a PR for that, though it's for blocking the user's entire domain through the conversation details windows. I should add a way to see one's own blocklist too I think
