### ISSUE TITLE
(QUESTION) setup for microsoft/google services

### ISSUE THREAD

**Issue by Radical4ever** [dino/dino#1430]
hi, my question is if it is possible to set up microsoft services (like teams or skype) or google meet, if it is possible wich address should i use for loggin in this app, thank you and very good app!

**Comment by licaon-kter** [comment]
Those are not running XMPP, but close source proprietary services.

/close this

**Comment by Radical4ever** [comment]
Welp, that's sad, thanks anyways for aswering!
