### ISSUE TITLE
Possibility to turn off notifications for specific chatrooms (and chats)

### ISSUE THREAD

**Issue by frederic-peters** [dino/dino#146]
I am often in multiple chatrooms and some of them I'm just there to glance over, I don't want to be distracted by them when a new message is posted.  I imagine a "bell" icon in the top bar that would toggle notifications, like there's the lock button.  Alternatively it could maybe not be that important and be available from the hamburger menu.

**Comment by fiaxh** [comment]
That feature already exists. ☰ > Contact Details > Notifications (Default/On/Off/Only when mentioned). By default the setting is "Only when mentioned" in public (not invite-only) groupchats.

**Comment by frederic-peters** [comment]
Thanks, sorry I missed that.
