### ISSUE TITLE
Removed and re-added reaction does not show up until chat is re-opened

### ISSUE THREAD

**Issue by mesonium** [dino/dino#1464]
### Issue
1) Add a reaction emoji to a message
2) Remove this reaction again
3) Add the same reaction from step 1)

### Result
The emoji does not show up immediately, but first after re-opening the chat.

### Setup
Dino git (8c8c2dc4b0e08a2e6d73b45fba795d462595418f)
openSUSE TW

**Comment by fiaxh** [comment]
I can no longer reproduce this.
