### ISSUE TITLE
MUC self ping doesn't use the appropriate nickname

### ISSUE THREAD

**Issue by truenicoco** [dino/dino#1467]
In a MUC where you are renamed on join (status code 210), dino will try to send [MUC self-pings](https://xmpp.org/extensions/xep-0410.html) directed at the local part of the account JID instead of the actual nickname.

In other words:
- I am `local@example.com`
- I join `muc@room.ex.com` requesting the nickname 'local'
- The MUC lets me in but informs me that my nickname is now 'real_nickname'

Dino handles that correctly in the UI, my own messages appear as my own, but I have noticed that the self pings it sends will be to `muc@room.ex.com/local` when they really should be sent to `muc@room.ex.com/real_nickname`.

FWIW, my MUC service is tolerant to that ATM and will reply to the self pings anyway (but I'll fix it), but I suspect other MUCs services won't. Also, it invalidates server-side optimisations for XEP-0410.

**Comment by horazont** [comment]
This can cause trouble with biboumi (IRC gateway) even. It will (attempt to) forward those pings to the corresponding IRC user as CTCP ping, which may:

- trigger antispam rate limits
- be annoying to that IRC user without any remedy available
- maybe even cause false-negatives if the remote user doesn't reply to CTCP ping/blocks the dino user?
- break in other funny ways if no matching user exists

**Comment by Neustradamus** [comment]
It is an important ticket!
