### ISSUE TITLE
Some unstranslated strings

### ISSUE THREAD

**Issue by srgcdev** [dino/dino#147]
Here I attached some screenshots with some strings that are not translated.
![dino-unstrlanslated-1](https://user-images.githubusercontent.com/24658184/30197967-8717e272-946b-11e7-9d42-706dec4318b6.png)
![dino-unstrlanslated-2](https://user-images.githubusercontent.com/24658184/30197965-8714e176-946b-11e7-8aa2-903089cc2ebb.png)
![dino-unstrlanslated-3](https://user-images.githubusercontent.com/24658184/30197968-871a6af6-946b-11e7-9c16-2ede46621e0a.png)
![dino-unstrlanslated-4](https://user-images.githubusercontent.com/24658184/30197966-8715192a-946b-11e7-85cf-8b8d6877c183.png)

**Comment by fiaxh** [comment]
The strings should all be translatable by now.
