### ISSUE TITLE
New contact dialog - crash

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#1484]
...if I press the button in 1:1

Debian Bookworm, amd64, local built e2c34bf2235c9f85fc91de9c0f1b74858f4ef89e

gdb log (no debug symbols): https://gist.github.com/licaon-kter/f1a7014e0c23d082604c1924350acaed

**Comment by licaon-kter** [comment]
Going back to 9eafe4139d6b2c0cabe3c77a903d6ae931a26975 and everything is fine

**Comment by fiaxh** [comment]
Could you have a look if [this](https://github.com/dino/dino/tree/conversation-details-dialog-fix) (c2efb214afa9f712c7ac112899c7d9b730e10de0) fixes it for you?

**Comment by licaon-kter** [comment]
@fiaxh confirmed fixed! :)

**Comment by fiaxh** [comment]
Fix pushed in c2efb214afa9f712c7ac112899c7d9b730e10de0.
