### ISSUE TITLE
Compile Dino 4.3 missing: Adwaita_LIBRARY 

### ISSUE THREAD

**Issue by rallep71** [dino/dino#1496]
-- Found GTK4: /usr/lib/x86_64-linux-gnu/libgtk-4.so (found version "4.6.9") 
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Adwaita (missing: Adwaita_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindAdwaita.cmake:9 (find_package_handle_standard_args)
  cmake/MultiFind.cmake:20 (find_package)
  main/CMakeLists.txt:7 (find_packages)

**Comment by fiaxh** [comment]
Dino depends on libadwaita, so you'll have to install that.
