### ISSUE TITLE
Installation missing in Makefile

### ISSUE THREAD

**Issue by seppiofish** [dino/dino#15]
Hi I was trying to make a test package for archlinux and I noticed there isn't an installation process yet. Are you planning to add an install directive to the makefile any time soon? I'm anyway going to look at it in a few days and eventually make a pull request. I may just need a few explenations of how the configure script is supposed to work because i'm not quite sure I got it. In fact i couldn't get the plugins to work in a manual testing installation (simply coping the binaries and libraries to the 'right' places).

Anyway, well done, I really like this client and I'm willing to help.

**Comment by mar-v-in** [comment]
`make install` is now available. `./configure` also provides some configs now (use `./configure --help` to list them)
