### ISSUE TITLE
Segmentation fault when showing contact details while server has no support for XEP-0191

### ISSUE THREAD

**Issue by horazont** [dino/dino#1508]
# How to reproduce

1. Log into a server without support for XEP-0191 (Blocking Command)
2. Add a contact
3. Open a chat with that contact
4. Click on the details menu

# What happens

<pre>
Thread 1 "dino" received signal SIGSEGV, Segmentation fault.
0x00007ffff7dfac48 in xmpp_xep_blocking_command_module_is_blocked (self=self@entry=0x555555fce940, stream=stream@entry=0x555555f2b900, jid=jid@entry=0x55555d123640 "XXX")
    at /home/horazont/Builds/dino/xmpp-vala/src/module/xep/0191_blocking_command.vala:15
15              return stream.get_flag(Flag.IDENTITY).blocklist.contains(jid);
(gdb) bt
#0  0x00007ffff7dfac48 in xmpp_xep_blocking_command_module_is_blocked (self=self@entry=0x555555fce940, stream=stream@entry=0x555555f2b900, jid=jid@entry=0x55555d123640 "XXX")
    at /home/horazont/Builds/dino/xmpp-vala/src/module/xep/0191_blocking_command.vala:15
#1  0x00007ffff7ef4048 in dino_blocking_manager_is_blocked (self=self@entry=0x55555593a410, account=account@entry=0x555555aaf030, jid=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
) at /home/horazont/Builds/dino/libdino/src/service/blocking_manager.vala:25
#2  0x00005555555dccf5 in dino_ui_conversation_details_populate_dialog (stream_interactor=<optimized out>, conversation=0x555556204f00, model=<optimized out>) at /home/horazont/Builds/dino/main/src/ui/conversation_details.vala:12
#3  dino_ui_conversation_details_populate_dialog (model=<optimized out>, conversation=0x555556204f00, stream_interactor=<optimized out>) at /home/horazont/Builds/dino/build/main/conversation_details.c:564
#4  0x00005555555dcfb5 in dino_ui_conversation_details_setup_dialog (conversation=conversation@entry=0x555556204f00, stream_interactor=stream_interactor@entry=0x55555591c560, parent=0x5555564f9e80)
    at /home/horazont/Builds/dino/main/src/ui/conversation_details.vala:112
#5  0x00005555555e401e in dino_ui_menu_entry_on_clicked (self=<optimized out>) at /home/horazont/Builds/dino/main/src/ui/conversation_titlebar/menu_entry.vala:37
#6  _dino_ui_menu_entry_on_clicked_gtk_button_clicked (_sender=<optimized out>, self=<optimized out>) at /home/horazont/Builds/dino/main/src/ui/conversation_titlebar/menu_entry.vala:19
#7  0x00007ffff6a83749 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff6a985bf in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff6a9e186 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6a9e243 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff6ebf615 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#12 0x00007ffff6a83749 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff6a985bf in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff6a9e186 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff6a9e243 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6f6df06 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#17 0x00007ffff6a86986 in g_cclosure_marshal_VOID__BOXEDv () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x00007ffff6a83749 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x00007ffff6a985bf in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff6a9e186 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff6a9e243 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff6f6ae23 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#23 0x00007ffff6f6c5bb in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#24 0x00007ffff6f6f5f6 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#25 0x00007ffff6f3b30a in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#26 0x00007ffff707eb1c in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#27 0x00007ffff7086472 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#28 0x00007ffff6fac79e in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#29 0x00007ffff6facf63 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#30 0x00007ffff70927b0 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#31 0x00007ffff720ad5a in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#32 0x00007ffff727fd83 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#33 0x00007ffff6a83540 in g_closure_invoke () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#34 0x00007ffff6a96afc in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#35 0x00007ffff6a97d51 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff6a9e186 in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff6a9e243 in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff7283556 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#39 0x00007ffff724f73e in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#40 0x00007ffff697e1b4 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#41 0x00007ffff69812d7 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007ffff69818f0 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007ffff6bb3b5d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#44 0x000055555558519e in dino_main (args_length1=1, args=0x7fffffffe228) at /home/horazont/Builds/dino/main/src/main.vala:22
#45 main (argc=1, argv=0x7fffffffe228) at /home/horazont/Builds/dino/main/src/main.vala:9
</pre>

This is a build from master.

**Comment by eerielili** [comment]
@horazont Hello, could you try building https://github.com/eerielili/dino/commit/612d9bcd1c408b66f3aac848e654206947bb4c53 and tell me if it stills segfaults for you
