### ISSUE TITLE
make the OMEMO error message more helpful

### ISSUE THREAD

**Issue by CouldBeThis** [dino/dino#1521]
Hello, 

I am new to XMPP and trying out a few different clients. I do not totally understand all the concepts and that is the perspective this is coming from. 

I logged into dino using an account and attempted to open an OMEMO-encrypted conversation from another device. All messages are replaced with:

> I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo

I read various issues on the subject OMEMO and am not clear on what my expectations should or shouldn't be regarding this use case. 

Whatever the technical limitations, feature status etc, my suggestion is to change *the error text*. Above is not helpful at all. It is a page on the website for a different project explaining some technical details and advertising some paid apps on Google Play. I am confused what I am supposed to be doing with all this. 

If there is any documentation about how to resolve this issue, it would be better to link to that. I'm not able to find any. The best I turn up is #783. Which has an index of sorts could be helpful as it would give a bit of a starting place to look for solutions. 

I find some other issues indicating this problem might resolve itself with time, when the other corespondent logs in or something. If that is accurate, it would be helpful to inform the user who is encountering this problem at the outset. If I didn't happen to have the time to trawl through the issues I would just think "this application doesn't work" and uninstall it. 

possibly related? but not sure: #367 #873

Thanks for your time making and sharing the application in any case. :) And for considering my request.

**Comment by mar-v-in** [comment]
The error message you see is not an error message. It is the fallback message sent by the other client (probably Conversations in this case, but could also be a fork) that is displayed in case the message is not targeting the recipient device.
OMEMO is a forward-secure, device-to-device message encryption system. As such, if you have a new device, it will not be a recipient of any previous messages (as it was not a known device before it is first used). This is why you see the fallback displayed instead.
If you think the fallback is confusing or could be more helpful, you need to report this to the sending client, not the receiving client.

**Comment by CouldBeThis** [comment]
hmmm thanks for taking the time to explain to me; this protocol is quite the learning curve.

Do I understand correctly? You are saying that this specific wording comes from some outside source? Not this project.

If correct, how do I determine where it comes from? 

I did a general web search for the message and found issues in several xmpp client repos. They seem to be largely opened by confused people like myself. Or are related to general implementation of OMEMO. I was unable to glean any useful information from them.

**Comment by licaon-kter** [comment]
The message will come with an encrypted part, if your client can't decrypt it (for some reason) the message also has a clear text part that your client can show to you. And that tries to explain to you a bit about the issue.

Eg. You joined an encrypted group or an 1:1 chat with a client that can't do OMEMO.

Now, if you use Dino, hope you aru up to date and everything :), but Dino supports encryption, so it signals that your chat partner didn't encrypt with your key for some reason.

**Comment by hrxi** [comment]
> The error message you see is not an error message. It is the fallback message sent by the other client (probably Conversations in this case, but could also be a fork) that is displayed in case the message is not targeting the recipient device.
> OMEMO is a forward-secure, device-to-device message encryption system. As such, if you have a new device, it will not be a recipient of any previous messages (as it was not a known device before it is first used). This is why you see the fallback displayed instead.
> If you think the fallback is confusing or could be more helpful, you need to report this to the sending client, not the receiving client.

Since Dino can recognize that this is an OMEMO message that it cannot decrypt, maybe it should render something other than the fallback text? E.g. "this message is encrypted, but not to this device".

**Comment by licaon-kter** [comment]
Conversations has `Message was not encrypted for this device.`

**Comment by mar-v-in** [comment]
The fallback body is generated here: https://codeberg.org/iNPUTmice/Conversations/src/branch/master/src/main/java/eu/siacs/conversations/generator/MessageGenerator.java#L27
If you have ideas for improving the text, feel free to open an issue at https://codeberg.org/iNPUTmice/Conversations/issues

<hr>

> Since Dino can recognize that this is an OMEMO message that it cannot decrypt, maybe it should render something other than the fallback text?

While technically possible, it would be non-compliant behavior

> from [XEP-0384 (v0.3.0) § 4.7](https://xmpp.org/extensions/attic/xep-0384-0.3.0.html#usecases-receiving)
>
> When an OMEMO element is received, the client MUST check whether there is a <key> element with an rid attribute matching its own device ID. If this is not the case, the element MUST be silently discarded.

Although I'm not aware of such a deployment in practice, one might want to use OMEMO only for optional authenticity validation and not for encryption. In such a case, the `<body>` of the message would contain the original plain text of the message and discarding it would be counterproductive.

There are also valid reasons to send OMEMO messages to only a subset of recipient devices (e.g. to finish a session setup). Those messages would not have a `<body>` and thus currently wouldn't be displayed in Dino.

<hr>

As the messages from Conversations also have a [XEP-0380](https://xmpp.org/extensions/xep-0380.html) tag, we could support that as an indicator for incoming messages to actually be encrypted and thus to not display the `<body>` as sent from the remote entity, but instead show a more helpful error messages.
