### ISSUE TITLE
How to change the Application ID without breaking the app

### ISSUE THREAD

**Issue by jukfiuune** [dino/dino#1524]
Hello! I would like to change the Application ID of your app and the binary, because when i try to install my modified version alongside the normal dino, there is a conflict. I tried once already, but a lot of stuff was broken. Thanks in advance!

**Comment by licaon-kter** [comment]
There's a wiki entry about running two Dino iirc

**Comment by hrxi** [comment]
For posteriority: https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)#how-to-run-another-separate-dino-instance.
> # How to run another separate Dino instance?
>     env DBUS_SESSION_BUS_ADDRESS=  XDG_DATA_HOME="${dino_folder_path_for_this_instance}" dino
