### ISSUE TITLE
0.42 Debian installtion. No menu entry to make Group.

### ISSUE THREAD

**Issue by uniunikde** [dino/dino#1529]
Hello, wish everyone a very Happy Holiday season.

I recently installed Dino 0.42 to Debian 12. There is an possible issue that puzzles me a lot: I can't make the Group from the menu. It only shows "Start conversation" and "Join channel". 

It there anything wrong for my installation? Or, How could I enable the Group creation option?

Thank you very much.

**Comment by licaon-kter** [comment]
https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)#how-to-create-a-group-chat

/close this

**Comment by uniunikde** [comment]
Thank you. It is a little bit confusing...but I got it.
