### ISSUE TITLE
No "Call" button. Linux Mint (LMDE 6) 

### ISSUE THREAD

**Issue by uniunikde** [dino/dino#1530]
Hello, Installed in Linux Mint.

Dino 0.42

Issue:  No "call" button to the up right corner. I can call in, but no way to call out.

As shown below, the "Call" button (highlight circle) disappeared in my LMDE installation.

![No Call button](https://github.com/dino/dino/assets/146258357/33ea302d-375e-4406-b4d5-7f1be83cce09)

Please see what shall be the reason. Thanks.

**Comment by licaon-kter** [comment]
Make sure you both added each other as contacts? Maybe re-add

**Comment by uniunikde** [comment]
Thanks. Yes, I tested the Dino between well connected JIDs. 

I can call in the LMDE Dino from App.

**Comment by uniunikde** [comment]
> Make sure you both added each other as contacts? Maybe re-add

Thanks, I redid the adding contact and now it works. Fixed.
