### ISSUE TITLE
No E2EE after a Group created. 

### ISSUE THREAD

**Issue by uniunikde** [dino/dino#1531]
OS: Linux Mint
Dino: 0.42

https://github.com/dino/dino/wiki/Frequently-asked-questions-(FAQ)#how-to-create-a-group-chat

I followed the procedure above and created a group. But the created group has no **E2EE** and no **Phone call button**.

![group](https://github.com/dino/dino/assets/146258357/f079394f-d1cf-436a-b0b4-9955150fa0cf)

What shall be the problem? Thanks.

**Comment by licaon-kter** [comment]
Group calls are limited to Dino users only.

Did you make the group "members only"?

**Comment by fiaxh** [comment]
As there was no reply, I'll assume that the above hint helped. For questions like this, you can also join the Dino Channel.
