### ISSUE TITLE
How can we help?

### ISSUE THREAD

**Issue by mid1221213** [dino/dino#1534]
Hi,

I started to reply to [this Dino related comment](https://github.com/processone/ejabberd/issues/4130#issuecomment-1869782648) on ejabberd's issue tracker, but I think a better place to do it, while not ideal, is here.

After thinking I prefer not to mention what I was wanting to reply because it was a kind of humorous text that could have been misunderstood and I surely don't want this.

I really like Dino, thanks a lot to the authors / maintainers / contributors for this nice and useful piece of work!

I understand that working on / maintaining such a project is a lot of work and that you may have other duties / job / priorities, and I was, like some others, willing to help, but… **How** can I help?

I submitted 2 PRs, #1473 and #1510, months ago and got zero comment / action from the project owners about them, even after asking on the chat. Of course these PRs were addressing some issues that were important to me, and I may have not fixed them the right way, but how could I know? Just a comment / an advice / a word from you would have been welcome. **Any**.

I've seen some PRs / issues from some other people left alone too, this is why I chose to open an issue about this topic, it's not only about myself.

I'm just asking how I could help and contribute efficiently, and I'm sure I'm not the only one wondering.

Thanks again.

**Comment by Neustradamus** [comment]
@mid1221213: You have done good PRs!

**Comment by Jieiku** [comment]
@mid1221213 You are not alone, there is a similar pull request I am interested here: https://github.com/dino/dino/pull/1414

**Comment by Jieiku** [comment]
If the issue is that the maintainers are too busy, maybe they could vet a couple more people and add them as maintainers to the repo.

**Comment by ivanstepanovftw** [comment]
Just fork someone...

**Comment by licaon-kter** [comment]
@ivanstepanovftw Y U don't? And maintain... Heard it's easy lol

**Comment by mid1221213** [comment]
I'm closing this "issue" because IMO it is not relevant anymore.
Thanks to all.
