### ISSUE TITLE
Subject with body or thread should not change MUC topic

### ISSUE THREAD

**Issue by singpolyma** [dino/dino#1542]
It seems like MUC groupchat messages with a subject but that have a body or thread may be interpreted by dino as a muc topic change, but the XEP says not to interpret them that way, and the servers do not.

**Comment by eerielili** [comment]
Can confirm. Sending this via Gajim XML console does change the muc in Dino. I haven't tested with a thread node but i presume it's the same.

```xml
<message xmlns="jabber:client" to="saloon@muc.xmppserver.net" type="groupchat">
  <subject>test tat tut subject change</subject>
  <body>test tat tut body</body>
</message>
```
