### ISSUE TITLE
Latest Dino from Flathub (0.4.3) just hangs while "beta" (0.4.2) version works fine

### ISSUE THREAD

**Issue by Newbytee** [dino/dino#1545]
Using Dino 0.4.2 from Flathub running on a phone in Phosh, I'm able to use Dino normally. I was using Dino from Flathub Beta as when I first installed it, there was no Dino on Flathub (stable). However, since then, the beta branch stopped updating and now is just stuck at 0.4.2.

Today I realised that it was an outdated version and installed Dino from the stable branch which is at 0.4.3, and Dino just hangs on startup. No errors are printed if I run it from a terminal, just runs indefinitely with no GUI appearing. If I revert to the beta version, Dino runs like normal. I've not changed any permissions in Flatseal, and I also tried removing all the data from `~/.var/app/im.dino.Dino`, but nothing changed.

System:

 - Device: Purism Librem 5 (aarch64)
 - OS: postmarketOS Edge
 - Distribution method: Flatpak from Flathub
 - DE: Phosh

**Comment by di72nn** [comment]
I can reproduce the same issue on Linux Mint (Cinnamon).

Debug messages don't seem to contain anything useful (the are exactly the same as for 0.4.2, which does work):
```
$ flatpak run --env=G_MESSAGES_DEBUG=all im.dino.Dino 
(process:2): GLib-GIO-DEBUG: 17:22:47.446: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(process:2): GLib-GIO-DEBUG: 17:22:47.450: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ‘gio-network-monitor’
(process:2): GVFS-DEBUG: 17:22:47.459: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (g-dbus-error-quark, 2)

(process:2): GLib-GIO-DEBUG: 17:22:47.459: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
```

**Comment by Newbytee** [comment]
I can't reproduce with 0.4.4 from Flathub, closing.
