### ISSUE TITLE
Reactions are not encrypted while OMEMO is enabled and functional

### ISSUE THREAD

**Issue by kirmaha** [dino/dino#1548]
**Specs**
Debian 12 testing (trixie) with Dino 0.4.3 (flatpak from Flathub)

**Steps to reproduce**
1. Ensure OMEMO is enabled. Send a regular message and check that the message is encrypted.
2. Add a reaction to a message. Check with _Monocles chat_ the status of that reaction.

**Expected result**
The reaction shows as an encrypted message.

**Actual result**
The reaction is highlighted as not encrypted (see printscreen from _Monocles chat_ app on /e/OS below)

![zb2rhcUfQuhCiVuhcNzfLg2oMeVk1ydhfcGGqpMHbHmQHWNJa](https://github.com/dino/dino/assets/93599009/e49a6944-0c90-4c72-9b84-ab73e9caa0bf)

**Comment by licaon-kter** [comment]
If you control the server can you confirm in MAM that the smiley is unencrypted?

**Comment by fiaxh** [comment]
The legacy version of OMEMO that most clients currently implement only encrypts the text content of a message. Any additional content in a message cannot be encrypted with it. Even though Monocles displays reactions the same as message text, it is a different element in the message.

This will be resolved with the new version of OMEMO, which also encrypts additional message content. At the moment almost no client supports the new version. We have a draft implementation of the new OMEMO version, and once it is finished we can encrypt additional message content - however only with other clients that also support the new version.
