### ISSUE TITLE
MAM for MUC is not syncing MUCs history properly

### ISSUE THREAD

**Issue by giantplaceholder** [dino/dino#1558]
Hi there,

I'm using latest version off the master, as well as latest stable release as of now (0.4.3).

The issue I'm having is that for some reason Dino, unlike Conversations and, say, Pidgin, refuses to properly load MAM for MUCs stored on the server (running current prosody-trunk, server has properly configured mod_mam and mod_muc_mam).

I do understand that XEP-0313 is stated as _partially_ implemented, but then again, [this](https://github.com/dino/dino/commit/6c6e7e3aa7935ec513b7e5ea9b53a92b741ecf92) states that MAM support for MUCs was added around 0.4.0.

For example, these are the logs:

> (dino:10012): libdino-DEBUG: 00:47:53.920: connection_manager.vala:185: [username@fqdn] (Maybe) Establishing a new connection
> (dino:10012): libdino-DEBUG: 00:47:55.134: connection_manager.vala:229: [username@fqdn] New connection with resource dino.<censored>
> (dino:10012): libdino-DEBUG: 00:47:55.930: history_sync.vala:34: MAM: [username@fqdn] Reset catchup_id
> (dino:10012): libdino-DEBUG: 00:47:56.286: history_sync.vala:468: [username@fqdn] MAM available
> (dino:10012): libdino-DEBUG: 00:47:56.286: history_sync.vala:124: Fetch everything for username@fqdn (until 1970-01-01T00:00:00+0000)
> (dino:10012): libdino-DEBUG: 00:47:56.286: history_sync.vala:188: [username@fqdn | username@fqdn] Fetching latest page
> (dino:10012): libdino-DEBUG: 00:47:56.289: muc_manager.vala:518: [username@fqdn] Using PEP native bookmarks (urn:xmpp:bookmarks:1)
> (dino:10012): libdino-DEBUG: 00:47:56.623: history_sync.vala:209: [username@fqdn | username@fqdn] Latest page result: DINO_HISTORY_SYNC_PAGE_RESULT_MorePagesAvailable
> (dino:10012): libdino-DEBUG: 00:47:56.623: history_sync.vala:242: [username@fqdn | username@fqdn] Creating new db range for latest page
> (dino:10012): libdino-DEBUG: 00:47:57.738: history_sync.vala:188: [username@fqdn | project-name-benchmarking@conference.fqdn] Fetching latest page
> (dino:10012): libdino-DEBUG: 00:47:58.105: muc_manager.vala:480: [username@fqdn] Default MUC: conference.fqdn
> (dino:10012): libdino-DEBUG: 00:47:58.819: history_sync.vala:188: [username@fqdn | project-name-interviews@conference.fqdn] Fetching latest page
> (dino:10012): libdino-DEBUG: 00:47:58.989: history_sync.vala:188: [username@fqdn | project-name-frontend-technical-only@conference.fqdn] Fetching latest page
> (dino:10012): libdino-DEBUG: 00:48:00.611: history_sync.vala:188: [username@fqdn | project-name-frontend@conference.fqdn] Fetching latest page
> (dino:10012): libdino-DEBUG: 00:48:00.837: history_sync.vala:209: [username@fqdn | project-name-benchmarking@conference.fqdn] Latest page result: DINO_HISTORY_SYNC_PAGE_RESULT_MorePagesAvailable
> (dino:10012): libdino-DEBUG: 00:48:00.837: history_sync.vala:242: [username@fqdn | project-name-benchmarking@conference.fqdn] Creating new db range for latest page
> (dino:10012): libdino-DEBUG: 00:48:01.229: history_sync.vala:209: [username@fqdn | project-name-frontend-technical-only@conference.fqdn] Latest page result: DINO_HISTORY_SYNC_PAGE_RESULT_MorePagesAvailable
> (dino:10012): libdino-DEBUG: 00:48:01.229: history_sync.vala:242: [username@fqdn | project-name-frontend-technical-only@conference.fqdn] Creating new db range for latest page
> (dino:10012): libdino-DEBUG: 00:48:01.622: history_sync.vala:209: [username@fqdn | project-name-frontend@conference.fqdn] Latest page result: DINO_HISTORY_SYNC_PAGE_RESULT_MorePagesAvailable
> (dino:10012): libdino-DEBUG: 00:48:01.622: history_sync.vala:242: [username@fqdn | project-name-frontend@conference.fqdn] Creating new db range for latest page
> (dino:10012): libdino-DEBUG: 00:48:01.624: history_sync.vala:209: [username@fqdn | project-name-interviews@conference.fqdn] Latest page result: DINO_HISTORY_SYNC_PAGE_RESULT_MorePagesAvailable
> (dino:10012): libdino-DEBUG: 00:48:01.624: history_sync.vala:242: [username@fqdn | project-name-interviews@conference.fqdn] Creating new db range for latest page

(log is slightly censored)

And whilst there are at least a few days of history available, which is being properly synced to the newly installed instance of Conversations, it does not sync in Dino apart for default 20 messages. And there's no option to scroll to previous messages and _force_ MAM to load, like Dino or Gajim or Pidgin does.

MUCs are set up to store up to 10K messages whilst syncing up to 200 messages by default.

**Comment by fiaxh** [comment]
When you enter a MUC, Dino will only fetch the latest MAM page. On consecutive joins it will fetch all history since the last time you joined, thus you should not encounter issues on consecutive joins.

However, Dino does not currently support scrolling-up-to-fetch-more-messages. From your description, MUC MAM sync seems to work as intended, within the boundaries of not dynamically loading more history as you scroll. This is not a bug, but a missing feature. On-demand MAM queries are on our wishlist.
