### ISSUE TITLE
A way to make dino open http links in a chosen web browser.

### ISSUE THREAD

**Issue by amano-kenji** [dino/dino#1575]
dino opens links in brave browser, but I want it to open http links in a web browser that I choose.

**Comment by licaon-kter** [comment]
Didn't you chose that when you defined your default browser?

**Comment by amano-kenji** [comment]
dino ignores ~/.config/mimeapps.list. It just uses brave browser... How does dino open a link actually? Does it use xdg-desktop-portal OpenURI?

**Comment by licaon-kter** [comment]
Can you read https://github.com/dino/dino/issues/1409 ? Maybe it explains better

**Comment by amano-kenji** [comment]
So, you are saying dino uses `org.freedesktop.portal.OpenURI`?

**Comment by amano-kenji** [comment]
Since dbus-monitor says dino uses org.freedesktop.portal.OpenURI. I guess this is an upstream issue.
