### ISSUE TITLE
org.gnome.Platform branch 44 is end-of-life

### ISSUE THREAD

**Issue by zookeeper76** [dino/dino#1580]
Flatpak Update on Fedora
--------------------------------------

Looking for updates…

Info: runtime org.gnome.Platform branch 44 is end-of-life, with reason:
The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   im.dino.Dino

**Comment by mar-v-in** [comment]
Bumped to platform 46 in 6eeac8a5a17e8270ef68ee47ea1225602da0cc6f.

**Comment by phoropter** [comment]
The flatpak is still using EOL runtime. Does something need to be done to use it?
