### ISSUE TITLE
Cannot Connection after Resume from Suspend.

### ISSUE THREAD

**Issue by cocker-cc** [dino/dino#1583]
After resuming my Laptop from Suspend, Dino cannot reconnect to Server:  all Avatars are greyed out, and my new Messages stay in `pending`.

After I go to `Accounts`, disable my Account and re-enable it again, everything works fine.

Dino 0.4.3 on Cinnamon on Ubuntu.  
Installed via `flatpak install im.dino.Dino`.

**Comment by licaon-kter** [comment]
Not #374 #532 and etc?

**Comment by cocker-cc** [comment]
Duplicate to #532 → close
