### ISSUE TITLE
Request to Implement XEP-0389 Support in Dino

### ISSUE THREAD

**Issue by assu-2000** [dino/dino#1588]
**Is your feature request related to a problem? Please describe.**
We are currently working on implementing XEP-0389 (Extensible In-Band Registration) in Ejabberd server as part of Google Summer of Code (GSoC) 2024 project. XEP-0389 aims to enhance the existing XEP-0077 by introducing more secure and flexible registration mechanisms, including multi-factor authentication and account recovery options. To thoroughly test the implementation in the ejabberd server, We need a compatible XMPP client. Currently, no XMPP clients, including Dino, support XEP-0389, making it difficult to validate the new functionalities.

**Describe the solution you'd like**
I propose that Dino incorporates support for XEP-0389. This would involve updating Dino to handle the new registration and account recovery processes defined in XEP-0389, thereby allowing users to benefit from improved security features. Implementing this support will facilitate thorough testing and validation of the new protocol in conjunction with the ejabberd server.

**Additional context**
This request is part of my GSoC project for 2024, and I am seeking collaboration from the Dino development team. Implementing XEP-0389 in Dino will not only assist in testing the protocol on the server side but also enhance the client's capabilities. 
Your feedback and support will be invaluable in achieving a successful and secure integration of XEP-0389 into both ejabberd and Dino.

Ejabberd issue : https://github.com/processone/ejabberd/issues/4225#issuecomment-2169528268

Thank you !

**Comment by Neustradamus** [comment]
To follow this ticket

**Comment by fiaxh** [comment]
This issue has already been raised in #527.

Unfortunately we weren't able to tackle this during the timeframe of GSoC 2024, I hope you were still able to test with a different client.
