### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by diesys** [dino/dino#16]
There's no app icon so I made this elementary-style icon with 4 colours variants, hope you enjoy it!

![dinos](https://cloud.githubusercontent.com/assets/3579256/24024106/0fea71a4-0ab1-11e7-9b7b-442cbffedd76.png)

**Comment by fiaxh** [comment]
Thanks for sharing your design! However, we'd like Dino to have a more unique icon. I've been thinking about an icon myself and came up with this speech-bubble-dinosour. Perhaps I'll have to do a slightly modified version for smaller versions. (Negative) feedback or improvement ideas are very welcome.
![](https://cdn.rawgit.com/dino/dino/master/main/data/icons/dino.svg)

**Comment by d9h02f** [comment]
That looks hilarious, I like it.

**Comment by Biondilbiondo** [comment]
I love this icon :D

**Comment by t2d** [comment]
@fiaxh amazing!

**Comment by mar-v-in** [comment]
The icon is in use.
