### ISSUE TITLE
[postmarketos] dino can't delete conversations

### ISSUE THREAD

**Issue by lm2lm2** [dino/dino#1600]
hello

i just figure out there is not button/feature to remove conversations from the list..

thank you!

**Comment by fiaxh** [comment]
Which version of Dino are you using? In release versions, you can hover the conversation row and press the x button that appears on hover. In the latest development versions, you find a "Close Conversation" option in the menu in the upper right corner of the window.

**Comment by lm2lm2** [comment]
> Which version of Dino are you using? In release versions, you can hover the conversation row and press the x button that appears on hover. In the latest development versions, you find a "Close Conversation" option in the menu in the upper right corner of the window.

last one of postmarketos, aka 0.4.3

btw, if you could also fix that one : https://github.com/dino/dino/issues/1563
thank you!

**Comment by fiaxh** [comment]
I'm going to close this then, since the issue is solved on master (via 2f1b806dfe43a6323d8331a70172f01da88034d7).
