### ISSUE TITLE
omemo always

### ISSUE THREAD

**Issue by je-vv** [dino/dino#1609]
I understand a xmpp client is not required to use omemo, but perhaps an user would like to behave dino so that it only communicates with omemo always.

Can such option be added.  Not that it matters but this option exists for the android conversation client.  That's where I grabbed the idea from.

Thanks !

**Comment by fiaxh** [comment]
This is already implemented on master and will be part of the next release.

**Comment by je-vv** [comment]
Would these two merged commits the ones?  https://github.com/dino/dino/commit/f1be90c02f26c942e67978fd6d10ff2feeec8f9e (Add logic for OMEMO by default setting) and https://github.com/dino/dino/commit/cfb0ca2a64c1d680799ce752412b089ac075b780 (Add omemo key management tooltip), plus perhaps some other newer merged commits about omemo...

Are you guys planning for a new release?  I believe this is a key enhancement that would make dino stand as one of the few applications which allow the user to make omemo always, and even better yet by default.
