### ISSUE TITLE
Non-image HTTP uploads not visible at sender

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dino/dino#165]
When sending a PDF file with dino 0.0~git178.9d8e1e8, it does not show any action at the sender (except listing "Me: <URL>" in the left-hand side chat bar.

**Comment by MarcelWaldvogel** [comment]
Client: Ubuntu 17.04
Server: Prosody 0.9.12

**Comment by inkhey** [comment]
On fresh debian package version from
https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino
I get a similar problem with all non-image file.
Link is send and i can see the url in the left-hand chat bar but i can't see anything in the main windows.

**Comment by fiaxh** [comment]
Fixed in f25fadd.
