### ISSUE TITLE
Unable to change avatar

### ISSUE THREAD

**Issue by inkhey** [dino/dino#168]
I tried to change avatar from both snap package and compiled dino.
On snap package, the program just block after choosing an image. ( Permission problem maybe ? The snap package can't also see also my gnupg key)

On fresh compiled dino, the program don't block but just don't change my avatar.

I think the problem may be link to my already existing avatar. Dino didn't see it at startup that why i try to modifiy it.

**Comment by fiaxh** [comment]
Duplicate of #75. Also, the snap package is not provided by us.
