### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by merlinnusr** [dino/dino#17]
Dependencies?

**Comment by jubalh** [comment]
You'll find out during configure ;)

**Comment by t2d** [comment]
I had to do this on Ubuntu 16.04. But not sure if this is everything.
```
sudo apt install cmake valac gee-0.8 libsqlite3-dev uuid-dev libnotify-dev libgpgme11-dev ninja-build
```

**Comment by fiaxh** [comment]
The dependencies are listed in the README now.
