### ISSUE TITLE
MAM handling behaves weirdly

### ISSUE THREAD

**Issue by ThibG** [dino/dino#181]
Hello,
I have just tried Dino (9d8e1e88ec61403659a8cc410d5c4414e3bd3a96) and I am experiencing a few weird issues regarding message archive management across several clients:
- Dino did not initially seem to have fetched any archive when I started a conversation with a contact
- A few minutes later, when I went back to the conversation, some archived messages were fetched, but not the most recent ones (rather, some from about a month ago)
- Later on, the messages retrieved by Dino are much more consistent, but the ones sent from Dino itself disappeared

Other clients (gajim 0.16.11 and Conversations) seem to have a complete view of the conversation. The server used is prosody 0.10.

**Comment by paskalito** [comment]
I have a contact, from which i cannot receive any answer anymore.
ridiculussly i still get typing notifications. but i can receive answers only in conversations. if disconnect conversations it does not help.
also i dont get them in gajim, and or pidgin.

don't know which mecanisms are supposed to be responsible to make these things work. - but it seems either conversations has the only correct implementation or all the neccessary workarounds..
maybe its chatsecure.. np.. enlight me ! ^^

In the beginning i could also receive answers from contact.. maybe it has something todo with having dino conversations and my contact online all together for the first time..

my server: Prosody 0.9.12
contact server : https://www.jabber.de/
conversations: 1.22.1
dino-git r198.f6ac5bb-1 ( arch repo)

client of my contact: chatsecure

**Comment by linkmauve** [comment]
This could be an issue with OMEMO encryption, but this really isn’t the correct place for reporting such an issue, please open another ticket.

**Comment by paskalito** [comment]
thank you i did so :)
https://github.com/dino/dino/issues/243

**Comment by fiaxh** [comment]
The MAM catchup was rewritten to sync the latest messages first. At the time this issue was opened, it would sync the oldest messages first, explaining the observations.
