### ISSUE TITLE
“Contact details” (app.contact_details) should show “Conference details” in MUCs

### ISSUE THREAD

**Issue by ThibG** [dino/dino#182]
Having the menu item labelled as “Contact details” in MUCs is confusing. This should probably be renamed to “Conference details” in that situation instead.

**Comment by stevenroose** [comment]
This happens to me only in some MUCs. It also actually shows Contact details, while on other MUCs, it shows the participant list etc.

**Comment by fiaxh** [comment]
This menu no longer exists.
