### ISSUE TITLE
Messages are sometimes not shown until the conversation is re-selected

### ISSUE THREAD

**Issue by ThibG** [dino/dino#184]
Sometimes, messages won't be shown until a conversation is re-selected. New messages will display, but not the messages that haven't been shown in the first place.

This seems to be some kind of race condition when rendering a conversation.

Steps to reproduce it:
- Have someone from an unfocused conversation send a succession of messages
- Switch to that conversation while the contact is sending messages
- Messages received during the switch won't be shown until that conversation is switched out and back in again

**Comment by fiaxh** [comment]
Much of the message receiving and parsing code was rewritten since this issue was opened. I cannot reproduce this problem anymore. If you are still able to reproduce it, I will reopen the issue.
