### ISSUE TITLE
Inline images

### ISSUE THREAD

**Issue by rscmbbng** [dino/dino#19]
Despite the project being very young I've found myself using it often. One of the modern features still missing is the ability to display images sent from other clients via http_upload. Especially when these images are shared over OMEMO encrypted connections. Conversations on Android  and UrlImagePreviewPlugin for Gajim are references of said feature.  Adding this would make the project much more pleasant for frequent use.

**Comment by fiaxh** [comment]
Images sent in the form of urls are displayed since a257b16.

**Comment by d9h20f** [comment]
Only for unencrypted pictures, so I think the issue should remain open for a bit longer.

**Comment by silberzwiebel** [comment]
also, it seems to me that MAM messages containing an image link are not shown as images
