### ISSUE TITLE
[roster] display availability in roster

### ISSUE THREAD

**Issue by arthurlogilab** [dino/dino#190]
I see that when I roll my mouse over a contact it displays if the contact is online or away or offline. It would be really useful to have that information displayed all the time.

**Comment by d9h20f** [comment]
Your contact's avatar is greyscale if they're offline and coloured when online.

**Comment by kawaii** [comment]
What about when clients are set to away or busy?

**Comment by zuglufttier** [comment]
I guess, dino has the same philosphy as Conversations: https://github.com/siacs/Conversations#where-can-i-see-the-status-of-my-contacts-how-can-i-set-a-status-or-priority

And I tend to agree.
