### ISSUE TITLE
[UI] marker line for messages already viewed

### ISSUE THREAD

**Issue by arthurzenika** [dino/dino#192]
It would be awesome to have a visual queue that shows in a chat or in a conference room which messages have already been read.

**Comment by aereaux** [comment]
I'm taking a look at implementing this feature.  Is there a particular style of UI marker that would be preferred?

**Comment by fiaxh** [comment]
Done in https://github.com/dino/dino/pull/1473 / https://github.com/dino/dino/commit/4cc7e076e65c604e7a2f840ddc394ea70700577d.
