### ISSUE TITLE
Messages with duplicate IDs not displayed

### ISSUE THREAD

**Issue by kawaii** [dino/dino#194]
When using the Dino client I noticed that in the prosody@conference.prosody.im MUC chatroom I could not see any messages posted by one of their bots (HAL), but could see messages sent by their other bot, Bunneh. A user in the chat explained to me that it was likely because HAL is using a duplicate ID and Dino is attempting to deduplicate.

**Comment by Zash** [comment]
Specifically, the bot uses the id of the message it is replying to.

**Comment by chrisballinger** [comment]
Seems like [XEP-0359](https://xmpp.org/extensions/xep-0359.html) would help here.

**Comment by fiaxh** [comment]
This issue should not exist anymore for some time. Dino should only deduplicate based on (UUID-format) stanza ids on a per-user basis.
