### ISSUE TITLE
GLib assertion when there is no connection

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#196]
Here is the `g_critical()` call:
```(dino:22465): GLib-CRITICAL **: g_date_time_difference: assertion 'end != NULL' failed```

**Comment by astavale** [comment]
If it's any help you can debug this using the G_DEBUG environment variable and `gdb`. Something like:

```
G_DEBUG=fatal-criticals gdb dino
```

Then in `gdb` use `run` and `bt` to get the backtrace. Compile with Vala's `--debug` switch should also give Vala source filenames and line numbers in the backtrace.

**Comment by fiaxh** [comment]
a8cc94c should have fixed that.
