### ISSUE TITLE
Randomize resource string on first connection to an account

### ISSUE THREAD

**Issue by ge0rg** [dino/dino#2]
Dino connects with "dino" as the resource string. If you have two instances of Dino on the same account, they will end up "kicking" each other from the server.

For multiple reasons it would be better to replace the fixed string by a randomized one:
- User surveillance: somebody who knows your bare JID can guess the resource part and determine your client version and probe you for online/offline presence (as well as an estimate of the RTT between you and your server)
- Multi-client operation: if you have two Dinos, no user interaction is required to resolve the conflict
- This would accord to Best Practices: https://wiki.xmpp.org/web/XMPP_IM_Client_Design_Guidelines#Do_not_to_encode_any_semantics_into_the_resource.2C_let_the_server_generate_a_resource_for_you

While the above article recommends a server-generated GUID, many clients generate the resource as <clientname>.<hex(randomuint32())>, e.g. `yaxim.4711CAFE`.

The important thing is that you generate/store the value on first connection to the server and reuse it on subsequent reconnects, so that a server can figure out when it needs to replace a dead session of yours.

**Comment by fiaxh** [comment]
Thanks for bringing this up. As of fa78573 a random resource like `dino.4711cafe` is generated at account creation.
