### ISSUE TITLE
message archive management

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#20]
Finally, a modern, good looking, easy client that I can install on non-nerd PCs. Already now it works like a charme, thanks a lot!

Not sure, whether I should open issues about missing functionality, because the program is still in its early stage and I'm sure you have a list of stuff floating somewhere around. Maybe you colud add this list here to github, potentially as issues?

But anyway, I'll open this one.
I logged in into my account and found the last 20 or so messages from the MUCs I'm in. I guess, this was not due to message archive management, as I can't scroll up more. Also, I did not receive history from single user chats. So, feature request: please implement message archive management.

**Comment by fiaxh** [comment]
Implemented in fb36ea0.
