### ISSUE TITLE
Broken Arch Linux repository

### ISSUE THREAD

**Issue by spacekookie** [dino/dino#203]
Adding the OBS source and updating pacman sources results in this

```sudo pacman -S dino                                                                        
resolving dependencies...
looking for conflicting packages...

Packages (1) dino-0.0~git187.193ca0b-0

Total Download Size:   0.63 MiB
Total Installed Size:  2.98 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
error: failed retrieving file 'dino-0.0~git187.193ca0b-0-x86_64.pkg.tar.xz' from download.opensuse.org : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.
```

Would rather not have to compile from source via AUR 😞

**Comment by darix** [comment]
need more details about the exact error. 404? are you using https and it blocks protocol downgrades?

**Comment by NicoHood** [comment]
Build your package from source instead of relying from an untrusted build server. I guess this project has nothing to do with this build server. Get the PKGBUILD from AUR, check it and build&install.

**Comment by jubalh** [comment]
> untrusted build server
It's the build servers of the openSUSE project. What is a trusted build server to you?

**Comment by svalo** [comment]
@NicoHood 
[Here](https://build.opensuse.org/package/show/network:messaging:xmpp:dino/dino) you can see how the package gets built. I contributed to the PKGBUILD which is really close to the one I co-mantain on the AUR. :)

**Comment by NicoHood** [comment]
@jubalh It is compareable to just using an AUR helper without checking the PKGBUILD at all. I dont like both of the options, but relying on a build server makes it even more intransparent, as you directly install a precompiled binary. I just dont recommend it.

This method is unsupported by Arch and by Dino. I guess the best way to solve the problem is to contact the maintainer of the opensuse package.

**Comment by jubalh** [comment]
> This method is unsupported by Arch and by Dino. I guess the best way to solve the problem is to contact the maintainer of the opensuse (arch) package.
1. As you can see at the [OBS page](https://build.opensuse.org/package/users/network:messaging:xmpp:dino/dino) @mar-v-in has access to it.
2. The [dino wiki](https://github.com/dino/dino/wiki/Distribution-Packages) clearly recommends to use packages built by OBS.

So I don't think "unsupported by dino" is right here ;)

**Comment by NicoHood** [comment]
Okay, I was wrong. Sorry.
