### ISSUE TITLE
Don’t send an unavailable presence on non-connected accounts

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#211]
There is a race when the user presses ^Q before the account is done connecting, Dino should only send said unavailable presence if the connection has reached the point where it’s bound.

When it happens before the socket is open, this error is printed:
```
** (dino:11145): CRITICAL **: file xmpp-vala/src/module/presence/module.vala: line 54: uncaught error: trying to write, but no stream open (xmpp_core_io_stream_error-quark, 1)
```

**Comment by fiaxh** [comment]
This shouldn't happen anymore.
