### ISSUE TITLE
[FR] Website & Communication

### ISSUE THREAD

**Issue by Echolon** [dino/dino#216]
Hello guys,

I'd like to suggest to start communicating via Twitter or GnuSocial once a client is released.

Furthermore it would be great to have an additional website to represent Dino. To keep the workload low, I added some suggestions to inspire and/or may reduce the effort.

https://pages.github.com/
http://www.profanity.im/
https://ring.cx/en#screenshots
https://conversations.im/

Cheers

**Comment by d9h20f** [comment]
Have there been any indications to suggest this wouldn't happen?

**Comment by Echolon** [comment]
@d9h20f Guess not, but I just started with my thoughts. Now we can discuss and hear what developers say.

**Comment by Echolon** [comment]
www.dino.im  Thanks again - great work!

I'll close this threat - but informing users via a news/Twitter/In-client information feed would be good, too - even for people who are not familiar with XMPP at all (once you release officially). Remind them about How To's or ongoing things in the community so. Just an idea.

Cheers
