### ISSUE TITLE
UX: don't reorder contacts list

### ISSUE THREAD

**Issue by bersace** [dino/dino#217]
Hi,

Regarding UX, it's better to have fixed position of contacts and conferences in contact list, this allow te remember where is a room or contact.

I suggest to sort contact alphabetically. What do you think of this ?

Thanks for dino !
Regards,

**Comment by fiaxh** [comment]
Dino displays a conversation list, not a contact list / roster. It focuses on the conversation, not some feature of the contact (like name or group). Conversations are sorted by the time of the last message, resulting in current conversations and conversations with people you frequently contact being at the top of the list.
