### ISSUE TITLE
Prebuilt packages

### ISSUE THREAD

**Issue by d9h20f** [dino/dino#22]
Until this hits main distro repos, it would be nice if someone could provide RPM/DEBs.

**Comment by jubalh** [comment]
Before it can hit any distro repos it should first be released ;)
The project is in a early state and suddenly all kinds of people are so happy with it that they want to have it already :)

So far [an install section](https://github.com/dino/dino/issues/15) is missing in the Makefile. Also the configure script uses git submodule init which probably won't work on the build infrastracture of some distros.

I started to package it for openSUSE at my [home repo](https://build.opensuse.org/package/show/home:jubalh/dino).

Only remaining issue is that RPATH is not allowed on such binaries. I'm not sure what I should do here.
Maybe dino devs can jump in here and give me a hand, then rpms will be ready.

OpenBuildService can also build packages for Fedora, Debian, Arch and Ubuntu from the same repo (if we add the corsponding files).

**Comment by michaelkanis** [comment]
Could Flatpak be an option?

**Comment by jubalh** [comment]
I guess an option for sure, though most upstream project so far tend to create AppImages AFAIK.

**Comment by jubalh** [comment]
for the record: https://github.com/dino/dino/commit/f4334732da0846c3e73f7bc490fabd807598925b adds a spec file too

**Comment by mar-v-in** [comment]
@jubalh 
The spec file should work for openSUSE as well. There is a patched tito for openSUSE in OBS, in case you want to use tito to populate the version field of the spec file.

`./configure` needs internet access to pull in the `libsignal-protocol-c` (if you are not using `./configure --disable-plugin=omemo`), in case you can't have internet access during build, you can use `./configure --fetch-only` while having internet access and run `./configure` on the target system later.

For Fedora users I set up a copr repo that automatically builds the current master here: https://copr.fedorainfracloud.org/coprs/larma/dino/

@michaelkanis 
flatpak is on the longterm todo list, as it will be supported by the all major distros, but right now, it's not high priority.

**Comment by d9h02f** [comment]
Thanks for the repos, @jubalh and @mar-v-in.

**Comment by ChloeWolfieGirl** [comment]
If flatpak is a longterm todo, what about deb or snaps?

**Comment by jubalh** [comment]
if they create flatpaks, why would they create snaps?

**Comment by ChloeWolfieGirl** [comment]
I'm not hear to argue what’s better, worse, or why, I'm just interested in an easy way of getting the app on my system :)

Flatpak is a Long term goal, Maybe debs and/or snaps are near term.

**Comment by mar-v-in** [comment]
debs: yes, snaps: no

Ubuntu 16.10 and Debian Jessie won't be supported (GTK+ version is too old) so no need to hurry with deb packages

**Comment by jubalh** [comment]
Also for distros to enable the omemo plugin by default, checking out libsignal-protocol-c from git wont be accepted.
Asked them to use symbol versioning so we can create a package. And add this as a proper dependency: https://github.com/WhisperSystems/libsignal-protocol-c/issues/59

**Comment by mar-v-in** [comment]
@jubalh we will have the libsignal-protocol-c source code in our release source archives, so distros can build from that archive.

**Comment by jubalh** [comment]
@mar-v-in I assumed that you would do this.

In any case its better if distros package libsignal-protocol-c and have it as a shared library.
If it has a bug only that package needs to be updated, not relied on all downstream to update their 'own' libsignal-protocol-c.

**Comment by mar-v-in** [comment]
@jubalh 
I would generally agree to this statement, but as libsignal-protocol-c is not used in the wild and it does not give any guarantees on stable API, this is not an easy thing. Also note that libsignal-protocol-c is not intended to be used for OMEMO, which means that an update that fixes a Signal-specific behavior might as well break an OMEMO-specific behavior. And OMEMO will move to olm eventually, which will make libsignal-protocol-c basically useless on desktops (you need a phone number for Signal, which desktops usually don't have).

However we will add a way to use a distro-packaged libsignal-protocol-c if available, so in case you really want to do it, it will be possible.

**Comment by jubalh** [comment]
@mar-v-in Okay I see.

> However we will add a way to use a distro-packaged libsignal-protocol-c if available, so in case you really want to do it, it will be possible.

Yes please do that. I already packaged libsignal-protocol-c and its available. Now dino only needs to be able to use the one from the distro.

**Comment by rugk** [comment]
I see @mariogrip also added a snap package…

**Comment by theScrabi** [comment]
Also a considerable way was to use [appimage](https://appimage.org/). This way you don't have to install snapd or flatpack. Appimage creates self containing binaries, that run everywhere.
