### ISSUE TITLE
Provide some way to tell whether the message was sent

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#225]
Currently, there is no way to tell whether a message was even sent or not.  I just used dino over a pretty unstable mobile connection, so dino was offline when I typed the message.  5 minutes later, I noticed by checking on my phone (thanks to carbon copies) that the message has since been sent. However, there is no indication about this whatsoever in the dino UI.

I thought that's what the checkmarks are for, but that does not seem to be right. Either "one checkmark" should be repurposed to indicate "message delivered to server" (which IIRC it means e.g. in Signal), or dino should do something like conversations and show "..." for the sent time until the message is sent -- or maybe there is a better UI. But having no UI for this pretty important information ("did the message leave my device") is not good.

**Comment by NicoHood** [comment]
I also noticed, that sometimes both checkmarks are missing, but the message is read. If my partner answers again the next message might have both checkmarks. The feature it very unreliable in general for me.

**Comment by RalfJung** [comment]
Note that I am not talking about the message being read, or the peer even being online. I care about the message having done the first hop, from my device to my own jabber server. That's important because it tells me whether I need to try and get internet connectivity to get the message out, or whether that part is already done.

**Comment by mightyBroccoli** [comment]
I would be interested in this too. Possibly or hopefully without special plugins on the serverside. This would enable users to WhatsApp like see that their stuff at least got sent correctly.

**Comment by Echolon** [comment]
Rel: **Warn user on first insecure chat message** #76

**Comment by fiaxh** [comment]
Since 7309c6f3ac4e580f197b4835d05bb011fa90780b Dino displays `(pending)` after a message that has not been ACK'ed by the server for 10 seconds. This depends on the server supporting stream management.
