### ISSUE TITLE
Crypt MUC

### ISSUE THREAD

**Issue by genofire** [dino/dino#226]
only allow when jid are public

**Comment by d9h20f** [comment]
?

**Comment by genofire** [comment]
If a muc runs with the settings "non-anonymous" all jid are known and crypto like omemo and gpg could work.

Try it with conversations ....

**Comment by fiaxh** [comment]
MUC encryption with OpenPGP already works, given that every occupant announces their key. For OMEMO encryption, this is part of #36 (OMEMO tracking).

**Comment by genofire** [comment]
@fiaxh u are right - (gpg i could not verifiy nobody else use it with xmpp in my list)

Could u implement the uncrypt at first?
`I sent you an OMEMO encrypted message but your client doesn’t seem to support that. Find more information on https://conversations.im/omemo` is really annoying (answer plain is okay, but not read the cryption recieved message ...

**Comment by d9h20f** [comment]
@genofire It will be done when it's done. Just use Gajim for encrypted group chats for now.

**Comment by genofire** [comment]
sry, i was not able to set a bounty on a closed issue:
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=44025760)](https://www.bountysource.com/issues/44025760-omemo-tracking?utm_source=44025760&utm_medium=shield&utm_campaign=ISSUE_BADGE) now it is on #36 - deal with it
