### ISSUE TITLE
Dino doesn't display contact avatars

### ISSUE THREAD

**Issue by bochecha** [dino/dino#227]
I've got a few contacts with pictures, but Dino doesn't show them.

For example this one, observe how Empathy (behind) shows a picture but Dino (in front) doesn't:

![screenshot from 2017-11-29 10-43-02](https://user-images.githubusercontent.com/272170/33368784-ec30e510-d4f2-11e7-96c8-d79cc13b33ab.png)

(note: I asked @toniob before putting his face/name here, and he was ok with it)

Note: I'm using Dino inside a Flatpak build that I'm testing (I'll submit it soon), so maybe the Flatpak sandbox is causing the issue, or maybe I'm missing a build dependency.

Any idea how I can debug this further to see whether something is missing? Maybe a special CLI invocation to observer what the XMPP server sends me and verify there's a picture in there? 🙂

**Comment by jubalh** [comment]
I think I have the same.
Contact added his avatar via Gajim.

**Comment by jubalh** [comment]
So it seems that if the contact used an "old" version of Conversation, it used webp to upload the avatar. Newer version seem to use another format which than can be understood by Dino (and others).
If this is the case the contact needs to get the newest Conversation *and* set the avatar again.

Also your contact and yourself need to be online at the same time for the avatar to be pulled.

However all this is the case for me and I still have some contacts where I don't see the profile picture.
It would be nice to be able to force dino to check if there is a new picture and get it, for example when clicking on 'Contact details'.

**Comment by jubalh** [comment]
Still suffering from this.

> It would be nice to be able to force dino to check if there is a new picture and get it, for example when clicking on 'Contact details'.

Would be awesome ;)

**Comment by Peque** [comment]
@bochecha Any updates on the flatpak availability? I created a new issue to track it: https://github.com/dino/dino/issues/453

**Comment by bochecha** [comment]
@Peque it is tracked over at https://github.com/dino/dino/pull/343.

It's completely unrelated to this issue though.

IIRC the problem is there are multiple standards for handling avatars, and Dino only supports some of them. At least that's what I remember from a conversation with @fiaxh, but that was a while ago.

**Comment by fiaxh** [comment]
Does the current master improve/fix this issue for you? (Except of WebP file format avatars set by old Conversations versions. Those won't be shown as argued [here](https://github.com/dino/dino/issues/548#issuecomment-486179210), but people can update them.)

**Comment by bochecha** [comment]
@fiaxh I have stopped using Dino, and in fact XMPP.

As a result I won't be able to test this any more.

Hopefully somebody else can confirm that this is fixed. :slightly_smiling_face:

**Comment by virtadpt** [comment]
It is not.

**Comment by licaon-kter** [comment]
@virtadpt what version do you have?

**Comment by virtadpt** [comment]
v0.1.0, installed from distribution package.  Talked about it in chat@dino.im this morning, I have a pretty good idea of what's going on (and it's not Dino), so I'm going to take a couple of days to dist-upgrade my servers to the latest and greatest to enable the XEPs that they don't support right now.  Keep this closed, but if it works I'll write it up on my blog and post a link here in another comment to document it.  I can't be the only person who scratched their head over this.
