### ISSUE TITLE
missing desktop file

### ISSUE THREAD

**Issue by diesys** [dino/dino#23]
I was trying to make a draft desktop file, by now it's just simple name, description, some keywords and the category.
Maybe you want to choose your own description but I hope could be useful!

`[Desktop Entry]`
`Version=1.0`
`Name=Dino`

`GenericName=XMPP/jabber client`
`Icon=dino`
`Terminal=false`
`StartupNotify=false`
`Categories=Network;`
`Keywords=chat;xmpp;jabber;dino;internet;`

`Exec=/usr/bin/dino`
`Name[en_GB]=dino.desktop`

**Comment by mar-v-in** [comment]
A `.desktop` file is now available at [mian/data/dino.desktop](https://github.com/dino/dino/blob/master/main/data/dino.desktop) and installed during `make install`.
