### ISSUE TITLE
Wrong URL to access the source from Weblate

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#241]
It makes it hard to go to the source in order to get some context.

For example for https://hosted.weblate.org/translate/dino/plugin-openpgp/fr/?checksum=c48f155a91734dcd I get https://github.com/dino/dino/blob/src/account_settings_widget.vala#L81 instead of https://github.com/dino/dino/blob/master/plugins/openpgp/src/account_settings_widget.vala#L81

**Comment by fiaxh** [comment]
This is fixed now.
