### ISSUE TITLE
cannot receive answers from chat partner (omemo)

### ISSUE THREAD

**Issue by paskalito** [dino/dino#243]
I have a contact, from which i cannot receive any answer anymore.
ridiculussly i still get typing notifications. but i can receive answers only in conversations. if disconnect conversations it does not help.
also i dont get them in gajim, and or pidgin.

don't know which mecanisms are supposed to be responsible to make these things work. - but it seems either conversations has the only correct implementation or all the neccessary workarounds..
maybe its chatsecure.. np.. enlight me ! ^^

In the beginning i could also receive answers from contact.. maybe it has something todo with having dino conversations and my contact online all together for the first time..

my server: Prosody 0.9.12
contact server : https://www.jabber.de/
conversations: 1.22.1
dino-git r198.f6ac5bb-1 ( arch repo)

client of my contact: chatsecure

**Comment by vanitasvitae** [comment]
I'm also experiencing this. The strange thing is, that only some messages are lost. Almost sounds like it has to do with carbons?

**Comment by licaon-kter** [comment]
Seeing this too, I guess:
* Dino gets the messages sent by Conversations
* Conversations shows "Dino user is typing"
* but will not receive any message sent by Dino

**Comment by NicoHood** [comment]
@iNPUTmice I saw you asked in the public chat on which issues you could help out. I guess that is one of the most annoying issues, because you cannot really use dino like that. I am unable to receive messages on desktop from some specific users and it really bugs me.

**Comment by fiaxh** [comment]
Lots about OMEMO usage has been fixed in various clients (and servers). Is this still an issue? @paskalito @vanitasvitae @licaon-kter @NicoHood

**Comment by alyssais** [comment]
I believe I have this problem, on the latest ChatSecure release and latest Dino commit.

**Comment by licaon-kter** [comment]
@alyssais do try with Monal maybe to exclude CS issues
