### ISSUE TITLE
Connection does not work when connecting to a .onion server

### ISSUE THREAD

**Issue by N07070** [dino/dino#244]
Hello.
I have an account on a .onion server, and I can connect to it using Orbot and Conversations on Android. 

I recently installed the last version of Dino by compiling it, and installed `tor` and `torsocks`  on my Ubuntu 17.04 Laptop. Connecting to the Internet and using the Tor Browser works perfectly.

The conversation I have on my phone don't show up on Dino.

Is there something I did wrong ?

Thanks

**Comment by N07070** [comment]
When I launch Dino from the command line, it gives me this : 
```
user@cmpt ~ » dino
CONNECTION LOST?
Stream Error: Error resolving “q*******za**ic.onion”: Name or service not known
recovering in 3

** (dino:4264): CRITICAL **: xmpp_stanza_listener_holder_disconnect: assertion 'listener != NULL' failed
CONNECTION LOST?
Stream Error: Error resolving “quvzi**********c.onion”: Name or service not known
recovering in 3
```

**Comment by licaon-kter** [comment]
Try with: `proxychains4 dino`

**Comment by fiaxh** [comment]
Connecting to .onion servers should work fine with current development versions of Dino.
