### ISSUE TITLE
No dialog on subscription request

### ISSUE THREAD

**Issue by mimi89999** [dino/dino#246]
When Dino receives a subscription request from a contact that adds me, it doesn't show any dialog. Because of that, I can't know when a contact adds me nor accept his presence request.

**Comment by lovetox** [comment]
Hi, 

i just tested this, and on my Ubuntu Gnome, it shows a System notification that there is a sub request, but if i click it nothing happens, and in Dino itself there is no indication that there is a open sub request

**Comment by lovetox** [comment]
The Problem seems to be that a Notification is the only way to accept a Sub Request.

The Notification is only available for 2 Seconds, after that there is no way to get the Buttons again, see my screencast

https://upload.jabberfr.org/p4mBUxdhpr4t3gaG/Screencast.webm
