### ISSUE TITLE
Issues with private messages from a room

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#250]
- Images sent in private are also displayed in the MUC tab.
- Switching from the MUC tab to the private tab generates a wrongly stacked view (see 
[wayland-screenshot.png](https://user-images.githubusercontent.com/7755816/34425882-fdda7038-ec30-11e7-9b3f-230822635575.png)).

**Comment by fiaxh** [comment]
1. Was fixed by #415 
2. Should have been fixed by 85d194e
