### ISSUE TITLE
Issues with ciphertext padding

### ISSUE THREAD

**Issue by real-or-random** [dino/dino#253]
I was in the mood and wanted to read some crypto code....

All of this applies to CBC mode and PKCS#7 padding, which is not used at all if I understand correctly:

 - `padded_len` could be `0`  in `out_buf[padded_len - 1]`, leading to an out-of-bounds read in https://github.com/dino/dino/blob/9728e832b18e8bbfcc0e011b5b1da9afe6021bf3/plugins/signal-protocol/src/signal_helper.c#L327
 - Independently, `out_buf[padded_len - 1]` could be larger than `padded_len`, leading to a negative array length two lines below. I have no idea what Vala actually does in this case.
 - All padding bytes needs to be verifed. At least the standard says so. And it's ugly to get this right in constant time. All of this is probably not a security issue if the ciphertext is authenticated. (And if not, there is a padding oracle anyway.)
 - (It's wrongly called PCKS#5 padding in the code).

Maybe it's easiest to just get rid of the code? And maybe also the CTR mode and the MACs if it's not used anywhere.

**Comment by mar-v-in** [comment]
- I addressed the two issues mentioned first in 6b58b348fa42c3206f56c4b897a255d81f0ea7a9
- PKCS#5 padding is technically incorrect, but the corresponding makro is set up in the header field of the library we use here - if you have some time to waste, you can create an issue there 😛 : https://github.com/WhisperSystems/libsignal-protocol-c/blob/d60dbf2e4fb05719c3d37513ae9a5472c106647f/src/signal_protocol.h#L59
- The PKCS padding code (as well as the CTR mode) are used from the signal-protocol-c library.
