### ISSUE TITLE
Don’t request our own OMEMO devicelist, we’ll receive it in a pubsub#event due to our caps

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#257]
Since we already have `eu.siacs.conversations.axolotl.devicelist+notify` in our caps, there is no need to request the `eu.siacs.conversations.axolotl.devicelist` node during connection.

**Comment by chrisballinger** [comment]
Although this is true in theory, in practice you may need a way to manually refetch the device list when PEP fails to work as intended.

**Comment by linkmauve** [comment]
If you assume PEP is broken, don’t use OMEMO at all, it can’t work without it.  If you know any broken implementation, please open a ticket on their bug tracker.

**Comment by iNPUTmice** [comment]
If this is about your own device list you basically have to request that because you don’t know if there is already a device list online. If there is no device list you wont received one and you would have to configure some sort of timeout.

**Comment by linkmauve** [comment]
Oh, I see, that makes sense.
