### ISSUE TITLE
Add a local caps cache

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#259]
Until XEP-0390 gains widespread support though, any entity could poison your XEP-0115 cache so there should be two layers:
- A trusted one generated from current known good caps;
- And a per-JID one, obtained from previous clients of this one contact.

This would reduce the startup traffic by quite a lot, especially in MUC joins (it may help #233 for example).

**Comment by Echolon** [comment]
https://xmpp.org/extensions/xep-0115.html
https://xmpp.org/extensions/xep-0390.html

**Comment by fiaxh** [comment]
Dino implements XEP-0115 and verifies the hash before saving the information in a "good caps" store.

**Comment by linkmauve** [comment]
One could poison the cache with a valid hash pointing to a different disco#info than expected, waqas demonstrated such an attack many years ago.

You should consider them per-JID until proven to be correct, and (to avoid unnecessary queries) you could also ship a database of known good caps such as xnyhps’s, actualised.
