### ISSUE TITLE
duplicate MUC messages

### ISSUE THREAD

**Issue by moparisthebest** [dino/dino#264]
In a biboumi MUC all the messages I send are duplicated, linkmauve says this would probably happen on conference.jabber.org as well, here are the relevant logs:

these are duplicated in dino, but not conversations or gajim:

```
XMPP OUT [me@me.com]
<message id='adf8ca4c-195e-4770-b8c1-677e40e275e9' to='#irc_chan@biboumi.host' type='groupchat'>
  <body>
    test
  </body>
</message>

XMPP IN [me@me.com]
<message type='groupchat' to='me@me.com/dino.d86c09f' from='#irc_chan@biboumi.host/moparisthebest'>
  <body>
    test
  </body>
  <stanza-id id='ebda31f5-cb1b-48be-9629-711b1691f337' by='#irc_chan@biboumi.host' xmlns='urn:xmpp:sid:0' />
</message>
```

these are not duplicated:

```
XMPP OUT [me@me.com]
<message id='0c8991fe-4cb7-4ca0-82b1-0d620cf36208' to='chat@dino.im' type='groupchat'>
  <body>
    test
  </body>
</message>

XMPP IN [me@me.com]
<message id='0c8991fe-4cb7-4ca0-82b1-0d620cf36208' type='groupchat' to='me@me.com/dino.d86c09f' from='chat@dino.im/moparisthebest'>
  <body>
    test
  </body>
</message>
```
I'm guessing dino is relying on id to de-duplicate, and lovetox on chat@dino.im said it should be sending and using origin-id for that instead.  I personally don't know the right solution.

**Comment by fiaxh** [comment]
This should have been solved in 321c3529f3fedbd5eaa9cd619ee408fb683921ca.
