### ISSUE TITLE
Small visual improvement: time

### ISSUE THREAD

**Issue by heipa0** [dino/dino#270]
Hi, imho the time in the chat window looks messy because it is jumping around.

It would look cleaner if the time is always on the very right site.

![dinotime](https://user-images.githubusercontent.com/35292661/34765249-fa99e8ae-f62b-11e7-8c58-0d4d4b180122.PNG)

**Comment by d9h20f** [comment]
You're using an old version of Dino, this changed recently to have the time and read/encryption indicators display right next to the username. I don't think that looks good either, though. Ideally, read and encryption indicators would be next to the username, and the time would be on the right as it was before.
