### ISSUE TITLE
Failed to enable smacks: Stream management is already enabled

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dino/dino#271]
On Prosody, up to 500 entries like the following can be seen every 5 seconds, on some (unclear) circumstances. Dino will also reopen the connection to that server every few seconds. 

> Jan 10 12:50:08 c2s5590cd5d6660	warn	Failed to enable smacks: Stream management is already enabled

It could be caused by awakening the machine Dino runs on from sleep. In this case, it was on a different network with different addresses. `netstat -tnap` shows that Dino still has network connections from the previous network open (source address from the other address space).

I do not know how to repeat the issue, but if there is anything I can do to debug that if it happens again, please let me know.

**Comment by MarcelWaldvogel** [comment]
Just noticed that this might be related/the same as #237

**Comment by fiaxh** [comment]
In a case in which this bug occurred after every suspend, 4ccdc1d fixed it. If this problem still occurs for anyone, I will reopen the issue.

**Comment by muppeth** [comment]
Just had similar issue with a user using dino. It brought the server totally to it's knees. I am waiting for the user to perhaps get some extra info on this but not sure I will get any. It was for sure dino though
