### ISSUE TITLE
feature request: support for message correction, XEP 0308

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#272]
https://xmpp.org/extensions/xep-0308.html

**Comment by Perflyst** [comment]
Some shiny new commit adds support for this https://github.com/dino/dino/commit/871ff33ac79f3d17b0260b8bfcd27780038edd6d

Would be nice if you could edit the message with arrow up press too, otherwise it works great!

**Comment by fiaxh** [comment]
Dino supports last message correction as of 871ff33 and d091a6c adds up arrow as a shortcut :slightly_smiling_face:

**Comment by wiktor-k** [comment]
Works very well @fiaxh, thank you :clap: By the way a funny bug: when I input some special characters in the autocorrect field that require right alt (`ó`, `ł`, `ą`) the focus jumps from the autocorrection field to the message field and inputs the special character there, not in the autocorrection.
