### ISSUE TITLE
How to change language

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#273]

**Comment by fiaxh** [comment]
Your system's language is used, if a translation for the language exists.

**Comment by licaon-kter** [comment]
What environment variable is checked exactly?

I've done the translation, I've added it to the folders (and ), recompiled, yet still in english.

Please reopen.

**Comment by svalo** [comment]
@licaon-kter On linux you can call dino from a terminal as follows `$ LANG="ro_RO.UTF-8" dino
` and you should have it localized in Romanian. Can you issue`$ echo $LANG`  in a terminal? It will show which language is set.

**Comment by licaon-kter** [comment]
So I've setup a Lubuntu VM, fight the build system (https://github.com/dino/dino/pull/276), but still can't change language:
`LANG="ro_RO.UTF-8" dino` -> still English
`LANG="de_DE.UTF-8" dino` -> still English

I've got all these `LC_*=ro_RO.UTF-8` yet they don't help.

All the apps respect `ro_RO`, except Dino.
