### ISSUE TITLE
More strings that can't be translated or appear as untranslated

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#274]
Since I can't trigger a language change and my added language is not detected ( https://github.com/dino/dino/issues/273 ) I've just replaced `en.po` (all 3) with [my own translated ones](https://hosted.weblate.org/projects/dino/translations/ro/) and recompiled. Yes, now Dino is in my language of choice, but I have no idea if this method might be reason for these strings to appear untranslated though.

So...
* Accounts->the account toggle has `ON/OFF` in English although they are translated
* Accounts->any account->press show OMEMO keys button->title bar says `OMEMO Keys`, text says `Own fingerprint` and `Other devices` in English, albeit there are translated
* Accounts->add account, `JID` should be available for translation, `Cancel` button is in English but `Save` is translated
* Accounts->delete account, `You won't be able to access...` it appears in English but is translated, `Cancel` button is in English, but `Delete` is translated

/LE: Was able to run in the correct language, and yes these still appear.

**Comment by licaon-kter** [comment]
More:
* MUC properties->discover true IDs-> `Anyone` and `Moderators Only` appear in English
* Accounts->any account->press show OMEMO keys button->other devices `- None -` appears in English

**Comment by linkmauve** [comment]
The above PR fixes most of the strings you reported, except the OMEMO-related ones (I think the plugin may not set the correct gettext domain, but I’m not sure), nor the MUC one which is sent by the MUC service itself.

**Comment by licaon-kter** [comment]
Seeing some in the new account setup that we can't translate: `Sign in`, `Username`, `Password`, `Required value missing`

**Comment by licaon-kter** [comment]
More in OMEMO, `Manage key`, `OMEMO key management`, `Automatically accept new keys`, `Own key`, `Associated keys`

ON/OFF still untranslatable...

Add account -> `Sign in`

**Comment by licaon-kter** [comment]
MUC tooltips for right side buttons: `Members`,`Search messages`,`Channel details`

**Comment by licaon-kter** [comment]
MUC editing (voice, members, change nick etc) has a dozen or so strings that we can't translate.
