### ISSUE TITLE
inline images are displayed at wrong times

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#287]
As seen in a MUC: someone sends one or more images using Conversations to the MUC and some text messages after the images, my dino is offline. I start dino and it receives the image links and downloads the images. However, the images are place above the text messages even though the text came later in time. I also saw both, the links to the images and the images. Restarting dino results in a proper order, so I missed to do a screenshot.

**Comment by albjeremias** [comment]
This bug happened to me... and i restarted dino, and the order is still wrong... the images are displayed in the bottom.. and the new messages always before...

**Comment by albjeremias** [comment]
how can this be debugged/researched, any hints? I can also request for some troubleshoot from the sysadmin!

**Comment by fiaxh** [comment]
I am not aware of this issue currently existing and am assuming that it is outdated. If you should encounter it again, please open an issue.
