### ISSUE TITLE
TlsError while trying to connect to a server with a let's encrypt certificate

### ISSUE THREAD

**Issue by Dracooooo** [dino/dino#292]
Hi, I'm getting the following error while trying to connect to a server with a let's encrypt certificate.

```
** (dino:6350): CRITICAL **: dino_connection_manager_connection_get_stream: assertion 'self != NULL' failed

** (dino:6350): CRITICAL **: xmpp_xmpp_stream_get_module: assertion 'self != NULL' failed

** (dino:6350): CRITICAL **: dino_connection_manager_connection_get_stream: assertion 'self != NULL' failed

** (dino:6350): CRITICAL **: xmpp_presence_module_send_presence: assertion 'self != NULL' failed

** (dino:6350): CRITICAL **: dino_connection_manager_connection_get_stream: assertion 'self != NULL' failed

** (dino:6350): CRITICAL **: xmpp_xmpp_stream_disconnect: assertion 'self != NULL' failed
Stream Error: TlsError: Unacceptable TLS certificate
```

Is there a way to accept the certificate?

**Comment by ne0h** [comment]
Did you include the complete certificate chain?

**Comment by Dracooooo** [comment]
@ne0h What do you mean? I didn't make any changes at any point. Where do I include the certificate chain?

**Comment by slaveriq** [comment]
@Dracooooo server side you(or the server admin) needs to use the `fullchain.pem` as certificate.
Client side you can add the letsencrypt ca to your trust store (that differs from OS to OS)
Dino currently has no way of accepting a "bad certificate", however there is a pull request  (  https://github.com/dino/dino/pull/209 ) that adds that functionality.

For more information on the trust chain you can checkout https://letsencrypt.org/certificates/
