### ISSUE TITLE
'Add account' window goes under 'Accounts' window and blocks it

### ISSUE THREAD

**Issue by elimohl** [dino/dino#296]
If I open 'Add account' window and move cursor outside it hides under 'Accounts' window. After that I'm not able to move 'Accounts' window with a mouse anymore. So I cannot reach 'Add account' window until I move 'Accounts' window into another workspace. I use i3-wm.

**Comment by licaon-kter** [comment]
Config i3 to move window with key+mouse. Works like that for me.

**Comment by elimohl** [comment]
@licaon-kter ok, it works. But I think it's strange that moving cursor outside 'Add account' makes it hiding. At first it makes me think that dino hangs (because I don't need mod key to move 'Accounts' window before).

**Comment by licaon-kter** [comment]
You use unclutter? That's kinda normal.

**Comment by elimohl** [comment]
@licaon-kter ok, thank you.
