### ISSUE TITLE
Add "New Account" under + Button Settings 

### ISSUE THREAD

**Issue by console-cowboy** [dino/dino#30]
As I understand it, it is presently impossible to reach the Account configuration window that is available upon launching the application initially in Budgie Desktop or other GTK+ DEs. I do not know as this is the case in GNOME, where there are contextual drop-downs with menu items in GNOME; presumably the menu button is located in aforementioned menu.

Ideally, a "New Account" menu option to pull up this view could exist alongside "Start Chat" and "Join Conference".

**Comment by d9h02f** [comment]
Normally the drop-down options in GNOME should show under a separate button in the title bar of the application on other desktops. If this isn't happening there's an issue in Budgie or in Dino, but duplicating functionality shouldn't be done.

**Comment by console-cowboy** [comment]
Well this functionality should actually exist in Budgie too; there are drop-down options for "New Window" and "New Document" in gedit. But whatever options you have aren't showing up in Budgie.

**Comment by mar-v-in** [comment]
I guess you just pressed the wrong button?
 
![image](https://cloud.githubusercontent.com/assets/994036/24620009/6a34ab2c-189c-11e7-88b2-b9a91ac93132.png)

**Comment by fiaxh** [comment]
The application menu fallback button now behaves more like it does in other GTK applications (d6e742e). Hopefully this will reduce the confusion about it.
![](https://cloud.githubusercontent.com/assets/9932450/24673221/cde46d34-1977-11e7-9d40-e919f7dce8d4.png)
