### ISSUE TITLE
how to build under windows OS

### ISSUE THREAD

**Issue by abugandar** [dino/dino#306]
how to build under windows OS

**Comment by svalo** [comment]
I think you can find some more infoes in the following issues : #18  #113  #304 . You can also search between the issues using windows as a keyword :)

**Comment by abugandar** [comment]
i didnt get any clear instruction

**Comment by fiaxh** [comment]
There are no "clear instructions" on how to build Dino for Windows at this point, because Dino won't work sufficiently well under Windows right now.
