### ISSUE TITLE
translate to languages different than English

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#31]
Please provide languages different than English / an interface to contribute translations easily.
I'd contribute to a German translation.

**Comment by d9h02f** [comment]
For easy translations:
https://hosted.weblate.org
https://www.transifex.com

**Comment by rscmbbng** [comment]
a translation interface is now provided, this includes the possibility to work on the german translation. See #37

**Comment by Jibec** [comment]
I think we should close this bug as it is using https://hosted.weblate.org/projects/dino/translations/
