### ISSUE TITLE
Today mark can be on top of older messages

### ISSUE THREAD

**Issue by Porkepix** [dino/dino#310]
Today by starting Dino and having the Dino room opened, I could see that while last messages were from Friday and Saturday, there was a "Today mark" on top of them.

See the joined screenshot.

![screenshot from 2018-03-19 10-07-53](https://user-images.githubusercontent.com/709500/37587295-332d1b24-2b5f-11e8-91e6-16476d19b2d9.png)

This is using Gnome's date format, so "ven." stands for "fri." and "sam." for "sat." and we currently are Monday.

**Comment by ThibG** [comment]
From what I understand of the source code, the `local_time` attribute of `Dino.Entities.Message` is the time a message was initially received (or forwarded to MAM) while the `time` attribute is the time specified by the message using [XEP-0203](https://xmpp.org/extensions/xep-0203.html).
See https://github.com/dino/dino/blob/master/libdino/src/service/message_processor.vala#L111-L117

However, `time` is used for display while `local_time` is used for sorting (see https://github.com/dino/dino/blob/master/main/src/ui/conversation_summary/default_message_display.vala#L38-L40).

So, the messages from friday and saturday are sorted according to the moment they were received (i.e., monday) and displayed at the date they were delivered to the MUC thanks to XEP-0203, while the older messages were probably loaded from Dino's database.

Indeed, there seem to also be a bug causing both `local_time` and `time` to be loaded from the same database row (`time`), see https://github.com/dino/dino/blob/master/libdino/src/entity/message.vala#L84-L85
