### ISSUE TITLE
 [suggestion] Join the Gnome project

### ISSUE THREAD

**Issue by Postroutine** [dino/dino#315]
Dino is an awesome chat application. Why not join it to the Gnome project?

Some advantages:
- Be hosted on the Gnome Project infrastructure
- Help from the gnome community
- Be distributed by the Gnome Project as part of their apps
- Possible more integration with other applications
- When you have new features on your app, it will be discussed in the release notes of Gnome

Generally, this mean more highlight on the application and help more people to know your work

**Comment by mar-v-in** [comment]
@jubalh 
> Probably means not having individual account settings but needing to your their general account settings thing?
It's not a requirement to use gnome-online-accounts and this is not how gnome-online-accounts work (the application stores the accounts, it just has some helper library to use it from goa).

@Postroutine 
We already discussed this within the team.

Some portions of the GNOME infrastructure isn't or wasn't very desirable to us. i.e. We think that using GitHub is a strength for the project. GNOME project seems to require projects to host their git on git.gnome.org with read-only mirror on GitHub.

We also don't want people to conclude that we only target the GNOME desktop: Dino is intended to run on all operating systems (including Windows, MacOS and any desktop for Linux/BSD) and we do want to promote by publishing on various channels (like Windows 10 Store, Mac App Store). While this is future talk and we indeed focus on the GNOME desktop right now, this project is not about improving GNOME by giving it a decent XMPP client, but about improving XMPP by giving it a decent desktop client.

Finally GNOME community seems to be more interested in Matrix these days, but this is just a personal opinion.

**Comment by diazbastian** [comment]
Hi, I've seen a lot on the GNOME mailing lists that are massively [migrating to Gitlab](https://csorianognome.wordpress.com/2018/03/20/important-gitlab-mass-migration-plan/), which greatly improves its infrastructure, there are even developers who are paying attention to Empathy and its rewrite that mainly provides XMPP/Jabber support.

Anyway I dont see the need to be part of the project to offer a product that mostly follows its guidelines, however, if I would like to see Dino in [flathub](https://beta.flathub.org/) at some point in the future 👍.
