### ISSUE TITLE
Ability to copy own OMEMO fingerprint

### ISSUE THREAD

**Issue by svalo** [dino/dino#32]
Using Arch+ KDE and latest commit from dino.
In the account window I can see my OMEMO fingerprint, however I'm not able to copy it nor to select it. The button which shows just on the side of the FP has no tooltip nor it copies the fingerprint.  

It would be very useful to support copying the FP as verification process would be easier.

**Comment by svalo** [comment]
svalo/dino@200bbfae5c03a6d4e0a4d14ebc78ac05eb5cbbd3 allows to select the fingerprint. If there are no downsides I'd open a pull request.

**Comment by mar-v-in** [comment]
Downside: it will look ugly ;) 

The button next to the fingerprint is supposed to open a dialog where you can
- Display your fingerprint as QR code
- Copy your fingerprint to clipboard
- Show your other devices' keys
- Remove trust from your other keys
- Clear the list of other devices

Similar to how it is done in Conversations

**Comment by mar-v-in** [comment]
OMEMO plug-in features will be tracked in #36

**Comment by svalo** [comment]
> Downside: it will look ugly ;)
Well, true =) 

Then it's  a 'bit' beyond my current knowledge, still if there are some 'junior jobs' I'd like to help.
