### ISSUE TITLE
XEP-0443: XMPP Compliance Suites 2021

### ISSUE THREAD

**Issue by Neustradamus** [dino/dino#325]
Please add support of XEP-0443: XMPP Compliance Suites 2021: https://xmpp.org/extensions/xep-0443.html

Which replaces:
- XEP-0423: XMPP Compliance Suites 2020: https://xmpp.org/extensions/xep-0423.html
- XEP-0412: XMPP Compliance Suites 2019: https://xmpp.org/extensions/xep-0412.html
- XEP-0387: XMPP Compliance Suites 2018: https://xmpp.org/extensions/xep-0387.html
- XEP-0375: XMPP Compliance Suites 2016: https://xmpp.org/extensions/xep-0375.html
- XEP-0302: XMPP Compliance Suites 2012: https://xmpp.org/extensions/xep-0302.html
- XEP-0270: XMPP Compliance Suites 2010: https://xmpp.org/extensions/xep-0270.html
- XEP-0243: XMPP Server Compliance 2009: https://xmpp.org/extensions/xep-0243.html
- XEP-0242: XMPP Client Compliance 2009: https://xmpp.org/extensions/xep-0242.html
- XEP-0216: XMPP Intermediate Server 2008: https://xmpp.org/extensions/xep-0216.html
- XEP-0212: XMPP Basic Server 2008: https://xmpp.org/extensions/xep-0212.html
- XEP-0211: XMPP Basic Client 2008: https://xmpp.org/extensions/xep-0211.html
- XEP-0073: Basic IM Protocol Suite: https://xmpp.org/extensions/xep-0073.html

**Comment by fiaxh** [comment]
Dino is mostly compatible with IM Advanced Client as well as A/V Calling Advanced Client. If you would like to see a specific standard implemented, please open a more narrowed-down issue.
