### ISSUE TITLE
macOS build problem: 'gpgme.h' file not found

### ISSUE THREAD

**Issue by ne0h** [dino/dino#326]
Hey guys,

I followed the official wiki page to build dino on macOS locally. I have the following errors:

> [87/611] Building C object plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_fix.c.o
> FAILED: plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_fix.c.o 
> /usr/local/Cellar/ccache/3.4.2/libexec/cc  -Iplugins/gpgme-vala -Iexports -isystem /usr/local/Cellar/libgee/0.20.1_1/include/gee-0.8 -isystem /usr/local/Cellar/glib/2.56.0/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.42/include -fdiagnostics-color -Wall -Werror=format-security -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC    -Wno-incompatible-pointer-types -Wno-pointer-sign -Wno-int-conversion -Wno-unused-variable -Wno-unused-function -Wno-unused-label -I/Users/ne0h/Downloads/dino2/plugins/gpgme-vala/src -MD -MT plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_fix.c.o -MF plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_fix.c.o.d -o plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_fix.c.o   -c ../plugins/gpgme-vala/src/gpgme_fix.c
> In file included from ../plugins/gpgme-vala/src/gpgme_fix.c:1:
> exports/gpgme_fix.h:5:10: fatal error: 'gpgme.h' file not found
> #include <gpgme.h>
>          ^~~~~~~~~
> 1 error generated.

and

> [95/611] Building C object plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_helper.c.o
> FAILED: plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_helper.c.o 
> /usr/local/Cellar/ccache/3.4.2/libexec/cc  -Iplugins/gpgme-vala -Iexports -isystem /usr/local/Cellar/libgee/0.20.1_1/include/gee-0.8 -isystem /usr/local/Cellar/glib/2.56.0/include/glib-2.0 -isystem /usr/local/Cellar/glib/2.56.0/lib/glib-2.0/include -isystem /usr/local/opt/gettext/include -isystem /usr/local/Cellar/pcre/8.42/include -fdiagnostics-color -Wall -Werror=format-security -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -fPIC    -Wno-incompatible-pointer-types -Wno-pointer-sign -Wno-int-conversion -Wno-unused-variable -Wno-unused-function -Wno-unused-label -I/Users/ne0h/Downloads/dino2/plugins/gpgme-vala/src -MD -MT plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_helper.c.o -MF plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_helper.c.o.d -o plugins/gpgme-vala/CMakeFiles/gpgme-vala.dir/src/gpgme_helper.c.o   -c plugins/gpgme-vala/src/gpgme_helper.c
> plugins/gpgme-vala/src/gpgme_helper.c:10:10: fatal error: 'gpgme.h' file not found
> #include "gpgme.h"
>          ^~~~~~~~~
> 1 error generated.

Running `./configure` previously does not report any error:

> ➜  dino2 git:(master) ./configure 
> -- Found Ninja: /usr/local/bin/ninja (found version "1.8.2")
> -- The C compiler identification is AppleClang 9.1.0.9020039
> -- The CXX compiler identification is AppleClang 9.1.0.9020039
> -- Check for working C compiler: /usr/local/Cellar/ccache/3.4.2/libexec/cc
> -- Check for working C compiler: /usr/local/Cellar/ccache/3.4.2/libexec/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/local/Cellar/ccache/3.4.2/libexec/c++
> -- Check for working CXX compiler: /usr/local/Cellar/ccache/3.4.2/libexec/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Building plugin: omemo
> -- Building plugin: openpgp
> -- Building plugin: http-files
> -- Installation directory for architecture-independent files: /usr/local
> -- Installation directory for architecture-dependent files: /usr/local
> -- Installation directory for read-only architecture-independent data: /usr/local/share
> -- Installation directory for user executables: /usr/local/bin
> -- Installation directory for dino-specific data: /usr/local/share/dino
> -- Installation directory for .desktop files: /usr/local/share/applications
> -- Installation directory for .service files: /usr/local/share/dbus-1/services
> -- Installation directory for icons: /usr/local/share/icons
> -- Installation directory for C header files: /usr/local/include
> -- Installation directory for object code libraries: /usr/local/lib
> -- Installation directory for locale files: /usr/local/share/locale
> -- Installation directory for dino plugin object code files: /usr/local/lib/dino/plugins
> -- Installation directory for Vala API files: /usr/local/share/vala/vapi
> -- Performing Test COMPILER_SUPPORTS_fdiagnostics_color
> -- Performing Test COMPILER_SUPPORTS_fdiagnostics_color - Success
> -- Performing Test COMPILER_SUPPORTS_Wall
> -- Performing Test COMPILER_SUPPORTS_Wall - Success
> -- Performing Test COMPILER_SUPPORTS_Werror_format_security
> -- Performing Test COMPILER_SUPPORTS_Werror_format_security - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_incompatible_pointer_types
> -- Performing Test COMPILER_SUPPORTS_Wno_incompatible_pointer_types - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_pointer_sign
> -- Performing Test COMPILER_SUPPORTS_Wno_pointer_sign - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_int_conversion
> -- Performing Test COMPILER_SUPPORTS_Wno_int_conversion - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_discarded_qualifiers
> -- Performing Test COMPILER_SUPPORTS_Wno_discarded_qualifiers - Failed
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_but_set_variable
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_but_set_variable - Failed
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_variable
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_variable - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_function
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_function - Success
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_label
> -- Performing Test COMPILER_SUPPORTS_Wno_unused_label - Success
> -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
> -- Found GObject: /usr/local/Cellar/glib/2.56.0/lib/libgobject-2.0.dylib (found version "2.56.0") 
> -- Found Vala: /usr/local/bin/valac (found suitable version "0.40.0", minimum required is "0.34") 
> -- Found Gee: /usr/local/Cellar/libgee/0.20.1_1/lib/libgee-0.8.dylib (found version "0.20.1") 
> -- Found GLib: /usr/local/Cellar/glib/2.56.0/lib/libglib-2.0.dylib (found suitable version "2.56.0", minimum required is "2.38") 
> -- Found SQLite3: /usr/lib/libsqlite3.dylib (found version "3.14.0") 
> -- Found GDKPixbuf2: /usr/local/Cellar/gdk-pixbuf/2.36.11_1/lib/libgdk_pixbuf-2.0.dylib (found version "2.36.11") 
> -- Found GIO: /usr/local/Cellar/glib/2.56.0/lib/libgio-2.0.dylib (found version "2.56.0") 
> -- Found GModule: /usr/local/Cellar/glib/2.56.0/lib/libgmodule-2.0.dylib (found version "2.56.0") 
> -- Found Gettext: /usr/local/bin/xgettext (found version "0.19.8.1") 
> -- Found GTK3: /usr/local/Cellar/gtk+3/3.22.29_1/lib/libgtk-3.dylib (found suitable version "3.22.29", minimum required is "3.22") 
> -- Found GDK3: /usr/local/Cellar/gtk+3/3.22.29_1/lib/libgdk-3.dylib (found version "3.22.29") 
> -- Found GPGME: /usr/local/lib/libgpgme.dylib  
> -- Found GCrypt: /usr/local/lib/libgcrypt.dylib  
> -- Looking for memset_s
> -- Looking for memset_s - found
> -- Found Soup: /usr/local/Cellar/libsoup/2.62.0_1/lib/libsoup-2.4.dylib (found version "2.62.0") 
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /Users/ne0h/Downloads/dino2/build
> -- Configured. Type 'make' to build, 'make install' to install.

What am I missing? Thanks in advance!

**Comment by silberzwiebel** [comment]
First of all: The instructions in the wiki are not official!

That said, you might try to reinstall gpgme via homebrew (`brew install gpgme`) and check whether the following links exist (created by homebrew):

```
/usr/local/lib/libgpgme.dylib -> ../Cellar/gpgme/1.10.0/lib/libgpgme.dylib
/usr/local/include/gpgme.h -> ../Cellar/gpgme/1.10.0/include/gpgme.h
```

Also, potentially `brew doctor`might give information on what's wrong in your setup.

**Comment by fiaxh** [comment]
You should be able to build Dino on MacOS using [these](https://github.com/dino/dino/wiki/macOS) instructions.

**Comment by rfinner** [comment]
sudo apt install golang-github-proglottis-gpgme-dev

**Comment by licaon-kter** [comment]
@rfinner what? This is about MacOS, right? So `homebrew` ?

**Comment by rfinner** [comment]
Right, sorry I did not read everything. I found this issue when searching for a similar problem. Installing these libs solved my issue and so I thought I should share. It seems this issue is Closed and is about MacOS and so I apologize if I was a bit off-topic.

**Comment by zoechi** [comment]
Looks like `sudo apt install swig libgpgme-dev` fixed it for me
