### ISSUE TITLE
Support XEP-0380: Explicit Message Encryption

### ISSUE THREAD

**Issue by weiss** [dino/dino#334]
It would be nice if Dino could mark encrypted messages with an [XEP-0380][1] tag.  E.g., for OMEMO messages, Conversations adds this:

```xml
    <encryption xmlns='urn:xmpp:eme:0'
                name='OMEMO'
                namespace='eu.siacs.conversations.axolotl'/>
```

For PGP messages, you [should][2] omit the `name` attribute:

```xml
    <encryption xmlns='urn:xmpp:eme:0'
                namespace='jabber:x:encrypted'/>
```

[1]: https://xmpp.org/extensions/xep-0380.html
[2]: https://xmpp.org/extensions/xep-0380.html#protocols

**Comment by weiss** [comment]
@stevenroose 
> Is `eu.siacs.conversations.axolotl` the official identifier for OMEMO? :)

It currently [is][1], actually.

[1]: https://xmpp.org/extensions/xep-0384.html#glossary-general

**Comment by sdhand** [comment]
Apologies, somehow managed to miss that @labdsf had already submitted a PR. I can alter mine to only affect OpenPGP if that would be preferred.
