### ISSUE TITLE
IRC support

### ISSUE THREAD

**Issue by mejo-** [dino/dino#336]
Do you have IRC support for Dino on the roadmap?

I understand that Dino is still in early development stage and that you focus on XMPP for now. In fact I'm thrilled to see that Dino finally might become the clean, beautiful and usable XMPP desktop client with sane and secure features (OMEMO!) that is missing so badly!

It's just that IRC is another widely used chat protocol, especially in the Free Software community. For me, having both XMPP and IRC available in one dektop client is really convenient. I have to admit that this the main reason why I'm still using Pidgin.

**Comment by d9h20f** [comment]
There are already countless IRC clients, many of them quite good. Polari is pretty much Dino for IRC.

**Comment by dos1** [comment]
There are plenty of IRC transports for XMPP. ejabberd even has integrated one distributed with itself. You should already be able to use Dino for IRC via any of them.

**Comment by dos1** [comment]
Unless you don't mind sharing your IRC credentials to some 3rd party service, no. Just use one of the publicly available ones. There's a good chance that your server already hosts one, but if not, you can use other ones too.

If you do mind, then yes, however, you don't even need to switch to this server, it only needs to host the transport.
