### ISSUE TITLE
Add support for aesgcm URI scheme

### ISSUE THREAD

**Issue by ThibG** [dino/dino#337]
A few XMPP clients use a non-standard URI scheme together with HTTP upload to transfer end-to-end encrypted files.
I don't think there is any proper specification anywhere, but here are multiple existing implementations:
* https://github.com/iNPUTmice/ImageDownloader/blob/master/src/main/java/eu/siacs/conversations/Downloader.java
* https://github.com/moparisthebest/ImageDownloader/blob/master/aesgcm.c

**Comment by fiaxh** [comment]
There is an OMEMO tracking issue (#36) which this is part of.

> OMEMO Encrypted HTTP File Uploads (ProtoXEP missing)
