### ISSUE TITLE
Some contacts show empty name

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#338]
I have Prosody configured to automatically create a roster group with all the users in our server. Somehow these users don't show up nicely in Dino. `erik@weuste.club` is an example. 

In the second screenshot, he's the second conversation.

![screenshot-2018-ym-18--16- m-37](https://user-images.githubusercontent.com/853468/38939406-244a7eea-4328-11e8-9f77-6aa476ab24fb.png)
![screenshot-2018-ym-18--16- m-14](https://user-images.githubusercontent.com/853468/38939405-24284cd0-4328-11e8-8f2a-1d81c8306f79.png)

The same contact is here in Gajim in my roster and in Conversations:
![screenshot-2018-ym-18--16- m-04](https://user-images.githubusercontent.com/853468/38939491-4fe578de-4328-11e8-98fc-e43f04f2e969.png)
![screenshot_20180418-164835](https://user-images.githubusercontent.com/853468/38939579-84db3b50-4328-11e8-84a0-df65c90f842f.png)

**Comment by fiaxh** [comment]
Does 5425243 solve this for you?

**Comment by stevenroose** [comment]
Ooooh, an all-numeric hash prefix! Let me check that real quick!

**Comment by stevenroose** [comment]
Yes. Now the JIDs show up instead of an empty string! The contact's name (from the vCard) would be very much preferred though.
