### ISSUE TITLE
selecting ranges of text from chats

### ISSUE THREAD

**Issue by rscmbbng** [dino/dino#355]
First of all, thanks for the great work! I use dino on a daily basis and it is great to see where it is going.

One issue I encounter frequently though is that it is only possible to select a single message from the conversation view. It would greatly improve the usability if one could drag and select arbitrary ranges in the chat history. This is used a lot when copying to pastebins for example. Incidentally, the last time I opened gajim was to copy a range of chat history which was impossible with dino.

**Comment by fiaxh** [comment]
This was already requested in issue #85.
