### ISSUE TITLE
OMEMO files preview

### ISSUE THREAD

**Issue by volga629** [dino/dino#357]
Hello Everyone,
When using OMEMO file preview not  display actual image or file. It just display sent file URI.
Without  OMEMO all works.

````
aesgcm://myhost.domain.com/daa42d5938ee90237dcbfd090890fbc94df30151e3e/ib0qTbJ6LQkOWFdGWbUtPjrBQOpkgaDIJNuIBs70CZgWoA3jyBXp1WPvIMCbFOYe/hMzG1QvmQ5C0nnjAMNDIcA.jpg#9882a710872e595e84e8ba928e403eeef2wsd56ccb2a6d26cbb12e89280690f81fd243390765cf276e391e1c1f9bc9ae9f

````

Version:
dino-0.0~git253.105006c-78.1.x86_64

**Comment by NicoHood** [comment]
I think this could be fixed with https://github.com/dino/dino/pull/339

**Comment by fiaxh** [comment]
That's part of #36.

**Comment by stevenroose** [comment]
@fiaxh It's not listed in #36 OP.
