### ISSUE TITLE
Smileys don't get converted if you don't type a trailing spacebar

### ISSUE THREAD

**Issue by jmallach** [dino/dino#362]
I just got a Debian update of Dino, from April 30, and I've noticed smileys don't get translated to unicode unless you hit spacebar to add a space after the smiley. When you do that, the smiley is translated to Unicode in the input field, and correctly sent as Unicode when you send your message.

Typing:

> `^Hello! :)$`

Will result in

`Hello! :)`

While  typing:

> `^Hello! :) $`

Will result in

`Hello! 🙂`

**Comment by fiaxh** [comment]
Fixed in e852a0a.
