### ISSUE TITLE
Dino crashes on Alpine Linux upon the window creation

### ISSUE THREAD

**Issue by marmistrz** [dino/dino#365]
Alpine Linux is one of these distributions which use musl instead of glibc. Happens both on 3.7 release and `edge` (current development release). The backtrace was collected on `edge`. 

The backtrace from valgrind doesn't mention dino anywhere, though: https://pastebin.com/upGcj18q

GDB doesn't show anything useful in the backtrace:

```
(gdb) bt
#0  0x00006a19f4ec22a5 in ?? ()
#1  0x0000000000000001 in ?? ()
#2  0x0000000000000000 in ?? ()
```
This may be due to
```
warning: Cannot call inferior functions, Linux kernel PaX protection forbids return to non-executable pages!
```

The `APKBUILD` used for building Dino under Alpine. 
[APKBUILD.txt](https://github.com/dino/dino/files/2020461/APKBUILD.txt)

**Comment by fiaxh** [comment]
Since Dino has been [packaged for Alpine Linux Edge](https://git.alpinelinux.org/aports/tree/testing/dino/APKBUILD) by now I assume this is not an issue anymore.
