### ISSUE TITLE
paste images from clipboard

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#385]
Expected Behavior
when i select "copy image" on firefox, gimp or other place, i then can go to another window and paste the image on a different window, and this image should be set in a standby, and then ask confirmation to be sent/uploaded

Faulty/Current Behavior
When i paste (ctrl+v) the image, nothing happens.

**Comment by albjeremias** [comment]
is this PR fixing it? 
https://github.com/dino/dino/pull/330

**Comment by Perflyst** [comment]
Gajims issue for this is open for years but this is quite a must have feature these days...

**Comment by wurstsalat3000** [comment]
One year, and it's been resolved.

See https://dev.gajim.org/gajim/gajim/issues/8864

**Comment by muesli** [comment]
Would love to see that, it's funnily the one thing I constantly stumble over when using Dino.

**Comment by muesli** [comment]
@fiaxh Installed dino from git just for that. Thank you :heart:
