### ISSUE TITLE
Cycle/Reconnect to a MUC

### ISSUE THREAD

**Issue by Ppjet6** [dino/dino#391]
When I get dropped from a MUC, the only way I have found to reconnect to that MUC is to join the channel again. It would be nice to have a quick "reconnect" button somewhere, in the left panel on the MUC name tag, or in the chat window.

**Comment by stevenroose** [comment]
It's also not obvious to me when I'm disconnected. It seems that an open MUC sometimes doesn't get messages delivered until I close the conversation and join it again. This is definitely an issue.

**Comment by selurvedu** [comment]
On 2020-08-18 I noticed that Dino does not rejoin MUCs automatically on MUC server restart. However, fiaxh made this commit https://github.com/dino/dino/blob/master/xmpp-vala/src/module/xep/0410_muc_self_ping.vala on 2020-08-14, and I'm not sure if I was using the latest git version when I made that observation. I will make another comment once I get a chance to test this again.

**Comment by fiaxh** [comment]
As selurvedu noted, Dino supports MUC self-ping (XEP-0410) since mid-2020. That means it should automatically reconnect in case the connection is lost; also in case the MUC server was restarted.

**Comment by selurvedu** [comment]
Yes, I don't recall any problems with MUCs since then. Thanks for fixing that!
