### ISSUE TITLE
Newlines in topic are not properly displayed

### ISSUE THREAD

**Issue by Ppjet6** [dino/dino#393]
## Steps to reproduce

- Set a room topic to something that include newlines

## What happens

Newlines are displayed as missing fonts

## Example

![dino-topic](https://user-images.githubusercontent.com/138302/42129792-87c1d936-7cc7-11e8-9e32-e78acfa74422.png)

## What I expect

Either replace newlines with some character, poezio uses `|`, or actually display newlines, cutting it to a number of chars, and maybe add an expand/show more feature to display the topic as the person who wrote it intended it to be.

I guess the expand feature could be added independant of newlines being replaced.

**Comment by licaon-kter** [comment]
On 2.2.4?

**Comment by Echolon** [comment]
Hello,

I guess this is still happening:

<img src="https://user-images.githubusercontent.com/29168011/53600620-4505d500-3baa-11e9-9899-ede8f3a09779.png" width="100">

The symbol is an 'Enter'. Happens for single enter aswell.

Kubuntu, 18.04, Plamsa Version 5.12.7.
