### ISSUE TITLE
Ubuntu 17.10 repository empty/broken

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dino/dino#398]
Since June 29, the [OBS repository for Ubuntu 17.10 is empty](http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_17.10/).

Could you please have it repopulated?

**Comment by MarcelWaldvogel** [comment]
I temporarily downgraded my repository to http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_17.04 . It seems to work (just started it, but nothing else). Are there any known downsides to that?

**Comment by fiaxh** [comment]
OBS does not seem to support building Ubuntu 17.10 packages anymore. We removed the repo.
