### ISSUE TITLE
Uploading a photo/file in whisper (private chat from MUC) looks to also upload it to the MUC while not doing that

### ISSUE THREAD

**Issue by Mikaela** [dino/dino#402]
I guess screenshots may explain this issue better:

![screenshot from 2018-07-09 16-37-39](https://user-images.githubusercontent.com/831184/42454042-2ba23f70-8397-11e8-8832-ed10d3c6b206.png)

At Conversations MUC people were interested in whether it's possible to upload files in private and I expressed interest to that and uploaded a file in Dino.

![screenshot from 2018-07-09 16-37-58](https://user-images.githubusercontent.com/831184/42454049-2fad1e3c-8397-11e8-9856-6c18309a37a4.png)

Then I opened the MUC in Dino and saw the screenshot there too, while no one else saw anything.

![screenshot from someone else](https://sotecware.net/images/dont-puush-me/O2l4-CfRE9S5mH8XaBNiDaj5KaYTyZPoReZ6tsPlET8.png)

Behaviour that I expected is that the screenshot only appears in the whisper chat and not in the MUC where the chat is originating from.

I am using flatpak from @bochecha with date 2018-06-25 07:38:20 +0000.

**Comment by fiaxh** [comment]
Fixed by #415.
