### ISSUE TITLE
Edit or change correspondent's avatar

### ISSUE THREAD

**Issue by Eragonfr** [dino/dino#408]
Dino does not download the profile picture of my correspondent, I suggest to be able to modify it locally or to download it from the xmpp server.
Sory if my english is bad.

**Comment by licaon-kter** [comment]
Avatar set with what app?

**Comment by fiaxh** [comment]
There won't be the feature to locally set the displayed avatar of another user, but there already is an issue for images not being loaded in some cases: #227.
