### ISSUE TITLE
I would like to use xmpp to make audio and video calls if the server supports it.

### ISSUE THREAD

**Issue by Eragonfr** [dino/dino#409]
I want use xmpp and webrtc in dino it's possible?

**Comment by licaon-kter** [comment]
Detail your case...

**Comment by Eragonfr** [comment]
I would like to use xmpp to make audio and video calls if the server supports it.
Sory for bad english.

**Comment by licaon-kter** [comment]
Rename your issue then

**Comment by fiaxh** [comment]
Duplicate of #154.
