### ISSUE TITLE
Usability: yellow on white contrast is too low

### ISSUE THREAD

**Issue by SamWhited** [dino/dino#41]
![contrast](https://cloud.githubusercontent.com/assets/512573/25053679/36f80828-211e-11e7-96a9-0c7c1748c4d5.png)

It's very hard for me to read the yellow text; users with worse vision than me may not be able to distinguish between the yellow and white at all. Colors should be adjusted to the themes background color to ensure high contrast.

*EDIT:* It actually looks higher contrast in the screenshot on another device; it's probably also partially my screen's color reproduction. Either way, higher contrast in the application would make it visible on a wide variety of non-color-corrected monitors. Other pastel's are similar, but I can at least make them out.

**Comment by mimi89999** [comment]
I also noticed that some colors are barely visible.
![Capture d’écran du 2020-10-02 21-56-19](https://user-images.githubusercontent.com/8530546/94965829-753af580-04fc-11eb-9304-6616e6d563ac.png)

**Comment by Zbergen-cli** [comment]
Maybe there is a way to fix this?

**Comment by fiaxh** [comment]
Dino does not display the sender name in color anymore as of ac2af047409c3cd9ecfc3c955da5975e79565961.
