### ISSUE TITLE
http file upload fails on conversations.im

### ISSUE THREAD

**Issue by tallero** [dino/dino#412]
the message displayed in the terminal is
```Failed getting upload url + Error getting upload/download url```

**Comment by fiaxh** [comment]
I can not reproduce this. Do you still have this issue? Does it always happen or just for some files?

**Comment by tallero** [comment]
I do not have a [conversations.im](https://conversations.im) account anymore, I switched to [Arcipelago](https://arcipelago.ml). I think you can close this bug for now.
