### ISSUE TITLE
Libgcrypt warning: missing initialization

### ISSUE THREAD

**Issue by tastytea** [dino/dino#416]
I got the following warning in my syslog:
`[dino] Libgcrypt warning: missing initialization - please fix the application`

Commit: ee5c838a6ba85c9d6e72ac2941a7994505aaa4fc
OS: Gentoo
libgcrypt: 1.8.3

**Comment by tastytea** [comment]
Steps to reproduce:

* Start dino
* Write an OMEMO-encrypted message from another client

The warning seems to only appear once per session.

**Comment by alexmat** [comment]
I am have the same issue. It looks like other apps use the following code to fix this issue: https://github.com/bitlbee/bitlbee-steam/commit/ccd6e8ca6e3de5c26d8d2a8098e809930d51af1d

**Comment by fiaxh** [comment]
The warning should appear anymore as of 3cfe0d60f679aec81343f12bb846e7805ecad2f2.
