### ISSUE TITLE
encrypted images with omemo

### ISSUE THREAD

**Issue by albjeremias** [dino/dino#419]
when the chat window is encrypted... I can't receive messages from other users because they are encrypted with a link that's no possible to open.
aesgcm://domain.tld:5281/upload/dsadt8321g3/anonymous.si.jpg#dsadasc4517a7a38ffac67964fff

**Comment by stevenroose** [comment]
@licaon-kter This is not part of #36, btw. It's not listed in the OP.

**Comment by selurvedu** [comment]
@albjeremias, until this feature is not implemented you can use this small project to decrypt the image:
https://github.com/moparisthebest/ImageDownloader (notice that this fork does not require JDK for building, unlike https://github.com/iNPUTmice/ImageDownloader)

```bash
git clone https://github.com/moparisthebest/ImageDownloader
cd ImageDownloader
gcc aesgcm.c -lcrypto -o aesgcm
# Replcace aesgcm with https
wget https://domain.tld:5281/upload/dsadt8321g3/anonymous.si.jpg
./aesgcm dsadasc4517a7a38ffac67964fff < anonymous.si.jpg > anonymous.si.decrypted.jpg
```

I also wrote a simple wrapper script (place it in the ImageDownloader dir):
```bash
#!/bin/bash -e
set -e
IFS=# read -a fields <<< "${1/#aesgcm/https}"
filename="$(basename "${fields[0]}")"
curl "${fields[0]}" | "$(readlink -f "$(dirname "$0")")/aesgcm" "${fields[1]}" > "$filename"
echo Saved to "$filename"
```

You can use it like this:
```bash
./download.sh aesgcm://domain.tld:5281/upload/dsadt8321g3/anonymous.si.jpg#dsadasc4517a7a38ffac67964fff
```

You can also use the bundled `openbrowser.sh` script.

**Comment by daryltucker** [comment]
@selurvedu Thank you for the very clear instructions to download and decrypt the file.

Please consider adding `export HISTCONTROL=ignoreboth` to `~/.bashrc` and prefix any commands with keys with a space.  Using @selurvedu's example:

```bash
HISTCONTROL=ignoreboth
 ./download.sh aesgcm://domain.tld:5281/upload/dsadt8321g3/anonymous.si.jpg#dsadasc4517a7a38ffac67964fff
```

This will prevent the `./download.sh` command from hitting your `~/.bash_history`.  It is recommended that you keep these keys secret, even after the files are deleted, etc.

**Comment by selurvedu** [comment]
@daryltucker, nice tip, I've been using this for years. I updated my comment to include that.
