### ISSUE TITLE
Feature Request - Important

### ISSUE THREAD

**Issue by vboxpro** [dino/dino#426]
1. Add Voice/Video facility (Integrated) without any thirdparty calling bridges.
2. Add basic Emjoi/Sticker pack (add facility for users to insert their own packs)
https://emojipedia.org/people
https://www.emojione.com/stickers

make build for windows. :)

**Comment by licaon-kter** [comment]
/duplicate #154

Please edit title to non-generic.

**Comment by fiaxh** [comment]
#88 is an issue on (custom) emojis.
