### ISSUE TITLE
Disrupted display of chats (makes dino unusable)

### ISSUE THREAD

**Issue by lnjX** [dino/dino#427]
![screenshot_20180909_151551](https://user-images.githubusercontent.com/13557034/45265092-a4c6c300-b446-11e8-8b6c-cbfd90ecc0fa.png)

OS: Debian GNU/Linux unstable (sid) x86_64
Package version: `0.0.git20180904-1`
GPU: Intel(R) Iris Plus Graphics 650 (Kaby Lake GT3e)
X11 compositor: compton
WM: i3

Excerpt from [chat@dino.im](https://i.kaidan.im/#chat@dino.im?join):
```
[15:35:17] ‎Licaon_Kter‎: lnj: did you rebuild recently? There was a fix for the b
‎[15:35:28] ‎Licaon_Kter‎: lue shadow.
‎[15:35:53] ‎lnj‎: Licaon_Kter, The build is from 2018-09-04
‎[15:38:55] ‎Licaon_Kter‎: lnj: I guess you have it, maybe that's the problem, it fixes some stuff but breaks yours
```

**Comment by kinkynekoboi** [comment]
i have the same behaviour on Debian Buster.
Strangely it shows this glitch on my T60 and my Desktop but not on my X60s ...

**Comment by fiaxh** [comment]
Does 85d194e (on current master) have an effect on your displaying issue?

**Comment by kinkynekoboi** [comment]
> Does [85d194e](https://github.com/dino/dino/commit/85d194e349858b3cbbb4dd2a8ca007428378c56c) (on current master) have an effect on your displaying issue?

Have to wait still a new dino-im package is out in debian testing to answer this ..

**Comment by LNJ2** [comment]
I'm still using the same version (0.0.git20180921-1) and the bug isn't there anymore, I guess it's because of the intel gpu driver upgrade. From my side this issue can be closed.

**Comment by fiaxh** [comment]
Closing this issue assuming it was a non-Dino bug that has been fixed.
