### ISSUE TITLE
Doesnt connect due to tls error

### ISSUE THREAD

**Issue by jubalh** [dino/dino#435]
Recently I get this when I open dino:
```
dino
[me@myserver.org] New connection with resource dino.c282923c: 0x65834b2bc050
[me@myserver.org]] Error: TlsError: Error performing TLS handshake: The operation was cancelled due to user error
```

Using dino 0.0~git313.6b7ef80-112.1 built by OBS.
On my own server with lets encrypt certs and prosody. Gajim and other clients connect without problem

**Comment by fiaxh** [comment]
Does this issue still exist? [This opensuse bug](https://bugzilla.opensuse.org/show_bug.cgi?id=1108450) was suggested to be related and seems to be fixed.

**Comment by jubalh** [comment]
Yes that indeed was the bug.
Issue not relevant anymore.
