### ISSUE TITLE
Lower cost entry for users and contributors.

### ISSUE THREAD

**Issue by sbernard31** [dino/dino#437]
I have the feeling that flatpak, meson and GNOME-builder begin to be really usable.
I think this kind of technology could really lower the entry cost for users (flatpak) and contributors. (GNOME-builder/Meson)

About GNOME-Builder, It would be really great if contributors could just clone the Dino repo from it, click on build/run and it just works without doing nothing more. I feel GNOME-Builder it pretty much ready to do that.

1. I have not so much experience with all of this, so I would really have your feeling about this ?
2. Is there any plan about making Dino available on [flathub.org](https://flathub.org/apps/search/Dino) ?

**Comment by qazip** [comment]
I agree with this, sadly, dino seems to not be actively maintained. Having it on flathub would be great.

**Comment by licaon-kter** [comment]
Builder has git integration... contributors that can code Vala, I feel, already know how to `git clone` ;)

**Comment by link2xt** [comment]
Related issue about Meson: #396

**Comment by sbernard31** [comment]
(#343 aims to provide a flatpack package, #453 ask for a flatpack version too)

**Comment by rugk** [comment]
#343 is blocked by flatpak gpg agent functionality. I just don't know why Dino devs don't at least provide a version without flatpak, but well…

**Comment by fiaxh** [comment]
Dino now supports meson and has a flatpak file. It still also supports cmake, but we'll remove it hopefully before the next release.
