### ISSUE TITLE
xmpp: URI/URL opens with %40 for @ symbol

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#439]
I clicked the button on https://yax.im/i/#vladimir@xmpp.example .

I selected the dino binary that I was running (current master + #418) and this was the result:

![screenshot-2018-10-09-17-20-51](https://user-images.githubusercontent.com/853468/46683447-28133a00-cbe8-11e8-80a5-dfe6cea8e319.png)

**Comment by fiaxh** [comment]
I can not reproduce this (anymore). Do you still have this issue?
