### ISSUE TITLE
Markdown-based bold and italics don't display as (likely) intended

### ISSUE THREAD

**Issue by LuccoJ** [dino/dino#445]
Dino version is the Fedora build marked 0.0~git318.ddd17e7 release 116.1.

The behavior is visible in the attached screenshot:

![weirdmarkdown](https://user-images.githubusercontent.com/1684791/48086928-4d529280-e1fe-11e8-9421-ce53cdf5acf5.png)

If I paste the same sentences here,

> I think *bolding* works in a bit of a *weird* way...
> Let's see if _italics_ do the _same_ thing first

the formatting (aside from bold not being a thing in the first place) is handled the way I'd expect it to, unlike in Dino.

**Comment by fiaxh** [comment]
Fixed in 5a4e509.
