### ISSUE TITLE
Cannot install dino-git from aur

### ISSUE THREAD

**Issue by qazip** [dino/dino#446]
Hey there,

There seems to be a problem installing dino-git from aur. Below is the error-code.

```
plugins/omemo/src/contact_details_dialog.c:15:10: fatal error: qrencode.h: No such file or directory
 #include "qrencode.h"
          ^~~~~~~~~~~~
compilation terminated.
....
==> ERROR: A failure occurred in build().
    Aborting...
Error making: dino-git
```

**Comment by licaon-kter** [comment]
Needs `libqrencode-dev` yes

**Comment by qazip** [comment]
Installing qrencode from extra makes it work. That should be added as a dependency in the aur package..

**Comment by NicoHood** [comment]
Please close the issue. It was reported on aur and the maintainer will fix it sooner or later.  You can add the dependency yourself for now.
