### ISSUE TITLE
Don't pull e-mail addresses with the translation

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#447]
...I have enough chinese spam thanks.

**Comment by fiaxh** [comment]
- If you are referring to the `Last-Translator` field in the .po files, that's what we get from weblate. We can remove the line from the `.po` files before uploading them to this repo, but they will still be on weblate containing the email address from your settings.
- If you are referring to the commit message in this repo: We can only write names, but mind that your commits also contain an email address.
