### ISSUE TITLE
Remove the password field when joining a MUC

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#46]
A better UX would be to try to join the MUC without it, and in case [you receive a <not-authorized/> error back](https://xmpp.org/extensions/xep-0045.html#enter-pw) prompt the user for a password, and on a successful join update the bookmark.

**Comment by fiaxh** [comment]
It is done this way by now 👍️

**Comment by linkmauve** [comment]
I just tried to onboard a new user, but when they clicked Join Channel > +, they still had a password field which they felt compelled to fill, and it was confusing.

Please reopen this issue until it is also fixed there. :)
