### ISSUE TITLE
Resize images based on window width

### ISSUE THREAD

**Issue by siikamiika** [dino/dino#460]
When an image wider than the current window width is displayed inline, the window is automatically resized to adapt to that. With a tiling WM it becomes a problem, because the width isn't adjusted but text (and the image) still overflows and is hidden. I understand that my WM doesn't respect dino's minimum width, but I would see shrinking the image as a solution when the window is force resized by the WM.

**Comment by siikamiika** [comment]
I'm currently happy with my setup after setting https://github.com/dino/dino/blob/c44489214e040f48042d27254d4c18a78e343049/main/src/ui/conversation_summary/content_item_widget_factory.vala#L93 to a lower value, and seems like window or buffer width isn't directly available to that part of code anyway. Providing an option for changing the maximum width of images would be one way to solve this problem, but I kind of like the simple settings menu and sane defaults. I could try to implement the dynamic resize based on window width if someone could tell me where it's available in the code.

**Comment by beelze** [comment]
I'm not sure if it should be FR because unexpected and unpredictable window resizing is an issue I believe.

**Comment by mar-v-in** [comment]
Fixed via d55f6691c68757d2c8f7a361c20ace8dac61da5c
