### ISSUE TITLE
Error: Content before root node

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#462]
```
$ build/dino --print-xmpp=all
[steven@konuro.net] New connection with resource dino.dc510f2b: 0x560641ab0e60
XMPP OUT ROOT [steven@konuro.net]
<stream to='konuro.net' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

XMPP OUT [steven@konuro.net]
<stream to='konuro.net' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

[steven@konuro.net] Error: Content before root node
[steven@konuro.net] Check reconnect in 3 sec
XMPP OUT [steven@konuro.net]
<iq id='4fb6e838-98e6-4aff-ab67-0222682ce596' type='get' to='konuro.net'>
  <ping xmlns='urn:xmpp:ping' />
</iq>

XMPP OUT [steven@konuro.net]
</stream:stream>
[steven@konuro.net] New connection with resource dino.dc510f2b: 0x560641df7b90
XMPP OUT ROOT [steven@konuro.net]
<stream to='konuro.net' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

XMPP OUT [steven@konuro.net]
<stream to='konuro.net' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

[steven@konuro.net] Error: Content before root node
[steven@konuro.net] Check reconnect in 3 sec
```

This problem occurred suddenly. The only thing that changed was that I was fixing an issue with serving Direct TLS s2c on port 443 (provided in the `_xmpps-client` SRV record).
I think I gave the _xmpps record the highest priority, so it Dino supports that, it might have switched from STARTTLS on 5222 to Direct TLS on 443.

The error message is related to https://github.com/dino/dino/issues/57, but I'm using Let's Encrypt certificates instead.

**Comment by mar-v-in** [comment]
Dino does not support ALPN right now due to missing support in GLib.

However you should be able to configure your system to be compatible with Dino without ALPN, by using a separate name via SNI, for example configure the DNS record as
```
_xmpps-client._tcp.konuro.net. 1800 IN	SRV	1 1 443 xmpp-client.konuro.net.
xmpp-client.konuro.net. 1800 IN CNAME konuro.net.
```
Then configure your proxy on port 443 to redirect `xmpp-client.konuro.net` to the XMPP server without ALPN introspection.

**Comment by stevenroose** [comment]
I don't think I can do that. I have inky one server with one IP. I don't
think I can split the nginx stream that handles 443 dependent on subdomain.

**Comment by stevenroose** [comment]
I currently have this nginx snippet:
```nginx

stream {
  upstream httpserver {
    server localhost:8443;
  }
  upstream xmppserver {
    server ejabberd:5223;
  }

  map $ssl_preread_alpn_protocols $upstream {
    default       httpserver;
    "xmpp-client" xmppserver;
  }
  
  server {
    listen      443;
    listen      [::]:443;

    ssl_preread on; 
    proxy_pass $upstream;
  }
}
```

So what is the best way to handle this? I can lower the priority of the _xmpps record? Or should Dino realize 443 requires ALPN and attempt the other record?

**Comment by stevenroose** [comment]
I think that boils down to assuming clients can avoid ALPN if they don't support it, or assuming clients can avoid ports that are being blocked by the firewall..

**Comment by mar-v-in** [comment]
Use something like
```
map $ssl_preread_server_name $upstream {
  default httpserver;
  "xmpp-client.konuro.net" xmppserver;
}
```
instead of 
```
map $ssl_preread_alpn_protocols $upstream {
  default       httpserver;
  "xmpp-client" xmppserver;
}
```

**Comment by stevenroose** [comment]
Hmm, I just added a second `_xmpps._tcp` record for port 5223 with a higher priority. Now just hoping that clients that are behind firewalls will still connect to 443 when needed. Conversations apparently tries all in order, which is good.

**Comment by fiaxh** [comment]
With d194eae Dino now sets ALPN info on XMPP connections (needs GIO >= 2.60).
