### ISSUE TITLE
Remove the join on startup checkbox when joining a MUC

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#47]
It is fine to keep this checkbox when modifying bookmarks, but in most cases the user will want to join it automatically once they joined it once, it makes the whole thing a lot more predictable.

**Comment by fiaxh** [comment]
The checkbox is removed from anywhere in the UI.

**Comment by kousu** [comment]
So there's no way to have non-autojoin chats anymore? On both ubuntu bionic (`dino-im` Version: 0.0.git20180130-1ubuntu0.1) and Arch (`dino` 0.1.0) I don't see this anywhere in the UI.
