### ISSUE TITLE
OMEMO messages disappearing into the ether

### ISSUE THREAD

**Issue by Chobbes** [dino/dino#473]
I seem to not be receiving OMEMO messages from somebody on gajim. Plain text messages come through, but OMEMO does not.

I believe if I can't decrypt the message or whatever I should get "This message is OMEMO encrypted" or some message to that effect, but I'm not getting anything... And all the keys are accepted, so it should in principle be fine?

Is there some way I can debug this? Can I get dino to print out debug information and see if I'm actually getting the messages and it's not displaying it, or something?

**Comment by NicoHood** [comment]
Maybe related: https://github.com/dino/dino/issues/243

**Comment by srgcdev** [comment]
Same problem here. I cannot receive omemo messages from gajim despite all the omemo keys are accepted.

**Comment by srgcdev** [comment]
It seems that gajim doesn't send a <body> so when message_processor.vala file executes 'if (message_stanza.body == null) return;' the message is lost.

**Comment by mar-v-in** [comment]
XEP-380 says:

> Entities SHOULD include a non-encrypted body as possible, since older clients not supporting this protocol might otherwise ignore messages sent with an unknown encryption, making both the sender frustrated that their message did not get an answer, and the recipient frustrated that they never saw any message.

**Comment by moppman** [comment]
> XEP-380 says:
> 
> > Entities SHOULD include a non-encrypted body as possible, since **older clients** not supporting this protocol might otherwise ignore messages sent with an unknown encryption [...]

> **older clients**

which clearly Dino is not :)

**Comment by jjrh** [comment]
Regardless of who's at fault, silently failing is a bug. The user should be informed they aren't seeing a message.
