### ISSUE TITLE
Segfault when sending large OMEMO encrypted files

### ISSUE THREAD

**Issue by herrwusel** [dino/dino#474]
I tried to send a mpeg video with dino and it crashed:
```bash
dino

(dino:23613): GLib-GObject-WARNING **: 14:03:36.835: ../../../../gobject/gsignal.c:2423: signal 'notify-message' is invalid for instance '0x55ad78a892e0' of type 'DinoNotificationEvents'
[user@xmpp.org] New connection with resource dino.ca9c01ff: 0x55ad792f08d0
[user2@xmpp.org] New connection with resource dino.bce5456b: 0x55ad792e9680
Speicherzugriffsfehler (Speicherabzug geschrieben)
```

**Comment by fiaxh** [comment]
I can't reproduce this. Can you please start Dino (with debug symbols) in gdb and give me a backtrace? You seem to be using an old version, so ideally update before.

`gdb build/dino`
`> r`
[Starts program, make it crash]
`> bt`

**Comment by MarcelWaldvogel** [comment]
The problem seems to start when trying to transmit a file of 4 MiB. I can send images < 4 MiB without problem, but larger than that, and Dino segfaults.
