### ISSUE TITLE
Sending a animated gif segfaults

### ISSUE THREAD

**Issue by migtavares** [dino/dino#475]
Sending a animated gif segfauls dino after clicking the select button on the file dialog.

**Comment by fiaxh** [comment]
I can't reproduce this. Can you please start Dino (with debug symbols) in gdb and give me a backtrace?

`gdb build/dino`
`> r`
[Starts program, make it crash]
`> bt`

**Comment by migtavares** [comment]
I just emerge dino (using gentoo and this way it pull newer code) and it didn't crash when I sent the gif. 
Sorry for the bogus issue. (I sent the animated gif to chat@dino.im for testing).

**Comment by fiaxh** [comment]
I'll close the issue since sending an animated gif does not seem to cause a problem. However, if you should be able to reproduce the crash - whatever the cause - and get a backtrace, please do open an issue.
