### ISSUE TITLE
Mentions are bold only if "login:" is used, if the mention is in a sentence it does show as bold

### ISSUE THREAD

**Issue by arthurlogilab** [dino/dino#477]
It would be nice to be able to find easily in a conversation where one has been mentioned. 

0.0.git20180130-1 from ubuntu bionic used

**Comment by fiaxh** [comment]
Unfortunately Ubuntu has a quite old version of Dino in its repository. I cannot reproduce this problem on a build of the git master. You can try a current version by using [the OBS Ubuntu package](https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino) or by compiling Dino yourself.

If you should still have the problem with a current build, please say so and I will reopen the issue.
