### ISSUE TITLE
Segmentation fault when some values are missing from file_transfer table

### ISSUE THREAD

**Issue by seppiofish** [dino/dino#479]
This might be hard to reproduce: it happened to me using gnome when trying to send an attachment with http upload and selecting it from the gnome recent files, rapidly, without leaving it the time to fully load the recent files list.

Dino crashes just after selecting the file and when trying to launch again it segfaults:
```
(dino:34746): GLib-CRITICAL **: 13:34:01.121: g_str_has_prefix: assertion 'str != NULL' failed
[1]    34746 segmentation fault (core dumped)  dino
```

Opening, then, the database, something like this should be found in the file_transfer table:
```
659|1|1|||1|1545654670|1545654670|2||f14e71f3_||0|0|0|
```
Deleting the faulty row in the database solved the issue and dino should be able to run again.

**Comment by bowlofeggs** [comment]
I experience this same error message a few seconds after starting dino on a new install:

```
$ time dino
[me@domain.com] New connection with resource dino.176ca06d: 0x5584589b21d0

(dino:10731): GLib-CRITICAL **: 20:13:42.435: g_strsplit: assertion 'string != NULL' failed
Segmentation fault (core dumped)

real	0m3.277s
user	0m1.672s
sys	0m0.263s
```

I built this from 49269c3173cff4a3a911aba33c52a6ca846e5b78 on Fedora 29:

https://koji.fedoraproject.org/koji/taskinfo?taskID=31713759

It happens every time I start it.

**Comment by bowlofeggs** [comment]
I used ```git bisect``` to trace the crash I'm observing to this commit: 1014b696f2cb6103968ee24ae7f32472e37085a0

**Comment by bowlofeggs** [comment]
Due to the timing of the commit and this issue, I think they are not the same. I have opened #483 instead. Sorry for the noise!
