### ISSUE TITLE
Add a way to join a bookmarked-but-without-autojoin MUC from the main window

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#48]
Currently those MUCs are grayed, we can click on them, we can see what was said the last time, we can even think we sent a message, but it isn’t the case.

My suggestion would be to join it automatically when clicking on it, maybe with a spinner until we receive our self-presence.

**Comment by linkmauve** [comment]
This is actually related to #24.

**Comment by mar-v-in** [comment]
This is actually a duplicate of #24
