### ISSUE TITLE
Fedora 29 package

### ISSUE THREAD

**Issue by hebrewd** [dino/dino#480]
#358 Does discuss the issue for the previous version of fedora, and that version might work on 29 just as well.
Still, as there doesn't seem to be a ticket for 29, I open this one to at least get feedback as to what the best practice for fedora 29 users would be.

**Comment by lionirdeadman** [comment]
The flatpak is the best option imo.

**Comment by jubalh** [comment]
Build finished.
You can install it with:

```
dnf config-manager --add-repo https://download.opensuse.org/repositories/network:messaging:xmpp:dino/Fedora_29/network:messaging:xmpp:dino.repo
dnf install dino
```

[Info page](https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino) will be updated automatically later.

**Comment by fiaxh** [comment]
Thanks jubalh 🙂
