### ISSUE TITLE
./configure doesn't find libgee

### ISSUE THREAD

**Issue by lhirlimann** [dino/dino#487]
-- Installation directory for dino plugin object code files: /usr/local/lib/dino/plugins
-- Installation directory for Vala API files: /usr/local/share/vala/vapi
-- Found Vala: /usr/bin/valac (found suitable version "0.42.3", minimum required is "0.34") 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Gee (missing: Gee_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindGee.cmake:11 (find_package_handle_standard_args)
  cmake/MultiFind.cmake:20 (find_package)
  qlite/CMakeLists.txt:1 (find_packages)

[ludovic@saraan dino]$ sudo dnf install libgee
Last metadata expiration check: 0:09:40 ago on Wed 02 Jan 2019 09:56:57 AM CET.
Package libgee-0.20.1-2.fc29.x86_64 is already installed.
[CMakeOutput.log](https://github.com/dino/dino/files/2720289/CMakeOutput.log)

**Comment by licaon-kter** [comment]
Yeah yeah https://github.com/dino/dino/pull/276 see my commit
