### ISSUE TITLE
Replace the dependency on libnotify with GNotification from Gio

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#49]
libnotify is deprecated and shouldn’t be used, GNotification is in every way better, and integrates properly with modern systems.  Will fix #27.

**Comment by fiaxh** [comment]
Replaced libnotify with GNotification in https://github.com/dino/dino/commit/8fdb38b99be9c588148d576c23212af765ff7302. However this is not related to #27.

**Comment by linkmauve** [comment]
It actually is, if you use e.g. a different string per contact for the notification, it will only replace it per contact.
