### ISSUE TITLE
Dino can't decrypt omemo messages in muc if sender is offline

### ISSUE THREAD

**Issue by srgcdev** [dino/dino#490]
Hello,

I have this problem receiving omemo messages in muc:

1. I'm offline in dino.
2. One of my contacts sends a omemo encrypted message to a muc
3. This contact goes offline
4. I go online in dino and I receive previous messages in muc, but the one sent by the contact offline is not decrypted. If the contact was online, there would be no problem to decrypt the message

Thanks.

**Comment by srgcdev** [comment]
Seems that in file trust.manager.vala, when execute:
{code}
if (conversation.type_ == Conversation.Type.GROUPCHAT) {
      jid = stream_interactor.get_module(MucManager.IDENTITY).get_real_jid(jid, conversation.account);
}
{code}
The jid is not retrieved properly when the sender is offline.

**Comment by fiaxh** [comment]
Thanks for pointing at where the problem came from!
