### ISSUE TITLE
Dino doesn't update read conversation (on the left) when file is received

### ISSUE THREAD

**Issue by srgcdev** [dino/dino#495]
Steps to reproduce:

1. Dino is offline
2. A contact sends an image
3. Dino goes online
4. I receive the image but despite I read the new message (the image), the conversation on the left keeps in bold.

Other way to reproduce a problem:
1. Dino is online
2. A contact sends an image
2. I receive the image but despite I don't read the new message (the image), the conversations on the left is not in bold.

Looking at the code, seems that in the method 'protected void update_read()' in the conversation_row.vala file, ContentItem that are FileItems are not treated, so for example the conversation.read_up_to has the url of the image in the body but the last_message has the previous message in the body.

**Comment by linkmauve** [comment]
Related highlighting issue: the IRC server messages from biboumi, containing the MOTD, identd information, etc. also never gets unhighlighted once received.

**Comment by stevenroose** [comment]
Do `/me`'s? Might be just all the not-standard-message types.

**Comment by trwnh** [comment]
also happens when i send a file to a contact, then dino receives messages with MAM
