### ISSUE TITLE
Implement XEP-0167: Jingle RTP Sessions

### ISSUE THREAD

**Issue by xmppwasabi** [dino/dino#497]
Related to #154.

"This specification defines a Jingle application type for negotiating one or more sessions that use the Real-time Transport Protocol (RTP) to exchange media such as voice or video. The application type includes a straightforward mapping to Session Description Protocol (SDP) for interworking with SIP media endpoints."

https://xmpp.org/extensions/xep-0167.html

I open this ticket knowing that it might be a long-term feature.

**Comment by trymeouteh** [comment]
+1 for SIP calling

**Comment by fiaxh** [comment]
Dino has call support on master by now :slightly_smiling_face:
