### ISSUE TITLE
Implement XEP-0234: Jingle File Transfer

### ISSUE THREAD

**Issue by xmppwasabi** [dino/dino#498]
Related to #154 

"This specification defines a Jingle application type for transferring a file from one entity to another. The protocol provides a modular framework that enables the exchange of information about the file to be transferred as well as the negotiation of parameters such as the transport to be used."

At the moment this XEP is experimental (and deferred) so only exploratory implementation is recommended. Like for other jingle-related tickets I think this will take time but I opened this ticket so this nice feature doesn't get lost.

https://xmpp.org/extensions/xep-0234.html

**Comment by fiaxh** [comment]
This was implemented in #577 and improved in #592.
