### ISSUE TITLE
Implement XEP-0391: Jingle Encrypted Transports

### ISSUE THREAD

**Issue by xmppwasabi** [dino/dino#499]
Related to #498, it adds encryption to the file transferred.

"This specification defines a method that allows to use established encryption schemes for end-to-end encryption of Jingle transports."

It is experimental but complementary to #498. I opened this ticket so it doesn't get lost, hopefully someday it will be accepted in XMPP and Dino will use it.

https://xmpp.org/extensions/xep-0391.html

**Comment by fiaxh** [comment]
This was done in e899668213ee8f7d3566bb5754b488d8633c30c7. Related: 392cb472abcdff9424197c8504175ee79c22dde5 (JET-OMEMO).
