### ISSUE TITLE
☰ Contact Details doesn’t do anything

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#50]
It should probably open a dialog displaying the JID and vCard of the user, or something.

In a MUC it shouldn’t be named Contact Details, if even present.

**Comment by fiaxh** [comment]
There was no code behind that button until 5ba95ef. The dialog still needs more work, but now it exists.

**Comment by NicoHood** [comment]
@fiaxh Looks nice. However changing the global setting overwrites the per user setting. What I expect is:
* Default -> Inherit Global Setting
* On/Off per User contact
