### ISSUE TITLE
segmentation fault on startup

### ISSUE THREAD

**Issue by alexmat** [dino/dino#505]
dino -h prints out the help meassage

just running dino (with strace) I get:

write(6, "\1\0\0\0\0\0\0\0", 8)         = 8
futex(0x7fb79d8565d8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\201\2\5\0\0\2\0\1\7\0\0\1\0\0\0\0\0\0\0\0\201\2\5\0\0\2\0\0\7\0\0\1"..., iov_len=412}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 412
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1(\37\1\7\0\0\0\234\3\0\0\0\0\0\0\0\0a\4\0\0\272\2\0\0\241\0\0\0\272\2"..., iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 60
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 1 ([{fd=6, revents=POLLIN}])
read(6, "\1\0\0\0\0\0\0\0", 16)         = 8
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="(\2\4\0\7\0\0\1\234\3\0\0\0\0\0\0", iov_len=16}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 16
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\1 \1\0\0\0\0\7\0\0\1\300\3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(3, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=3, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}, {fd=10, events=POLLIN}], 4, 0) = 0 (Timeout)
brk(0x55d9bfdbd000)                     = 0x55d9bfdbd000
brk(0x55d9bfdbb000)                     = 0x55d9bfdbb000
futex(0x7fb79d8565d8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7fb79d8565d8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by alexmat** [comment]
I tried that every which way. I rebuilt against several different commit points, tried changing libqrcode to 3.4.4 since I have it installed at 4.0.0. Tried disabling omemo plugin. Same behavior across the board. I wonder if it's something with my setup, but hard to debug for me at this point.

**Comment by fiaxh** [comment]
Can you please run dino in gdb, wait until it crashes and provide a stack trace?

`gdb ./build/dino`
`> r`
[crash]
`> bt`

**Comment by fiaxh** [comment]
@alexmat I will close this issue due to a lack of information provided (see my previous comment). However, if you can provide a stack trace, please post it here.

**Comment by alexmat** [comment]
Sorry, forgot about this issue. It is resolved for me in recent builds and I am enjoying a functional dino :)
