### ISSUE TITLE
Option to launch dino automatically at OS startup

### ISSUE THREAD

**Issue by WPFilmmaker** [dino/dino#506]
On many Linux distros is quite hard to add a program to the startup (just google it, it requires copying/editing file strings etc., definitively not user-friendly).

It would be nice having an option in the preference to launch dino automatically as the OS starts.

You could toggle/untoggle it from the options as many IM already do.

**Comment by fiaxh** [comment]
In Gnome, you can open the Gnome Tweak Tool and go to `Startup Applications` to set Dino to be launched on startup. In KDE, you can open the system settings and go to `Startup and Shutdown` > `Autostart` to do the same. There's a list on how to achieve autostart on different desktop environments and window managers [here](https://wiki.archlinux.org/index.php/autostarting#On_desktop_environment_startup).

I don't think there is need for Dino to duplicate this functionality.
