### ISSUE TITLE
TLS where install CA?

### ISSUE THREAD

**Issue by fred2cool** [dino/dino#508]
Hi, I try to load my CA into linux, but dino do not trust my TLS connection, the CA is installed and a 
dpkg-reconfigure ca-certificates
update-ca-certificates
was done and the CA is installed but Dino always say: Invalid TLS certificate

Is there any fix or do I need to place the CA from my TLS certificate in some other destination?
thank you

**Comment by fiaxh** [comment]
Dino does not do anything related to certificates itself. It relies on the the information which certificates are accepted by your system.
Thus, I think the certificate is either not correctly installed or the server is wrongly configured. How a certificate can be installed depends on the system you are using. For the latter problem you can check by letting the [IM Observatory](https://xmpp.net/) check your server.
