### ISSUE TITLE
Google Summer of Code

### ISSUE THREAD

**Issue by WPFilmmaker** [dino/dino#511]
Deadline for applications is February 6 so I doubt Dino will make it for this year. However maybe next year? I opened a github ticket similar to this for another free software I use and despite a few months of silence now that deadline is approaching several people are asking to participate as students.

If dino dev team wants to participate to gsoc could this thread be pinned? So that people can see it. Also I couldn't find a list of ideas it would be cool to make one (perhaps jingle support)

**Comment by fiaxh** [comment]
Dino did publish [project ideas](https://wiki.xmpp.org/web/GSoC/2019/Project_Ideas#Dino) under the XMPP umbrella organisation. The application period is over now and applications are being reviewed.
