### ISSUE TITLE
[UI] Put own messages to the right window side

### ISSUE THREAD

**Issue by Echolon** [dino/dino#525]
Hi,

would like to suggest to offer the possibility to put your own messages to the right side, like in most other client. At least an opt-in option would be great.

Hope that not a double. If so, please close

Cheers

**Comment by licaon-kter** [comment]
This works on a narrow window, yes, else this is a desktop app so your messages will end up pretty strange.

**Comment by Echolon** [comment]
Yes, right, but I always put Dino to the right screen corner. Thereby, the chat window becomes narrow.

Another thing could be to mark it with a differnt background. but I guess its not intended...

**Comment by fiaxh** [comment]
This isn't something we plan to do at the moment.
