### ISSUE TITLE
Flag messages as editable

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#526]
Conversations has logic to edit the last sent message. However this doesn't work for messages sent from Dino. Is it possible to allow Conversations to edit messages sent via Dino?

**Comment by ge0rg** [comment]
This should be a Conversations issue. Or maybe first a XEP change request for https://xmpp.org/extensions/xep-0308.html#rules

> A correction MUST only be allowed when both the original message and correction are received from the same full-JID.

**Comment by fiaxh** [comment]
Closing this following ge0rg's argumentation.

**Comment by albjeremias** [comment]
This is wrongly closed.. this is implemented by each client of XMPP.. check it out:
- https://xmpp.org/extensions/xep-0308.html

**Comment by fiaxh** [comment]
@albjeremias No, this issue is not about implementing XEP-0308 (Last Message Correction), please reread the initial message. The issue about implementing XEP-0308 is #272 and it is still open.

**Comment by albjeremias** [comment]
hm sorry im still confused.. but nice to known there is another one open..
