### ISSUE TITLE
joining a chat room

### ISSUE THREAD

**Issue by humanitiesNerd** [dino/dino#531]
I have a chat room, I created it with Conversations

With Gajim I can join the room and post encrypted messages in it (although I have to do the trusting fingeprint dance)

With Dino I ffind no way to post encrypted messages to my chat room

is it me ? Or is it Dino ?

I can't even see which Dino version I'm uusing

I installed it via the system repos on Ubuntu 18.04

**Comment by licaon-kter** [comment]
`sudo apt-cache policy dino` ?

Don't you have a lock icon on the right side of the input box?

Try the OBS latest builds:

**Comment by joe-average-user** [comment]
Oh, I just opened the same question with an OMEMO reference. I am using latest AUR version for arch linux. The thing is: only in group chat the OMEMO option you are pointing to is disabled (as well as OpenPGP). But in a single contact chat it is enabled and working ...

**Comment by fiaxh** [comment]
With the current master, you can always select OMEMO in a members-only + non-private MUC. If there is a problem, a description of the problem should appear below the message input field.
