### ISSUE TITLE
Pending messages are wrongly marked as sent after restart

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#533]
Related to #532.

If there are connection issues and messages can't reach the server, Dino marks messages as pending by putting the `...` icon on them.

However, after restarting Dino, the messages are no longer marked as pending. Even though they have never reached the server.

**Comment by fiaxh** [comment]
Dino has a more solid message resending since 74f7fa897f9aec298eeadcfc7a7b971f06498858. Dino now tries to send a message until the server acknowledges that it received the message using stream management.
