### ISSUE TITLE
Try all SRV records in priority order, instead of just the first one

### ISSUE THREAD

**Issue by roobre** [dino/dino#534]
Right now, dino fetches `xmpp-client` and `xmpps-client` records and tries to connect to the more prioritary (the one with the smallest priority number), failing if it is not reachable.

This is not the expected behavior according to [XMPP-Core, 3.2.1](https://tools.ietf.org/html/rfc6120#page-18):

>    7.  If the initiating entity fails to connect using all resolved IP
       addresses for a given FDQN, then it repeats the process of
       resolution and connection for the next FQDN returned by the SRV
       lookup based on the priority and weight as defined in [DNS-SRV].

This could be useful to expose a regular xmpp port as the most prioritary option, and 443 as a fallback for restricted networks.

**Comment by joe-average-user** [comment]
Is it possible that dino memorizes the dns record connection host and never tries to fetch the current setup of the accounts' domain again?
We found that conversations re-checks this with every start, whereas dino stays at outdated host...
