### ISSUE TITLE
How to enable OMEMO in group chat?

### ISSUE THREAD

**Issue by joe-average-user** [dino/dino#538]
I havent found any answer on that in issues or elsewhere. 
If talking to a single contact OMEMO can easily be enabled by clicking on the key lock (right) and choosing the "OMEMO" option in the upcoming window.
But in a group chat the "OMEMO" (and OpenPGP) is disabled. So how can I enable it?

**Comment by shibotto** [comment]
I believe it's not supposed to work if some of the participants don't use OMEMO.

**Comment by joe-average-user** [comment]
That is really not the problem. Some time ago I saw the same problem in Conversations (Android-App). But it was later on fixed there. The problem seems to arise if not all the participants are online at the time the group is recognised for the first time in dino. In fact an eye should be kept on the situation where not all participants are online, because in almost every group with a longer list this is the case most all of the time. Conversations had such problems too in the past, but they were fixed (though I don't know how).

**Comment by shibotto** [comment]
My guess is that it doesn't find a key in the user's PEP, being it a presence problem, expired key or whatever. I'm inclined to think this is a participant server side issue, though I can't test this and therefore can't be sure.

**Comment by joe-average-user** [comment]
I have no deep insight in the XMPP protocol nor its extensions. But I can tell you that the issue arises in a group with all participants being on the same server. The server itself is the very same one where Conversations has no issues at all (now).

**Comment by aearil** [comment]
As mentioned in #545, I had the same issue where dino wasn't able to get the OMEMO key from one of my contacts. We managed to solve the problem by both enabling presence update/subscription.

**Comment by fiaxh** [comment]
Since 08a5088, you can always select OMEMO in the encryption selection and might get an error about why you can't use it. It also solves some cases in which OMEMO didn't work.
Can you please check how this affects your issue?

**Comment by aearil** [comment]
The user-experience is definitely better that way. Unfortunately I was
only able to test it with a single contact (the error message
displayed as expected when I tried to enable OMEMO).

Otherwise I've (un)fortunately managed to solve all key exchange
problem with my other contacts (often with the help of Conversations).

**Comment by JonnyTischbein** [comment]
You need to setup the group properly. 

Set
- JID visible: anyone
- Group permanent: true
- Moderated: true

OMEMO has to gather the device list of every user in group. Without JID only a nick is visible.
Tested in 4a3cef89fd7ebf15bfc6a108ac31f36e469cf80a

**Comment by Echolon** [comment]
I think its not yet supported in Dino

28 dic. 2019 1:02:15 PM Jonny Tischbein <notifications@github.com>:

**Comment by JonnyTischbein** [comment]
But it's working though.

![Screenshot_2019-12-28_16-18-22](https://user-images.githubusercontent.com/10757520/71545981-215e1780-2992-11ea-81bc-1bfc65e8b471.png)

**Comment by licaon-kter** [comment]
> Afterwards restart dino

This is always needed sadly :(

**Comment by fiaxh** [comment]
If the group chat is configured accordingly (members only + jid visible: anyone), there shouldn't be issues anymore.

@JonnyTischbein @licaon-kter You don't need to restart anymore after configuring the group chat as of ed6eda1.

**Comment by licaon-kter** [comment]
@fiaxh Thanks, yes it works.
