### ISSUE TITLE
Document how to regenerate the pot file and merge it into the po files

### ISSUE THREAD

**Issue by linkmauve** [dino/dino#54]
A make target would probably be enough too, just something to avoid the documentation lagging behind.

**Comment by fiaxh** [comment]
The state of the git repo is not automatically synced with weblate, but needs to be done manually by someone with permissions on weblate. Just before that, we update all .po and .pot files in one go. Thus, it would be rather contra-productive if code contributors would regenerate translation files and include them in PRs.
