### ISSUE TITLE
Can't enable OMEMO encryption for multiple contacts

### ISSUE THREAD

**Issue by vanitasvitae** [dino/dino#545]
For some of my contacts, the option to enable OMEMO encryption is greyed out.
I can however receive and decrypt encrypted messages sent both from my contacts devices as well as from my own other devices (conversations...). Also I'm pretty sure that sending encrypted messages to those contacts worked at some point in the past.

Relogging does not solve the issue.

I installed latest dino-git from Arch AUR.

**Comment by aearil** [comment]
I think I have the same issue. After digging around in the code it seems that dino never retrieved any key material from that contact (no trace of them in **identity_meta** from `omemo.db`). As a consequence, it is also impossible to enable OMEMO for me in any MUC where that person is present.

**Comment by aearil** [comment]
Update : with one of my contacts, we managed to solve the problem by enabling presence subscriptions on both sides, after that it worked like a charm.

Is this normal behaviour ? It might be a good idea to have some user feedback on why OMEMO isn't available.

**Comment by vanitasvitae** [comment]
I doubt that this is the issue tbh, but still thanks for the hint :)
I tried the same with my contacts and it did not solve the issue for me.

**Comment by vanitasvitae** [comment]
Fixed in latest master :)
