### ISSUE TITLE
Notifications are not working on Ubuntu

### ISSUE THREAD

**Issue by Sylvhem** [dino/dino#547]
On Ubuntu, I'm not noticed when I'm mentioned in a MUC or when I receive a new message in a conversation, even though notifications are enabled.
I tested this on Ubuntu 18.10 using both the repositories and OBS's versions and on Ubuntu 19.04 with the OBS version.

**Comment by aearil** [comment]
This feels relevant to the problem, but I'm not well enough versed into gnome-shell to propose a fix: https://stackoverflow.com/questions/33723549/glib-notification-and-gnome-shell

**Comment by denisu** [comment]
Also does not work in Fedora 30 (Gnome 3.32.2).

**Comment by MaggiWuerze** [comment]
confirmed on Ubuntu 19.04

**Comment by fiaxh** [comment]
Can you please check if using the latest master has an effect on your issue?

**Comment by MaggiWuerze** [comment]
seems fixed for me, thank you very much

**Comment by fiaxh** [comment]
I'll assume this is fixed.

@Sylvhem @denisu If you still these problems, please report so.
