### ISSUE TITLE
Window doesn't scroll to latest conversation when opened

### ISSUE THREAD

**Issue by neildarlow** [dino/dino#559]
Dino-0.0~git440.f4778ef-amd64 on Linux Mint 19.1 Cinnamon.

If you start Dino with MUC channels available the first listed will be opened and some conversations are shown in the chat window.

The last conversation shown isn't the latest one and it's necessary to click the channel selector twice (the first click clears the window and second click restores and scrolls the conversations) in order to see the latest conversation.

**Comment by fiaxh** [comment]
Do you still observe this issue with the 0.1 release (or the current master)?

**Comment by neildarlow** [comment]
Checking against a few other clients, Dino seems to perform the same. So, yes, I'd say it's fixed. I'll close this.
