### ISSUE TITLE
repopulate history on fresh install

### ISSUE THREAD

**Issue by trwnh** [dino/dino#563]
when reinstalling dino, the only thing visible is a blank screen with "start conversation". starting a conversation with a contact inits a messaging pane with an empty log.

it would be nice for dino to fetch messages from MAM on fresh installs. it would also be nice to allow importing/exporting local message db so that OMEMO messages are not lost, too.

**Comment by fiaxh** [comment]
Actually, Dino does fetch MAM messages. What version are you using?

**Comment by trwnh** [comment]
i've installed aur/dino which says it's at commit b0dde02bc9e5ff29025ff5fc70fd46d56df5d2ec https://github.com/dino/dino/commit/b0dde02bc9e5ff29025ff5fc70fd46d56df5d2ec

**Comment by trwnh** [comment]
wait, i think i figured it out. prosody defaults to expiring after 1 week, but the config i got from homebrewserver.club had `archive_expires_after = "1w"` manually defined despite it already being the default.
