### ISSUE TITLE
downloading or viewing a omemo encrypted .pdf file.

### ISSUE THREAD

**Issue by nehrwert** [dino/dino#564]
I'm running dino 0.0~git444.951be63. While i can view / download .jpg files, the same i not possible with .pdf files. 
Dino shows the url aesgcm://my.server.tld/something/random something.pdf#random somthing. But I can't do anything to get or open the file with that url.

**Comment by fiaxh** [comment]
This should have nothing to do with the file type but is more likely related to the file size. Dino currently downloads, decrypts and displays files below the encrypted file size of 5 MB.

The idea is that Dino should in the future display a "download" button/link for files above some size limit, and after the user clicked, Dino should get the file and decrypt it.

**Comment by nehrwert** [comment]
Ok, you are right, that is the problem. The file i tried was over 5mb and it works with smaller .pdf files. So a download option would be a good feature. Thanks for the fast reply and your good work!

**Comment by fiaxh** [comment]
> The idea is that Dino should in the future display a "download" button/link for files above some size limit, and after the user clicked, Dino should get the file and decrypt it.

This is done in f0abb8a.
