### ISSUE TITLE
ctrl + backspace act strangely with anything else than letters and digits

### ISSUE THREAD

**Issue by Porkepix** [dino/dino#566]
If you try to `ctrl + backspace` in the discussion prompt, it will work without any issue for letters or digits, but will stop on most of the other characters. Won't work for example on dot, parentheses or spaces… excepted in some weird cases where it goes away with other characters.

For example on my `fr-oss` layout, the digit row give me the following characters: `&é"'(-è_çà)=`.
First `ctrl + backspace` will leave me with `&é"'(-è_`.
Second `ctrl + backspace` will leave `&é"'(-`
Last one will leave the `&` and not remove it.
But of all of those characters, `&`, `"`, `'`, `(`, `-`, `_`, `)` and `=` will fail to be ctrl + backspaced if it's the only character in the prompt (or the first one).

**Comment by fiaxh** [comment]
> But of all of those characters, &, ", ', (, -, _, ) and = will fail to be ctrl + backspaced if it's the only character in the prompt (or the first one).

This is not a Dino bug but a GTK bug: https://gitlab.gnome.org/GNOME/gtk/issues/737 . In general, Dino implements none of the described behavior itself.

**Comment by Porkepix** [comment]
@fiaxh I thought at first about a toolkit bug, but tried for that reason to do the same thing in the textbox where you search for a contact to open a conversation, and there was no bug there.
Different component, and bug not present on all of them?

**Comment by fiaxh** [comment]
In all other places where you can enter text in Dino, `Gtk.Entry` widgets are used. The element where you type in the chat messages is the only one of type `Gtk.TextView`. The GTK bugreport only refers to `TextView`s.

**Comment by heinrich5991** [comment]
> This is not a Dino bug but a GTK bug: https://gitlab.gnome.org/GNOME/gtk/issues/737 . In general, Dino implements none of the described behavior itself.

This was fixed a month ago: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6080. 🎉
