### ISSUE TITLE
Connection Issue probably related to Tor Support

### ISSUE THREAD

**Issue by HulaHoopWhonix** [dino/dino#567]
Hi I tested Dino for integration with out anonymity distro Whonix and it doesn't seem to connect with any server in the list or otherwise.

**Comment by licaon-kter** [comment]
I've tested with `proxychains4` and it works fine, so I guess this is a setup issue.

Any logs?

**Comment by HulaHoopWhonix** [comment]
How do I start it in debug mode to obtain logs?

**Comment by HulaHoopWhonix** [comment]
A Whonix team member has tested it on plain Debian with same results. 

https://forums.whonix.org/t/client-server-instant-messengers-im/3081/25

**Comment by licaon-kter** [comment]
So on plain Debian it doesn't connect without any proxy? What was tested exactly?

**Comment by fiaxh** [comment]
I just made some changes that might help in 8120203 (related to timeouts).

You can get debug output by starting Dino as `env G_MESSAGES_DEBUG=all ./build/dino`. This will also include debug outputs from the glib components responsible for connection establishment.

**Comment by HulaHoopWhonix** [comment]
> So on plain Debian it doesn't connect without any proxy? What was tested exactly?

Yes plain Debian 10 with no proxy gives same result. Please backport the patch to Debian Buster (stable-next) so we can install Dino by default after they release a bug fixing point release.

**Comment by HulaHoopWhonix** [comment]
I installed runtime and built time deps and it still insists sqlite3 is not found though it is installed:

user@host:~/dino$ ./configure
-- Found Ninja: /usr/bin/ninja (found version "1.8.2")
-- Building plugin: omemo
-- Building plugin: openpgp
-- Building plugin: http-files
-- Installation directory for architecture-independent files: /usr/local
-- Installation directory for architecture-dependent files: /usr/local
-- Installation directory for read-only architecture-independent data: /usr/local/share
-- Installation directory for user executables: /usr/local/bin
-- Installation directory for dino-specific data: /usr/local/share/dino
-- Installation directory for .appdata.xml files: /usr/local/share/metainfo
-- Installation directory for .desktop files: /usr/local/share/applications
-- Installation directory for .service files: /usr/local/share/dbus-1/services
-- Installation directory for icons: /usr/local/share/icons
-- Installation directory for C header files: /usr/local/include
-- Installation directory for object code libraries: /usr/local/lib
-- Installation directory for locale files: /usr/local/share/locale
-- Installation directory for dino plugin object code files: /usr/local/lib/dino/plugins
-- Installation directory for Vala API files: /usr/local/share/vala/vapi
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find SQLite3 (missing: SQLite3_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSQLite3.cmake:19 (find_package_handle_standard_args)
  cmake/MultiFind.cmake:20 (find_package)
  qlite/CMakeLists.txt:1 (find_packages)

**Comment by licaon-kter** [comment]
https://github.com/dino/dino/blob/7a1fd5dfa688c28033a226bb03763b8815de3e99/README.md#L19

**Comment by HulaHoopWhonix** [comment]
You're missing two more deps that break the configure process: g++ libqrencode-dev

**Comment by HulaHoopWhonix** [comment]
"No response from server" in this one

**Comment by licaon-kter** [comment]
@HulaHoopWhonix what server? Any server? Dine debug output?

**Comment by HulaHoopWhonix** [comment]
I thought the point of me building from git was to test a patched version @fiaxh referred to. Anyway i started the Debian package with the debug command:

user@host:~$ env G_MESSAGES_DEBUG=all dino
env: ‘dino’: No such file or directory
user@host:~$ env G_MESSAGES_DEBUG=all dino-im
(dino-im:2316): GLib-GIO-DEBUG: 22:54:34.960: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(dino-im:2316): Gtk-DEBUG: 22:54:35.523: Connecting to session manager
(dino-im:2316): Gtk-DEBUG: 22:54:35.525: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
CONNECTION LOST?

The issue is when I try to register an account of sign in with a pre-existing one, dino always says "no response from server"

**Comment by fiaxh** [comment]
@HulaHoopWhonix Sorry for the confusion. The idea was that you execute the self-compiled binary with the debug command :slightly_smiling_face:

**Comment by 0brand** [comment]
>A Whonix team member has tested it on plain Debian 10 with same results.
>
>https://forums.whonix.org/t/client-server-instant-messengers-im/3081/25

Was able to get that sorted out. Had to make a few firewall adjustments. Dino is connecting and I was able to set up a @yax.im account. I'm getting the  "Failed to initialize ..." errors  but I'm not seeing any noticeable connection issues. Thanks for the help with debug output @fiaxh! 

```
user@deb-10-clone:~$ dino-im
(dino-im:1382): GLib-GIO-DEBUG: 19:24:00.049: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(dino-im:1382): GLib-GIO-DEBUG: 19:24:00.051: Failed to initialize networkmanager (GNetworkMonitorNM) for gio-network-monitor: 
(dino-im:1382): Gtk-DEBUG: 19:24:00.102: Connecting to session manager
(dino-im:1382): Gtk-DEBUG: 19:24:00.102: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(dino-im:1382): Gtk-DEBUG: 19:24:00.102: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(dino-im:1382): Gtk-DEBUG: 19:24:00.103: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
[account-creation@yax.im] New connection with resource dino.7932b5cf: 0x5719e086e4f0

**Comment by HulaHoopWhonix** [comment]
To clarify, the results from @0brand are from a Buster VM running on Qubes OS which runs a firewall routing VM for all network connections.

https://forums.whonix.org/t/client-server-instant-messengers-im/3081/28

On a VM behind a Tor Gateway dino simply cannot connect and no connection errors show up in the log at all. So it is something Tor specific. Tor in Whonix is configured to force route all programs over the anonymity network even if they don't explicitly support SOCKS5.

**Comment by HulaHoopWhonix** [comment]
Here is a pcap file for dino connecting: https://www.filehosting.org/file/details/804950/xmpp.pcapng


It seems to be the server is refusing to accept SRV DNS requests for some reason.

**Comment by licaon-kter** [comment]
@HulaHoopWhonix It does it's own DNS requests?

Then, I wonder, how is it that proxychains works?

**Comment by adrelanos** [comment]
Licaon_Kter:
> Then, I wonder, how is it that proxychains works?


Maybe it auctually leaks these requests over clearnet?

**Comment by HulaHoopWhonix** [comment]
>@HulaHoopWhonix It does it's own DNS requests?

It does them in a way that doesn't support a SOCKS proxy or specifically the way Tor mediates the request on its behalf.

**Comment by adrelanos** [comment]
At time of writing Tor only supports A, AAAA and PTR records. Tor Project upstream ticket:

`Support all kinds of DNS over Tor`
https://trac.torproject.org/projects/tor/ticket/7829

**Comment by HulaHoopWhonix** [comment]
The coyim xmpp chat client uses the dns.go library to do its lookups. The code in there might be an inspiration for a similar solution in Vala for Dino

https://github.com/coyim/coyim/search?q=dns&unscoped_q=dns

**Comment by fiaxh** [comment]
@HulaHoopWhonix I just committed a change that might help. Dino works fine in Tails, now. Could you please test the current master with Whonix? You might have to start Dino with `torsocks` or similar, depending on how Whonix works.

**Comment by whonixdino** [comment]
I tested it. Works fine! :) 

Please update the Debian Package, so you can easily install dino with packet manager.

Sadly, you can not connect via a hidden service to a xmpp server.

**Comment by fiaxh** [comment]
Since the general issue is fixed, I'll close this. The hidden service issue will be tracked in the new issue you opened.

> Please update the Debian Package, so you can easily install dino with packet manager.
The package in Debian Sid and Bullseye has been updated since and contains the fix now.
