### ISSUE TITLE
Support MUC status 


### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#568]
...is xmpp:chat@dino.im?join down?

**Comment by stevenroose** [comment]
I can't seem to join either.

**Comment by licaon-kter** [comment]
It appears to connect now.

**Comment by comradekingu** [comment]
I can't join. It didn't visually appear to disconnect, just started refusing messages, also without visible error.

**Comment by fiaxh** [comment]
The MUC works again, thanks for pointing out to the issue.
