### ISSUE TITLE
Messages with some numbers not showing up

### ISSUE THREAD

**Issue by github-k8n** [dino/dino#573]
When entering messages like "1" or any number between 16 and 83, and some higher numbers as well (like "232") and nothing else but the number in that message, the message is sent but is not shown in dino at all.

This is on Gentoo at commit 
34f9677c4e5384c9b823ce76c3dbeb143a3ff625
for dino
and commit 
4a137eaf4eb4421949e2e1dde9f11ec7bc07b88f
for libsignal.

**Comment by github-k8n** [comment]
This definitely seems to be a bug.
When switching to another user and back or even just clicking on the same user again, the missing lines reappear.
See recording of the issue here:
https://xmpp-upload.k8n.de/share/093585e8-7156-4196-b609-ef27da5bb67f/Bildschirmvideo%20von%2018.10.2019%2022%3a15%3a23.webm

**Comment by github-k8n** [comment]
No warnings, nothing,

output of dino --gtk-debug=all --gdk-debug=all 2> dino_debug.txt

https://xmpp-upload.k8n.de/share/dd7c4a2e-1394-4de5-90a0-e75b415d5d13/dino_debug.txt.gz

I opened dino, entered "1" in the chat window (group chat) then clicked on the group name on the left to reveal it then closed the application.

**Comment by selurvedu** [comment]
@fiaxh this did not get closed automatically via "fixes". I guess that's because GH accepts only one issue number per "Fixes" line. Please close.
