### ISSUE TITLE
Debian install instructions are missing the signing key fingerprint

### ISSUE THREAD

**Issue by Mikaela** [dino/dino#575]
* https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino

There is an instruction to download the key, but nothing to verify the fingerprint, so how do I know I don't get a MITMed key?

```
wget -nv https://download.opensuse.org/repositories/network:messaging:xmpp:dino/Debian_Next/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```

Compare to e.g. Tor Project install instructions:

```
curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
```

* https://2019.www.torproject.org/docs/debian.html.en

There the fingerprint is specified and I am at least a little less likely to get a MITM unless the torproject website was compromised or I was trusting a wrong certificate.

I also find it confusing that the install instructions refer to Debian Next that I haven't heard of before. Is it the same thing as Debian Testing?

Edit: I also forgot to say that the instructions tell using http:// sources.list entry while I heard on XMPP that it also supports https://. I think it should use https://, but I imagine that is because you don't wish to advice people to install `apt-transport-https` ?

**Comment by mar-v-in** [comment]
The key is downloaded via https, which is already protecting you against mitm.
