### ISSUE TITLE
Release version 0.1?

### ISSUE THREAD

**Issue by faulesocke** [dino/dino#578]
Hey,

I would like to package dino for Void Linux but our policy only allows packaging of released versions. Packaging just a random git commit or "nightly" versions is not accepted.

So, are there any plans to release 0.1 in the near future?

Kind regards and thanks for the hard work on this nice project!

**Comment by ArchangeGabriel** [comment]
Same here for Arch Linux. ;)

**Comment by stevenleeS0ht** [comment]
There is a lot of issue, which is duplicate to this this issue. But none of them (include this issue) give the answer to the question.

Is there anyone who is in charge able to provide some information about this?

Does dino use different release cycle or publish model? 

Or Dino is too young to become taged?

For the usual situation, a software should be taged as 0.0.0 or 0.0.1 if it is workable even if it might unstable and unreliable.

But now, of course Dino is much better than those worst situation.

Can anyone give some explanation?

**Comment by ahkok** [comment]
Same here for ClearLinux. Please use tags. If you tag often, no problem. If you tag rarely, great. If you never tag, big problem for us. A tag for the initial commit is entirely useless.

This isn't a crazy request. Thousands of OSS projects do proper tags. Please join the fun :)

**Comment by silvernode** [comment]
> Hey,
> 
> I would like to package dino for Void Linux but our policy only allows packaging of released versions. Packaging just a random git commit or "nightly" versions is not accepted.
> 
> So, are there any plans to release 0.1 in the near future?
> 
> Kind regards and thanks for the hard work on this nice project!

I came here to ask the same thing, I just packaged Dino for void but I had to pull from master and give the package a 1.0 version since there really isn't a recent version to name it after.

**Comment by licaon-kter** [comment]
@silvernode and what happens when they Tag 0.1?

**Comment by silvernode** [comment]
> @silvernode and what happens when they Tag 0.1?

Nothing because my template for the package is local to my machine. I won't publish it until Dino gets tagging or releases on a regular basis.

**Comment by stevenleeS0ht** [comment]
@fiaxh , @mar-v-in , @sdhand , Please see [semantic versioning](https://semver.org/) for additional information.

In addition make milestone for tagging is a good manner and can also bring clear target for all developer.

**Comment by stevenleeS0ht** [comment]
@licaon-kter , tagging is not a essential step of open source development. But it is a good practice and it can make software development and publish workflow healthier.

**Comment by stevenleeS0ht** [comment]
@fiaxh , @mar-v-in , Could you please tell us what is the cost of make a tagging.

Tagging is a relaxing activity. if you think the software is currently fine and all currently known bugs have been fixed than make a release.

you don't have to worry too much especially the current stage is 0.x, you can have a more flexible release versioning.

**Comment by ahkok** [comment]
Note, nobody really cares about "what the numbers mean". Whether you follow semantic versioning strictly, or just tag everything incrementally `v1`, `v2`, `v3` (as I do in some of my projects) is entirely up to you.

The only thing that matters is that, by tagging, you are telling users (us) that you've made something that you would consider appropriate for deployment, and not a random git commit.

For some of the projects I have, I tag almost every commit, since they're stable projects and everything is usually a bug fix that is useful to users.

**Comment by stevenleeS0ht** [comment]
@ahkok , semantic versioning is not a law, it is a good reference. Users can know what has been changed without read much Changlog in details.

**Comment by jubalh** [comment]
Guys.. I'm pretty sure the authors know what versions are and how to do them ;)

**Comment by jubalh** [comment]
Oh my gosh: https://github.com/dino/dino/releases/tag/v0.1.0

**Comment by ahkok** [comment]
`\o/`

**Comment by selurvedu** [comment]
![Shocked Chris Pratt GIF](https://user-images.githubusercontent.com/11262062/73398773-bb491500-42ee-11ea-9979-bd4dca69698a.gif "Shocked Chris Pratt GIF")

**Comment by fiaxh** [comment]
As people already noted, Dino 0.1 is has been released yesterday. 🙂 [(Release blog post)](https://dino.im/blog/2020/01/dino-0.1-release/)

@faulesocke @ArchangeGabriel @ahkok  We are looking forward to see Dino packaged in Void Linux, Arch Linux and ClearLinux! If you have any questions or comments, please contact us here or in our public XMPP channel at [`chat@dino.im`](xmpp:chat@dino.im?join).

@ahkok We've been linked to your message on the clearlinux forum:
> The signal plugin build code isn’t properly functional and fails to install the needed files. Building without it breaks entirely. This is too fragile right now and I’d prefer if they didn’t use git submodules for system libraries.

The submodule is entirely optional and only there to make things easier for some, we'll probably remove them soon. The intended way is to have libsignal-protocol-c (version 2.3.2) installed as a you normally do for libraries (as a "system library"). Only if you run `./configure --with-libsignal-in-tree` it will consider the submodule - which you shouldn't when building distribution packages.

**Comment by jubalh** [comment]
@fiaxh I assume we want https://build.opensuse.org/package/show/network:messaging:xmpp:dino/dino to stay there to build git for several platforms. So I'll create a new repo for the official (versioned) openSUSE package at https://build.opensuse.org/project/show/network.

**Comment by ArchangeGabriel** [comment]
@fiaxh https://www.archlinux.org/packages/community/x86_64/dino/

**Comment by jubalh** [comment]
@fiaxh @mar-v-in  would you like network:messaging:xmpp:dino/dino to build the stable version or continue to build git?

**Comment by silvernode** [comment]
Awrsome! I will clean up my void template and submit a pull request
possibly today unless someone is already on top if that. I didn't notice
there was a release since I started chatting in this thread a few weeks
ago. Late to the game but still excited. thanks

**Comment by ahkok** [comment]
I had to disable parallel builds(!) but otherwise it compiled ok. Will be available in clearlinux as well, *with* signal support. Cheers!

**Comment by fiaxh** [comment]
@ArchangeGabriel I noticed that you are compiling the Dino Arch Linux package with the notification sound plugin included by default. However, the plugin is not intended to and not ready to be included by default:
- Once included, users don't have an option to disable the sound
- There are some counter-intuitive side-effects with system notification settings
- The plugin is barely tested

For now, the plugin is only intended for people who know that they want sound and are compiling themselves. Thus, it would be good if you could remove the respective compile flag.

@jubalh Yes it would be nice to have `network:messaging:xmpp:dino/dino` build the git versions. By making pre-build git versions easily accessible, we'll hopefully get more beta testers and thus less bugs in our releases :slightly_smiling_face:

**Comment by ArchangeGabriel** [comment]
@fiaxh I initially did not (because I did not know about it), but it was requested (https://bugs.archlinux.org/task/65341). But with your arguments against it, I’ll disable it right away.
