### ISSUE TITLE
segfault at start

### ISSUE THREAD

**Issue by silberzwiebel** [dino/dino#58]
I don't know what exactly happened to run into this bug but the dino I've installed under Fedora 25 with the copr repo does crash at startup.

Here are two different gdb backtraces, I get the second one more often.

```Thread 5 "dino" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd742b700 (LWP 8733)]
signal_type_ref (instance=0x2)
    at ../plugins/signal-protocol/libsignal-protocol-c/src/signal_protocol.c:48
48	    assert(instance->ref_count > 0);
```

```
Thread 5 "dino" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd73fa700 (LWP 15224)]
0x00007fffd7bae205 in signal_constant_memcmp (s1=s1@entry=0x7fffd0175670, s2=0x12, 
    n=n@entry=32)
    at ../plugins/signal-protocol/libsignal-protocol-c/src/signal_protocol.c:586
586	        result |= c1[i] ^ c2[i];
```

Interestingly, dino does not crash when starting the self-compiled version (which should be the same version as the the one from the copr repo)

**Comment by mar-v-in** [comment]
The build in the copr repo uses the `-O2` compile flag which might cause segfaults in broken code that happen less often (or never) when not optimizing.

First error: can you try to reproduce and show a full stack trace? This line alone does not help to find the culprit.
The second error is likely the same as reported in #44.

**Comment by silberzwiebel** [comment]
Sorry, I couldn't reproduce the first error.
However, sometimes dino did not start at all (i.e., I did not see a GUI) but kept waiting for something.
[Here is a complete backtrace of this situation which I CTRL-C-ed.](https://gist.github.com/anonymous/6b3add624d4781c0192a7e724acd0145)
