### ISSUE TITLE
No automatic login after account creation

### ISSUE THREAD

**Issue by zuglufttier** [dino/dino#584]
While the creation process for a new account is straight forward and very usable, there is one thing missing: After the account is created, you still have to login manually!

So, it would be great if the account that was just created on the server would be added to dino automatically.

**Comment by fiaxh** [comment]
This is actually what should already happen - accounts created through in-band registration are added automatically. Some servers provide websites to register, those are not added.

**Comment by zuglufttier** [comment]
My server supports IBR but it uses captchas maybe that's a problem. I just saw that a new account is not created every time I try that. Most of the time, the button to create the new account (after I entered the correct captcha) displays the circle animation forever.
