### ISSUE TITLE
Crash sending OMEMO message

### ISSUE THREAD

**Issue by svalo** [dino/dino#59]
Crash happens when sending omemo encrypted message.
Unencrypted messages are fine
OS: ArchLinux with latest update, here is the trace from gdb https://paste.debian.net/928419/

Name            : glib2
Version         : 2.50.3-1

Name            : gtk3
Version         : 3.22.10-1

Name            : gpgme
Version         : 1.9.0-1

Name            : libgee
Version         : 0.18.1-1

Name            : libnotify
Version         : 0.7.7-1

Name            : libgcrypt
Version         : 1.7.6-1

Name            : sqlite
Version         : 3.18.0-1

**Comment by svalo** [comment]
Dino doesn't crash anymore, thanks! When I send an ecrypted message using OMEMO there are 1-2secs delay between the moment when I press enter to send the message and the moment when the message appears in the chat , gdb don't report anything.

**Comment by svalo** [comment]
I noticed I have random delays with omemo using gajim as well so it might not be related to dino, I think this issue can be closed.

**Comment by NicoHood** [comment]
@svalo you can close the issue yourself then :)

**Comment by svalo** [comment]
yup, I know, what I didn't know is wheter I should close it myself or not :)
