### ISSUE TITLE
emojis are not displayed

### ISSUE THREAD

**Issue by cyBea** [dino/dino#593]
distro: ubuntu 18.04
dino-version: 0.0~git493.08a5088 (from http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/)

Emojis are not displayed at all. 
- I cannot select emojis using `right-click->Insert Emoji` (searching results in "No Results Found")
- I can insert emoji using copy and paste (still invisible) and send it to conversations client where it is visible.

The only emoji related package installed is `fonts-noto-color-emoji`. It is unrelated to dino. Do I need to install an additional package?

**Comment by licaon-kter** [comment]
CTRL - dot ?

**Comment by cyBea** [comment]
same as `right-click->Insert Emoji`

![dino-no-emojis-screenshot](https://user-images.githubusercontent.com/5377772/62576658-96269d00-b89d-11e9-9da6-eefe602e7a34.png)

**Comment by mar-v-in** [comment]
Does your system display emojis in other apps (other than the browser)?

**Comment by cyBea** [comment]
Generally emojis work on my system ex. in filenames (file browser and command line). Using dino I can receive them (invisibly) and then copy them and see them for instance in clip board.

**Comment by bbx-github** [comment]
With dino Version: 0.0~git539.784319a and a click on the new button I got a slightly different emoji selector. (Everything above is still valid)
![dino-no-emojis-screenshot2](https://user-images.githubusercontent.com/53237674/64970900-036b1c00-d8a7-11e9-9de8-1e28b1a44989.png)

Any ideas
- how to debug this?
- how to fix this?

I observed this behavior only in kde-neon but not in kubuntu using the same dino repo.

**Comment by cyBea** [comment]
With dino Version: 0.0~git539.784319a and a click on the new button I got a slightly different emoji selector. (Everything above is still valid)
![dino-no-emojis-screenshot2](https://user-images.githubusercontent.com/53237674/64970900-036b1c00-d8a7-11e9-9de8-1e28b1a44989.png)

Any ideas
- how to debug this?
- how to fix this?

I observed this behavior only in kde-neon but not in kubuntu using the same dino repo.

**Comment by Echolon** [comment]
rel: https://github.com/dino/dino/commit/9950742bf1903291c271619aea101b0e2f81d19c#commitcomment-35074231

**Comment by cyBea** [comment]
It was just too strange: I tried to narrow down this bug again and played with lots of things in plasma system settings. Finally I disabled font anti-aliasing: the fonts went ugly but the emojis appeared. Turning anti-aliasing back on made the fonts look nice again and the emojis disappeared again.
Then I tried to find the font size and excluded various single font sizes from anti-aliasing. The emojis were always visible. Finally I didn't exclude any font sizes from anti-aliasing (same setting as I as ever before) and the emojis stayed. I'm curious if this lasts after reboot.

**Comment by gerg5c42g542g2c54g52c** [comment]
Please reopen. This isn't fixed.

I don't see any emojis in dino 0.1.0 on standard Debian buster GNOME install. Emojis are visible in gajim and in firefox, I cannot see them in filenames in nautilus.

Dino should definitely show emojis on any setup even if they can't be seen in nautilus, that's perfectly clear to me, hence it's in issue to fix. Perhaps it's just a matter of adding a dependency to dino-im on debian.

**Comment by licaon-kter** [comment]
@gerg5c42g542g2c54g52c you have the font mentioned in the first post installed?

**Comment by gerg5c42g542g2c54g52c** [comment]
@licaon-kter yes I do.

**Comment by gerg5c42g542g2c54g52c** [comment]
More info: emojis work on another PC I have with a similar setup, both PCs have fonts-noto-color-emoji installed. I'm guessing the bug could be triggered if Dino 0.1.0 is installed over an old version (0.0.git20181129-1+deb10u1) or if the Debian installation is old (standard Debian 8.1 with GNOME was installed originally and then it was continuously updated until this day - Debian 10.3).

**Comment by cyBea** [comment]
My "solution" was to delete `~/.config/fontconfig/fonts.conf`. I'm not sure if the file was corrupted by another program. I think reopening should only be done if it's dino's fault...

**Comment by tdm4** [comment]
@cyBea can you share your $HOME/.config/gtk-3.0/settings.ini by any chance? I'm trying to get emojis working (#1337)
I don't know what font dino is trying to use.

**Comment by cyBea** [comment]
```bash
:~$ cat ~/.config/gtk-3.0/settings.ini
[Settings]
gtk-application-prefer-dark-theme=true
gtk-button-images=true
gtk-cursor-theme-name=breeze_cursors
gtk-cursor-theme-size=24
gtk-decoration-layout=icon:minimize,maximize,close
gtk-enable-animations=true
gtk-fallback-icon-theme=gnome
gtk-font-name=Noto Sans,  10
gtk-icon-theme-name=breeze-dark
gtk-menu-images=true
gtk-modules=colorreload-gtk-module:window-decorations-gtk-module
gtk-primary-button-warps-slider=false
gtk-theme-name=Breeze
gtk-toolbar-style=3
gtk-xft-dpi=98304
```

**Comment by licaon-kter** [comment]
@tdm4 `noto color emoji font`
