### ISSUE TITLE
images sent from dino can't be decrypted

### ISSUE THREAD

**Issue by fauno** [dino/dino#595]
Hi, we're getting this error whenever we send an image or file from dino on an omemo conversation. In dino, the message is not shown at all, conversations shows a downloadable image that can't be opened.

```
(dino:14653): OMEMO-CRITICAL **: 20:13:56.598: file /build/dino-git/src/dino/plugins/omemo/src/file_transfer/file_decryptor.vala: line 68: uncaught error: Sign
al error: SG_ERR_UNKNOWN ((null), -1000)
```

**Comment by fiaxh** [comment]
Can you please check if this still occurs with the current master?

**Comment by fauno** [comment]
it doesn't!  i sent an image from dino and could see it from
conversations.  sorry to leave this hanging, i'm too busy :(
