### ISSUE TITLE
Dino doesn't seem to receive announcements of new OMEMO keys

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#599]
A contact had an old client. My Dino had the key for that client as "unused" because it was removed from the device list ([by Conversations apparently](https://github.com/siacs/Conversations/issues/3499)), and it didn't reactivate the key after the client came online and sent messages to Dino. After a reboot, the key was active again.

**Comment by stevenroose** [comment]
Also, Dino had been running for a day or 2, without suspending the PC. I type in a group chat and a contact can't get the messages. He seems to have a new phone, but Conversations was aware of the second OMEMO key of that person, while Dino wasn't.

It seems to somehow miss out on OMEMO keys.

Is anyone aware of a way to query OMEMO keys for a node using some tool so that I can debug whether it's Dino's fault or some other thing? I can't really see which OMEMO keys the server advertises for a contact because clients might cache/be out-of-date/....

**Comment by stevenroose** [comment]
Now even after a restart it doesn't get to know the new OMEMO key.

**Comment by mar-v-in** [comment]
Should be fixed in 6257e9705cd51543437507dbe805b8913845dc40
