### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by evaryont** [dino/dino#61]
There is no notification sound at the moment. It would be nice to include one, and make it configurable. (Changing the sound, and possibly disabling it altogether.)

Unless there is some feature of GNOME 3 that I've missed?

**Comment by bebehei** [comment]
With #49 the backend got changed from `libnotify` to `GNotification`. There is the problem, that  [backend does not support](https://developer.gnome.org/gio/stable/GNotification.html) sounds in the notification protocol.

Supporting notifications would require to change the notification backend again.

**Comment by fiaxh** [comment]
Currently it is possible to get notification sounds by building dino with `./configure --enable-plugin=notification-sound`
