### ISSUE TITLE
Cannot open accounts/preferences window

### ISSUE THREAD

**Issue by andreygursky** [dino/dino#617]
Using dino-im 20190911 2a70a4e from Debian/testing. I had one disabled account, then I've added a new one. Now I don't see any icon-button to open some configuration window:

![dino-git-2a70a4e](https://user-images.githubusercontent.com/280321/64954130-f4737200-d884-11e9-8e84-ce52a4dffcb3.png)

**Comment by fiaxh** [comment]
This was solved in df37166.
