### ISSUE TITLE
Debugging: view XML stanzas with timestamps

### ISSUE THREAD

**Issue by andreygursky** [dino/dino#618]
Using dino-im 20190911 2a70a4e from Debian/testing.

According to https://github.com/dino/dino/wiki/Debugging it is possible to view XML stanzas. It would be useful to be able to enable timestamps printing in a such way, they could be easily cut off if needed in some editor.

**Comment by mar-v-in** [comment]
Fixed in 1bb75f40d26ad20381a200e09eaa9f519cffe398
