### ISSUE TITLE
Reply/Quote messages

### ISSUE THREAD

**Issue by Perflyst** [dino/dino#625]
Please add an option to quote / reply to a message

**Comment by roobre** [comment]
I'm interested in this as well. I'd like to discuss it a bit tho. What should be the UI/UX for replying/quoting? It would need to stick to the currrent design, so contextual menus are out of the question. Some ideas that come to my mind:

* A small reply button appearing at the end of a message
  * :heavy_check_mark: Non-intrusive
  * :x: Uses hover, so needs mouse interaction (neither keyboard nor touchscreen friendly)
* Single/double click/tap on message
  * :heavy_check_mark: Works on touch
  * :x: Not intuitive, conflicts with selecting text
* Just right click/long tap
  * :heavy_check_mark: Touch/mouse friendly
  * :x: Maybe harder to implement?
  * :grey_question: Needs extra care for not conflicting with the contextual menu when text is selected

Any thoughts? Once the UI/UX is clear it should be fairly easy to implement, as it's just appending the selected message text to the input box.

**Comment by fauno** [comment]
telegram and conversations use contextual menus for replying, single and long taps respectively. tg desktop shows a 'reply' link on hover (not sure how to do it with keyboard)

also, conversations adds a '> ' quote and processes it as a markdown blockquote, so maybe you could follow the same convention? it makes me think xmpp doesn't have support for threading messages

**Comment by roobre** [comment]
AFAIK there is no threading support (at least not widespread) for XMPP.

Regarding styling, the markdown-ish syntax you mean is [XEP-0393: Message Styling](https://xmpp.org/extensions/xep-0393.html#quote), for which there is WIP support on Dino.

**Comment by mimi89999** [comment]
I think that a right click on desktop and long click on mobile and option from context menu would be the best UI. There could also be a keyboard shortcut like ctrl+up/down to scroll through the messages one wants to reply to.

**Comment by singpolyma** [comment]
> AFAIK there is no threading support (at least not widespread) for XMPP.

Threading support is actually baked right into the base standard, and is supported in a basic way by many clients (such as Gajim) -- what's largely missing from the ecosystem is clients with good UI for it...

**Comment by muppeth** [comment]
I think being able to just right click (or long press in case of mobile) and select quote like on conversations would be already a good feature. Currently its hard to quote someone easily (you need to manually copy the text and add formatting for quote).

**Comment by selurvedu** [comment]
For the record, I added a quote button in a local branch, which greatly improved my UX. Unfortunately, it required a few hacks in the code that nobody would merge, so there is no point in publishing it until I figure out how to implement it properly.

**Comment by Quix0r** [comment]
Much wanted feature! So far I have to add a `>` + copy-paste the message when I want to quote it. This would shortcut it. And what about existing messages in the input box?

**Comment by MarcoPolo-PasTonMolo** [comment]
As no such button is welcomed for the quote feature by the devs, if somebody is interested an idea would be to implement autocompletion for previous messages when the start of the input starts with '>'. https://github.com/profanity-im/profanity/pull/1651 relevant pull request for profanity

**Comment by fiaxh** [comment]
Done in dc52e7595cca06d0a2da7d11b3c88cb2f7ce529c.

<img src="https://user-images.githubusercontent.com/9932450/211021983-623c0b8a-ef36-49d3-aa44-4d20a8913737.png"  width="500" />
