### ISSUE TITLE
OMEMO - corrupted files sent to Conversations 2.5.12

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#630]
HEAD (8e6db8859c756ef2445e1f5277103d83c735c726)

1:1 chat, OMEMO encrypted, works fine w/o OMEMO

Original file: 
![om_orig](https://user-images.githubusercontent.com/2282799/66749555-a9478180-ee79-11e9-8646-307f3876ad58.jpg)

Corrupt file:
![om_corrupt](https://user-images.githubusercontent.com/2282799/66749560-ad739f00-ee79-11e9-933a-0982276c9c5b.jpg)

Diff:
```
0001aa60: a43a 3d45 2814 0a05 0281 40a0 5028 140a  .:=E(.....   0001aa60: a43a 3d45 2814 0a05 0281 40a0 5028 140a  .:=E(.....
0001aa70: 0502 8140 a050 2814 0a05 0281 40a0 5028  ...@.P(...   0001aa70: 0502 8140 a050 2814 0a05 0281 40a0 5028  ...@.P(...
0001aa80: 140a 0502 8140 a050 2814 0a05 0281 40a0  .....@.P(.   0001aa80: 140a 0502 8140 a050 2814 0a05 0281 40a0  .....@.P(.
0001aa90: 5028 140a 0502 8140 a050 2814 0a05 0281  P(.....@.P   0001aa90: 5028 140a 0502 8140 a050 2814 0a05 0281  P(.....@.P
0001aaa0: 40a0 5028 140a 0502 8140 a050 2814 0a05  @.P(.....@ <
0001aab0: 0281 40a0 5028 140a 0502 8140 a0ff d9    ..@.P(.... <

```

Yes on desktop the viewer shows it ok, since it copes with the missing 16(!!) bytes, but ironically not Dino, and not my Android gallery.

No issues between Conversations

**Comment by Echolon** [comment]
Hello,

I can confirm th issue!
