### ISSUE TITLE
OMEMO decryption fails: "Client doesn't support OMEMO'

### ISSUE THREAD

**Issue by depate** [dino/dino#637]
Hello everyone, 
I got problems with OMEMO in Dino. Dino will encrypt messages successfully to conversations but has trouble decrypting received msgs. Debug gives following feedback:

``` 
** (dino:3175): CRITICAL **: 10:48:50.600: signal_store_get_local_registration_id: assertion 'self != NULL' failed
```

Where can I get more info about that error?

**Comment by licaon-kter** [comment]
@depate Dino version?

**Comment by depate** [comment]
I installed it as dino-git from AUR. I can't find any --version option or hint in the GTK, but AUR says it's ```r375.7497f1f-1```

**Comment by fiaxh** [comment]
@depate Your version is rather outdated, please update it and check if the problem persists. Unfortunately the package won't be automatically updated, but has to be updated explicitly. Commit 375 was a year ago - we are currently at 563.

An explanation from the AUR package maintainer about this [[link]](https://aur.archlinux.org/packages/dino-git):
> The user is supposed to check for updates. In the past I used to update the pkgver variable every few commits but that was wrong and I was asked to stop by a TU. Here are the guidelines: https://wiki.archlinux.org/index.php/VCS_package_guidelines#Guidelines

**Comment by depate** [comment]
Ok, I did not check the revision number before - my fault.  Updated to the latest non-git PKGBUILD which is r557 and runs without noticeable flaws.
Thanks!
