### ISSUE TITLE
Address shown instead of nickname / alias when sending files

### ISSUE THREAD

**Issue by Zash** [dino/dino#643]
![Screenshot_2019-11-07_19-50-15](https://user-images.githubusercontent.com/197474/68418087-de54a480-0197-11ea-88f9-c5b3136797ba.png)

1. Send a file
2. Send a normal chat message

Expected: Nickname or local alias shown in both cases

Actual: When sending a file ones address is shown instead of nickame/alias as sender.

**Comment by Ppjet6** [comment]
related to #248?

**Comment by Zash** [comment]
Possible dupe, yes.

**Comment by fiaxh** [comment]
This was fixed in cf1c7d3.
