### ISSUE TITLE
CAPTCHA not working properly

### ISSUE THREAD

**Issue by Mati20187** [dino/dino#644]
I wanted to register a new account through Dino but there's something wrong with CAPTCHA. I entered the text from the link, clicked "Register" and got loading animation on the button which never ends (I waited for 10 minutes and nothing).
I've tried registering an account from a different XMPP client and everything went smoothly.

**Comment by ericschdt** [comment]
I have tested it with the `conversations.im` server: 2 out 3 times I could reproduce it, once however it worked immediately.

**Comment by fiaxh** [comment]
@Mati20187 @ericschdt Did the username you wanted to register include upper-case letters?

**Comment by ericschdt** [comment]
> @Mati20187 @ericschdt Did the username you wanted to register include upper-case letters?

Only lower case ascii characters. Unfortunately I cannot reproduce it always. It may be possible that you need several tries in order to invoke this bug.
