### ISSUE TITLE
Compilaton fails on Arch Linux

### ISSUE THREAD

**Issue by kousu** [dino/dino#646]
I checked out a fresh copy (0acbe4855d1cfb42832aae1d18b668e2ceb18d2c) on Arch Linux and get several copies of this error from different files:

```
[597/697] Generating C source src/account_settings_entry.c
FAILED: plugins/openpgp/src/account_settings_entry.c 
cd /home/kousu/src/dino/build/plugins/openpgp && /usr/bin/valac -C -d /home/kousu/src/dino/build/plugins/openpgp/src --pkg=gee-0.8 --pkg=glib-2.0 --pkg=gmodule-2.0 --pkg=gobject-2.0 --pkg=gtk+-3.0 --gresources /home/kousu/src/dino/build/plugins/openpgp/resources/.gresource.xml -g --target-glib=2.38 --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/file_transfer/file_decryptor.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/file_transfer/file_encryptor.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/account_settings_widget.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/contact_details_provider.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/database.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/encryption_list_entry.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/manager.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/plugin.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/register_plugin.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/stream_flag.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/stream_module.vapi --use-fast-vapi /home/kousu/src/dino/build/plugins/openpgp/src/util.vapi /home/kousu/src/dino/plugins/openpgp/src/account_settings_entry.vala /home/kousu/src/dino/build/exports/gpgme.vapi /home/kousu/src/dino/build/exports/xmpp-vala.vapi /home/kousu/src/dino/build/exports/qlite.vapi /home/kousu/src/dino/build/exports/dino.vapi
stream_module.vapi:65.4-65.41: error: A const field requires a value to be provided
			internal const string NS_URI_ENCRYPTED;
			^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stream_module.vapi:67.4-67.38: error: A const field requires a value to be provided
			internal const string NS_URI_SIGNED;
```

I have vala 0.46.4-1.

Here is a complete build [log.txt](https://github.com/dino/dino/files/3837960/log.txt)

I like dino very much! I'm hoping I can get it building again :)

**Comment by wiktor-k** [comment]
This is clearly a problem with one of the recent upgrades. When I tested building Dino 2 days on Arch (with vala 0.46.3) it was OK but now it fails with the same error as yours. Downgrading vala did not help but there were multiple changes in between so it's possible that some other package change broke it.

**Comment by wiktor-k** [comment]
I did play around with the source a little bit and found out that inlining const strings works around the bug. In case someone is interested here's the commit: https://github.com/wiktor-k/dino/commit/2967b024af9b58ce4d3e5ada960411273ef661a1

There are more computed consts in the source and it's not a problem so maybe the underlying issue is some flag for plugins or something :man_shrugging: .

**Comment by mar-v-in** [comment]
This issue is fixed in the git of vala compiler and will probably be fixed in the next release. Thanks @ricotz for swift sction.

We should provably still add 0.46.4 (and various others) to our list of versions that have bugs in fast vapi generation (we already have a workaround for such issues in place just need to activate it for this version of valac.

**Comment by genofire** [comment]
And last OBS Build is also not usable ;( 
```
dino: error while loading shared libraries: libicuuc.so.64: cannot open shared object file: No such file or directory
``` 
current version is: `/usr/lib/libicuuc.so.65.1`
