### ISSUE TITLE
website dino.im not accessable per ipv6

### ISSUE THREAD

**Issue by genofire** [dino/dino#648]
Maybe webserver not running on ipv6 or wrong ipv6 address (but icmp6 works)

**Comment by fiaxh** [comment]
It works now.

**Comment by masipcat** [comment]
I'm getting this over IPv4:
![image](https://user-images.githubusercontent.com/775189/69012251-a6a1e580-096b-11ea-9155-8000fcd453f7.png)

**Comment by genofire** [comment]
The Website is down ...

**Comment by mightyBroccoli** [comment]
It seems that the DNS record are set, but the ip is not reachable.

```bash
ping -6 dino.im
ping: connect: Network is unreachable
```

```DNS
;; QUESTION SECTION:
;; dino.im.	IN	A
;; dino.im.	IN	AAAA

;; ANSWER SECTION:
dino.im.	287	IN	A	109.230.233.131
dino.im.	274	IN	AAAA	2a05:bec0:25:f::64
```
