### ISSUE TITLE
Attachment icon not displayed right after start

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#652]
Dino does not immediately display the attachment icon to me:

![dino_icon_missing](https://user-images.githubusercontent.com/43318127/68992700-9b18c680-0866-11ea-881a-95663cc216a8.png)

First if the UI becomes updated eg by opening a different chat the icon is displayed again.

Source: Recent compiled AUR package
Operating System: Manjaro Linux (KDE)

**Comment by fiaxh** [comment]
Does your server offer HTTP file upload or can you only transfer files using Jingle file transfers?

**Comment by ericschdt** [comment]
> Does your server offer HTTP file upload or can you only transfer files using Jingle file transfers?
It does offer HTTP file upload.

**Comment by ericschdt** [comment]
I noticed, it takes some time until it is displayed: It can take ~ 5 seconds.

**Comment by fiaxh** [comment]
> Probably that's the time until Dino knows whether the server does support (HTTP) file transfer or not?

Yes, exactly. Dino waits until it knows whether the server supports file uploads and only then displays the attach button. Thus, I would not classify this as a bug.

> Edit: Well, it's immediately there when I open another chat from the same account right after the start, so the above guess does not hold.

I guess the little time it took you to change the conversation was the time it took Dino to figure out the upload question.
