### ISSUE TITLE
Message input is rendered with garbage.

### ISSUE THREAD

**Issue by akhilman** [dino/dino#653]
Dino's message input is rendered with garbage.
Dino's version: actual git master.
OS: Debian Sid
GTK: 3.24.12
Theme: Adwaita Dark
![Screenshot from 2019-11-20 07-35-21](https://user-images.githubusercontent.com/180812/69198764-72dfdf00-0b68-11ea-9ab8-03c21e833f9d.png)

**Comment by mar-v-in** [comment]
GPU and GPU driver? Wayland or Xorg?

**Comment by akhilman** [comment]
OpenGL renderer string: AMD RS780 (DRM 2.50.0 / 5.3.0-2-amd64, LLVM 9.0.0)
Xorg

**Comment by mar-v-in** [comment]
Can you try starting dino with `env GDK_RENDERING=image dino`? This disables hardware accelerated rendering.

**Comment by akhilman** [comment]
Same result with **env GDK_RENDERING=image dino**.

**Comment by akhilman** [comment]
But works fine with wayland.

**Comment by fiaxh** [comment]
Another data point from the Dino Channel:

- Xorg
- Intel 2nd Generation Integrated Graphics, i915 driver
- OS: Xubuntu 19.10

> It seems like the text field background is not drawn. When I erase a word, the new word just overlays it
> When I minimise and maximise, the background contains the part of the window behind it

![178209dc_Screenshot_2019-10-24_17-09-33](https://user-images.githubusercontent.com/9932450/69439844-091e2b80-0d48-11ea-8588-076f6e62a4ba.png)
