### ISSUE TITLE
Auto rejoin after hibernating does not work

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#655]
Coming from hibernation Dino reconnects automatically all accounts. 
However, from two different accounts both MUCs were not rejoined automatically. Each of the two MUC avatars kept being grayed out until the related account was reconnected. 

Further, one of the accounts, which was only joined in a single MUC but does not has any other contacts or bookmarks, was said to be connected but its avatar was grayed out:

<img width="435" alt="dino_wrong_color" src="https://user-images.githubusercontent.com/43318127/69370222-70c76e80-0c95-11ea-9165-af64c680301a.png">

Operating System: Manjaro (KDE)
Source: AUR dino-git

**Comment by mar-v-in** [comment]
@ericschdt Is this still an issue after the fix for #682 ?

**Comment by ericschdt** [comment]
> @ericschdt Is this still an issue after the fix for #682 ?

Seems to be fixed now! :) Thanks.
