### ISSUE TITLE
Add MAM for MUCs

### ISSUE THREAD

**Issue by wiktor-k** [dino/dino#657]
Currently Dino does not do MAM for MUCs instead fetching only few last messages.

Having MAM support would allow fetching all messages thus making the history complete.

**Comment by Echolon** [comment]
That hasn't been mentioned yet? :smile:

**Comment by eeeeeta** [comment]
This seems like a relatively large omission, as someone who just started using Dino; it's really nice compared to gajim, but having this feature does make things somewhat trying...!

**Comment by eeeeeta** [comment]
fwiw, I've [started work on this in a fork](https://github.com/dino/dino/compare/master...eeeeeta:eta/mam). Hoping to get it smoothed out and merged to upstream at some stage (the current version works, but has major UX flaws).

**Comment by rozzin** [comment]
@eeeeeta
> fwiw, I've [started work on this in a fork](https://github.com/dino/dino/compare/master...eeeeeta:eta/mam). Hoping to get it smoothed out and merged to upstream at some stage (the current version works, but has major UX flaws).

Nice! Have you hit any major roadblocks?

**Comment by eeeeeta** [comment]
@rozzin It's at the stage where it works for me, but won't be accepted by upstream due to lack of support for partial MAM backfill (e.g. you must keep dino open for one long period of time while it backfills your whole MAM history, and this process will restart from the beginning if interrupted)

**Comment by resoli** [comment]
MAM in MUC is absolutely fundamental. I discovered this bug today after wasting a lot of time with friends losing messages in our MUCs. Will not recommend Dino anymore till this issue will not be solved.

**Comment by christf** [comment]
I have tried building your fork, @eeeeeta and it does not build for me:

```
xxxxx/dino-eta/qlite/src/column.vala:99.32-99.37: error: `double' is not a supported generic type argument, use `?' to box value types
    public class Real : Column<double> {
```

**Comment by christf** [comment]
... I rebased this code onto master. It builds now.
And with it I cannot join MUC any more.
This is the code: https://github.com/dino/dino/compare/master...christf:mam-all?expand=1

**Comment by christf** [comment]
I have been able to isolate the mam feature and build it in the above branch https://github.com/christf/dino/tree/mam-all

Dino starts and the dialogue is showing that retrieval of messages happens. Test commencing.

**Comment by eeeeeta** [comment]
for what it's worth, I'm no longer interested in working on that MAM feature; as expressed previously, it was very much a hack that upstream indicated they wouldn't accept, and I never ended up putting in the effort to finish it (partially because it worked well enough for my usecases). if anyone else can get anything useful out of that code, that'd be pretty great, though!

**Comment by christf** [comment]
great. Let's have it from upstream then, what the problem actually is.

**Comment by mesonium** [comment]
Fixed by https://github.com/dino/dino/commit/6c6e7e3aa7935ec513b7e5ea9b53a92b741ecf92 ?
