### ISSUE TITLE
Display issue: Massive MUC message duplication of history fetch

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#659]
After starting Dino the first time for 12 hours, lot's of messages came in, especially in the Converstions' MUC. Interestingly, besides the most newest messages all former messages were duplicated many many times from all users

![dino_bug](https://user-images.githubusercontent.com/43318127/69440106-19320d00-0d40-11ea-8818-08751d7f9a72.png)

![dino_bug2](https://user-images.githubusercontent.com/43318127/69440184-3ff04380-0d40-11ea-9f61-f796016c678a.png)

When I search for a string of one of the duplicate messages, it's only found once. That's why I guess it's an issue with displaying the messages.

Edit: *After restarting Dino once again, everything went back to normal.*

Source: AUR-git
System: Manjaro (KDE)

**Comment by ericschdt** [comment]
Something weird happens: If I scroll to the top, three messages can shortly be seen containing files, but then a kind of duplication takes place:

![deepin-screen-recorder_Select area_20191122170207](https://user-images.githubusercontent.com/43318127/69440905-90b46c00-0d41-11ea-9b6a-7fa432dfcbc2.gif)

**Comment by licaon-kter** [comment]
Fixed in HEAD

/close
