### ISSUE TITLE
Install on openSUSE not working

### ISSUE THREAD

**Issue by jnnkB** [dino/dino#668]
I'm not quite sure if this is the right place for this issue.

I tried to install dino via https://software.opensuse.org/download.html?project=network:messaging:xmpp:dino&package=dino on openSUSE Tumbleweed. I think the build might be broken: https://build.opensuse.org/package/show/network:messaging:xmpp:dino/dino

 ```
Problem: nothing provides libicuuc.so.suse64.2()(64bit) needed by dino-0.0~git557.394862d-259.1.x86_64
 Solution 1: do not install dino-0.0~git557.394862d-259.1.x86_64
 Solution 2: break dino-0.0~git557.394862d-259.1.x86_64 by ignoring some of its dependencies
```

**Comment by jubalh** [comment]
394862d is from 18th October. So quite some days old. The openSUSE package builds d194eae, which is the latest commit done on 29th November. So if you post this issues two days ago. I don't know why you use the old version.

The [spec file](https://build.opensuse.org/package/view_file/network:messaging:xmpp:dino/dino/dino.spec?expand=1) also does not mention any libicuuc. I don't see right now where this should come from.

Will check later once I have my dino openSUSE install ready.

**Comment by jubalh** [comment]
The reason is this: the latest commits didn't built for openSUSE Tumbleweed due to warning settings resulting in a build failure.
So there was only the "old" dino binary in OBS. But openSUSE Tumbleweed moved on already and so doesnt provide libicu-suse64_2 anymore but only libicu-suse65_1.

So the old binary was looking for an lib that didn't exist anymore on Tumbleweed. And the new one was never built due to:

```
[   98s] upsert_builder.c: In function 'qlite_upsert_builder_real_prepare':
[   98s] upsert_builder.c:541:1: error: no return statement in function returning non-void [-Werror=return-type]
[   99s] cc1: some warnings being treated as errors
```

**Comment by fiaxh** [comment]
@jnnkB You should be able to install Dino from OBS now - it has been newly built (thanks, darix).

**Comment by jnnkB** [comment]
It worked.
