### ISSUE TITLE
Welcome view isn't displayed after all accounts are deleted

### ISSUE THREAD

**Issue by Ppjet6** [dino/dino#679]
## Steps to reproduce

1. Start new profile
2. Create/configure an account
3. (optional) Deactivate the account
4. Remove the account
5. Restart Dino with the same profile

## What happens

A welcome view is shown in 1 as expected. 3 shows an "all accounts disabled" view, and that also make sense. 4 shows the same as 3, and 5 shows the welcome view again.

## Expected behaviour

It might be better to unify steps 4 and 5?

I am not entirely sure which of the views should be used though. Either there could be just one view because "it's the same state", or they the "all accounts disabled" view could be used after a first account has been created with the rationale being that the users knows and it's fine without a welcome view anymore?

**Comment by fiaxh** [comment]
This is fixed now.
