### ISSUE TITLE
Wrong Window Buttons Position

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#68]
I am using xfce and my window buttons are normally on the left. Dino mixes this up and also this "dino" button and the X and _ is available twice in the UI.

![screenshot_2017-05-07_09-02-33](https://cloud.githubusercontent.com/assets/6888294/25778661/2f06492e-3305-11e7-9580-a361e35b6f2f.png)

**Comment by NicoHood** [comment]
Se #83 also. This is because the user list panel is also split in the window header. Thatswhy each symbol is duplicated.

**Comment by NicoHood** [comment]
As a reference: Polari (also coded in vala but and IRC client) has a simlar layout, and the buttons are displayed correct there:
![screenshot_2017-05-09_12-08-16](https://cloud.githubusercontent.com/assets/6888294/25845965/435e7520-34b0-11e7-9237-14ff2b0a49ad.png)

So it should be technically possible to get this working correct under xfce.

**Comment by fiaxh** [comment]
This should have been fixed in 784319a.
