### ISSUE TITLE
Account appears connected but not receiving messages

### ISSUE THREAD

**Issue by Ppjet6** [dino/dino#682]
Dino version: 9ef4dddfdc40f515be6c780bf9fa089111590a74
glibc: 2.30 (ArchLinux)

## Steps to reproduce

I am testing with a new profile.

- `DBUS_SESSION_BUS_ADDRESS= XDG_DATA_HOME=/some/path G_MESSAGES_DEBUG=all ./dino`
- Add a new account (and connect)
- Remove the account
- Re-add the account

## What happens

Even though the account appears connected (it says "Connected" under the account JID, and the nob is turned on), the icon in the account list is greyed out.

I can send messages with that account, but I can't receive any (apart from MAM). The server considers me offline and in the server logs I see messages going into the archive directly.

I hear no initial presence would be sent which causes this issue?

I also observe new accounts being adding after this point appearing in the same way (greyed icon in the list), maybe unrelated?

The issue resolves itself when I reconnect the account (turning off and on again).

**Comment by ericschdt** [comment]
> Even though the account appears connected (it says "Connected" under the account JID, and the nob is turned on), the icon in the account list is greyed out.

Could it be related to https://github.com/dino/dino/issues/655?

**Comment by mar-v-in** [comment]
Fixed in 1bb75f40d26ad20381a200e09eaa9f519cffe398
