### ISSUE TITLE
Implement XEP-0392: Consistent Color Generation

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#684]
As Conversations [does](https://github.com/siacs/Conversations/blob/94ee4d48c679d228e88f7d40704a5574f7ec9d54/CHANGELOG.md#version-231). 

https://xmpp.org/extensions/xep-0392.html

> Colors provide a valuable visual cue to recognize shapes. Recognition of colors works much faster than recognition of text. Together with the length and overall shape of a piece of text (such as a nickname), a color provides a decent amount of entropy to distinguish a reasonable amount of entities, without having to actually read the text.

> Clients have been using randomly or deterministically chosen colors for users in multi-user situations for a long time already. However, since there has been no standard for how this is implemented, the experience differs across platforms. The goal of this XEP is to provide a uniform, platform-independent, stateless and easy-to-implement way to map arbitrary bytestrings to colors.

> To allow cross-client use, it is important that the color scheme can be adapted to different environments. This specification provides means to adapt colors to different background colors as well as Color Vision Deficiencies.

> In no way is the system presented in this specification a replacement for names. It only serves as an additional visual aid.

**Comment by iNPUTmice** [comment]
I’d like to add that the upcoming Conversations 2.6.2 will copy the '#' avatars for channels. Having the same background color for those channel avatars would boost the recognition for specific channels.

**Comment by fiaxh** [comment]
Dino supports consistent color generation for avatar colors by now.
