### ISSUE TITLE
OMEMO file transfer: won't send correct URI

### ISSUE THREAD

**Issue by suomiph** [dino/dino#697]
I use my own XMPP server, which does not accept https connections to retrieve uploaded files, but it does accepts http connections on port 5280.

When sending a file with OMEMO enabled, dino sends incorrect aesgcm URIs. As a result, other clients cannot retrieve the file content. Instead of the correct URI "aesgcm://hostname.tld/foobar#", dino send "aesgcm://ostname.tld/foobar#" (the first letter of the hostname is missing).

The culprit might be in file dino/plugins/omemo/src/file_transfer/file_encryptor.vala, at the following line:
`aesgcm_link = "aesgcm://" + aesgcm_link.substring(8); // replace https:// by aesgcm://`

When I enable https connections (on port 5281), dino can send files using OMEMO, as expected.

**Comment by sandwm** [comment]
`aesgcm://` URLs must be converted to / from `https://`. Plain HTTP (without TLS transport encryption) is not allowed. Citing the "OMEMO Media sharing" ProtoXEP (i.e. the corresponding not-yet-standard, but as close as we currently get to a standard concerning OMEMO HTTP file upload):

https://xmpp.org/extensions/inbox/omemo-media-sharing.html#aesgcm

> Note: HTTP Upload has transport encryption as a MUST. Non HTTPS URLs MUST not be converted to the aesgcm URL scheme.

Thus I would recommend just using HTTPS for file up-/download.

**Comment by suomiph** [comment]
Indeed, https is a MUST here.

There still is a bug: dino should not send a malformed URI to the other client. Instead, dino should validate the URI (got from the server after having requesting a slot for upload) and should then act accordingly (eg. display an error) if the URI starts with "http://" instead of "https://".
