### ISSUE TITLE
Message styling: ~Strike through~ support

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#702]
It seems that Dino only partly implements `XEP-0393: Message Styling` as \~~Strike through~\~ does not work.

**Comment by ericschdt** [comment]
Since https://github.com/dino/dino/commit/81bde9197bd83ce37baac13924c782c02353a172 `*https://dino.im*` becomes \*[https://dino.im*](https://dino.im*)

**Comment by alyssarosenzweig** [comment]
#626

**Comment by fiaxh** [comment]
#626 was merged and thus ~strike through~ is supported now.
