### ISSUE TITLE
Message styling: Reduce constrast slightly of styling commands

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#704]
like Conversations does:  ![strong_plain1](https://user-images.githubusercontent.com/43318127/71697380-c2443c80-2daf-11ea-90aa-2b270e5db1b9.png)

This helps to visually differentiate between the actual content and unimportant styling elements.

**Comment by Manav-Kumar** [comment]
I want to work upon it, but didn't understand it well. @fiaxh  Can you explain it please.

**Comment by fiaxh** [comment]
@Manav-Kumar You can do text formating using a markdown-style syntax in Dino and other XMPP clients. For example like this: **\*emphasis\*** . The idea is to give the formating characters (like *) less contrast, e.g. make them grey. Like in the picture.

**Comment by Manav-Kumar** [comment]
Ok, but I guess this feature is in yaxim client for android?

**Comment by Manav-Kumar** [comment]
@fiaxh please give me some hint, about it.
