### ISSUE TITLE
Avatar is set locally but other contact can't see it.

### ISSUE THREAD

**Issue by WPFilmmaker** [dino/dino#705]
I have two similar machines both running Lubuntu 18.04 and the same version of dino 0.0~git622.20200102.067184f (and they both have accounts from the same xmpp provider and atm testing is done on the same wifi), I set avatars on both machine but when I send messages only the owner of the account can see his avatar, the other person can't. Any idea?

**Comment by licaon-kter** [comment]
Did you restart Dino or at least dis/re-connect?

**Comment by WPFilmmaker** [comment]
I tried both :/

**Comment by WPFilmmaker** [comment]
works.
