### ISSUE TITLE
Two dino contacts can't send omemo-encryped messages

### ISSUE THREAD

**Issue by WPFilmmaker** [dino/dino#706]
I have two similar machines both running Lubuntu 18.04 and the same version of dino 0.0~git622.20200102.067184f (and they both have accounts from the same xmpp provider and atm testing is done on the same wifi).

Both accounts have automatically accept new keys in settings, yet when I try to message from one to the other, Dino tells me "this contact does not support Omemo encryption"...how is that?

ps: the xmpp server supports omemo

**Comment by licaon-kter** [comment]
But they have their keys already in Contact details?

**Comment by WPFilmmaker** [comment]
I supposed it would happened by default? I didnt see any dialog on how to accept/reject the keys, and navigating in dino I am unable to find how to add the keys :/

Def that message should be more clear (refer only to users using a software without omemo support or who turned it off).

**Comment by licaon-kter** [comment]
Eg. In chat with that contact upper right menu, then OMEMO button, do you have your contacts keys?

**Comment by mar-v-in** [comment]
There is no such thing as "server supports OMEMO". Servers may support PEP and public PEP nodes. PEP is required for OMEMO, but is also supported by probably any server out there that isn't stuck in the 90s. Public PEP nodes are used by Conversations by default but not by Dino (for privacy reasons). If you don't have each other as a contact (mutual subscription), public PEP nodes are required for OMEMO.

**Comment by WPFilmmaker** [comment]
> Eg. In chat with that contact upper right menu, then OMEMO button, do you have your contacts keys?

Ok so I checked and the keys are not there..... so now the dumb question is.....how do I exchange the keys?

Linphone for instance shows a popup the first time you message with a new contact, but here I tried looking everywhere and I can't find, any help?

**Comment by mar-v-in** [comment]
Did you add each others account to the contact list?

**Comment by WPFilmmaker** [comment]
Ok I hadn't...and since I tried doing it without luck... dumb question no2, how do you add others to contact list?

**Comment by fiaxh** [comment]
> how do you add others to contact list?

You go to '+', 'Start Conversation' and click the '+' at the lower end of the contact list. Enter the JID of your contact there and click 'Add'.
There is definitely room for improvement in this flow, we have some ideas for that.

Does OMEMO work after you added the contacts to each other's rosters?

**Comment by WPFilmmaker** [comment]
works:)

**Comment by L911P** [comment]
just got bit by this and had no idea that's how you deal with it

> > how do you add others to contact list?
> 
> You go to '+', 'Start Conversation' and click the '+' at the lower end of the contact list. Enter the JID of your contact there and click 'Add'. There is definitely room for improvement in this flow, we have some ideas for that.
> 
> Does OMEMO work after you added the contacts to each other's rosters?
