### ISSUE TITLE
Notifications body parse as HTML

### ISSUE THREAD

**Issue by alyssarosenzweig** [dino/dino#707]
The notification I get when I receive a message is (incorrectly?) parsed as HTML. So if I receive a message like `</afk>`, it will be received empty. Or if I receive -- as bare escaped text -- `<b>foo</b>` it will show up bold.

This is unexpected behaviour, diverging from how the text is rendered in Dino versus how it appears in the notification.

On the other hand, this could be leveraged to bold the author name in a notification which could be useful.

**Comment by fiaxh** [comment]
I can't reproduce this with GNOME and its notifications. What are you using to display notifications?

**Comment by alyssarosenzweig** [comment]
dunst, I think.

**Comment by HolyStephano** [comment]
I also get incorrect notifications. Using the notification plugin provided by [rootbar](https://hg.sr.ht/~scoopta/rootbar) the only thing it actually gets (which doesn't happen with other notifications) is `username: message` in the body.

**Comment by YtvwlD** [comment]
I also have this problem with Plasma Desktop.
