### ISSUE TITLE
Show default file widget if Pixbuf can't display Image inline

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#713]
For some reason the following image (and another one) are sent but won't be displayed in Dino, it will neither be displayed if it's received from Conversations:

![missing-image](https://user-images.githubusercontent.com/43318127/72211011-9fa2d980-34bb-11ea-9762-65998a918727.png)

![Auf_dem_Wasser_fahren-35c7dcef5e0575e7](https://user-images.githubusercontent.com/43318127/72210801-d0354400-34b8-11ea-887a-a19191c87b3c.jpg)
(MD5: ada907a0e760b3646bedd57419047359)

All other JPEGs or PNGs are fine. Can someone reproduce it?

```
** (dino:25318): WARNING **: 22:25:26.478: file_widget.vala:66: Can't load picture /home/[user]/.local/share/dino/files/6dd9bdf9_72210801-d0354400-34b8-11ea-887a-a19191c87b3c.jpg
```

Source: AUR git
Version: 0.0~git628.20200109.3fc9bda
System: Manjaro KDE (stable)

**Comment by ericschdt** [comment]
If I try to use the file as avatar, I receive the following error:

```
(dino:26972): libdino-WARNING **: 22:49:42.654: avatar_manager.vala:126: Could not read file type of image »/home/user/Downloads/Test.jpg«
```

Dino seems to be the only app on my system and phone having issues with the image.

**Comment by fiaxh** [comment]
The picture is actually a WebP image that was merely wrongly saved with a `.jpg` file extension. Dino (or rather: `GtkPixbuf`) doesn't support WebP by default.

If you want to add WebP to Pixbuf on your system, you can install the `webp-pixbuf-loader` package from [AUR](https://aur.archlinux.org/packages/webp-pixbuf-loader/).
