### ISSUE TITLE
Wrong Profil Picture Colors on reconnect

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#73]
My picture is normally blue (N) and my partner has red/orange with the letter (P). When I reopen the app and old chats are loaded, all message icons are blue. New messages will be red again for me partner.

**Comment by fiaxh** [comment]
The conversation is opened (and messages rendered) before the roster was received. At that point only the JID of a message's sender but not the corresponding contact name is known. The avatar generation prioritizes the name over the JID, resulting in the described behavior.
This will be resolved as soon as roster versioning (#74) is implemented.
