### ISSUE TITLE
Setting for omemo as default

### ISSUE THREAD

**Issue by BlackLotus** [dino/dino#733]
It would be nice to have a setting to enable omemo for chats that support it, to have it enabled by default

**Comment by alyssais** [comment]
I’ve been using #632 for a while and it works perfectly.

**Comment by jpds** [comment]
Conversations also has this as an option.

**Comment by BluebonnetField** [comment]
Hello!

I don't think I need to explain why people want this as an option, I'm sure you've already heard that before :). What do you need to see in a PR for this to happen? There have been several attempts that haven't been merged, so I think it would be helpful to know what the requirements are so we can move this forward. Reading some of the PR comments I've seen two requirements far, please add any others.

 - Don't exclude PGP in a setting for the default encryption
 - The default encryption method should be account specific, not global

**Comment by fiaxh** [comment]
Dino has an per-account setting for OMEMO by default now.
