### ISSUE TITLE
No security warning if conversation partner switches to unencrypted messages

### ISSUE THREAD

**Issue by kirschner** [dino/dino#736]
I had the following experience: I start an OMEMO conversation with another person. Also made sure to verify the fingerprint(s). For a long time everything is fine. Then in one conversation I realised -- rather by chance -- after a while that although I was always sending OMEMO encrypted messages, the other person was answering unencrypted (could be several reasons).

Would it be possible to add a warning if a contact is switching to unencrypted if I already had encrypted chats before with the same contact? Else that could cause serious security issues.

**Comment by fiaxh** [comment]
As of 853dfa2 you'll get a warning for unencrypted messages in an encrypted conversation. It looks like this:
![Screenshot from 2020-04-05 16-23-51](https://user-images.githubusercontent.com/9932450/78501110-8fb53180-775a-11ea-8958-4d7d1963c06d.png)
