### ISSUE TITLE
Support Roster Versioning

### ISSUE THREAD

**Issue by fiaxh** [dino/dino#74]

**Comment by NicoHood** [comment]
After the update all contacts in the "start chat" menu disappeared for me. They are still in the opened chats list.

**Comment by fiaxh** [comment]
@NicoHood Confirmed. 142257a fixes that.

**Comment by NicoHood** [comment]
@fiaxh thanks. Btw I noticed the colors of my contacts changed. Sadly the most active contact has the same color as mine. This commit fixed it again!
