### ISSUE TITLE
[FR] Store account passwords in an encrypted form

### ISSUE THREAD

**Issue by errhammr** [dino/dino#743]
I was wondering how the account password was stored by Dino. As it turns out, the password is stored in plain text in an SQLite3 database, in my case in the file `$HOME/.local/share/dino/dino.db`.
It would be a security improvement to store the password in the GNOME keyring (for GNOME users) or KWallet (for KDE users) or whichever keyring application best integrates into the user's desktop environment.

I'm running Dino version 0.1.0~git0.20200129.fd9db13

This issue is somewhat related to issue #66

**Comment by Elinvention** [comment]
I think this is the same as #102?
