### ISSUE TITLE
Dino fails to load under Manjaro Linux

### ISSUE THREAD

**Issue by solus-hq** [dino/dino#744]
`** (dino:32726): WARNING **: 14:07:03.707: main.vala:25: Fatal error: libsignal-protocol-c.so.2: cannot open shared object file: No such file or directory`

**Comment by ericschdt** [comment]
Weird, because the dependence  should be installed
```
pacman -Si dino
Repository  : community
Name : dino
Version : 0.1.0-2
Denpendencies : glib2  glib-networking  gtk3  gpgme  libgee  libgcrypt  libsignal-protocol-c  libsoup  sqlite  qrencode  libcanberra
Packager : Bruno Pagani <archange@archlinux.org>
Created at : Sa 01 Feb 2020 19:52:01 CET
```

**Comment by solus-hq** [comment]
Well, after installing a package from Community repo everything started working.

Issue resolved.
