### ISSUE TITLE
Encrypt chat history

### ISSUE THREAD

**Issue by TNTBOMBOM** [dino/dino#745]
Im aware of dino doesnt support removing/disabling chat logging, what im requesting here is even when its enabled it should be stored in an encrypted form not in plain text.

**Comment by mar-v-in** [comment]
Rather then duplicating encryption logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).

**Comment by TNTBOMBOM** [comment]
Accessing system (just opening it using keys or even decrypting it) will 
lead to plain text access to dino (or any similar app) that dont encrypt 
user confidential info.



Marvin W:
> Rather then duplicating encryption logic in every application, it makes more sense to use encryption at the lower level. This can be realized by using full disk encryption (luks, md-crypt), file system encryption (fscrypt) or overlay file encryption (ecryptfs, encfs).
>

**Comment by licaon-kter** [comment]
@TNTBOMBOM by whom?

**Comment by TNTBOMBOM** [comment]
Federal Agents , Harmful/Silly friend/family member happened to be 
given/know key access to the system to do certain job but NOT to 
steal/open dino account (or opening dino with his account not with X 
account, which all are stored in plain-text locally at the current 
moment)....

Licaon_Kter:
> @TNTBOMBOM by whom?
>

**Comment by mar-v-in** [comment]
You can use encfs on a per folder basis and using a password independent of your login. Dino stores all information in `~/.local/share/dino/`, so here is a rough sketch on what you could do:
1. Close dino
2. Install encfs
3. `mv ~/.local/share/dino ~/.local/share/dino.old`
4. `encfs ~/.local/share/dino-encrypted ~/.local/share/dino`
5. Confirm two times (`y`) and then select paranoid mode (`p`)
6. Enter an encryption password you want to use for dino data twice
7. `mv ~/.local/share/dino.old/* ~/.local/share/dino`
8. `fusermount -u ~/.local/share/dino`
10. Create a shell script and store it at a proper location:
    ```
    #!/bin/sh
    extfs ~/.local/share/dino-encrypted ~/.local/share/dino
    dino # or path to dino executable
    fusermount -u ~/.local/share/dino
    ```

Whenever you want to start dino, start the shell script. You will be required to enter your password and as soon as dino quits, the encrypted folder will be unmounted. As long as dino is running, everyone who is on your computer (using your account or an administrator account) will be able to access your chat history. There is no feasible way to protect against that. Most importantly, Dino adding any functionality for encryption natively will not protect you from people being able to access your chat history while dino is running.

As this is can be realized perfectly fine without any work in dino, there is nothing we can do. We will not add code that lures people into a false sense of security by hiding the fact that one can access chat history while Dino is running. Closing here.

**Comment by lm2lm2** [comment]
> You can use encfs on a per folder basis and using a password independent of your login. Dino stores all information in `~/.local/share/dino/`, so here is a rough sketch on what you could do:
> 
>     1. Close dino
> 
>     2. Install encfs
> 
>     3. `mv ~/.local/share/dino ~/.local/share/dino.old`
> 
>     4. `encfs ~/.local/share/dino-encrypted ~/.local/share/dino`
> 
>     5. Confirm two times (`y`) and then select paranoid mode (`p`)
> 
>     6. Enter an encryption password you want to use for dino data twice
> 
>     7. `mv ~/.local/share/dino.old/* ~/.local/share/dino`
> 
>     8. `fusermount -u ~/.local/share/dino`
> 
>     9. Create a shell script and store it at a proper location:
>        ```
>        #!/bin/sh
>        extfs ~/.local/share/dino-encrypted ~/.local/share/dino
>        dino # or path to dino executable
>        fusermount -u ~/.local/share/dino
>        ```
> 
> 
> Whenever you want to start dino, start the shell script. You will be required to enter your password and as soon as dino quits, the encrypted folder will be unmounted. As long as dino is running, everyone who is on your computer (using your account or an administrator account) will be able to access your chat history. There is no feasible way to protect against that. Most importantly, Dino adding any functionality for encryption natively will not protect you from people being able to access your chat history while dino is running.
> 
> As this is can be realized perfectly fine without any work in dino, there is nothing we can do. We will not add code that lures people into a false sense of security by hiding the fact that one can access chat history while Dino is running. Closing here.

looks interesting, but i dont imagine doing it while using dino on my postmarket phone.. :)

https://github.com/dino/dino/issues/1005
https://github.com/dino/dino/issues/1754
https://github.com/dino/dino/issues/1754
it's really an interesting (and wished) feature :)
