### ISSUE TITLE
A correct support of OMEMO: 12 byte for initilization vector (IV)

### ISSUE THREAD

**Issue by Neustradamus** [dino/dino#749]
There is a problem in the code:
- https://github.com/xsf/xeps/pull/894

**Comment by mar-v-in** [comment]
Duplicate of #265

**Comment by Neustradamus** [comment]
It is now solved:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 (https://github.com/dino/dino/issues/909)

**Comment by Neustradamus** [comment]
Good news:
- https://github.com/dino/dino/issues/265#issuecomment-726389726
