### ISSUE TITLE
Profil Picture change not shown

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#75]
I added a profil picture but the chats, also the new ones and the setting UI did not change. But my partner saw the new picture. Not even after a restart the picture changed.

**Comment by matthewrfennell** [comment]
I think this has been fixed in meantime. At least for me, on latest master profile pic change works as expected.

https://github.com/dino/dino/assets/148400980/4a1ae1e0-28b0-4c0e-b648-3c77fec4626f
