### ISSUE TITLE
Confirm after Drag and Drop

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#756]
Having a drag and drop feature now is awesome, but it increases the potential to accidentally send a file to a wrong recipient. Therefore it would be convenient if the dropped file would offer two buttons "sent" and "cancel" before it goes actually over the wire.

It could also have a countdown: If the user does not react within N seconds, it's autosent.

**Comment by Echolon** [comment]
I prefer the count down to the dialogue. Still, the dialogue should be opt-in in my opinion

**Comment by trwnh** [comment]
apps like discord and telegram have confirmation dialogs not only as a confirmation, but also as a chance to add a caption
