### ISSUE TITLE
Warn user on first insecure chat message

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#76]
For every new chat session (after each startup) Dino should warn once (or multiple times) with a red marker when a Message was received unencrypted.

I know that on the right side there is no encrypted symbol, but users might overlook this. Another idea is to add a red open lock to show that the messages are NOT encrypted. This is more obvious to me. And users dont get bothered too much.

Sample from pidgin:
![screenshot_2017-05-07_13-32-55](https://cloud.githubusercontent.com/assets/6888294/25780570/c747e2aa-3329-11e7-8a34-3e72bf4ded58.png)

**Comment by d9h02f** [comment]
Those types of warnings are extremely frustrating, but the red open lock seems like a good idea.

**Comment by NicoHood** [comment]
@d9h02f I agree. It would look like this, just with an open lock and no red timestamp.
![IMG](https://cloud.githubusercontent.com/assets/6888294/25784100/46e3996c-3368-11e7-9414-f909bdb4ddac.png)

**Comment by qooob** [comment]
Could someone explain what does this _read lock_ and _exclamation bubble_ mean (exclamation bubble was replaced with double checks (supposedly delivered))? Not sure why it is red. No body disabled encryption ..

![screenshot from 2017-07-21 18-23-09](https://user-images.githubusercontent.com/4426533/28470232-cc5a1c1a-6e41-11e7-8e6c-8fa2cabec440.png)

It's definitely better to add a tooltip, I think. It's confusing.

**Comment by Echolon** [comment]
In general, I think if there are any errors a normal human understandable message should always be shown. Not hidden behind a bubble.

Good cases are: Why was a message not delivered? Why was a message not send?
Those are "critical" issues. I think Dino does that already, however, it should mention always what happened. This enables more interaction and awareness with and to the user.

**Comment by fiaxh** [comment]
Since 853dfa2d6f0d1300b096f0c6a12ca179208f5287 unencrypted messages in encrypted conversations are highlightend with a red open lock.
