### ISSUE TITLE
[FR] Advanced message writing box manipulation

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#77]
I found it useful to hit ESC to delete the current message. However it should be possible to undo this with CTRL+z which currently is not supported. It would be great to have some writing history in the message box, as in browser input field such as this github issue box.

So ESC should delete stuff and CTRL+Z and CTRL+Y should be independent features. This feature request is minor though. But you might want to take it into account for further design decisions.

**Comment by fiaxh** [comment]
CTRL+Z for undo and CTRL+Shift+Z / CTRL+Y for redo work since 500adea.
