### ISSUE TITLE
MUC - Don't parse the members status/vcards on join

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#770]
...else it takes a lot of time to actually open said MUC since all need to be parsed one by one.

Yes, I'm doing this on a RPi1 so it's slow anyway, but I see no reason to wait for them since I don't see the list by default and afaik you can update avatars as you find them later on.

**Comment by fiaxh** [comment]
The MUC server sends the presences of all current MUC participants to the client when it joins. And we can't just "nor parse" what we are being sent.

However, at the time you wrote this issue, Dino would request vcard-avatars once it sees a new avatar hash. This changed in 50c55c7f55aff6622d242bdcf2b58d5f7956f28e. Now avatars are only fetched once they are needed. That should take some load off the MUC joining.
