### ISSUE TITLE
Hovering highlights wrong message

### ISSUE THREAD

**Issue by PilzAdam** [dino/dino#795]
When hovering over the message view, the wrong message is highlighted with the hover effect. It looks like the mouse position is calculated incorrectly; the highlighted message is roughly 150px below the actual mouse position.

This bug is present since 42ae68eb40b27e3ce72fdcd2faec3bcd400ce7b6 (I am not 100 % sure on this, but it was around that time).

**Comment by PilzAdam** [comment]
While playing around a bit I found something interesting: The wrong offset changes depending on the vertical size of the window. If the vertical window size is decreased, the offset gets larger (i.e. a message further below the cursor is highlighted).

**Comment by selurvedu** [comment]
Same here. I've noticed this about a week ago.

**Comment by mar-v-in** [comment]
Do you use Dino with or without client side decorations?

**Comment by selurvedu** [comment]
Yes, I use Dino with CSD.

**Comment by PilzAdam** [comment]
CSD is when additional buttons (e.g. the search button) are in the titlebar? If this is the case, then yes, I do use Dino with CSD.

Also, I run KDE with Kwin (version 5.18.4) as the window manager, if that is relevant.

**Comment by xorbital** [comment]
This is happening to me too, using KDE Plasma as well, it seems to be the vertical position
When the window is at the top of the screen (vertically) the cursor position is almost correct, however moving the window down introduces an even bigger offset equal to the px the window moved downwards. Clicking UI items works, however you can't access the edit button most of the time.

**Comment by selurvedu** [comment]
> This bug is present since [42ae68e](https://github.com/dino/dino/commit/42ae68eb40b27e3ce72fdcd2faec3bcd400ce7b6) (I am not 100 % sure on this, but it was around that time).

I can confirm that the bug is present since that particular commit.

**Comment by selurvedu** [comment]
I just submitted #795 to fix this issue.

**Comment by selurvedu** [comment]
I noticed that the offset is constant as long as I don't move the window, and it becomes bigger when the window is moved to the bottom of the screen. Some debugging indicated that geometry_x and geometry_y were always 0, so the window position was never subtracted on coordinate conversion. `get_geometry` was causing this:

> public int get_origin (out int x, out int y)
> Obtains the position of a window in root window coordinates. 
> (Compare with get_position and get_geometry **which return the position of a window relative to its parent window**.)

Switching to `get_origin` fixed the issue.

**Comment by PilzAdam** [comment]
I can confirm that this is fixed now. Thank you.
