### ISSUE TITLE
Password field shouldn't indicate password length

### ISSUE THREAD

**Issue by guilieb** [dino/dino#797]
Hi, 

When connecting using an account which is protected by a very long password, the window with is too large. As well, for security reasons, this password field should not give any indication on the password length.

![Capture d’écran du 2020-04-06 11-47-39](https://user-images.githubusercontent.com/49333734/78545670-749afe00-77fc-11ea-837d-f22631a2d37e.png)

```
Installed Packages
Name         : dino
Version      : 0.1.0
Release      : 1.fc31
Architecture : x86_64
Size         : 3.8 M
Source       : dino-0.1.0-1.fc31.src.rpm
Repository   : @System
From repo    : updates
Summary      : Modern XMPP ("Jabber") Chat Client using GTK+/Vala
URL          : https://github.com/dino/dino
License      : GPLv3
Description  : A modern XMPP ("Jabber") chat client using GTK+/Vala.
```

**Comment by fiaxh** [comment]
#1017 fixed the window width problem, however I'll keep this issue opened for the second point that you mentioned: the password length indication.

**Comment by eerielili** [comment]
@guilieb I pushed something that might fix it.
Tested it on my side and it works well. The password length is only ever revealed when you update your password by typing/copy pasting. Once you reopen the dialog the obsfucation is back again.

**Comment by fiaxh** [comment]
This is solved as part of https://github.com/dino/dino/commit/21ae42762d8a57da5cb1ec40b46e7510fc3121ad, as the field no longer exists in that form. Now, passwords are only displayed (in dots) when the user enters them.
