### ISSUE TITLE
Add the join on startup option when editing a MUC

### ISSUE THREAD

**Issue by kousu** [dino/dino#798]
I have lots of individuals available on my roster without having active conversations with them, but the same is not true of group chats in Dino, because I can't control the autojoin flag with Dino. Dino does seem to respect the flag, but has no UI for it. I have to use Gajim to toggle it.

I know this option was removed on purpose in https://github.com/dino/dino/issues/47 but I would like it to come back. Maybe it should be hidden on the _initial_ join dialog but I definitely want to be able to toggle it off without fully deleting the bookmark once I'm done.

Here's a way to this could be made coherent and keep Dino's coolitude in effect: make closing a groupchat with the X on the conversations list set `autojoin=no`; make rejoining it set `autojoin=yes`; then, roughly, all clients will be in all the same groupchats (once they've bounced off/online a couple times). This matches how the bigger proprietary messengers work, with all clients syncing the same active chats.

Otherwise, please put the toggle back on the MUC dialog.

**Comment by mar-v-in** [comment]
> make closing a groupchat with the X on the conversations list set autojoin=no; make rejoining it set autojoin=yes

This is exactly how it already works today.

**Comment by kousu** [comment]
wow! amazing!! I did not notice that. Thank you thank you thank you.

On April 10, 2020 12:48:02 PM EDT, Marvin W <notifications@github.com> wrote:
>> make closing a groupchat with the X on the conversations list set
>autojoin=no; make rejoining it set autojoin=yes
>
>This is exactly how it already works.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dino/dino/issues/798#issuecomment-612116224

-- 
kousu
