### ISSUE TITLE
Issue with dino repo

### ISSUE THREAD

**Issue by WPFilmmaker** [dino/dino#799]
I am on lubuntu 18.04 and I am having issues upgrading my system, from terminal I get:
Failed to fetch http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/./amd64/dino_0.1.0~git36.20200328.a6a9248_amd64.deb 404  Not Found [IP: 195.135.221.134 80]

I never had issues before, has something changed?
How can I fix this?

**Comment by ericschdt** [comment]
Try to update your local repo index, the dino version on the opensuse server is newer:
http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/amd64/

**Comment by WPFilmmaker** [comment]
@ericschdt I tried, however I got an error about the update not being secure. 

After using your link, I had added the key following:

wget -nv https://download.opensuse.org/repositories/network:messaging:xmpp:dino/xUbuntu_18.04/Release.key -O Release.key 

Then I thought maybe I should change to:

wget -nv http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/amd64/Release.key -O Release.key

To reflect the new link butt I got:  ERROR 404: Not Found.

Whats the key for the new url?

**Comment by mar-v-in** [comment]
@WPFilmmaker Try the following:
```sh
curl "https://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/Release.key" 2>/dev/null | sudo apt-key add -
```
Then enter your sudo password. Afterwards update as usual:
```sh
sudo apt-get update
sudo apt-get upgrade
```

**Comment by WPFilmmaker** [comment]
@mar-v-in Thanks I tried and got an "OK", so I think key was imported correctly.

However with sudo apt-get update I get:

E: The repository 'http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/amd64  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mar-v-in** [comment]
@WPFilmmaker something is wrong with your `/etc/apt/sources.list.d/network:messaging:xmpp:dino.list` file. Maybe try to recreate it using
```
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/network:/messaging:/xmpp:/dino/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/network:messaging:xmpp:dino.list"
```

**Comment by WPFilmmaker** [comment]
@mar-v-in thanks a lot it works!
