### ISSUE TITLE
Dark theme incorrect displayed

### ISSUE THREAD

**Issue by vanitasvitae** [dino/dino#8]
Hi!
I know, this project is pretty young, but I'm impressed, how usable it already is.
However, I found that there is a visual inconvenience when the system has a dark theme is enabled. The white background layer is not colored dark grey like the rest of the UI:
![bildschirmfoto von 2017-03-13 10-27-17](https://cloud.githubusercontent.com/assets/7854206/23848679/a7b96746-07d8-11e7-8b65-9a4d2f3e6677.png)

Kind regards
vanitasvitae

**Comment by ge0rg** [comment]
Probably related, but with the default theme, some MUC nicknames are rendered yellow-on-white, so they are effectively unreadable.

**Comment by vanitasvitae** [comment]
Great, its fixed :+1:
