### ISSUE TITLE
Cannot set alias

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#80]
I set some alias on pidgin for my other chat users. I've added them not as contacts to dino. But I cannot change the alias. I expected this option in 2 menus:
* Rightclick the contact and open details
* In the "Start Chat" Menu. It seems the edit button there is completely broken.

**Comment by fiaxh** [comment]
The edit button was broken as in not implemented. It's removed now, however. A contact's name can be set in the ConversationDetails dialog (26973c8).

**Comment by NicoHood** [comment]
Works now.
I noticed that if you click outside the textbox it still has the focus. It think that is not intended. Also if you change one of the options below they are a bit glitchy from the UI and left aligned after change.
