### ISSUE TITLE
More options to interact with shared images

### ISSUE THREAD

**Issue by Shungy** [dino/dino#803]
When someone shares an image, you can hover on it and click on the button on the overlay to open with an external program. I suggest extra options to “save as” and “copy link” be added. These can be items in right click menu like other links, or as buttons beside the existing button in the overlay.

**Comment by Echolon** [comment]
Rel. 
#556 C**hat: Delete inline image locally** 
#716 **Add a lightweight image viewer like a lightbox in the browser**

**Comment by fiaxh** [comment]
An option to "Save as" has been added. For "copy link" there is #322.
