### ISSUE TITLE
FTBFS with SignalProtocol 2.3.3

### ISSUE THREAD

**Issue by thiagomacieira** [dino/dino#808]
```
CMake Error at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find SignalProtocol: Found unsuitable version "2.3.3", but
  required is exact version "2.3.2" (found
  /usr/lib64/libsignal-protocol-c.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:443 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSignalProtocol.cmake:9 (find_package_handle_standard_args)
  plugins/signal-protocol/CMakeLists.txt:35 (find_package)
-- Configuring incomplete, errors occurred!
```

Please remove the maximum version requirement. It's bad practice to have those.

**Comment by mar-v-in** [comment]
I removed the exact version requirement in fbd70ceaac5ebbddfa21a580c61165bf5b861303.

> It's bad practice to have those.

I totally agree, however we deemed this necessary as libsignal-protocol-c developers considered it a non-issue in the past to do breaking changes in patch version change (from 2.3.1 to 2.3.2, and that specific change also only caused a compiler warning, leading to a number of users creating broken builds that had memory corruption issues and therefor crashed on random occasions). I verified that 2.3.3 does not include any such breaking changes.

**Comment by thiagomacieira** [comment]
Thank you, I'll backport that patch to our release. The problem is that libsignal-protocol-c was upgraded and the dino package wasn't. We only caught the problem after some weeks, when the package was rebuilt. So if libsignal-protocol-c broke anything in 2.3.3, the application was broken for that time.

Should we disable the plugin instead, if the underlying library cannot be expected to follow regular practices of releases?

**Comment by jubalh** [comment]
Thats why some distros trigger a rebuilt once a dependency changes ;)

**Comment by fiaxh** [comment]
> Should we disable the plugin instead, if the underlying library cannot be expected to follow regular practices of releases?

@thiagomacieira You mean disable the OMEMO plugin? No, please absolutely don't do that. It's not a plugin because we consider it to be optional, it's merely a code design choice. OMEMO is a very important functionality and it would be problematic if there was a "Dino" in distribution repositories without that functionality.
