### ISSUE TITLE
Remove visible stuff from formatted text. Improve formatting.

### ISSUE THREAD

**Issue by llathasa-veleth** [dino/dino#827]
Hi! There is a couple of problems while formatting messages (bold, italic, etc.) - I can see all this stuff like `*`, `_`, `~~`, `>`,  ...

![Screenshot_20200425_025030](https://user-images.githubusercontent.com/61933599/80265216-89eaa600-869f-11ea-87d2-4a5ebc09db3a.png)

As you can see, all these chars are visible, which is quite annoying. BTW, `> quote` thing was working before the last update. Multiple formatting features do not work like such **~~*`text`*~~**.

\*\*text\*\* should be bold, \*italic\*, \_\_underlined\_\_

Also, I suggest to add the **||spoiler||** feature if it's not too hard. And, may be, some day, syntax highlight feature for code blocks likewise in discord and Markdown.

**Comment by mar-v-in** [comment]
Dino and other XMPP clients do not use Markdown. Instead we are using the [Message Styling](https://xmpp.org/extensions/xep-0393.html) specification, which is similar but different. By that specification it is also recommended to display the formatting characters.

Dino does not have special handling for quotes yet. It is also known that certain combinations of styling are not properly handled just yet.

**Comment by llathasa-veleth** [comment]
Thank you for the answer and clarification! Should I close this issue?

**Comment by licaon-kter** [comment]
Related: https://github.com/siacs/Conversations/issues/2689

**Comment by fiaxh** [comment]
The proper solution for "formatting without styling characters" would probably be to implement [XEP-0394 (Message Markup)](https://xmpp.org/extensions/xep-0394.html), however in it's current state it lacks some features that would be required for a reasonable user experience.

Until XEP-0394 becomes usable, #704 might help.

> Multiple formatting features do not work like such text.

There's already an issue for this: #703.

> Also, I suggest to add the ||spoiler|| feature

Using `|x|` or `||x||` for spoilers is not standardized and I foresee clashes with mathematical notions (absolute value, vector norm).

Feel free to open dedicated issues for quote displaying and syntax highlighting.
