### ISSUE TITLE
nothing provides libcrypto-vala.so in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by ITwrx** [dino/dino#832]
when trying to install dino-plugin-omemo i get the message in the title of this issue. What upstream software should provide this dependency?
thanks

**Comment by fiaxh** [comment]
Where did you get a package `dino-plugin-omemo` from? openSUSE Tumbleweed does not seem to package Dino officially, does it?

**Comment by ITwrx** [comment]
@fiaxh i added the network repo with `zypper addrepo -f https://download.opensuse.org/repositories/network/openSUSE_Tumbleweed/network.repo`, then dino and dino-plugin-omemo were available, IIRC

**Comment by jubalh** [comment]
I didn't finish the `network/dino` package yet. I don't remember the state right now, but it's not submitted to Factory for a reason. I have it on my todo to take care about it so that additionally to the git version in`network:messaging:xmpp:dino/dino` we also have the stable one in `network/dino`.

**Comment by ITwrx** [comment]
@jubalh that's cool. no rush. i was just wondering what upstream software would provide libcrypto-vala in case i want to make my own obs package for it.

**Comment by jubalh** [comment]
I see. I don't know (yet), actually I totally forgot about the state I left `network/dino` in, I hope I can soon finish working on it.

**Comment by ITwrx** [comment]
ok, thanks

**Comment by mar-v-in** [comment]
[libcrypto-vala](https://github.com/dino/dino/tree/master/plugins/crypto-vala) is part of the dino source code. The omemo and openpgp plugins link it statically during the default build process, so no libcrypto-vala.so is supposed to be built.

**Comment by fiaxh** [comment]
Closing this since the question was answered and since it's not an issue with Dino.
