### ISSUE TITLE
Make it easier to tell which OpenPGP keys are expired

### ISSUE THREAD

**Issue by Sylvhem** [dino/dino#835]
OpenPGP users often keep expired keys on their machines, as a way to be able to read files that were previously encrypted with them (such as old e-mails, etc.). Currently, Dino doesn't display the expiration date of the available keys, nor does it provide any visual clue about which keys are expired.
If it's possible to tell apart expired keys by looking at their fingerprint (something that user should always be doing), displaying the expiration date of they key alongside the identity and fingerprint would make it easier to find a specific key and should reduce the possibility to select the wrong-one by mistake in the drop-down menu.

**Comment by fiaxh** [comment]
We want to treat expired keys similarly to revoked ones and not display them at all. This will be tracked in #91.
