### ISSUE TITLE
UX: use GtkSwitch instead of GtkCheckButton for settings dialog

### ISSUE THREAD

**Issue by MicroJoe** [dino/dino#840]
The settings dialog currently looks like this:

![Screenshot 2020-05-09 18-05-03](https://user-images.githubusercontent.com/989521/81478759-a3532c80-921f-11ea-86a0-9a5085dff8a0.png)

It has no "save" button, so I assume the settings are saved upon checkbox trigger.

I think it is an UX mistake to use checkboxes for an action that takes effect immediately. Rationale can easily be found on the web, here is a quotation from [one of the first results](https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8) on my search engine for "switch vs checkbox ux":

> Tapping a toggle switch is a two-step action: selection and execution, whereas checkbox is just selection of an option and **its execution usually requires another control**.

Since there is no validation control, I think GtkSwitch would be a better fit in this window. Below is an example of the GNOME settings panel which shows how GtkSwitch can be integrated with a label.

![Screenshot 2020-05-09 18-09-33](https://user-images.githubusercontent.com/989521/81478877-502da980-9220-11ea-889e-5b4636632197.png)

While not being familiar enough with Gtk to propose this change, I think the modification has to be done in `dino/main/src/ui/settings_dialog.vala ` but would be more elaborated that just changing the `CheckButton` to `Switch` as the labels for the buttons would have to be generated also.

**Comment by fiaxh** [comment]
This was done by #1361.
