### ISSUE TITLE
Encryption by default

### ISSUE THREAD

**Issue by tg-x** [dino/dino#844]
Encryption should be enabled by default.
Currently one has to manually enable it for every conversation.

**Comment by dvn0** [comment]
+1

Particularly enabling omemo by default. This will help prevent accidentally sending messages unencrypted. (Which I've done several times with Dino)

**Comment by licaon-kter** [comment]
No need for a Dino default, just have a toggle in settings so users can do this, globally or per account.

**Comment by dvn0** [comment]
If it's not default, then lots of people won't use it or notice the option.

I agree there should be a toggle in the settings for the default behavior, but that should be set to omemo to begin with.

**Comment by licaon-kter** [comment]
Why not PGP then? Why not Unencrypted?

**Comment by dvn0** [comment]
> Why not PGP then?

PGP requires account configuration before it will work. OMEMO does not.

>  Why not Unencrypted?

From my PR: "This helps to prevent the unintentional sending of unencrypted messages,
as well as promotes the usage of e2e encryption."

**Comment by stevenroose** [comment]
Somehow it would be cool if the "I want to use OMEMO by default" setting could be persisted somewhere server-side. Perhaps having an OMEMO key node should be sufficient for a client to think the user wants to use OMEMO.

**Comment by kalkin** [comment]
@stevenroose 

> Somehow it would be cool if the "I want to use OMEMO by default" setting could be persisted somewhere server-side.

Bad idea you do not want to trust the server.

**Comment by stevenroose** [comment]
Well some people do trust their server to a big extent. I host the server for my social circles myself and while of course my friends don't want me to be able to read their conversations, they do trust me to not actively try mess up their privacy. I think that's a perfectly valid situation.

**Comment by mar-v-in** [comment]
The information could be signed using your device key, so servers can't manipulate it. However existence of an OMEMO device list is not a good indicator for if OMEMO should be used, because that only indicates that one used at least one OMEMO capable client in the past. And the signed message is only worth something if you trust that device (i.e. verified it).

**Comment by gsantner** [comment]
I agree, client side, enable encryption by default on, good idea.

However the "manage client side omemo configuration on server" gives me worries. I dont think storing client settings on server, and restoring them is and should be part of xmpp or dino.

**Comment by Echolon** [comment]
rel. #733

**Comment by Raviu56** [comment]
Should simply have an option on settings "enable omemo by default" with sub-option "enforce omemo for all conversations" so it cannot be disabled by mistake

**Comment by selurvedu** [comment]
A person a message regarding this issue in [chat@dino.im](xmpp:chat@dino.im?join) and I thought it may be worth to forward it here.

> (2021-09-03T22:04:09Z) purplebeetroot: I would like to also remind, that the description at dino's web page is at best miss leading and at worst a lie. Please prefer educational messages over miss leading messages, even so the later might sell better.
I know that this was already reported a while ago, but maybe rethinking it might change.
> 
> "Dino is secure by default: Your chats never leave your computer unencrypted...only you and your chat partners can read your messages, but not your server administrator or anyone else."
> 
> This is just not true. Please either fix software or web page.

**Comment by xekon** [comment]
Is this the right place to ask that a setting be added to the options where you pick your preferred encryption method?

**Comment by ltGuillaume** [comment]
Why wouldn't Dino just try to use OMEMO by default and fall back to unencrypted if no OMEMO keys are availale (with a warning)? Let's be honest, times have changed: if people do _not_ want to use E2EE, or want to use PGP, _that's_ the conscious/active choice, while using OMEMO is the default. Dino is attracting a lot of new users and they get needlessly confused by having to enable E2EE for _every single new conversation_, and frankly, they're right, it _is_ confusing for me as well. There doesn't need to be setting, there needs to be a change.

**Comment by selurvedu** [comment]
@ltGuillaume FYI, the keys are generated by default and there is no way to disable that except for removing the OMEMO plugin. The only reason OMEMO may be unavailable in Dino is if your server does not support it (i.e. PEP is not available). So your point is even more valid.

**Comment by licaon-kter** [comment]
Hope at least that having a conversation with OMEMO (from other clients) would trigger the OMEMO toggle in Dino, for those chats.

Yes, having keys might not mean anything, but when I open the same chat in Dino, which sees and decrypts the messages, maybe...it's a sign. :)

**Comment by tuxayo** [comment]
> No need for a Dino default, just have a toggle in settings so users can do this, globally or per account.

> Should simply have an option on settings "enable omemo by default" with sub-option "enforce omemo for all conversations" so it cannot be disabled by mistake

If there is no big downside it should be by enabled by default. To help having E2EE adopted as largely as possible, people shouldn't need to know there is something to enable.

**Comment by fiaxh** [comment]
OMEMO by default was added as an option as part of https://github.com/dino/dino/commit/21ae42762d8a57da5cb1ec40b46e7510fc3121ad.
