### ISSUE TITLE
Migrating key material

### ISSUE THREAD

**Issue by HulaHoop0** [dino/dino#850]
Hi. I am looking to document how a user can preserve their OMEMO keys by backing them up to their personal storage and restoring them in case of a reinstall. Where are the keys stored?

**Comment by anubister** [comment]
Hello, on Linux it looks like the keys are in ~/.local/share/dino/omemo.db (a SQLite DB).

**Comment by mar-v-in** [comment]
In addition to the fingerprint displayed in clients, OMEMO uses session/ephemeral keys: as soon as you write with someone, these keys are created and they are replaced with new ones after every message exchange

Without the latest session keys, you can't decrypt incoming messages. Thus when importing session keys from an older backup, you are likely going to have issues if the keys were used in between.

Both types of keys are stored in the `~/.local/share/dino/omemo.db` as @anubister pointed out. As long as you only backup them while Dino is not running and do not start Dino from the same database twice, there is no issue.
