### ISSUE TITLE
aesgcm-scheme OMEMO Media Sharing IV Length

### ISSUE THREAD

**Issue by aw32** [dino/dino#865]
The proposed standard describes a IV length of 12 bytes / 24 hex characters.
It seems that the original proposition was changed from 16 to 12 bytes.
At the moment Dino still uses a 16 byte IV for encryption.

https://github.com/xsf/xeps/blob/0f41853a55125dd0057059a73108dac2e0862144/inbox/omemo-media-sharing.xml
https://xmpp.org/extensions/inbox/omemo-media-sharing.html

**Comment by aw32** [comment]
Thanks, I did not find the old one.

**Comment by Neustradamus** [comment]
Thanks @aw32 about the recall :)
I have done a PR: https://github.com/dino/dino/pull/819.

**Comment by Neustradamus** [comment]
Any news on it?

**Comment by Neustradamus** [comment]
@aw32: It is solved:
- https://github.com/dino/dino/commit/cd5b639a826ccafe5741a51f10cc8ca76ebfdd14
- https://github.com/dino/dino/commit/1956f63179c4f3ac3232cc4a2da8046565fad2a1 (https://github.com/dino/dino/issues/909)

**Comment by Neustradamus** [comment]
Good news:
- https://github.com/dino/dino/issues/265#issuecomment-726389726
