### ISSUE TITLE
Relative dates not updated

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dino/dino#868]
A conversation has been open for a few (two?) days. Now, there are two "today" marks, one referring to today (Wednesday), the other one to Tuesday (and "yesterday" is referring to Monday, i.e., the day before yesterday).

![image](https://user-images.githubusercontent.com/3014737/84856899-21e58a00-b068-11ea-98da-a5bbd36013ff.png)

It seems that relative dates are only updated when reactivating the conversation. Switching to another conversation and back fixes the display issue. There probably should be a timer event set to update the relative dates of the current conversation at midnight.

(While the end user result may be similar to the one in #310, I think the cause is different, as there it is described for a freshly started Dino.)

**Comment by alyssarosenzweig** [comment]
I can reproduce this.
