### ISSUE TITLE
OMEMO encrypted messages sent from Psi Plus XMPP Client

### ISSUE THREAD

**Issue by ec1warc1** [dino/dino#869]
When I send messages from Psi Plus XMPP Client (windows version) using OMEMO encryption, the messages are not displayed in the Dino IM chat window. Only messages sent in plain text are displayed.
Messages sent from Psi Plus to Gajim are displayed in Gajim and visa versa.
Messages sent from Gajim to Dino are displayed in Dino and visa versa.
The problem _could_ be with Psi Plus (windows version), but I doubt it. 
I don't see an xml console for Dino. I also don't see any way to display what version of Dino is installed.

**Comment by licaon-kter** [comment]
Use OBS or your distro repo to update to 0.1.0 first (if you don't see the about dialogue I guess you have older) and retry.

**Comment by licaon-kter** [comment]
FYI: https://github.com/dino/dino/wiki/Debugging

**Comment by fiaxh** [comment]
I just tested this with Psi+ 1.4.654. OMEMO encrypted messages worked fine in both directions - from and to Dino.

Your Dino version is displayed in the "About Dino" dialog. Since you you don't seem to have that, that means you're not using the release version. As licaon-kter already suggested, you should grab Dino 0.1 and try again.

**Comment by Neustradamus** [comment]
@ec1warc1: It is now solved with Dino 0.2.0?
- https://github.com/dino/dino/issues/265#issuecomment-726389726

**Comment by Neustradamus** [comment]
@ec1warc1: It has solved with the latest current Psi+ build?

**Comment by fiaxh** [comment]
I'll close this issue since it seems you were using a pre-release version of Dino. If you encounter this issue with a recent Dino version, please leave a message and I'll reopen the issue.
