### ISSUE TITLE
Error in encryption

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#87]
See this screenshot:
![screenshot_2017-05-07_21-00-54](https://cloud.githubusercontent.com/assets/6888294/25784100/46e3996c-3368-11e7-9414-f909bdb4ddac.png)

I dont know why this happens. A Moveover gives no additional information, which I would normally expect. Checking the encryption settings OMEMO is checked even though its not available (its gray, not black). I dont know what went wrong with my contact partner.

**Comment by NicoHood** [comment]
I created my account with pidgin + lurch (OMEMO plugin). To enable OMEMO encryption for a new contact I need to start pidgin and hit "authorize" for every new contact. Then I can use OMEMO for my partner. I do not know why this is not possible with Dino, even tho those people are in my friend list.

ref #36

**Comment by d9h02f** [comment]
I'd guess the key starting with 9AE is the one used by your Pidgin client. Every OMEMO instance has its own key.

**Comment by NicoHood** [comment]
Yes and this confuses Dino I think. My partner who has a conversations and a dino account cannot communicate OMEMO encrypted with me from the dino site. I can write him encrypted though. No Idea why this happens.

**Comment by minils** [comment]
I had the same problem.
I couldn't send encrypted messages to a contact using the 2 clients conversations and dino. Receiving encrypted messages was possible.
It resolved when both clients of this contact were online. OMEMO is selectable and encrypted messages can be sent again.

**Comment by wuzzap** [comment]
Same issue. minils solution didnt work for me. Would like to help if i can give needed Informations.

**Comment by fiaxh** [comment]
Dino's OMEMO implementation has improved and changed a lot since this issue was opened. Thus, I will close the issue. If anyone still experiences problems, please open a new issue.

**Comment by adrianheine** [comment]
I can't get lurch 0.6.8. or 0.7 and dino 0.2.1+git20210824.93e2e0d-1 to talk with each other.

**Comment by licaon-kter** [comment]
Ssme debug logs?  See Wiki for procedure
