### ISSUE TITLE
EmojiOne Emojis

### ISSUE THREAD

**Issue by jfkimmes** [dino/dino#88]
I would like to suggest to use EmojiOne 2.3 as the default emojis:  
https://www.emojione.com/emoji/v2

**Comment by albjeremias** [comment]
yeah emoji is important!! \o/
hmm is there any xmpp standard for custom emoji?

**Comment by d9h20f** [comment]
@albjeremias They're just Unicode symbols, what @jfkimmes is suggesting is to use EmojiOne as the default images to represent those symbols.

**Comment by albjeremias** [comment]
ah ok... should i open a new issue for the possibility of custom emojis? is there a xmpp standard for this maybe? on mastodon is great \o/

**Comment by d9h20f** [comment]
@albjeremias Again, they're just Unicode symbols. No XMPP standard is needed, because Unicode already is a standard.

**Comment by albjeremias** [comment]
@d9h20f i mean this: https://developer.pidgin.im/ticket/5627

**Comment by benrob0329** [comment]
@d9h20f s/he means *custom* emoji, as in nonstandard, non Unicode emoticons that can be used like emoji. Technically XHTML could be used to simply embed custom emoji, but that is a different request.

**Comment by d9h20f** [comment]
Ah, I misunderstood. @albjeremias, you can create a new issue for that so other people interested in custom emoticons can more easily find it.

**Comment by mar-v-in** [comment]
Dino supports Unicode emojis for sending and receiving. The font used to display emojis is decided by the operating system and shouldn't be overwritten by Dino. If you can't see emojis in your installation, it's probably caused by a system configuration issue, maybe consult your distribution wiki for help to correctly setup emoji fonts.
