### ISSUE TITLE
Segmentation fault causes crash

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#884]
```
(dino:1958464): libdino-DEBUG: 10:57:11.114: connection_manager.vala:267: NetworkMonitor: Network reported online

(dino:1958464): xmpp-vala-CRITICAL **: 10:57:11.216: xmpp_xmpp_stream_get_module: assertion 'self != NULL' failed

(dino:1958464): xmpp-vala-CRITICAL **: 10:57:11.216: xmpp_xmpp_stream_get_flag: assertion 'self != NULL' failed

(dino:1958464): xmpp-vala-CRITICAL **: 10:57:11.216: xmpp_xep_service_discovery_flag_has_entity_feature: assertion 'self != NULL' failed
[1]    1958464 segmentation fault (core dumped)  env G_MESSAGES_DEBUG=libdino,OMEMO ~/software/dino/build/dino
```

Might have been related to me turning off network or so.

**Comment by fiaxh** [comment]
I have a fix for this locally. It's part of a larger change which I'm currently testing and improving. I'll close this issue once I pushed my changes.

That being said, if you were the first one to report the issue, those logs wouldn't have helped me much to locate the issue. I'd need a [stack trace](https://github.com/dino/dino/wiki/Debugging#stack-trace) for that (can also be retrospectively obtained from a core dump). Just as a note for next time :slightly_smiling_face:

**Comment by fiaxh** [comment]
e159fd2492c28c1ef4ab64828ca0e8c2de877b41 should fix this.
