### ISSUE TITLE
offering keybindings in dino

### ISSUE THREAD

**Issue by wmey** [dino/dino#885]
Right now Dino doesn't provide keybindings, so I'd love to see keybindings as the ability to cycle through conversations using my keyboard, either using ctrl + tab for this or j / k (maybe it'd be cool to make this configurable?). I think this is a pretty common feature for messengers to have, and I would argue that this can be seen as an expected behavior pattern.

I'd say that this issue is related to #876 and #876, as both integrate into the scope of having some sort of keybinding functionality.

I can offer my help to integrate this functionality in dino, but would like to have a discussion on this first if this is generally a feature users would like to have. 

I would propose to integrate it by setting the default bindings users would expect to as other programs they use commonly introduced them (middle-click/ctrl+w to close conversations). Also making them customizable (add a separate menu to do so to avoid clutter in preferences) would be a good idea, so users would be able to to adjust them to their needs (that can vary for different keyboard layouts/usage scenarios).

**Comment by licaon-kter** [comment]
CTRL-Tab works

**Comment by wmey** [comment]
It doesn't work for me at least, have tried it in dino build from source as well as with the version offered by the apt repository in debian. The only functionality ctrl-tab has is in the text input field of a channel to cycle through usernames to directly mention. Maybe the reason it works for you is global behaviour by your desktop environment?

**Comment by licaon-kter** [comment]
i3 here, so nothing like that defined.

What's your DE/WM?

**Comment by licaon-kter** [comment]
@wmey What does Menu -> Keyboard shortcuts dialog show for you?

**Comment by fiaxh** [comment]
> The only functionality ctrl-tab has is in the text input field of a channel to cycle through usernames to directly mention.

Could it be that you are mixing up CTRL and Shift? Cycling through usernames should be available under Shift+Tab. Cycling through conversations should be under CTRL+Tab.

**Comment by fiaxh** [comment]
Closing this as Dino has a shortcut for cycling through conversations, as mentioned above.
