### ISSUE TITLE
Doesn't work on Tails

### ISSUE THREAD

**Issue by waweic** [dino/dino#889]
Terminal says: `CONNECTION LOST?` while logging in, Log-In-Window says: `Could not connect to <my domain>`
I would probably need to configure sockets before logging in

**Comment by licaon-kter** [comment]
Your domain has a valid cert (not selfsigned), right?

Can you try with other domains?

**Comment by waweic** [comment]
I did try with all the other servers in the drop-down-list, neither of them worked

**Comment by fiaxh** [comment]
Did you start Dino from the console with
```bash
proxychains4 dino
````
?

**Comment by waweic** [comment]
I currently do not have a working x86_64 device at hand, but I will try as soon as I have the possibility to do so. Although I have a faint memory of having tried it with proxychains4, which also didn't work

**Comment by waweic** [comment]
So I have now tried it with proxychains4. It doesn't change the situation

**Comment by licaon-kter** [comment]
On a normal non-Tails system proxychains4 works fine, fyi.

**Comment by fiaxh** [comment]
Which Dino version are you using? If you're using the one you get in Tails with `apt install dino-im`, you get a pre-release version from 2018, which didn't work with Tails yet. You can for example use Dino 0.2 from Debian backports, which should work.

**Comment by fiaxh** [comment]
Closing as there was never an answer and it's likely outdated.
