### ISSUE TITLE
Click on Gnome notification doesn't change virtual desktop

### ISSUE THREAD

**Issue by jfkimmes** [dino/dino#89]
When I have multiple virtual desktops in gnome, and I am currently working in a different one that the dino application is open in, and I click on the notification, I expect to switch to the application on the other desktop.

**Comment by mar-v-in** [comment]
I think this shouldn't be an issue with current GNOME versions. And even if it is, that would be an issue of GNOME. If it still happens for you, please report upstream at https://gitlab.gnome.org/GNOME/gnome-shell/issues
