### ISSUE TITLE
window makes text gray as if unfocused when taking a screenshot with slurp+grim

### ISSUE THREAD

**Issue by Soundtoxin** [dino/dino#893]
This makes the thing you're trying to screenshot different than it looked a second ago. Any chance this behavior can be disabled? I can't say I'm a fan of the faded text anyway

**Comment by licaon-kter** [comment]
Which WM/DE? Which GTK version? Etc

**Comment by Soundtoxin** [comment]
What does the theme have to do with the window fading when inactive? That's clearly a deliberate feature, I just want to disable it so the window looks the same whether it's focused or not.
Using Sway, Adwaita-dark, can't easily check my gtk version (sorry). Have tried the non-dark Adwaita and it functions the same. I don't think it's a matter of themes. Just to confirm, if you have dino open and then you change windows (with dino still visible), doesn't it become "faded" for you as well? I am almost positive this is just a feature that I don't want that is causing problems. When slurp launches for me to make a selection to screenshot, it's being counted as changing windows, and so it becomes grayed out, and then if I was screenshotting part of dino it looks grayed out. The only workaround I found is to take a delayed screenshot where I select the area, start a timer, and then it screenshots that spot, giving me time to make the window active again so the colors look normal.

**Comment by fiaxh** [comment]
This graying-out-if-the-window-is-in-background behavior is a GTK feature, it's called backdrop. We can't sensibly change anything about it. GTK doesn't want to make it opt-out [[link]](https://gitlab.gnome.org/GNOME/gtk/-/issues/777). However, this is a theme-thing, so it would theoretically be possible to have a theme that does not make use of this feature.
As a side-note, my screenshot tool on GNOME takes the pictures in the "normal" window state, so some screenshot tools are able to handle this.
