### ISSUE TITLE
Some kind of partially disconnected state

### ISSUE THREAD

**Issue by stevenroose** [dino/dino#896]
I don't have the most stable internet where I'm staying these last weeks, and I find myself quite often in some sort of partially disconnected state. This is how some of the chats look:

![screenshot-2020-08-23-14-02-34](https://user-images.githubusercontent.com/853468/90977825-f17b0a00-e548-11ea-90b0-bd8f2703438b.png)

I have print-xmpp=all, so I started experimenting a little bit. Here are some of my findings.

- when I open a 121 conversation, no stanzas are exchanged.
- when I start typing in a gray conversation, no stanzas are exchanged.
- when I open a private group chat, some OMEMO stanzas are exchanged and the red warning "the contact does not support OMEMO encryption" is shown (while the chat usually does support OMEMO) I get this stanza
```xml
 [steven@<redacted> 0x558c37c3a5c0 2020-08-23T14:09:29+0200]
<iq lang='en' to='steven@<redacted>/dino.93a626a6' from='<redacted>@muc.<redacted>' type='error' id='a6f0c992-3374-4744-8e4a-725950ff15e4'>
  <pubsub xmlns='http://jabber.org/protocol/pubsub'>
    <items node='eu.siacs.conversations.axolotl.devicelist' />
  </pubsub>
  <error code='503' type='cancel'>
    <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' />
    <text lang='en' xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>
      The feature requested is not supported by the conference
    </text>
  </error>
</iq>
```
- when I open a gray public channel, no stanzas are exchanged consistently, but I did notice this one some times:
```xml
 IN [steven@<redacted> 0x558c37c3a5c0 2020-08-23T14:07:25+0200]
<iq to='steven@<redacted>/dino.93a626a6' from='chat@dino.im/IKEAMeatballs' type='error' id='82223d1a-f4ce-4135-8d8b-d3ef8bea469f'>
  <error type='cancel'>
    <not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' />
    <text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>
      You are not currently connected to this chat
    </text>
  </error>
</iq>
```
- when I type in a gray public channel, no stanzas are exchanged

The only way for me to fix this is to restart Dino.

It might be caused/reproducable by restarting the NetworkManager service on a Linux machine using NetworkManager for networking.

**Comment by eeeeeta** [comment]
@licaon-kter unclear --- from what I've seen so far, yes

**Comment by github-deimos** [comment]
I have a similar issue on unstable internet connections. Once disconnected, even for a few seconds, dino will never resume. Here are debug logs:
```
(dino:12666): xmpp-vala-DEBUG: 10:05:33.345: stream_connect.vala:37: Got no xmpps-client DNS records for chat.example.com: No DNS record of the requested type for “_xmpps-client._tcp.chat.example.com”
(dino:12666): xmpp-vala-DEBUG: 10:05:33.345: starttls_xmpp_stream.vala:19: Connecting to chat.example.com:5222 (starttls)
(dino:12666): GLib-GIO-DEBUG: 10:05:33.345: GSocketClient: Starting new address enumeration
(dino:12666): pxbackend-DEBUG: 10:05:33.346: px_manager_get_proxies_sync: url=none://chat.example.com:5222 online=1
(dino:12666): pxbackend-DEBUG: 10:05:33.346: px_manager_get_proxies_sync: Proxy[0] = direct://
(dino:12666): GLib-GIO-DEBUG: 10:05:33.347: GSocketClient: Address enumeration succeeded
(dino:12666): GLib-GIO-DEBUG: 10:05:33.347: GSocketClient: Starting TCP connection attempt
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Connection attempt failed: Connection refused
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Starting new address enumeration
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Address enumeration succeeded
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Starting TCP connection attempt
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: TCP connection successful
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: Starting application layer connection
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: Connection successful!
(dino:12666): libdino-DEBUG: 10:05:42.980: connection_manager.vala:185: [hello@chat.example.com] (Maybe) Establishing a new connection
(dino:12666): libdino-DEBUG: 10:05:42.980: connection_manager.vala:193: [hello@chat.example.com] Connection attempt already in progress. Directly retry if it fails.

(dino:12666): xmpp-vala-CRITICAL **: 10:06:54.983: file /usr/src/debug/dino/dino-0.4.2/xmpp-vala/src/core/stanza_reader.vala: line 42: uncaught error: TLS connection closed unexpectedly (g-tls-error-quark, 6)
```

Despite the log messages, it never retries. I never see tcp connection attempt (via tcpdump).

I've tracked it down to an interaction with glib networking.  Possibly this logic needs to be more aggressive in retrying connections (https://github.com/dino/dino/pull/236#pullrequestreview-86851793) and this code `private bool Dino::ConnectionManager::network_is_online ` which is https://github.com/dino/dino/blob/4bb0c465fc8f1737a1f2668519a6e0cfbc7bfa0d/libdino/src/service/connection_manager.vala#L328

**Comment by github-deimos** [comment]
I have a similar issue on unstable internet connections. Once disconnected, even for a few seconds, dino will never resume. Here are debug logs:
```
(dino:12666): xmpp-vala-DEBUG: 10:05:33.345: stream_connect.vala:37: Got no xmpps-client DNS records for chat.example.com: No DNS record of the requested type for “_xmpps-client._tcp.chat.example.com”
(dino:12666): xmpp-vala-DEBUG: 10:05:33.345: starttls_xmpp_stream.vala:19: Connecting to chat.example.com:5222 (starttls)
(dino:12666): GLib-GIO-DEBUG: 10:05:33.345: GSocketClient: Starting new address enumeration
(dino:12666): pxbackend-DEBUG: 10:05:33.346: px_manager_get_proxies_sync: url=none://chat.example.com:5222 online=1
(dino:12666): pxbackend-DEBUG: 10:05:33.346: px_manager_get_proxies_sync: Proxy[0] = direct://
(dino:12666): GLib-GIO-DEBUG: 10:05:33.347: GSocketClient: Address enumeration succeeded
(dino:12666): GLib-GIO-DEBUG: 10:05:33.347: GSocketClient: Starting TCP connection attempt
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Connection attempt failed: Connection refused
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Starting new address enumeration
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Address enumeration succeeded
(dino:12666): GLib-GIO-DEBUG: 10:05:33.483: GSocketClient: Starting TCP connection attempt
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: TCP connection successful
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: Starting application layer connection
(dino:12666): GLib-GIO-DEBUG: 10:05:33.602: GSocketClient: Connection successful!
(dino:12666): libdino-DEBUG: 10:05:42.980: connection_manager.vala:185: [hello@chat.example.com] (Maybe) Establishing a new connection
(dino:12666): libdino-DEBUG: 10:05:42.980: connection_manager.vala:193: [hello@chat.example.com] Connection attempt already in progress. Directly retry if it fails.

(dino:12666): xmpp-vala-CRITICAL **: 10:06:54.983: file /usr/src/debug/dino/dino-0.4.2/xmpp-vala/src/core/stanza_reader.vala: line 42: uncaught error: TLS connection closed unexpectedly (g-tls-error-quark, 6)
```

Despite the log messages, it never retries. I never see tcp connection attempt (via tcpdump).

I've tracked it down to an interaction with glib networking.  Possibly this logic needs to be more aggressive in retrying connections (https://github.com/dino/dino/pull/236#pullrequestreview-86851793) and this code `private bool Dino::ConnectionManager::network_is_online ` which is https://github.com/dino/dino/blob/4bb0c465fc8f1737a1f2668519a6e0cfbc7bfa0d/libdino/src/service/connection_manager.vala#L328

**Comment by qstambaugh** [comment]
This happens quite often on my Pinephone when using a sleepwalk script. The script will put my phone to sleep for a set amount of time, then wake it up to have apps check for messages for about a minute, then go back to sleep. Dino does not handle it well. It will connect properly most of the time, but sometimes it'll get stuck in that partially connected state or give up on reconnecting all together and never retry. over the course of an hour with my phone going in and out of sleep mode, Dino will reliably get stuck and I have to restart it

**Comment by stevenroose** [comment]
I'm having this issue again, resulting in the following logs:
```
(dino:286976): xmpp-vala-CRITICAL **: 16:07:53.066: file /build/source/xmpp-vala/src/core/stanza_reader.vala: line 42: uncaught error: TLS connection closed unexpectedly (g-tls-error-quark, 6)

(dino:286976): GLib-GIO-CRITICAL **: 16:07:53.066: GTask 0x2c496d00 (source object: (nil), source tag: (nil)) finalized without ever returning (using g_task_return_*()). This potentially indicates a bug in the program.
(dino:286976): libdino-DEBUG: 16:07:53.480: connection_manager.vala:255: [steven@<redacted> 0x2b0e2420] Connection error: Error receiving data: Connection reset by peer

(dino:286976): libdino-WARNING **: 16:07:53.484: connection_manager.vala:262: [steven@<redacted> 0x2b0e2420] Stream Error: conflict
```

This time it seems that it's related to me migrating to a new computer by copying my home folder. I had to manually get new omemo keys by deleting `omemo.db`, but it seems that some server-related session data is also causing conflicts between my old machine that is still running Dino and the new one.

Ideally, this would be resolved with Dino automatically refreshing whatever session state it has when this error occurs on the first time.

**Comment by stevenroose** [comment]
Ok I think I managed to resolve this issue by changing the resource part in the `dino.db` `accounts` column. I'll make a separate issue for that.

**Comment by fiaxh** [comment]
As Dino now handles resource collision (https://github.com/dino/dino/commit/4d4ba7dde6d3153fa5ea652a8b37d7b78f511484), I assume this issue can be closed as well. I also fixed the uncaught error that can be seen in your log.
