### ISSUE TITLE
Words that contain a colon are highlighted as hyperlinks.

### ISSUE THREAD

**Issue by raketenlurch** [dino/dino#897]
When you use a colon inside a single word (e.g Benutzer:innen (a form of gender-sensitive german)), Dino highlights these words as hyperlinks. 

![dino](https://user-images.githubusercontent.com/38227375/91186349-3a6cc300-e6ef-11ea-9b5a-cb2815063545.png)

**Comment by schiederme** [comment]
A "simple" fix, would be the implementation of URI Schemes by IANA (https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)

**Comment by fiaxh** [comment]
What version of Dino are you using?

**Comment by fiaxh** [comment]
The reason I asked for the version is that I'm fairly sure you're using an older Dino version. This doesn't happen on master (and probably also not in v0.1; without having verified it).
