### ISSUE TITLE
Cannot add account on Ubuntu 16.04

### ISSUE THREAD

**Issue by t2d** [dino/dino#9]
Thanks to https://github.com/dino/dino/commit/2804799f61eb4c68c5cf88b9996d13a81fe6317d I can now compile successfully on Ubuntu 16.04. But how do I add an account? Is this a Unity problem?
![image](https://cloud.githubusercontent.com/assets/1834580/23864117/dcad8cfa-0811-11e7-94b1-506dd5f3d7e8.png)

**Comment by lovetox** [comment]
there should be a menu in the global menu, dont look at the application :)

**Comment by t2d** [comment]
Sadly, there is nothing in the global menu

**Comment by mar-v-in** [comment]
@t2d 

![](http://i.imgur.com/jT0diI6.png)

Beside that, UI is currently terribly broken in Unity because of Ubuntu's crippled GTK version.

**Comment by t2d** [comment]
There seems to be something wrong with my user profile. I created a new one and it is working
