### ISSUE TITLE
Friend request issues

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#90]
Hi,
Someone added me via conversations app. I was shown a notification and I accepted the request. The guy is in my chat list, but shown offline. If I go to "start chat" he is not shown there. If I manually add him, his status is shown. However OMEMO support is not available which I cannot understand. #36 It also seems to happen for some other accounts of mine #87

**Comment by C3realGuy** [comment]
Same problem for me, it also seems like it's not possible to add someone to contacts manually.

**Comment by fiaxh** [comment]
Lots of development has happened since this issue was opened, including on OMEMO. Contact request accepting should also work fine. If you still have problems with any of the described points, please open a new issue.
