### ISSUE TITLE
compiling problem xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o

### ISSUE THREAD

**Issue by denis-robel** [dino/dino#901]
dini.im stops to compiling with following error:

`Building C object xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o
FAILED: xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o 
/usr/bin/cc -DG_LOG_DOMAIN=\"xmpp-vala\" -Dxmpp_vala_EXPORTS -Ixmpp-vala -Iexports -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/glib-2.0 -isystem /usr/lib64/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/gee-0.8 -fdiagnostics-color -Wall -Wextra -Werror=format-security -Wno-duplicate-decl-specifier -g -g -fPIC    -Wno-unused-but-set-variable -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-value -Wno-unused-variable -Wno-discarded-qualifiers -Wno-discarded-array-qualifiers -Wno-deprecated-declarations -Wno-missing-braces -pthread -MD -MT xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o -MF xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o.d -o xmpp-vala/CMakeFiles/xmpp-vala.dir/src/module/xep/0115_entitiy_capabilities.c.o -c xmpp-vala/src/module/xep/0115_entitiy_capabilities.c
In Datei, eingebunden von xmpp-vala/src/module/xep/0115_entitiy_capabilities.c:7:
/home/denis/Downloads/dino.im/dino/xmpp-vala/src/module/xep/0115_entitiy_capabilities.vala: In Funktion »xmpp_xep_entity_capabilities_module_compute_hash_for_info_result«:
exports/xmpp-vala.h:4670:48: Fehler: »XMPP_XEP_SERVICE_DISCOVERY_NS_URI« nicht deklariert (erstmalige Verwendung in dieser Funktion); meinten Sie »XMPP_XEP_SERVICE_DISCOVERY_NS_URI_INFO«?
 4670 | #define XMPP_XEP_SERVICE_DISCOVERY_NS_URI_INFO XMPP_XEP_SERVICE_DISCOVERY_NS_URI "#info"
`

my system: 
Mageia 8 x86_64
Vala 0.49.92

Is there any hint for this problem?

**Comment by mar-v-in** [comment]
@denis-robel 
Vala 0.49.92 is an experimental preview version of vala compiler, so I guess this is a bug introduced to the vala compiler just now. Can you report this upstream with the vala compiler?
