### ISSUE TITLE
When receiving files, provide a interface to save it on disk

### ISSUE THREAD

**Issue by rscmbbng** [dino/dino#903]
Dear Dino devs,

First of all, thank you for your fantastic client. I'd like to request a feature that makes it possible to save received files to a location that I have specified. Not as a general setting, but a UI to do so on specific files. This is especially relevant to non-image files. 

I am aware I can find them in `~/.local/shared/dino/files/` so this issue is not about being able to find them at all.

**Comment by trymeouteh** [comment]
Would be great to be able to choose were to save a file when you want to save it to your computer.

**Comment by wkg** [comment]
https://github.com/dino/dino/pull/1080

**Comment by fiaxh** [comment]
This has been done in #1080.
