### ISSUE TITLE
search_processor.vala:34.26-34.26: error: syntax error, expected `('

### ISSUE THREAD

**Issue by alexmat** [dino/dino#911]
Error compiling the following checkout:
commit 1956f63179c4f3ac3232cc4a2da8046565fad2a1 (HEAD -> master, origin/master, origin/HEAD)

$ vala --version
Vala 0.50.0

[324/769] Generating C code for target LIBDINO_VALA_C
FAILED: libdino/src/application.c libdino/src/dbus/login1.c libdino/src/dbus/upower.c libdino/src/entity/account.c libdino/src/entity/conversation.c libdino/src/entity/encryption.c libdino/src/entity/file_transfer.c libdino/src/entity/message.c libdino/src/entity/settings.c libdino/src/plugin/interfaces.c libdino/src/plugin/loader.c libdino/src/plugin/registry.c libdino/src/service/avatar_manager.c libdino/src/service/blocking_manager.c libdino/src/service/chat_interaction.c libdino/src/service/connection_manager.c libdino/src/service/content_item_store.c libdino/src/service/conversation_manager.c libdino/src/service/counterpart_interaction_manager.c libdino/src/service/database.c libdino/src/service/entity_capabilities_storage.c libdino/src/service/entity_info.c libdino/src/service/file_manager.c libdino/src/service/jingle_file_transfers.c libdino/src/service/message_correction.c libdino/src/service/message_processor.c libdino/src/service/message_storage.c libdino/src/service/module_manager.c libdino/src/service/muc_manager.c libdino/src/service/notification_events.c libdino/src/service/presence_manager.c libdino/src/service/registration.c libdino/src/service/roster_manager.c libdino/src/service/search_processor.c libdino/src/service/stream_interactor.c libdino/src/service/util.c libdino/src/util.c exports/dino.vapi exports/dino_internal.vapi exports/dino.h exports/dino_internal.h
cd /tmp/pkgmk-dino/src/dino/build/libdino && /usr/bin/valac --color=always -C --header=/tmp/pkgmk-dino/src/dino/build/exports/dino.h --internal-header=/tmp/pkgmk-dino/src/dino/build/exports/dino_internal.h --vapi=/tmp/pkgmk-dino/src/dino/build/exports/dino.vapi --internal-vapi=/tmp/pkgmk-dino/src/dino/build/exports/dino_internal.vapi -b /tmp/pkgmk-dino/src/dino/libdino -d /tmp/pkgmk-dino/src/dino/build/libdino --pkg=gdk-pixbuf-2.0 --pkg=gee-0.8 --pkg=glib-2.0 --pkg=gmodule-2.0 --pkg=gobject-2.0 -g --target-glib=2.38 /tmp/pkgmk-dino/src/dino/libdino/src/application.vala /tmp/pkgmk-dino/src/dino/libdino/src/dbus/login1.vala /tmp/pkgmk-dino/src/dino/libdino/src/dbus/upower.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/account.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/conversation.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/encryption.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/file_transfer.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/message.vala /tmp/pkgmk-dino/src/dino/libdino/src/entity/settings.vala /tmp/pkgmk-dino/src/dino/libdino/src/plugin/interfaces.vala /tmp/pkgmk-dino/src/dino/libdino/src/plugin/loader.vala /tmp/pkgmk-dino/src/dino/libdino/src/plugin/registry.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/avatar_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/blocking_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/chat_interaction.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/connection_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/content_item_store.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/conversation_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/counterpart_interaction_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/database.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/entity_capabilities_storage.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/entity_info.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/file_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/jingle_file_transfers.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/message_correction.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/message_processor.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/message_storage.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/module_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/muc_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/notification_events.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/presence_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/registration.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/roster_manager.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/search_processor.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/stream_interactor.vala /tmp/pkgmk-dino/src/dino/libdino/src/service/util.vala /tmp/pkgmk-dino/src/dino/libdino/src/util.vala /tmp/pkgmk-dino/src/dino/build/exports/xmpp-vala.vapi /tmp/pkgmk-dino/src/dino/build/exports/qlite.vapi
/tmp/pkgmk-dino/src/dino/libdino/src/service/search_processor.vala:34.26-34.26: error: syntax error, expected `('
                    with = word.substring(5);
                         ^
Compilation failed: 1 error(s), 0 warning(s)

**Comment by mar-v-in** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/vala/-/issues/1073
