### ISSUE TITLE
Cannot download attachment

### ISSUE THREAD

**Issue by MCMic** [dino/dino#913]
Hello,

I sent myself a GPX file from OSMAnd to save it on my computer, in Dino I can click on it and it opens with marble, but I do not see a way of saving the file to disk. There is no right-click menu so I’m out of ideas on how to get this file. Did I miss something?

**Comment by fiaxh** [comment]
You did not overlook it, this option does not exist yet (it's on a long list of todos, though). For the time being you might want to know that all files are saved in `~/.local/shared/dino/files/`.

This feature has already been requested in #903, so I'll close this one as a duplicate.

**Comment by MCMic** [comment]
I searched for "attachment" and #903 did not pop up ^^

Thank you for the information, sorry about the duplicate.

**Comment by licaon-kter** [comment]
@MCMic it's not attachment (this is not email)...but file :)
