### ISSUE TITLE
Bypass system URI allocator for xmpp: links ?

### ISSUE THREAD

**Issue by anubister** [dino/dino#914]
Currently clicking on a xmpp: link like `xmpp:chat@dino.im?join` inside a conversation rely on the OS URI allocation to decide how to handle the link. If another Jabber client is installed on the system it could be launched by clicking this link.
Expected behaviour : to bypass system allocation and to force opening of the xmpp: link inside Dino.

**Comment by selurvedu** [comment]
\o/
Thank you fiaxh!
