### ISSUE TITLE
Creating an index on the content_item table leads to a *massive* speedup in load times

### ISSUE THREAD

**Issue by eeeeeta** [dino/dino#923]
Dino seems to hammer the content_item table with hundreds of queries of the form

```
[sqlite 55ms] SELECT * FROM content_item  WHERE ((1) AND content_item.conversation_id = ?) AND content_item.hide = ?  ORDER BY content_item.local_time DESC, content_item.time DESC  LIMIT 1 OFFSET 0
```

which, as indicated, take about 50ms each to execute. The cumulative effect is that Dino takes about 50 wall-clock seconds to even paint a window, which is quite annoying.

Adding the following index speeds it up by literally a factor of 10x (50s -> 5s).

```
CREATE INDEX content_item_temp2 ON content_item (conversation_id, hide, local_time, time);
```

Perhaps this is something you want to add to the schema? (I could potentially PR this if you wanted...)

**Comment by fiaxh** [comment]
Following up on our exchange in the Dino MUC, in case you didn't see my reply.

You are right, the index that you proposed is much more suitable.

> I could potentially PR this if you wanted...

Yes that would be welcome! We'll want to replace the [current index](https://github.com/dino/dino/blob/master/libdino/src/service/database.vala#L65) with the one you suggested. Also, we'll need a migration routine (they're [here](https://github.com/dino/dino/blob/master/libdino/src/service/database.vala#L380)) that drops the existing index and creates the new one in existing databases.
