### ISSUE TITLE
Cut a new release 

### ISSUE THREAD

**Issue by paulmenzel** [dino/dino#938]
Version 0.1.0 is from January 2020. After several months of development and improvements, it’d be great to have a new release, so that distribution, often only packaging release, can package the improvements, and users can profit from them.

**Comment by licaon-kter** [comment]
Soon™

/close this

**Comment by Neustradamus** [comment]
@paulmenzel: Thanks for your request :)

**Comment by fiaxh** [comment]
https://dino.im/blog/2020/11/dino-0.2-release/

**Comment by Neustradamus** [comment]
@fiaxsh: Thanks but there is a problem of date, we are not the 6 november, can you change it?
