### ISSUE TITLE
Feature request - view message stanza 

### ISSUE THREAD

**Issue by muppeth** [dino/dino#945]
As a user I would like to be able to see message stanza (source) similar to gajim or Fractal (similar to dino matrix client).
eg. RIght-clicking on the message and select "View message stanza" where I coudl see it in a pop up window.

**Comment by fiaxh** [comment]
In what situations did you wished for this feature in the past? What information did you look for in these cases?

**Comment by fiaxh** [comment]
If there is something important Dino does not parse from the stanzas, that's what we should address instead.

If you want to look at stanzas for debugging or development purposes, you can already do so with Dino by using [command line options](https://github.com/dino/dino/wiki/Debugging#view-xml-stanzas).
