### ISSUE TITLE
[Bug] .xsession-errors is heavily spammed with error messages

### ISSUE THREAD

**Issue by C0D3D3V** [dino/dino#946]
If Dino freezes and I do not notice it, so dino remains open, after a few minutes my hard disk is full because the .xsession-errors file is spammed.

This is useful because you finally get to see where the garbage is on the harddisk, but it's more like a bug.

The file is full with this error message:
```
(dino:59453): GLib-WARNING **: 13:28:22.953: GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code. You must ensure an error is NULL before it's set.
The overwriting error message was: local session-terminate: transport error: Fehler beim Senden von Daten: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
```
This message is written to the logfile 15 times per millisecond, so you can get up to 45GB in a few minutes or until the hard disk is full.

My Dino Version: 0.2.0~git6.20201120.11d9855a

**Comment by Quix0r** [comment]
Doesn't happen here with my server. Maybe a server-side problem?

**Comment by C0D3D3V** [comment]
My server is toll.ml (But I deactivated account creation currently, I can activate it again if you want to do some tests).

I suspect that Dino freezes when sending files, but I haven't found out when exactly. Because most of the time sending files works quite normal.

**Comment by C0D3D3V** [comment]
I have not seen this error again
