### ISSUE TITLE
Contact/Conversation list light gray sometimes

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#95]
I dont know what exactly triggers this bug, but the contact list (or open conversations list) on the left sometimes gets very light. If I hover the contacts the colors gets normal again. I think this most of the time happens in combination with notifications when the windows was out of focus.

I am still trying to get a screenshot of that.

**Comment by fiaxh** [comment]
While I also sometimes experienced this problem back when this issue was opened, it didn't happen anymore for quite some time.
