### ISSUE TITLE
File transfer: add a way to store the file somewhere

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#951]
When someone performs file transfer, dino seems to only offer the option to open the file in the default application. But often that is not what I want; I want to store the transmitted file somewhere on disk so I can process it further. For some reason I cannot figure out how to do that with dino.

**Comment by licaon-kter** [comment]
#903 #803 ?

**Comment by RalfJung** [comment]
Ah, #903 it is. Somehow I couldn't find it when searching for duplicates, probably I used the wrong keywords.
