### ISSUE TITLE
Implement XEP-0444 : Message Reactions

### ISSUE THREAD

**Issue by anubister** [dino/dino#952]
> Message reactions allow to express an opinion or feeling towards a message in a quick and light-weight way. 

I think it's going to be a key feature for groupchats and a must have for a modern XMPP client. Movim is already implementing it (https://nl.movim.eu/?node/pubsub.movim.eu/Movim/fd1921c6-219f-477b-a4be-ebb25e4cccc5), implementing it in a desktop client will be definitely a step forward for the XMPP ecosystem.

I've been told the work is already in progress : https://github.com/dino/dino/commits/feature/reactions 
so this bug report is just to make aware and track progress :)

**Comment by poVoq** [comment]
I think this can be closed?

https://github.com/dino/dino/commit/80258a874ddfeb87b4b71f5791eab94a2465de6d
