### ISSUE TITLE
Scrub client user-agent

### ISSUE THREAD

**Issue by HulaHoop0** [dino/dino#954]
Please do not broadcast the chat client user-agent during normal usage (I can see a valid case for it needed during debugging) to avoid making Dino users noticeable to network adversaries who may use that info to track and target the relatively smaller userbase.

Original user report from our forum:

> 2) Open user info. Everyone can see the record “Using Dino” and the name resource like “dino.535nshGJ”. It identifies that you are not Windows user. It reduces privacy. And it can help to choose an attack vector using Dino vulnerabilities. There are no plugins or settings to hide this data.

**Comment by licaon-kter** [comment]
@HulaHoop0 So once Dino on Windows is released this can be closed? Maybe you are on a mac?

**Comment by fiaxh** [comment]
The background of the "user-agent" are [Service Discovery](https://xmpp.org/extensions/xep-0030.html#info-basic) and [Entity Capabilities](https://xmpp.org/extensions/xep-0115.html#howitworks). The purpose of these protocol extensions is to tell other clients about the capabilities of your client.

Let's assume we remove the name "Dino" and from the Service Discovery information, use a random `node` name and a random resource. Your client would still be identifiable by it's capabilities and by the way it behaves. Examples for that include:

- The order of XML elements that are exchanged
- The format of message IDs
- The exact wording of fallback strings

There is no XMPP client out there that is able to hide its identity. If it claims otherwise, the privacy it might provide can only be superficial. What you request would only "hide" the client identity from people with little insight into how things work.

**Comment by HulaHoop0** [comment]
Fair points. Thanks for explaining. I guess it is just as impossible for xmpp clients to conceal identity as it is for browsers.

> @HulaHoop0 So once Dino on Windows is released this can be closed? :) Maybe you are on a mac?

@licaon-kter Linux forever here ;)

**Comment by IMVIX** [comment]
> There is no XMPP client out there that is able to hide its identity. If it claims otherwise, the privacy it might provide can only be superficial. What you request would only "hide" the client identity from people with little insight into how things work.

"People with insight into how things work" are 2% users. Of course, I prefer to have an option to hide or show personal information at least for 98% of users. 

Let's explore the current situation.

a) 100% of my contacts can see that I use Dino now.

b) I can not **show** my system time to my contacts (or other data). Dino hasn't this option.

For example, Psi/Gajim can optionally:

- hide or show system time
- hide, show and **spoof** client name

I think it will be good to have such options in Dino.

**Comment by fiaxh** [comment]
- Providing a way to superficially "hide" or "spoof" the client identity might give the user a false sense of security or privacy. That is problematic especially for people that really rely on having security or privacy.
- You said that you are concerned about Dino-specific attacks. I think you should consider the possibility that people that have the ability to attack you are among the "2%" of people that know how things work.

We are not going to implement a badly-working security-by-obscurity option.

**Comment by IMVIX** [comment]
> We are not going to implement a badly-working security-by-obscurity option.

Your position is quite clear. Thank you for answers and arguments. My opinion is different. But this option is not so important.

**Comment by Username834521** [comment]
@IMVIX @licaon-kter @fiaxh   

> For example, Psi/Gajim can optionally:
> 
>     * hide or show system time
> 
>     * hide, show and **spoof** client name
> 
> 
> I think it will be good to have such options in Dino.

I agree too I think they should be added and others should be looked into

### What Can Be Randomized (with Caution)

+ **Resource and node parts of JIDs**: These are client-controlled and can be randomized.
+ **Whitespace, attribute order, and XML declaration**: Minor randomization is possible here.
              -`id` Attribute
    		 - `xml:lang` Attribute
    		- Resource Part of JID: (e.g. `user@domain/resource123`)
    		- Custom Extensions (XEPs): - If you include custom or optional elements (like message receipts, chat markers, etc.), you can randomize presence, values, or ordering of these elements, as long as you conform to the relevant XEPs.
    		- Order of Child Elements
+ **Presence of optional elements**: Some optional XML elements can be omitted or included at random, if allowed by the server and the XMPP protocol.
