### ISSUE TITLE
Message list does not scroll to the end by itself

### ISSUE THREAD

**Issue by morciej** [dino/dino#957]
Dino starts with the message list scrolled all the way to the top, and it takes a while for it to automatically scroll to the bottom to show the latest message. Is there anything that can be done to have it happen faster? Or is it because getting all messages from server takes that long?

**Comment by fiaxh** [comment]
What version of Dino are you using?

**Comment by morciej** [comment]
0.1.0

**Comment by licaon-kter** [comment]
@morciej what OS? There's no 0.2 availablu?

**Comment by morciej** [comment]
Mint Ulyssa/Focal.
