### ISSUE TITLE
Unable to connect to servers hosted behind Tor Onion services

### ISSUE THREAD

**Issue by intrigeri** [dino/dino#958]
Context: we want to replace Pidgin with another XMPP client in [Tails](https://tails.boum.org). Dino is one of the 2 candidates we're currently evaluating. We just got started with the evaluation but so far, this issue is the only clear blocker I've spotted for Dino.

The problem: Onion services have self-signed TLS certificates. As we know, this is a deal breaker for current Dino.

This is a special case of #57 (related to #452 and #209). I think Onion services deserve to be treated separately, in case no mutually agreeable general solution to #57 is found, because contrary to the general case:

  - Validating the certificate is not strictly necessary, and adds little value: by design, Onion services already provide
    transparent authentication of the server by the client lower in the stack.

    This is why, for example, Tor Browser treats Onion websites over plaintext HTTP just the same as HTTPS:
    the connection is considered to be secure.

  - Requiring a CA-signed certificate is a constraint impossible to meet by Onion services: it's
    currently not possible, in practice, to get a CA-signed certificate for an Onion service. Well, Facebook did,
    but they have means that few other XMPP server providers have.

Would you be amenable to handle Onion services in a specific manner regarding TLS certificate validation, in order to solve this problem?

Are there specific implementation or security constraints that can make this costly?

If, on the Tails side, this is the only clear blocker we identify, I would be happy to ask help from our UX designer (@sajolida) wrt. the corresponding user interactions (or lack thereof).

Thanks for considering :)

**Comment by fiaxh** [comment]
Are you referring to accounts that are actually on .onion domains (`user@823urjksj9dfiejsf.onion`) or are you referring to accounts on normal domains (`user@example.com`) that also provide a .onion service for users to connect with?

About the first case (account on .onion domains): It would indeed make sense to allow invalid certificates for .onion domains, since encryption is provided independent of TLS. We can do that.

About the second case: In those cases the .onion server should provide a certificate for example.com, since clients need some way to verify that the server is actually allowed to serve this account.

> I would be happy to ask help from our UX designer (@sajolida) wrt. the corresponding user interactions (or lack thereof).

I believe it will be a simple matter of allowing all certificates for .onion domains without asking the user anything. However if @sajolida has any feedback on that matter or any other part of Dino, we'd be happy to hear it.

Improving Tor support has been on our wishlist anyways, so we'll be happy to work with you Tails people to make Dino suitable to be used within Tails.

**Comment by intrigeri** [comment]
Hi @fiaxh,

thanks for your quick reply!

> Are you referring to accounts that are actually on .onion domains (`user@823urjksj9dfiejsf.onion`) or are you referring to accounts on normal domains (`user@example.com`) that also provide a .onion service for users to connect with?

I'm referring to the former: accounts that are actually on .onion domains.

> About the first case (account on .onion domains): It would indeed make sense to allow invalid certificates for .onion domains, since encryption is provided independent of TLS. We can do that.

I'm glad we're on the same page here :)

> I believe it will be a simple matter of allowing all certificates for .onion domains without asking the user anything.

This would make sense to me.

> Improving Tor support has been on our wishlist anyways, so we'll be happy to work with you Tails people to make Dino suitable to be used within Tails.

I'm really happy to read this!

**Comment by ElonSatoshi** [comment]
Just bumping this thread to show my support for Dino being able to connect to .onion domains in the future. I'll be one of the first to download the update!

**Comment by fiaxh** [comment]
> I'm referring to the former: accounts that are actually on .onion domains.

I can't seem to find a server that offers `user@1234567890abcdef.onion`-style accounts. All I find are [servers](https://gist.github.com/dllud/a46d4a555e31dfeff6ad41dcf20729ac) that offer accounts on normal domains that are also reachable via a .onion service. Do you maybe know a server that offers .onion accounts which I can use for testing?

**Comment by intrigeri** [comment]
Unfortunately, I'm not aware of such a server that would offer accounts to the general public.

**Comment by fiaxh** [comment]
I've been made aware of [this](https://xmpp.is/account/register/hidden_service/) server that provides .onion accounts and was thus able to test it.

For accounts on .onion domains, Dino will now accept certificates from unknown CAs (81a55052707d460a7f437b664682817c2c99dce6). I also tested it with Tails.

**Comment by intrigeri** [comment]
> For accounts on .onion domains, Dino will now accept certificates from unknown CAs (81a55052707d460a7f437b664682817c2c99dce6). I also tested it with Tails.

Awesome, thanks a lot! :)

**Comment by user82622** [comment]
> I've been made aware of [this](https://xmpp.is/account/register/hidden_service/) server that provides .onion accounts and was thus able to test it.
> 
> For accounts on .onion domains, Dino will now accept certificates from unknown CAs ([81a5505](https://github.com/dino/dino/commit/81a55052707d460a7f437b664682817c2c99dce6)). I also tested it with Tails.

How have you been able to get it running on Tails? The version in the dino-im/buster-backports repo is to old for the fix and with newer versions i have dependency issues. I even tried to compile a appimage with all the dependencies but there i run into the problem that somehow omemo is not working. 
Is there any workaround to get it running on tails?
