### ISSUE TITLE
set Application Name for notifications

### ISSUE THREAD

**Issue by xorbug** [dino/dino#959]
Currently, it seems Dino does not set the [`Application Name`](https://developer.gnome.org/notification-spec/#basic-design) field for its desktop notifications. That may be an useful attribute for custom filtering and and rules functionalities provided by some notification daemons.

**Comment by fiaxh** [comment]
What gives you the impression that Dino does not set the application name? I did not look into it in greater detail, but the application name should be provided e.g. [here](https://github.com/dino/dino/blob/master/main/src/ui/notifier_freedesktop.vala#L101) as the first parameter.

**Comment by licaon-kter** [comment]
dunst picksz
 it up just fine, which daemon do you have?

**Comment by xorbug** [comment]
Luckily I can answer both questions in one, since I'm using _dunst_, and in fact the statement was based on the observation of the output of `dunst -print` for a Dino notification, e.g.:

```
	appname: ''
	summary: '<edited>'
	body: '<edited>'
	icon: 'dialog-information'
	raw_icon set: false
	category: 
	timeout: 0
	urgency: NORMAL
	transient: 0
...more metadata...
```
As you can see `appname` is empty and there is no reference whatsoever to `Dino` string as per the code linked by @fiaxh.
Now this could also be a bug in _dunst_? Sorry if that's the case. Anyway `appname` looks ok for notifications sent by other applications. Compare with `notify-send dino 'we love dino'`:
```
	appname: 'notify-send'
	summary: 'dino'
	body: 'we love dino'
	icon: 'dialog-information'
	raw_icon set: false
	category: 
	timeout: 0
	urgency: NORMAL
	transient: 0
	formatted: '<b>dino</b>: we love dino'
	fg: #A89984
	bg: #504945
	frame: #000000
	id: 5
	script: (null)
```

@licaon-kter 
> dunst picks it up just fine

Does that mean `appname` is not empty for you, or something else?

**Comment by licaon-kter** [comment]
There's a string param `format:` and putting `%a` yielded app name.

See `man dunst`

**Comment by xorbug** [comment]
> There's a string param `format:` and putting `%a` yielded app name.
> 
> See `man dunst`

Mhh `%a` gives me an empty string as well, I guess for the same reason -whatever it is- that gives an empty `appname`. Maybe it's about the _dunst_ version then (mine is _1.3.2_ from debian stable, so a bit outdated), and not about Dino.

**Comment by licaon-kter** [comment]
I'm on Sid so... whatever dunst it has.
Dino 0.2, right?

**Comment by xorbug** [comment]
> I'm on Sid so... whatever dunst it has.
> Dino 0.2, right?

Yes, from backports.

**Comment by fiaxh** [comment]
The notification code has been largely rewritten since 0.2. Dino 0.2 used glib Notifications, while the current development version directly uses a freedesktop notification dbus service. It might be that glib notifications do not set the Application Name. I assume that @licaon-kter uses the current development code, so the results you two got from dunst are not comparable.

**Comment by licaon-kter** [comment]
@fiaxh I might have missed such a change indeed, I'm on git HEAD and I've only tested the icon these past week

**Comment by fiaxh** [comment]
I'm closing this since I assume that 0.2 doesn't set the application name due to Dino using glib notifications at that time. If you find this behavior to also exist with the current development version (although licaon-kter already suggested that it should work), feel free to leave a message.
