### ISSUE TITLE
Use Twemojis instead of current emojis

### ISSUE THREAD

**Issue by Porrumentzio** [dino/dino#967]
Twemojis are emoji display used at the beginning by Twitter but, since it's open source, also by many other programs.
They are more easy to understand for many people.

Here's the code: https://github.com/twitter/twemoji

**Comment by licaon-kter** [comment]
In which Linux distro repos are these available?

**Comment by Porrumentzio** [comment]
At least on AUR for Arch based distros: https://aur.archlinux.org/packages/ttf-twemoji/

**Comment by mimi89999** [comment]
I personally prefer Noto emojis. Conversations is also using them, so the emojis are consistent.

**Comment by fiaxh** [comment]
There is no such thing as the "current emojis". Dino does not set a specific emoji font.
Dino just says it wants to display some text. Your system picks whatever emoji font it finds suitable to display the text. When you install the twemoji font and set it to be the default emoji font, you will see twemoji emojis in Dino.
