### ISSUE TITLE
OTR support

### ISSUE THREAD

**Issue by jvoisin** [dino/dino#97]
It would be wonderful to add [OTR]( https://otr.cypherpunks.ca/ ) support ([coy]( https://coy.im), [pidgin](https://pidgin.im) and others are supporting it), since not that many clients are supporting OMEMO (yet?), and GPG doesn't provide forward-secrecy.

**Comment by NicoHood** [comment]
I generally agree, but the focus should be on OMEMO as its the better protocol and also it needs to get finished first. There are clients available for all platforms that support OMEMO (conversations, chatsecure, gajim, pidgin and dino).

**Comment by jvoisin** [comment]
Zomg, pidgin indeed [supports OMEMO]( https://github.com/gkdr/lurch ), even on Windows !

**Comment by d9h02f** [comment]
OTR is broken and outdated. OMEMO isn't.

**Comment by jvoisin** [comment]
Please don't say this, I contributed a bit to it </3

**Comment by Mic92** [comment]
OTR + pidgin is a strange combination given the security track-record of pidgin (regarding memory bugs).

**Comment by tonghuix** [comment]
It may have to re-write libotr using vala. I don't think it is wise.

**Comment by elimohl** [comment]
>There are clients available for all platforms that support OMEMO (conversations, chatsecure, gajim, pidgin and dino)
OMEMO support for pidgin is actually broken and it seems like its maintainer have abondoned it so it will be broken forever possibly.

I'd like to use dino but most of my friends use clients without OMEMO support.

**Comment by licaon-kter** [comment]
@elimohl Is [lurch](https://github.com/gkdr/lurch] broken?

**Comment by Echolon** [comment]
@jvoisin I understand, probably that came a bit harsh from the others - but what about contributing to the better implementation of omemo? And as I understood OMEMO is like OTR + PGP ..... <3?

**Comment by elimohl** [comment]
@licaon-kter lurch [doesn't support whitelist and doesn't notifiy about new devices in the conversation](https://github.com/gkdr/lurch/issues/62) which makes it almost worthless. Additionally it sometimes just not work (doesn't send messages and show mistake or send unencrypted messages despite of running OMEMO session).

**Comment by LuccoJ** [comment]
I just found out about this client and I'm *very* excited there is finally something decent with OMEMO, which so far was only useful to me on Android, hence losing its highlight of facilitating multi-device use.

However, I do have to the choir of feeling OTR support shouldn't be excluded: realistically, there will still be people I have on XMPP who won't have OMEMO support at least for a while longer, which would mean being forced to use two different clients, again making something potentially great a lot more annoying to use...

I agree OTR should be phased out, but that literally involves a phase-out for OTR and a phase-in for OMEMO.

**Comment by NicoHood** [comment]
I think this issue should be closed, because OTR support was dropped for some good reasons in conversations. Since omemo works really nice in dino now (even multi user channels), there is no need for implementing OTR.

**Comment by lionirdeadman** [comment]
The reason this was brought up at all was generally not because OMEMO was bad but simply because not everyone uses it. For example, I don't think there's any OMEMO client other than Gajim (which looks.. dated to say the least) on Windows.

But it seems developers are not interested so it may be best to close it indeed.

**Comment by abunasar** [comment]
+1 for otr support

**Comment by destruction-as-art** [comment]
i (and believe not only i),  searching for xmpp client with otr support. your client seems great, but without otr i cant use it .

**Comment by mejo-** [comment]
I agree that OTR support would be great to have. Right now, lots of people still use XMPP clients that lack proper OMEMO support (like Pidgin, Bitlbee or Weechat). If Dino had OTR support, we could suggest this client as an alternative to users of old (and crappy) Pidgin.

Besides, missing multi-device support in OTR can be seen as a security feature - with OMEMO, server admins (more or less silently) can add new identity keys (devices), which brings back the problem that you have to trust the server. See e.g. https://blogs.fsfe.org/vanitasvitae/2018/09/07/future-of-omemo/ for more context.

**Comment by mar-v-in** [comment]
@mejo- You also have to trust the server in case of OTR if you don't verify keys. Most implementations of OMEMO do Blind-Trust-Before-Verification, which means that as soon as you verified one of the users keys, other keys also need to be trusted to be used. Thus, the situation is pretty much the same with OMEMO and OTR with regard to this part: Whether MITM is possible depends on the users first verification of a key.

Dino has a plugin API that could be easily used to make an OTR plugin (in fact OpenPGP and OMEMO support are also just plugins). If you want to, feel invited to create such a plugin. It's just not a priority for us right now.

**Comment by mejo-** [comment]
> Thus, the situation is pretty much the same with OMEMO and OTR with regard to this part: Whether MITM is possible depends on the users first verification of a key.

Here, I tend to disagree. With OMEMOs multi-device support, it's much more common that new devices (and new fingerprints) arise. So users will be accustomed even more to (blindly) accept new fingerprints. Also, unfortunately some implementations of OMEMO so far lack support for fingerprint verification.

> Dino has a plugin API that could be easily used to make an OTR plugin (in fact OpenPGP and OMEMO support are also just plugins). If you want to, feel invited to create such a plugin. It's just not a priority for us right now.

Fair enough. Unfortunately, I lack the time (and skills) to develop an OTR plugin myself.

Nevertheless, thanks a lot for working on a modern XMPP desktop client. It's highly appreciated!
