### ISSUE TITLE
VM snapshots and OMEMO

### ISSUE THREAD

**Issue by IMVIX** [dino/dino#977]
I am running Dino with OMEMO encryption in a virtual machines.

1. I created a snapshot of this VM before retrieving the possibly unsafe file.

2. Then I wrote to the OMEMO chat in Dino. And I downloaded a file from this chat.

3. Next, I booted the virtual machine from the snapshot that was made at the step №1. I launched Dino, but now I cannot decrypt new messages.

Is it possible to run Dino from such snapshots and not lose the ability to write in OMEMO-chat? Or it's impossible for the OMEMO identity?

**Comment by licaon-kter** [comment]
OMEMO is a _decrypt once_ type.

Use a different account, that you only use in the VM.

Or use PGP but be aware files can be retrieved later and decrypted always.

**Comment by fiaxh** [comment]
The key used for encryption is changed with every message exchange. Thus, you can't reuse some random key state from the past.

From https://github.com/dino/dino/issues/850#issuecomment-692272324:

> In addition to the fingerprint displayed in clients, OMEMO uses session/ephemeral keys: as soon as you write with someone, these keys are created and they are replaced with new ones after every message exchange
>
> Without the latest session keys, you can't decrypt incoming messages. Thus when importing session keys from an older backup, you are likely going to have issues if the keys were used in between.

**Comment by adrelanos** [comment]
> I launched Dino, but now I cannot decrypt new messages.

So now the chat is totally broken, cannot read new messages, cannot send new messages?

Do you have to perform a reset or something to fix this?

If yes, is this a bug that could be addressed?

**Comment by licaon-kter** [comment]
Which Dino version?
