### ISSUE TITLE
Memory leak when scrolling up in MUC

### ISSUE THREAD

**Issue by mimi89999** [dino/dino#989]
1. Be in several MUCs
2. Scroll up several times in a MUC: Dino allocates memory
3. Do the same thing in another MUC: Dino allocates memory
4. Open the first MUC again and scroll up to the same place as previously: Dino again allocates memory

That memory seems to never bee freed.

**Comment by fiaxh** [comment]
Should be solved by a417cb396b18fe7ffc2a75fc640327d70793f85d.
