### ISSUE TITLE
Wrong link recognition

### ISSUE THREAD

**Issue by NicoHood** [dino/dino#99]
This is recognized as link:
```
test:test
```

**Comment by fiaxh** [comment]
This was fixed in f3af064262e3ea8afe8397424b5f05d260a2a57e.

**Comment by licaon-kter** [comment]
Please reopen, 11a118d53d4ef9c27c096b8c9c15dfeb4cb41e03:
![dinolinksok](https://user-images.githubusercontent.com/2282799/71451157-132cb300-2768-11ea-93ff-dd9829099a46.png)

But f3af064262e3ea8afe8397424b5f05d260a2a57e:
![dinolinkswrong](https://user-images.githubusercontent.com/2282799/71451158-14f67680-2768-11ea-8474-9cf3e34916ac.png)

**Comment by mar-v-in** [comment]
Thanks @licaon-kter, this should work with 4a3cef89fd7ebf15bfc6a108ac31f36e469cf80a now. Please report back if you find any other issues with the new URL detection.

**Comment by licaon-kter** [comment]
@mar-v-in That is fixed indeed, thanks.

Two more issues:
![dinoregex1](https://user-images.githubusercontent.com/2282799/71546096-2d92a680-298b-11ea-8fe4-1434ed281005.png)
Parenthesis should be included
and
![dinoregex2](https://user-images.githubusercontent.com/2282799/71546098-32575a80-298b-11ea-8457-a1999db24d2c.png)
Parenthesis should NOT be included

Something about: "you need logic that checks if the bracket has been opened in the url" I guess

**Comment by licaon-kter** [comment]
@mar-v-in Thanks, these 2 are fixed now
