### ISSUE TITLE
keyboard shortcuts not working when multiple keyboard layouts enabled

### ISSUE THREAD

**Issue by Soundtoxin** [dino/dino#991]
I am using release 0.2.0 of Dino. Installed from the Guix repos on Guix System.
C-v to paste does not work, I can only paste via right-click menu.
I also noticed C-k opens the "start conversation" window, which is supposed to be on C-t.
Further experimentation shows C-f acts as "send a file" (normally "search messages"), C-u acts as "join channel" (normally "send a file"). C-p acts as "search messages". Dvorak p is where qwerty r is, not f, so not sure what's up with that.
The best logic I'm finding here is that there's a link between the layouts. U on dvorak is where F is on qwerty, so Dino interprets my C-f like C-u maybe. I haven't been able to paste even with a "wrong" shortcut, though, and not every shortcut is wrong in the same way. 

I have these input settings in my `~/.config/sway/config` file to enable a us qwerty and us dvorak keyboard layout (and set a compose key).

```
input type:keyboard xkb_layout us,us
input type:keyboard xkb_variant dvorak,
input type:keyboard xkb_options compose:menu,compose:caps
```

I have this mode where I can press d to switch to dvorak or q to switch to qwerty.

```
    bindsym $mod+i mode "j: japanese; k: korean; v: vietnamese; esc: english"

    mode "j: japanese; k: korean; v: vietnamese; esc: english" {
        bindsym j exec ibus engine anthy; mode "default"
        bindsym k exec ibus engine hangul; mode "default"
        bindsym v exec ibus engine Unikey; mode "default"
        bindsym d input type:keyboard xkb_switch_layout 0; mode "default"
        bindsym q input type:keyboard xkb_switch_layout 1; mode "default"
        bindsym Return exec ibus engine xkb:us::eng; mode "default"
        bindsym Escape exec ibus engine xkb:us::eng; mode "default"
    }
```

My keyboard uses a dvorak layout in the firmware, so it expects the OS to be using a qwerty layout, so I am in qwerty mode in software now generally. I used to use only a dvorak layout in software and could paste fine.
Both my external keyboard and the laptop's internal keyboard have the same issue, so I suspect it's related to the layouts.
None of the other programs I use seem to have any issues with the usual keybinds or pasting in general.
I want to be able to switch layouts still in case I undock my laptop and have to use the built-in keyboard, so it would be nice if something could be fixed on Dino's end.

**Comment by fiaxh** [comment]
Do keyboard shortcuts work in other GTK3 application for you? For example in gedit?

**Comment by Soundtoxin** [comment]
> Do keyboard shortcuts work in other GTK3 application for you? For example in gedit?

Interesting. It seems not. I just installed gedit and can't copy or paste via keyboard. Is this a gtk issue then?

**Comment by fiaxh** [comment]
Dino doesn't do anything regarding `CTRL+C`, `CTRL+V` copy pasting itself. We just use GTK3 input fields and rely on GTK3 to do the magic. Thus, I'd suggest you [open an issue with GTK](https://gitlab.gnome.org/GNOME/gtk) instead.
