### ISSUE TITLE
Video group call

### ISSUE THREAD

**Issue by sualko** [dino/dino#994]
Hi everyone,

I'm the main developer of [JSXC](https://jsxc.org) and I plan to start working on video group calls / video conferences. Daniel told me (see https://github.com/iNPUTmice/Conversations/issues/3891) that you got a funding for the same feature. Is that right? What is the current state / your plans? Maybe we can work together on a new standard.

Cheers,
Klaus

**Comment by licaon-kter** [comment]
/duplicate https://github.com/dino/dino/issues/154

Read https://dino.im/blog/2020/08/setting-out-for-calls-and-conferences/

**Comment by sualko** [comment]
@licaon-kter thanks for the link to the blog post, but I think this is no duplicate, because your linked issue is about two party video calls.

**Comment by licaon-kter** [comment]
As the blog says it's a mix of stuff, imho, no need to split it atm.

**Comment by fiaxh** [comment]
@sualko so far we have only worked on one-to-one calls, but we plan to implement group calls after that. We'll be happy to work with you on proper group calls! I'll add you on XMPP such that we can collaborate. :slightly_smiling_face:

**Comment by trymeouteh** [comment]
Would love to see audio and videos calls, 1:1 and group calls!

**Comment by Quix0r** [comment]
I guess due to NAT traversal it won't be an easy task and not everybody can open a port on the firewall and redirect it.

**Comment by tacerus** [comment]
> I guess due to NAT traversal it won't be an easy task and not everybody can open a port on the firewall and redirect it.

Jitsi does it too.

**Comment by crocket** [comment]
If at least one of group call participants has an open port, everyone can connect to the port?

**Comment by fiaxh** [comment]
Dino suports peer to peer group calls by now. Closing this.
