### ISSUE TITLE
How do you import your private PGP key and add public PGP keys for your contacts?

### ISSUE THREAD

**Issue by trymeouteh** [dino/dino#997]
How do you import your private PGP key and add public PGP keys for your contacts in Dino?

**Comment by fiaxh** [comment]
You don't "import" keys into Dino. Dino makes use of the keys that are in your GPG keyring.

You can choose your own key in the account settings. Dino will then announce that you are using this key to your contacts.

In the other direction, your contacts (or rather: their clients) have to announce which key they are using; if that key is in your GPG keyring, Dino will use it to encrypt messages for that contact. You can see the fingerprint of the key that your contact announces in the Contact Details.

**Comment by trymeouteh** [comment]
Is a GPG keyring an app you download to manage PGP keys? If so what are the common apps for Linux and MacOS?

**Comment by E34rrsff** [comment]
You need to allow the app access to your `~/.gnupg` folder.

Run this if you have the flatpak app:
`flatpak --user override --filesystem=~/.gnupg im.dino.Dino`

You can make a PGP/GPG key with the GNOME Seahorse GUI app, or "Passwords & Keys."
